### ISSUE TITLE
Route not changing

### ISSUE THREAD

**Issue by r7l** [jeanropke/RDR2CollectorsMap#1]
When selecting a different day, the markers change but the route will always remain the same (**Day 2**). 

Does this map show the active route for each given day? Checking the code, it seems always to default to **Day 2**.

**Comment by jeanropke** [comment]
Just added route 2. I implemented a very basic system to routers.
I'll added routes 1 and 3 today.

**Comment by r7l** [comment]
Oh, you only had one route. I wasn't aware of that. Thought this is a bug. Anyways, thanks allot for this maps! Awesome work!

**Comment by jeanropke** [comment]
Added routes 1 & 3.
