### ISSUE TITLE
Add/remove all from map

### ISSUE THREAD

**Issue by can-u-lie** [jeanropke/RDR2CollectorsMap#100]
The add/remove from map feature is incredibly helpful but once the cycle resets i have to go through and manually add them back to the map, an option to add all removed items from the map back at once would save time and hassle. This map is already a godsend and the add/remove feature was a fantastic addition.

**Comment by jeanropke** [comment]
I added an option to reset markers daily.

![reset markers](https://user-images.githubusercontent.com/6243818/66088063-2278d780-e550-11e9-9c5a-a0128b503306.png)
