### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by Spacecase300** [jeanropke/RDR2CollectorsMap#1002]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

Cylcle 4 for the arrowheads does not seem to be showing up in the spot the map is saying they are.

**Comment by MichalD96** [comment]
I checked in game and found 2 arrowheads in places marked on the map, try change the session or restart the game
