### ISSUE TITLE
Thorburn Turquoise Ring - Cycle 1 

### ISSUE THREAD

**Issue by maeeh** [jeanropke/RDR2CollectorsMap#1005]
Everythings fine from map side, but i tried today multiple times in multiple sessions to obtain the ring. the detection lamp is glowing, and everythings pointing that i am at the right spot, but there is no possibility to get the ring by pressing R (PC). Normally this is indicated in the bottom right corner, but here it is not.

Maybe another bug.

**Comment by MichalD96** [comment]
Thanks for info. I'll check that too

**Comment by maeeh** [comment]
forget it, just re-validated and noticed that I have 10 of them. Seems one of the surprise locations gave it to me.
