### ISSUE TITLE
Incorrect item Random #29 Cycle: day #4

### ISSUE THREAD

**Issue by JeremyHoek** [jeanropke/RDR2CollectorsMap#1007]
![0626E3D4-3A9B-4EAF-90A5-35350E88E238](https://user-images.githubusercontent.com/65834651/82742197-282f6180-9d5b-11ea-9d66-0488cea06206.png)
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
Could you provide more info why this spot is not correct?

**Comment by JeremyHoek** [comment]
Hi Michal,

I arrived at the location and there was nothing there, not with the metal
detector nor with the spade or anything.

**Comment by MichalD96** [comment]
In some sessions is problem with certain spots. This problem applies to all items, not only random spots, and If you change the session, everything should work again.
