### ISSUE TITLE
Item bugged, Cycle 5

### ISSUE THREAD

**Issue by TheLexoPlexx** [jeanropke/RDR2CollectorsMap#1008]
The Tarotcard "Five of Pentacles" located near the Emerald Ranch with the description "On the windowsill of the barn, sometimes next to some moonshine" cannot be picked up. I tried this morning and now again. The map is not wrong, it was exactly where described but needs an Info.

**Comment by MichalD96** [comment]
Check how many Five of Pentacles cards you have in your inventory, this happens if you have 10 of them, in this case you can not pick up next one. I picked up this card many times and everything was fine, i really dont think that anything changed.

**Comment by TheLexoPlexx** [comment]
I did not even have one. I could not complete the Tarot-Card set of Pentacles yesterday.

**Comment by MichalD96** [comment]
I just checked this card and i had to change lobby 3 times to pick it up, but it is possible. i will add note in the card description about it.
