### ISSUE TITLE
App crashes with long search strings

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#101]
You have just updated the app but now it crashes when I paste a long search string. It was working perfectly but now its broken.

Legacy version still works though.

You can use this string for testing if you want:

Three of Cups;Four of Cups;Five of Cups;Nine of Cups;Page of Cups;King of Cups;Three of Swords;Four of Swords;Three of Wands;Four of Wands;Six of Wands;Seven of Wands;Knight of Wands;Queen of Wands;King of Wands;Two of Pentacles;Page of Pentacles;1800 Gold Quarter;1787 One Cent Token;1794 Silver Dollar;1700 New Yorke Token;1792 Quarter;1800 Gold Dollar;1792 Nickel;1796 Halfpenny;1795 Half Eagle;1797 Gold Eagle;1800 Half Dime;1789 Penny;Spoonbill;Irish Whiskey;Old Tom Gin;Crude;Feldspar;Raw;Quartz;Agate;Ebony Hairpin;Ivory Comb;Texas Bluebonnet;Bitterweed;Agarita;Wild Rhubarb;Cardinal;Creek Plum;Blood;Chocolate Daisy;Wisteria;Harland Coral;Pilgrim Moonstone;Bonnard Pearl;Banais Topaz;Beaulieux Diamond;Yates Diamond;Aubrey Onyx;Sackville Diamond;Blakely Miniatue;Pelle Pearl;Ainsworth Cross;Braxton Amethyst;Rou Pearl;Gosselin White Gold;Dane Topaz;Orchidee Diamond;Sterling Tooth;Harford Garnet;Endicott Diamond;Greco Sapphire;Abello Ruby Bangle;Ojeda Rose Gold Bangle;Helena Sapphire;Durant Pearl;Infanta Turquoise;Elliston Carved;Hajnal Garnet Bangle

**Comment by Shaftoe62** [comment]
And its no use to still show al un-found icons in grey. They are just confusing. Please revert to earlier version! Bad idea!!!

**Comment by jeanropke** [comment]
Crash fixed.

**Comment by Shaftoe62** [comment]
Great! I can see you are working really very hard on this project. Much appreciated!!
