### ISSUE TITLE
Lost Jewelry - Rings - Cycle Six (Thorburn Turquoise Ring)

### ISSUE THREAD

**Issue by debbie0005** [jeanropke/RDR2CollectorsMap#1010]
**Is your feature request related to a problem? Please describe.**

Wasn't at location and wasn't receiving any vibrations from it.  Searched several times to no success.  This is its current description "
At the supports of rail bridge, next to the path underneath the railroad bridge."

**Describe the solution you'd like**
If this is a recurring error for many people, so way to notify them.

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalD96** [comment]
this ring is definitely there
![TBRing](https://user-images.githubusercontent.com/53737762/83344056-8b446980-a302-11ea-9df9-99d0140906d8.jpg)
