### ISSUE TITLE
Incorrect Tarot Card Cycle: day #3

### ISSUE THREAD

**Issue by JimMilton1907** [jeanropke/RDR2CollectorsMap#1012]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
Cycle 3 for tarot cards is correct. Try change session or restart the game.

**Comment by JimMilton1907** [comment]
Great, thanks...
