### ISSUE TITLE
Egg near cairn lake

### ISSUE THREAD

**Issue by doolz90** [jeanropke/RDR2CollectorsMap#1014]
this egg doesn't appear to be here even after a few lobby hops

**Comment by MichalD96** [comment]
The egg is where it supposed to be for me. If you have problem to find the item sometimes is needed to restart the game.
![Adnotacja 2020-06-10 062358](https://user-images.githubusercontent.com/53737762/84226781-049e4200-aae3-11ea-80fc-c29d4095a10f.jpg)
