### ISSUE TITLE
Is there a more secure way to donate

### ISSUE THREAD

**Issue by sieversmatthew1610** [jeanropke/RDR2CollectorsMap#1015]
I absolutely love this map, and would love to donate to the creator, however my info has been stolen from PayPal previously, and would love another option to contribute $ for this amazing work!

**Comment by jeanropke** [comment]
Hey, thank you for considering to donate.
Sadly no, PayPal is easiest way to receive money from another countries in Brazil.

If you can't use PayPal, I'll be glad if you donate to charity or another cause.
