### ISSUE TITLE
Locations for Jewelry

### ISSUE THREAD

**Issue by Rodiboki** [jeanropke/RDR2CollectorsMap#1016]
Hi,
I could find something in places with wildflowers, tarot cards, bottles, eggs and family heirlooms. But in all the places with jewelry, arrowheads and coins, I find nothing.
Where is the problem?

Best regards 
Rodiboki

**Comment by MichalD96** [comment]
Hey, 
Do you have metal detector and shovel? Some items are only able to pick up with metal detector or shovel, if you dont have it you have to change to correct tool type (`Shovel` or `No tools`) in map settings. then map will show you only items you can pick up with tools you purhased from madam Nazar

**Comment by Rodiboki** [comment]
ok, I try it.
Thank You.
