### ISSUE TITLE
Items on map incorrect

### ISSUE THREAD

**Issue by CaptainSkips** [jeanropke/RDR2CollectorsMap#1017]
A new patch just came out for the game and I have already found a couple items that are not in the spots specified on the map.

**Comment by MichalD96** [comment]
Could you provide more info? What have you found and where? 
Enable option "Show coordiantes on click" and paste coordinates here

**Comment by CaptainSkips** [comment]
The Hajnal Garnet Bangle Bracelet is shown near Fort Mercer at Latitude: -118.625 Longitude: 41.1016 but I found it some where around Latitude: -37.5469 Longitude: 155.5703 buried in the ground. I also haven't been able to locate the Dane Topaz Necklace which is supposed to be at Latitude: -37.5469 Longitude: 155.5703

**Comment by MichalD96** [comment]
You found this random spot:
https://jeanropke.github.io/RDR2CollectorsMap/?m=random_item_92
Dane Topaz Necklace is in correct place here:
https://jeanropke.github.io/RDR2CollectorsMap/?m=necklace_dane_topaz

**Comment by CaptainSkips** [comment]
We changed servers and looked again, our metal detectors went off this time! We were in lobby with a hacker so that might've interfered with our collecting. Thank you so much for your help!
