### ISSUE TITLE
Madam Nazar location is wrong

### ISSUE THREAD

**Issue by ralejandrormz** [jeanropke/RDR2CollectorsMap#1019]
No sure if is a bug or simply the laction is not updated but often Madam Nazar is not where the map points.

Thanks.

Rafael.

**Comment by ralejandrormz** [comment]
Mistake on this, needed to reload the page.

**Comment by MichalD96** [comment]
Hey, you can click on madam Nazar marker and check if her position was updated, if everything is ok it should show you today's date
