### ISSUE TITLE
Knight of Cups is glitched (at least for me and my friends)

### ISSUE THREAD

**Issue by AcIdRedemption** [jeanropke/RDR2CollectorsMap#1020]
We have been collecting all the Tarot cards and other collectables tonight and the only one that is unavailable is the Knight of Cups at Benedict Point, it is not on the table nor anywhere else. If anybody has any ideas please let me know, if not just wanted to give a heads up.

**Comment by MichalD96** [comment]
Sometimes happens that items not spawn or you are unable to pick it up. You should change the session or restart the game, it helps in most cases.

If you play on PC and restart the game didn't help you can also delete all `.dat` files in temp folder
`C:\Users\<your user name>\AppData\Local\Temp`
