### ISSUE TITLE
 The quarter coin is bugged

### ISSUE THREAD

**Issue by Aassassinstyle99** [jeanropke/RDR2CollectorsMap#1021]
I want to say that 1792 quarter is bugged my friend and i we cant dig it(sorry if i used this feature with another use)
I ask if you please remaind  to our fellers collectors to not sell it

**Comment by MichalD96** [comment]
Hey, if you have problem to pick it up you should change the session / restart the game, it helps in most cases.
I collected this coin multiple times in this place and i am sure everything is fine with it, you only need to change session to spawn it.

**Comment by Aassassinstyle99** [comment]
thank you i tried but didnt work for my friend and i

**Comment by MichalD96** [comment]
Do you play on PC?
If restart the game doesnt work you can delete all `.dat` files from temp folder:
`%AppData%\..\Local\Temp`

**Comment by Aassassinstyle99** [comment]
No my friend and i  we play ps4

**Comment by MichalD96** [comment]
how many '1792 Liberty Quarter coins' you have?
Rockstar messed up this coins and if you have other 1792 coins you cant pick up this one anymore, the solution is to sell 1792 Liberty Quarter coins, then pick up 1792 Quarter and collect again coins that you sold.
You always need to collect 1792 Quarter first.
check this issue:
#850
