### ISSUE TITLE
1792 Quarter

### ISSUE THREAD

**Issue by zmbeh8r** [jeanropke/RDR2CollectorsMap#1022]
I have not been able to get this quarter hog for a week seven days straight if not eight. It is only queen or item for that matter that has this problem for me.

**Comment by MichalD96** [comment]
This is known bug, Rockstar messed up this coins and if you have other 1792 coins you cant pick up this one anymore, the solution is to sell `1792 Liberty Quarter coins`, then pick up `1792 Quarter` and collect again coins that you sold.
You always need to collect `1792 Quarter` first.
check this issue:
https://github.com/jeanropke/RDR2CollectorsMap/issues/850
