### ISSUE TITLE
How to import/export marked and hidden items?

### ISSUE THREAD

**Issue by T0SEMFREIO** [jeanropke/RDR2CollectorsMap#1026]
I removed / hid some items I already have from all collectibles (coins, cards, etc.) and then I unchecked the entire flower tab and then exported.

I reloaded the page (because the cycle changed) and then chose the file to import, when it imported only the flower tab was hidden but all the items that I deselected from the other tabs (coins, letters, etc.) were showing again.

There is no option to export / import the items that I deselect and do not want to show on the map because I already have them?

**Comment by MichalD96** [comment]
You dont need to reload the map to change cycles, map do this automatically. If you export the settings there should be all settings and items properties. It is possible that something removed your browser cookies, programs like Ccleaner do this in on the background. Post here the exported file, i will check what have been saved.

**Comment by T0SEMFREIO** [comment]
I access it in an anonymous tab, but I thought that exporting my bookmarks to a file and then importing it again would reload only the items that I checked, that didn't need to keep cookies in the browser. I reload the page because Madame Nazar doesn't change. I'll log in without an anonymous tab to see if it works. Thank you for your help.

Obs: my imported file is attached.
[collectible-map-settings-(2020-06-24).zip](https://github.com/jeanropke/RDR2CollectorsMap/files/4826888/collectible-map-settings-.2020-06-24.zip)

**Comment by MichalD96** [comment]
Madam Nazar position is no-cached so reload the map should always update her position if the position have been updated by server. Yes, incognito window don't save any collectables data, you have to use normal window.

**Comment by T0SEMFREIO** [comment]
I understood, thank you for your attention.
