### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xCODENAMEJellyx** [jeanropke/RDR2CollectorsMap#1029]
The Rhodes Saloon is currently bugged. Unable to even enter the building without the entire game crashing. Submitted a trouble ticket to Rockstar as well.

**Comment by MichalD96** [comment]
Do you play on console or PC?

**Comment by xCODENAMEJellyx** [comment]
Console, Xbox One

**Comment by MichalD96** [comment]
Everything works on PC
I tried to get in and out from the saloon a few times and nothing happened.
As far as i know you can't verify game files on the console, but if you are able to reinstall the game it may solve the problem
