### ISSUE TITLE
Day 1 Missing Harford Garnet Earrings lat: -90.5390625 lng: 89.578125

### ISSUE THREAD

**Issue by STG1993** [jeanropke/RDR2CollectorsMap#103]
Day 1 Missing Harford Garnet Earrings lat: -90.5390625 lng: 89.578125

**Comment by jeanropke** [comment]
I found the same item.
@iligalodin can you confirm too?

**Comment by iligalodin** [comment]
will look at it now

**Comment by iligalodin** [comment]
Item is already on the map

**Comment by STG1993** [comment]
Returned an item was there , it was missing in game
