### ISSUE TITLE
Unable to pick up item.

### ISSUE THREAD

**Issue by NomadikFlakk** [jeanropke/RDR2CollectorsMap#1030]
Today I found the 5 of pentacles tarot card in the barn. It's sitting on a window sill and neither the card or the moonshine bottle next to it are collectable at the moment. Nothing at all happens when I try to pick them up.

**Comment by MichalD96** [comment]
It is known bug, a few weeks ago i added a warning in item description about it,
you have to change the session (sometimes a few times) to pick up this card
