### ISSUE TITLE
Incorrect item Cycle: day #6 American Wildflowers Rhubarb

### ISSUE THREAD

**Issue by HFM1101** [jeanropke/RDR2CollectorsMap#1034]
Hi,

  No Wild Rhubarb today. Went to three different locations, not at any of these. Here are the links. Also seems to be issue/bug with coordinates, as I got the first lot for the first location but now the coordinates will not appear. Have tried to reset all, also unchecked and rechecked the 'show coordinates' option, plus refreshed page, still nothing. Here are the links at any rate:

https://jeanropke.github.io/RDR2CollectorsMap/?m=flower_wild_rhubarb_1

Latitude: -72
Longitude: 44.75

https://jeanropke.github.io/RDR2CollectorsMap/?m=flower_wild_rhubarb_9

https://jeanropke.github.io/RDR2CollectorsMap/?m=flower_wild_rhubarb_6

**Comment by MichalD96** [comment]
I didn't have any problem to find all flowers you listed. 
Flowers cycle is on 100% correct.
if you will have this problem in the future just change the session and everything should spawn agin.
Show coordinates on click also works as it should, probably you was clicking too close to the marker.
