### ISSUE TITLE
Incorrect item Cycle: day #2 Ebony hairpin 

### ISSUE THREAD

**Issue by Grapple201** [jeanropke/RDR2CollectorsMap#1036]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
Cycle is correct, try change the session or restart the game
