### ISSUE TITLE
Key/Legend/Explanations of Symbols & Text Colours

### ISSUE THREAD

**Issue by DoctorNefari0us** [jeanropke/RDR2CollectorsMap#1037]
While using the map in the last couple of days, I have noticed symbols and identifiers being added to collections/items that have some sort of issue. At time of writing there was a yellow exclaimation point beside the Family Heirlooms, and Random Spots lists; yesterday the 1800 Gold Dollar coin, and one of the pairs of earrings were written in red text, and the earrings' marker on the map had a red cross on it.

The problem is that what these markers mean is not immediately identifiable to new users, and there is no legend or key to understanding them provided either on the map, or on the map's wiki.

Can we please have a key/legend provided on the map, and in the wiki, of what these symbols, text colours, et cetera are intended to represent when applied to the collectables?

**Comment by MichalD96** [comment]
There is detailed info when you hover (or long press on mobile) over the option in menu.
![exclamation mark](https://user-images.githubusercontent.com/53737762/87837148-e15d7400-c892-11ea-9e02-78405d5127d3.png)

You are right that wiki should be updated, a lot have changed on the map.

**Comment by MichalD96** [comment]
New wiki:
https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide-(English)
