### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by huckleberry007** [jeanropke/RDR2CollectorsMap#1042]
Due to the current update cycle has appeared to change. I don’t know which cycle it is on but it’s not what is being shown on this site :(

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
yes, we are working on it
you can join our discord:
https://discord.gg/eRPCBDy
we post all map updates there

**Comment by Goose7** [comment]
I think there is more to this than just being on a different cycle.

I am finding items in the correct locations on the map today, but many of them are the WRONG ITEM in the correct category.  (Different Necklace than what the map says it should be for example)

Also... None of the Detector Spots I have gone to today are actually in the game.   (Dig spot next to the building in Emerald Ranch across from the Emerald Ranch Fence for example.)

**Comment by MichalD96** [comment]
yes
Categories that are still correct are: american flowers, cards, alcohol bottles, heirlooms, eggs, radom spots.

All jewelry sets have been randomized but locations remained the same.
Same with coins, but in "old" coin spot you can find only random coin.
In arrowhead spot you can find now only random arrowhead.

   `Also... None of the Detector Spots I have gone to today are actually in the game. (Dig spot next to the building in Emerald Ranch across from the Emerald Ranch Fence for example.)`

Cycle for random spoth have been updated an hour ago bc was wrong

**Comment by Goose7** [comment]
Thanks for the additional info.  That backs up what I had been observing over the course of my first session with the update today.

I read in the patch notes that they have actually added over (1000) NEW collectible locations in addition to some NEW collectibles that have not been in the game prior to today.  Obviously, all this is going to present a lot of issues for you guys to deal with, which I can only imagine is going to be a royal pain to sort out on your end.

As a big fan of your map... I wish you well and understand that this is not something that can be updated quickly.

Keep up the great work!  :o)
