### ISSUE TITLE
New Fossil Location for Map

### ISSUE THREAD

**Issue by Keegan-T-aP** [jeanropke/RDR2CollectorsMap#1043]
Found Oceanic Fossil: Sea Lily at location in attached image at 10:40 p.m. EST July 28th. Hope this helps to update the map with new Collector i
![15959908111214965937015436475660](https://user-images.githubusercontent.com/54673841/88750817-4f702980-d124-11ea-97a2-73fae5461a4e.jpg)
tems

**Comment by jeanropke** [comment]
Fossils cycles updated. Thanks.
