### ISSUE TITLE
Not able to Remove randomised items from Map

### ISSUE THREAD

**Issue by TearGod** [jeanropke/RDR2CollectorsMap#1044]
I noticed just a few minutes ago that I am not able to Remove random items on the map. Is there any way this could be fixed or changed so we can hide them if we wanted to? Or is there anything I can do to mark it for myself in some sort of way? Mostly just for me to know that I've either already been to that area or have gotten that item.

**Comment by Senexis** [comment]
Fixed. It now hides the randomized items when all the other corresponding categories are disabled.
