### ISSUE TITLE
Cephalopod Fossil (Thursday UTC location)

### ISSUE THREAD

**Issue by swampthiing** [jeanropke/RDR2CollectorsMap#1045]
Used the fossil collectors map
![DD519F7E-60E7-4BBB-B8F8-0621FD99C482](https://user-images.githubusercontent.com/68977399/88868042-1ba50a80-d1dd-11ea-8c41-6753c42acbb2.jpeg)
![A1642EA4-0358-4C4D-9CC1-B959E48D735E](https://user-images.githubusercontent.com/68977399/88868052-1f389180-d1dd-11ea-81c6-ddf9b63949fc.jpeg)

**Comment by jeanropke** [comment]
Updated. Thanks.
