### ISSUE TITLE
Behavior Uniformity for 'Random Items' Update

### ISSUE THREAD

**Issue by MoodyWA** [jeanropke/RDR2CollectorsMap#1046]
Right-click to hide is currently hiding all and not just the one specific instance. Would it be possible to give each random instance of the item a unique designation so each can be hidable individually?

Also, hide is not working for the arrowhead icons at all (via right-click or popup menu).

[Link to example](https://imgur.com/0COeXBN)

**Comment by MichalD96** [comment]
Fixed

**Comment by MoodyWA** [comment]
PS4 players might report the hide function not working on the Random Fossils icons (unsure if the group-hide is happening to those). Recommend checking all 3 PS4 icon sets to have them match the update you did to the arrowheads - awesome update btw.

**Comment by MichalD96** [comment]
Yes, i did it on purpose, we still need to change names of fossils sets. It will be fixed today.

**Comment by MoodyWA** [comment]
> 
> 
> Yes, i did it on purpose, we still need to change names of fossils sets. It will be fixed today.

Show-off  ; )
