### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Vitor-Borba72** [jeanropke/RDR2CollectorsMap#105]
My suggestion is to implement registration/login. Don't even know if that is possible. 
So you could access the map, with the icons you want, routes and stuff, across devices. 

Let's say I'm at work. I prepare a map for when I'm at home. That's my suggestion.

**Comment by jeanropke** [comment]
Not possible using Github pages. No server-side code running

**Comment by iligalodin** [comment]
we could make it so you get a link to your current map layout

**Comment by iligalodin** [comment]
related #39
