### ISSUE TITLE
Nie wyświetlają się znaczniki

### ISSUE THREAD

**Issue by v-Omerta-v** [jeanropke/RDR2CollectorsMap#1050]
Na mapie nie ma trzech znaczników przedmiotów potrzebnych madame nazar w tym tygodniu.

**Comment by MichalD96** [comment]
Nie ma, ponieważ nie da się określić gdzie dokładnie dany przedmiot jest. Prawie cała biżuteria, monety, groty, pamiątki rodzinne jest teraz randomowa. Pracujemy nad wieloma usprawnieniami, ale to jeszcze trochę zajmie.

**Comment by v-Omerta-v** [comment]
Ok. Dziękuję za informację i powodzenia.

sob., 1 sie 2020, 01:30 użytkownik Michal__d <notifications@github.com>
napisał:

**Comment by MichalD96** [comment]
Poczytaj sobie o wszystkich zmianach:
https://github.com/jeanropke/RDR2CollectorsMap/wiki/Naturalist-Update-Changes
