### ISSUE TITLE
Incorrect item Cycle: rings and earrings (2) and coins (1)

### ISSUE THREAD

**Issue by kitbxtch** [jeanropke/RDR2CollectorsMap#1051]
As of 1:57AM UTC, 8/2/2020, I've found that coins (cycle 1), rings (cycle 2), and earrings (cycle 2) are not accurately represented.  I've gone to several spots for each and not found the intended item, following the video and everything.  So far, I haven't found any others--the rest seem to be accurate for their cycle.  Will update with any others I've found.

EDIT: Including now necklaces, also cycle 2.

EDIT #2: Including now arrowheads, cycle 1.

Items I've not been able to get, specifically:
Harland Coral Ring - Cycle 2
Random Coin #5 - Cycle 1
Yates Diamond Ring - Cycle 2
Random Jewelry #11 - Cycle 2
Richelieu Amethyst Necklace - Cycle 2
Random Arrowhead #2 - Cycle 1

Collections I have been able to get:
Tarot (cups), cycle 2
Eggs, cycle 3
Tarot (pentacles, cycle 2
Alcohol bottles, cycle 1
Flowers, cycle 2

**Comment by MichalD96** [comment]
We had some problems to determine today's cycles, because even Rockstar's sources was wrong and everyone got different results. Map has been updated and now everything should be fine.
