### ISSUE TITLE
Incorrect random jewelry location: Random Jewelry #18 - Cycle 1

### ISSUE THREAD

**Issue by BlueFire1712** [jeanropke/RDR2CollectorsMap#1052]
The location seems to be incorrect as there is no collectible at the location.
Edit: also found the exact same issue with the Random Arrowhead #1 - Cycle 2 location.

**Comment by MichalD96** [comment]
We had some problems to determine today's cycles, because even Rockstar's sources was wrong and everyone got different results. Map has been updated and now everything should be fine.
