### ISSUE TITLE
Incorrect item Cycle: 1800 gold dollar 

### ISSUE THREAD

**Issue by rugerar224** [jeanropke/RDR2CollectorsMap#1054]
1800 gold dollar is really a 1792 penny
8/6

**Comment by MichalD96** [comment]
Seems that you use wrong map version
This is the only one correct (and original) map now:
https://jeanropke.github.io/RDR2CollectorsMap/

read also what have changed after the last RDO update:
https://github.com/jeanropke/RDR2CollectorsMap/wiki/Naturalist-Update-Changes

**Comment by rugerar224** [comment]
I am using the correct map. But I see thw coins and arrow heads are random
now, everything else has been correct.

**Comment by jawwal** [comment]
Hello there can you tell me how can I copy the location in my red dead map thanks 

Abdulrahman Alshamlan

**Comment by MichalD96** [comment]
It depends what you want to copy. You can enable `Show coordinates on click` and copy the position.
you can also `Add custom marker on click` and then export pins to the file
if you are more familiar with JavaScript you can use something like this to add markers on the map:
```javascript
items = [
    { "x": "/*lat coordinate*/", "y": "/*lng coordinate*/", "name": "" },
];

items.forEach(({ x, y, name }) => {
    Pins.addPin(x, y, null, name);
});
```
