### ISSUE TITLE
BUG: Show Weekly Collections

### ISSUE THREAD

**Issue by progtronix** [jeanropke/RDR2CollectorsMap#1058]
if using the "show all / hide all" buttons  then it works as intended and all items are removed from the map

if items are turned off individually, then weekly collections still stay on the map just the colour changes from green to the normal cycle colours

**Comment by jawwal** [comment]
Can you explain to me how to copy location on original map of the game 

Abdulrahman Alshamlan

**Comment by MichalD96** [comment]
@progtronix
> if using the "show all / hide all" buttons then it works as intended and all items are removed from the map
> if items are turned off individually, then weekly collections still stay on the map just the colour changes from green to the normal cycle colours

 Fixed https://github.com/jeanropke/RDR2CollectorsMap/commit/521dcf120385c4ad20f15aaf2046e9aad986426e

<br>

@jawwal 
> Can you explain to me how to copy location on original map of the game Abdulrahman Alshamlan

Next time please create new issue,
You can't copy the locations on your map in game. You have to check the map, and then manually mark the location in your game.
If you meant the location on our map, you can Enable `Show coordinates on click` then click the position on the map, and copy the coordinates.

**Comment by progtronix** [comment]
@MichalD96 Thank You :)
