### ISSUE TITLE
Weekly collection issue

### ISSUE THREAD

**Issue by Khaos-Wolf** [jeanropke/RDR2CollectorsMap#1059]
I play on PS4 and my weekly collection is different than the one listed. Normally everything by syncs up so well I had to report this. Below I will list the collection my game lists and under that the map’s weekly collection.

My game lists the Penny Collection:
1789 Penny
1787 One Cent Token
1796 Halfpenny

The map’s weekly collection is Naturalists:
Cherry wood Comb
Egret Egg
Bitterweed

**Comment by MichalD96** [comment]
Your browser cached the data and display wrong set. Try to simply reload the map, if this will not help, export your map settings, Remove all map settings, and import the settings again.

**Comment by MichalD96** [comment]
I just changed the way of caching weekly set data, it should update automatically, without manual page reload.
Let me know if that helped.

**Comment by MichalD96** [comment]
@Khaos-Wolf is that fixed the problem?

**Comment by Khaos-Wolf** [comment]
Yes, the list has been correct ever since.

Thank you for the help.
________________________________
