### ISSUE TITLE
Time correction on app

### ISSUE THREAD

**Issue by Whspringmoon** [jeanropke/RDR2CollectorsMap#1060]
Hi
I would like to know if something can be put in place to change the time on the map?
I am adding a screenshot to help explain.
For instance on the collector map it shows 6:51 am. For me it is actually 1:09 pm.
Can something be added to be able to make time match my time?
It used to match but since the changes, it does not match.
![Screenshot_20200820-130537](https://user-images.githubusercontent.com/69982579/90803370-a366cc00-e2e6-11ea-8f3c-e8787fe8180b.png)

**Comment by Whspringmoon** [comment]
Notice the time difference on my phones upper right corner and the maps time.
It matched before the changes were made. Can this be fixed?

**Comment by MichalD96** [comment]
Do you use this map in the browser or app from google play?
We dont have any app, this is the only one official map:
https://jeanropke.github.io/RDR2CollectorsMap/

it shouldn't match your time, first counter count time to cycles change. at 00:00 UTC time
Second timer is time in game, it is normal time (also UTC) sped up 30x
None of the counters shows your local time, every counter is only related to the time in game.
