### ISSUE TITLE
Ojeda Rose Gold Bangle Bracelet - Cycle 1

### ISSUE THREAD

**Issue by nachoha** [jeanropke/RDR2CollectorsMap#1062]
Item location is no longer accessible. The top of the slope shown in the video is now a slip zone and there doesn't seem to be any other path up.

**Comment by MichalD96** [comment]
It is hard to get there but not impossible, you need to jump there from good angle.
i did it in 3rd attempt.
![Adnotacja 2020-08-25 053539](https://user-images.githubusercontent.com/53737762/91129579-89dcd000-e6aa-11ea-8fb9-72702c4d1776.png)
