### ISSUE TITLE
Braxton Amethyst Necklace Cycle: 2#

### ISSUE THREAD

**Issue by CrazyyyDutchMan** [jeanropke/RDR2CollectorsMap#1064]
* 2
* Braxton Amethyst Necklace
![image](https://user-images.githubusercontent.com/26065182/91486030-fecb2800-e8ab-11ea-8690-32be50b1236b.png)

**Comment by MichalD96** [comment]
Look on your minimap in game, you are in completely different location and it is not this item.
you found this random spot: https://jeanropke.github.io/RDR2CollectorsMap/?m=random_item_34
