### ISSUE TITLE
Incorrect item Cycle: day 2

### ISSUE THREAD

**Issue by RogueFlame** [jeanropke/RDR2CollectorsMap#1065]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? hairlooms cycle 2

* Coordinates or a clear image of the location Latitude: -104.2656
Longitude: 55.1563

* Include the item name

Horse hair brush found in the chest in front of the smoking building next to the sheriffs office in Armadillo. This is in addition to the one in the saloon at black water, possibly 2 day cycles running at the same time

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
Since Naturalist update items may spawn on the map in differnet cycles, it is game bug.
