### ISSUE TITLE
Pin Highlight Feature NOT WORKING!

### ISSUE THREAD

**Issue by Huntress757** [jeanropke/RDR2CollectorsMap#1066]
I LOVE using this map. I use it every single day and it has helped me tremendously playing Red Dead Online. When I opened up the map this morning, I noticed that none of the Collector's items I had highlighted as "important items" were highlighted anymore. I tried to select any random pin on the map to highlight and nothing was happening. Not only were the previous items I had highlighted were still highlighted, but I could not highlight any news ones either. So I have no way of knowing which collector items I need to find to complete sets anymore and which ones I already have. I did notice that some of the pins still have the blue hue behind them. I am still trying to figure out what that means,but I am guessing that is the feature that shows which items I am low on in my inventory. I do have that selected in my options menu and that still works. This is the first time I have ever experienced an issue using this map, otherwise it has worked great for me.

**Comment by MichalD96** [comment]
After the Naturalist update i decided to remove `Mark as important` from random categories. but you can still mark as important items you need in menu (even if items are random) - all you need to do is right mouse click on the item (or long press on mobile). Every random category has disabled this option but if you highlight item in menu, and in some cycle item will be not random, map will highlight this marker on the map automatically. Check in what cycles you can find specific items from jewelry and heirlooms: 
https://github.com/jeanropke/RDR2CollectorsMap/wiki/Naturalist-Update-Changes

Coins and arrowheads are fully random and `Mark as important` will never work in this categories.
Also all items that are premanently disabled in certain cycles will be automatically enabled when item will be available.

Stroke around marker in color oposite to marker color means that item is low in your inventory.
Fading red glow around the marker means important item and similar glow but in white color means active night flowers. I recently updated map Wiki: 
https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide-(English)
you can check all map features there. I will add to the wiki naturalist changes soon.

**Comment by Huntress757** [comment]
There is only one way that I know of how to highlight pins on the map and that is to left click on a collectible to pull up the little menu and click on "mark as important" and it will put a red ring around the pin. I have only been doing that for collectibles that aren't randomized. It has been a HUGE help for me to be able to keep track of which collectibles I need to find to complete a set and when I find them, I remove the highlights as I go. For the randomized ones, I right click to remove them from the map so I know which ones I have already collected for the current 24 hour cycle. For some reason, it is not letting me highlight anything today and this is the first time it has not worked for me. It has been working well beyond the Naturalist update released, with the exception of the randomized collectibles of course. Without the ability to differentiate between which collectibles I already have and which ones I still need, makes things much more difficult, frustrating, and time consuming. I think I only collected less than 10 items today and they have all been close to my camp. I would be eternally grateful if you could look into the matter and try to resolve the issue. This map has been a lifesaver for me and I heavily rely on it. It has been my greatest source of income. Thank you for getting back to me so quickly and I appreciate the help.

**Comment by MichalD96** [comment]
It is weird that it stopped working for you now. I did this changes 2 days after the naturalist update and everything works fine for me. I need more info. First oped the map from this link:
https://jeanropke.github.io/RDR2CollectorsMap/?show-alert=1
Can you see any alert?
Do you use map on PC / console? On what browser? If on pc try to open the console (F12) then hide all items from map except cards and try to highlight any card as important from marker popup. Go to the menu and right-click on the same card. Is this card in menu is underlined on red? Make a screen of the console.

**Comment by Huntress757** [comment]
Yes I see an alert. I use the map on my Dell laptop. I use Google Chrome as my primary web browser. A bit confused by the "F12 console instructions". The easiest way for me to use the map is on my laptop cuz it's sitting right next to me while I play Xbox. It's so weird how it just randomly stopped working one day. I haven't done anything differently with it either lol. When I clicked on the card in the left-hand menu, it was underlined red, but the pin on the map never got the red shadow like it used to. I have tried the "reset all settings" hoping that might help, but it didn't fix it, unfortunately.
I also noticed one day, a while back, that the clock in the upper left corner no longer shows the time. It's just a blank white square now. It's not a big issue or anything,I can live with not seeing the time on the map. Just thought you might wanna know.

**Comment by MichalD96** [comment]
What is on this alert? About the console, when you have opened the tab with map press F12 on the keyboard
Click on 'console' and do every step i wrote in prev. message

**Comment by Huntress757** [comment]
I figured out the console. I pasted the code in console. I did the steps. The cards are underlined in red in the left menu, but I cannot get the pins on the map to highlight at all. Trying to figure out how to take aq screenshot of the console.

**Comment by MichalD96** [comment]
You can use `shift ÷ windows + s` or just make a pic with your phone

**Comment by Huntress757** [comment]
There are a bunch of "failed to load" error codes in the console window about the marker icons on the map. "server responded with a status of 404". Ok hang on a sec. Im gonna get some shots sent to ya.

**Comment by Huntress757** [comment]
![Annotation 2020-08-31 112401](https://user-images.githubusercontent.com/70472452/91737393-037a2f80-eb7d-11ea-97b8-02587d58ee8b.png)

**Comment by Huntress757** [comment]
![Annotation 2020-08-31 113044](https://user-images.githubusercontent.com/70472452/91737793-8d29fd00-eb7d-11ea-9d17-a0251fa59b6c.png)

**Comment by MichalD96** [comment]
It looks like bigger problem than only highlighting markers.
White clock background is caused by your browser extension that makes websites darker - "dark reader" or something like that, you need to disable it on the map

**Comment by MichalD96** [comment]
Do you have any extension that disables javaScript?
Try to open map in private window. And check the console for that 404 error
If jt will still happen try to install mozilla firefox and check the console.
This bug is not caused by map code. So.ething is wrong between your PC and the server

**Comment by Huntress757** [comment]
Oh yea that's right. I forgot the clock changed right after I switched my background theme. Sorry, I have been up all night and did not sleep. I completely forgot about that. I do remember thinking that could've been the cause. I don't know shit about coding, but maybe it is a problem with trying to use the map on Google Chrome? I'm gonna try using it on Microsoft Edge and see if that makes any difference. Gonna science it! lol
Reading through the console, it looked like something about the format of the map was not compatible and Chrome was not having it.

**Comment by MichalD96** [comment]
If it doesn't work on chrome it is very possible it will also doesn't work on edge because this browsers has the same engine. Would be the best if you can test it on mozilla firefox

**Comment by Huntress757** [comment]
same issue on edge. I will try disabling Javascript next.

**Comment by MichalD96** [comment]
No, don't disable anything
Try on mozilla firefox

**Comment by Huntress757** [comment]
Almost done.

**Comment by Huntress757** [comment]
**_YAY IT WORKS AGAIN!!!!!_**

**Comment by Huntress757** [comment]
You are a friggin miracle worker my dude ;) Thank you sooooooo much for taking the time to help me through this.

**Comment by Huntress757** [comment]
You have made my life much easier and my life sure could use some "easier" lol.

**Comment by MichalD96** [comment]
No problem :) i am glad it works.
But the issue with google chrome still exists, i will try to simulate this bug on my google chrome and check if is possible to fix it

**Comment by Huntress757** [comment]
Ok, as long as I have a way to use the map with the highlighting,I'll use any web browser.

**Comment by MichalD96** [comment]
btw join our Discord: https://discord.com/invite/eRPCBDy
you can get help much faster there, and maybe i may need some more info about this bug
