### ISSUE TITLE
I found an Arrowhead that was not on the map.

### ISSUE THREAD

**Issue by chuckzombie84** [jeanropke/RDR2CollectorsMap#1068]
I was searching for the "Random Heirloom #0 - Cycle 6" (Near Ridgewood Farm) with my metal detector and I found an Arrowhead not far from it that was not listed on the map (next to the larger of a pair of cacti). I'm not sure if random things like that can happen, but I figured I'd post it just in case anyway.  Screenshot of map: https://i.imgur.com/DjEvGp6.png

**Comment by MichalD96** [comment]
it is random item 181
https://jeanropke.github.io/RDR2CollectorsMap/?m=random_item_181
