### ISSUE TITLE
Collect map with no items on it

### ISSUE THREAD

**Issue by JACKAL-6568** [jeanropke/RDR2CollectorsMap#1071]
-Collectors Map has nothing on it apart from Madame Nazar and fast travel locations.
It's been working perfectly up until now. It's been reset, reloaded and nothing is hidden. I can't do anything with the Show All button, because everything is unhidden. Just collectables not showing up.

RDO Map is working fine. 

Both maps are showing correct time.

Help!-

RESOLVED

I typed something in the search bar and it all came back.

**Comment by Recoil86** [comment]
I'm have in this problem at the moment can't get any think on the map. 😭😭😭

**Comment by MichalD96** [comment]
Should be fixed in a moment, reload the map

**Comment by MichalD96** [comment]
if something still isn't working, you have to click `Reset all settings`

**Comment by Recoil86** [comment]
Working 👍🏻👍🏻👍🏻

**Comment by JACKAL-6568** [comment]
All fixed. Thanks!!
