### ISSUE TITLE
Incorrect item Random Jewelry #18 - Cycle 1 

### ISSUE THREAD

**Issue by whytheseaisboilinghot** [jeanropke/RDR2CollectorsMap#1073]
incorrect cycle. 
Jewelry #18 - Cycle 1 
Latitude: -108.8249 / Longitude: 28.3283
Is: cycle 1 (incorrect)
Should be : cycle 2 (correct)

**Comment by squirrel-37** [comment]
All cycle 1 items no where to be found. Using metal detector and can't find anything. By squirrel-37

**Comment by whytheseaisboilinghot** [comment]
> All cycle 1 items no where to be found. Using metal detector and can't find anything. By squirrel-37

Yeah, you can search for the items if you enable the ability to ajust to cycle 2, jewelry will be found on that cycle day.
