### ISSUE TITLE
Please tell me how you get the internal time from the game?

### ISSUE THREAD

**Issue by rubiqoff** [jeanropke/RDR2CollectorsMap#1075]
Please tell me how you get the internal time from the game? link? I would like to display it, for example, using FPS Monitor or other software.

**Comment by Senexis** [comment]
Here's our implementation: https://github.com/jeanropke/RDR2CollectorsMap/blob/0c3cbc97778d71f51b6ce54277ca0bd2883f037e/assets/js/scripts.js#L215

If you're not that technically inclined, here's a website dedicated to showing it: https://www.reddeadonlineclock.com/
