### ISSUE TITLE
Let people fill in the unknown marker what they find there daily

### ISSUE THREAD

**Issue by hossamsy** [jeanropke/RDR2CollectorsMap#1076]
Since there are lot of unknown markers on the map, let trusted people insert what they find in that marker, like a text box or something when you click on the marker, then at the end of the day people can go to specific marker and get the item if they don't have it

**Comment by MichalD96** [comment]
It doesn't work like that. Let's assume you collect items with a friend. Your friend found the coin you need. When you dig in the same place a few seconds later, you will get totally different coin. Your own game draws the item you will get. Every randomized spot works the same as regular random spots earlier. There is no pattern, and every player get different item from one spot.

**Comment by hossamsy** [comment]
Anyway, it is nerfed already I think, earrings and arrowheads and coins are totally nerfed there are 1-3 items at least not spawning at all in these collections, I have collected all random spots for many days then when I use purchased maps it says there are no items to collect, it is not your map that is missing items, those missing items are not included in the map at all anymore.

**Comment by MichalD96** [comment]
It is all about luck. Since naturalist update i completed at least 5 sets of each random set so definitely you can find every item on the map. All locations are directly from game files, so we are sure we have every possible item location on the map.
Look on the loot table for the coins,
from every random coin spot you can get any random coin from this list:
![obraz](https://user-images.githubusercontent.com/53737762/92987223-ef112d80-f4c0-11ea-8523-b17460a2164c.png)
you have 2% chance to get the rarest coins.

**Comment by MichalD96** [comment]
About jewelry and heirlooms - look on my tables when you can look for specific items:
https://github.com/jeanropke/RDR2CollectorsMap/wiki/Naturalist-Update-Changes

**Comment by hossamsy** [comment]
Quartz Arrowhead, Endicott Diamond Earrings, Beauchene Ruby Earrings, Emmeline Coral Earrings not spawning in any cycle since last 3 weeks for me, after naturalist update I was able to get full collections until last 3 weeks I stopped getting those items at all, even when using purchased maps, they are not showing anywhere although I have gotten those items after the naturalist until I stopped getting them at all in the past 3 weeks, nerfing happened after the update, it happened at the second update after the naturalist.

**Comment by hossamsy** [comment]
I found the Quartz in random gray spot, I will try to get the 3 earrings and finish the collections, weird that I have finished everything on map before and still didn't get those items

**Comment by hossamsy** [comment]
I finished all random spots and all jewelry spots, Beauchene Ruby Earrings is still now show, others all found
