### ISSUE TITLE
Found Jade hairpin item Cycle: day #6 

### ISSUE THREAD

**Issue by LouPol** [jeanropke/RDR2CollectorsMap#1077]
[RDR2 Online Jade Hairpin.pdf](https://github.com/jeanropke/RDR2CollectorsMap/files/5221790/RDR2.Online.Jade.Hairpin.pdf)

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 
6

* Coordinates or a clear image of the location
not sure how to do this but see attached pdf, 

* Include the item name
I found the Jade Hairpin in the "S "of New Austin there is a lock box which was glowing next to what appears to be a campfire with a pot & boot in it.

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
It is Random Item #20
https://jeanropke.github.io/RDR2CollectorsMap/?m=random_item_20

**Comment by MichalD96** [comment]
Make sure you have enabled Random spots in menu:
![Adnotacja 2020-09-13 205750](https://user-images.githubusercontent.com/53737762/93152152-359f9b80-f6fe-11ea-9d6a-c8a080f68375.png)

**Comment by LouPol** [comment]
its not showing under family heirloom cycle #6

**Comment by MichalD96** [comment]
Because this is random item. From this spot you can get any item from this list: https://github.com/jeanropke/RDR2CollectorsMap/wiki/Random-Item-Possible-Loot
It is independent from any category. Also if anyone else go to this location will find completely different item.
