### ISSUE TITLE
10.22pm role mission changed

### ISSUE THREAD

**Issue by T0rNaDo69** [jeanropke/RDR2CollectorsMap#1078]
the 10.22pm role mission

that should be protect legendary animal (aligator)

looks like its been replaced with a  day of reckoning

because for the past 5 days 

day of reckoning has come up at 10.22pm instead of the PLA mission.

**Comment by MichalD96** [comment]
thank you
yes, free roam events order change a lot lately. We will fix it soon

**Comment by MichalD96** [comment]
All events should be correct now
