### ISSUE TITLE
Item not at location In wapatii the 

### ISSUE THREAD

**Issue by DocHunt** [jeanropke/RDR2CollectorsMap#1081]
There is NO family heirloom in the wapatii location on your map. Wondering if there is a new cycle

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
it is definitely there
![obraz](https://user-images.githubusercontent.com/53737762/94352989-548e1e00-006c-11eb-9d6f-e3f11e37c3a0.png)
try change the session or restart the game

**Comment by DocHunt** [comment]
OK will do thank you for the timely response

Sent from my Sprint Samsung Galaxy S10.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DocHunt** [comment]
________________________________
