### ISSUE TITLE
Spoonbill egg Cycle5 day #

### ISSUE THREAD

**Issue by kolonelwoefke** [jeanropke/RDR2CollectorsMap#1082]
* Cycle 5
* Latitude: -78.125
Longitude: 135.5313
* Spoonbill Egg
Egg can not be shot down, when shot the nest will disappear but the egg will still be stuck in the tree.

**Comment by MichalD96** [comment]
After the naturalist update all eggs seems to have such problem, depends on session.
You can try change the session and there is a little chance that this egg finally fall from the tree.
