### ISSUE TITLE
Incorrect item Cycle: day # 1

### ISSUE THREAD

**Issue by DocHunt** [jeanropke/RDR2CollectorsMap#1083]
Looking for the boar bristle brush. It's not on the table. I found the random metal detection dig spot here but no brush. I have logged out and logged back in I have refreshed the map in my web browser I have deleted the cash in my web browser it's just not here just thought I'd let you know. This map is amazing I'm not complaining I just wanted to bring it to your attention  thank you for all your hard work that goes into this 

![20201006_032821](https://user-images.githubusercontent.com/71951354/95190498-459e1e80-0784-11eb-96df-3117f07532b3.jpg)
![20201006_032821](https://user-images.githubusercontent.com/71951354/95190511-4b93ff80-0784-11eb-88a9-cde316038e2c.jpg)

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by DocHunt** [comment]
I have no idea why it posted the same picture here is the other picture I was trying to send
![Uploading 20201006_032850.jpg…]()

**Comment by MichalD96** [comment]
Hey, we are glad you like the map. I guess it is game bug, it happens very often lately. If you are able to find any other heirloom marked on the map, this one also should be there. 
You can try change the session or restart your game.

**Comment by MichalD96** [comment]
i just found this brush, so definitely it is game bug
![Zrzut ekranu 2020-10-07 012341](https://user-images.githubusercontent.com/53737762/95270500-e0a5ff80-083b-11eb-8c7d-a7a98fc3981b.png)
