### ISSUE TITLE
madam nazar not showing

### ISSUE THREAD

**Issue by T0rNaDo69** [jeanropke/RDR2CollectorsMap#1084]
hi all, madam nazar not showing on the map today ?
thought il let you know..

any idea's where she is today.

cheers all.

**Comment by MichalD96** [comment]
We hava a little problems with the server today, that's why she is not on the map.
she is there:
![Zrzut ekranu 2020-10-06 195523](https://user-images.githubusercontent.com/53737762/95241401-fc92ac80-080d-11eb-962e-f8599e2ed033.png)

**Comment by T0rNaDo69** [comment]
aww ok no worries, glad you know that she isn't showing... and thanks for telling me where she is.
