### ISSUE TITLE
tarot card cycle today? 

### ISSUE THREAD

**Issue by JRSC01** [jeanropke/RDR2CollectorsMap#1087]
at the house just under the 'r' in Forest (Cumberland) there was a 5 of Wands Tarot Card not listed under todays cycle which was cycle 5, but is under cycle 2.
![16022702526044503240392228554625](https://user-images.githubusercontent.com/53097543/95622084-b25a3700-0a6a-11eb-8667-4e7b3f548b39.jpg)
![16022702984056018540394918887981](https://user-images.githubusercontent.com/53097543/95622110-c0a85300-0a6a-11eb-9c0d-c2f8961b9926.jpg)

https://jeanropke.github.io/RDR2CollectorsMap/?m=wands_five

**Comment by JRSC01** [comment]
Also at same location the skulls table there was a king of pentacles,  cycle 6, but the map defaults to cycle 5 today for this,  is this an issue on my side, as it is unusual

**Comment by MichalD96** [comment]
This is the issue with R* servers, after the last update items spawn in different cycles, sometimes don't spawn in certain sessions - one big mess...
If you have that situation try to change the session or restart the game, it should reload saved data and spawn items in correct location

**Comment by JRSC01** [comment]
thanks, i thought it was strange, seems ok fixed.
