### ISSUE TITLE
Incorrect item Cycle: day #5

### ISSUE THREAD

**Issue by gold007eye** [jeanropke/RDR2CollectorsMap#1088]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 5

* Coordinates or a clear image of the location
Latitude: -79.1641
Longitude: 137.8438

* Include the item name: Antique Alcohol Bottle - Scotch Whiskey Bottle
Inside the shack on the table to the right, right-hand side.

![image](https://user-images.githubusercontent.com/4365462/95655303-e31e8880-0acb-11eb-9752-8daa1baf63e0.png)

![image](https://user-images.githubusercontent.com/4365462/95655262-963ab200-0acb-11eb-9889-9d46f3ff8c09.png)

**Comment by MichalD96** [comment]
This whiskey remained there from previous day, it is the game bug, it happens very often after the naturalist update. Some items spawn in incorrect cycles, some items don't spawn i certian sessions. In most cases change the session/ reload the game fix that problem.
