### ISSUE TITLE
A small correction on 2 objects

### ISSUE THREAD

**Issue by Gromino** [jeanropke/RDR2CollectorsMap#109]
Sorry for the last false one, I didn't think the objects we dig up without the metal detector could be random.

So.

On day 1, I followed the map and 2 items are not indicated correctly

Here are the screenshot and location : 

Infanta Turquoise Bracelet - Day 1
https://i.imgur.com/XGNJ6xK.png
is not finding by metal detector, and is in a chest, on the big central rock just on top of the waterfall

Thorburn Turquoise Ring - Day 1
https://i.imgur.com/hkuuph2.png
Is find with the metal detector

**Comment by iligalodin** [comment]
thanks! will submit a commit
