### ISSUE TITLE
Map Not Reloading

### ISSUE THREAD

**Issue by KirsiValsheer** [jeanropke/RDR2CollectorsMap#1093]
Nothing on the map is reloading for any of the collectibles

**Comment by MichalD96** [comment]
Could you provide any more info? 
Why you think like that? 
can you see any errors?
What browser do you use (PC / mobile)?
are items in wrong spots?

**Comment by MichalD96** [comment]
i just noticed we talked about it on Discord (https://discord.com/channels/631510938016677889/669898569318137865/769254556613738527)
is that solved the problem?

**Comment by MichalD96** [comment]
If you still have any problem with map, reopen the issue, but i saw on the screenshot that everything was correct on your map,
