### ISSUE TITLE
Madam Nazar isn't appearing on the map

### ISSUE THREAD

**Issue by RatBatCat** [jeanropke/RDR2CollectorsMap#1094]
Madam Nazar isn't appearing on the jeanropke map at all. Toggled on/off, cleared cache, nothing.

**Comment by MichalD96** [comment]
yes, we know about it, we have problem with the server.
Dailies, madam nazar location, and weekly set are unavailable now.

**Comment by laughinCorpze** [comment]
Its been more like 1 wk and 2 days since I've seen her on the map

**Comment by MichalD96** [comment]
Fixed
