### ISSUE TITLE
Incorrect item Cycle: #4

### ISSUE THREAD

**Issue by DocHunt** [jeanropke/RDR2CollectorsMap#1096]
The goose eggs were not here. I've included a picture which if you zoom in on the mini map you can see that I'm in the right spot and they are just not there. I joined a new session, as well as reloaded the map in my browser I just wanted to let you know. Thank you
![20201023_203355](https://user-images.githubusercontent.com/71951354/97067174-a8a6f800-156f-11eb-8961-687ca2a44af3.jpg)

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
In this spot should be duck eggs not goose. Goose eggs are there: https://jeanropke.github.io/RDR2CollectorsMap/?m=egg_goose
and duck eggs are also in correct spot:
![Zrzut ekranu 2020-10-24 065859](https://user-images.githubusercontent.com/53737762/97068287-91472980-15c6-11eb-998c-0ba1fd2f80c3.png)
if changing the session/ reload the game doesn't work, you have to wait until next cycle reset. It is a game bug

**Comment by DocHunt** [comment]
OK thanks
________________________________
