### ISSUE TITLE
Spawn time of the panther

### ISSUE THREAD

**Issue by Outlaw247** [jeanropke/RDR2CollectorsMap#1098]
The new panther near Rhodes stated spawn time is wrong it says 6pm to 9pm?

**Comment by MichalD96** [comment]
yes, what is wrong with this spawn time?
This values are directly from game files so i doubt that something is wrong.

**Comment by Outlaw247** [comment]
Oh right ok, just i know i didnt find it at that time and seen people saying its between 5pm to 5am for 1 panther and 8pm to 8am for the other thats all, just thought the 3 hours was too short but if thats showing the beat time for it then great 👍  i think ive been unlucky with that time tho personally
