### ISSUE TITLE
Bug: Madam Nazar not on map

### ISSUE THREAD

**Issue by malcolmhart67** [jeanropke/RDR2CollectorsMap#1099]
A couple of weeks ago, I noticed Madam Nazar's location is not appearing in the map. I gave checked this with multiple browsers and tried toggling her location on and off with no success. Hopefully there's an easy fix.

**Comment by Golko** [comment]
I dont see it also

**Comment by MichalD96** [comment]
madam Nazar should be visible on the map since 12 hours,
there still can be problems on mobile, because of cached data, but when she change the location it should be updated everywhere

**Comment by malcolmhart67** [comment]
I have tried this on multiple platforms, both mobile and desktop with a number of different browsers. I regularly clear my browser cache, particularly on my MacBook and have it to delete the cache on my Windows Desktop PC. I have not seen Madam Nazar on the map for at least two weeks. I have just checked on my MacBook as I type this reply, and her location is still missing from the map. I have hidden every other icon in the settings, so she's not being hidden by one of them either.

**Comment by MichalD96** [comment]
Can you try open the map in incognito window?

**Comment by malcolmhart67** [comment]
The same result. I teach IT and these are all steps I regularly use to help people troubleshoot websites. I have done multiple tests and Madam Nazar's location is not showing up on the map. Have you at least checked to see if there is an issue?

**Comment by MichalD96** [comment]
Everything works for me, but i just updated nocache on the map, lets see if that help. I see her location on the map, weekly set and dailes. it is all on the same API, 
I know there is problem because not only you have that issue, but it is hard to say where exactly the reason is.

**Comment by MichalD96** [comment]
And i also can't force my mobile browser to update her position

**Comment by MichalD96** [comment]
ok, i found the error, it is related with our API

**Comment by malcolmhart67** [comment]
OK it now seems to be working in Windows using Edge, doesn't work with Chrome. Isn't working with either Safari or Chrome on MacBook. Isn't working with Chrome or Samsung Internet on Android. Isn't working with Safari on IOS. Hope this is at least some help. If I recall correctly, it might have got broken with the Halloween Update? I don't recall if it had problems before that, but it definitely hasn't been since then.

**Comment by MichalD96** [comment]
For some reason everything works on firefox.
Issue is related with our server, we decided to change way of caching data, because server got overloaded lately, and it needs some changes in the php headers.
it schould be fixed soon

**Comment by malcolmhart67** [comment]
OK I'll give you more feedback tomorrow if I find any issues. Hope I have been some help at least.

**Comment by malcolmhart67** [comment]
Had a quick look this morning and it seems to be working on my platforms,. Thanks again for your help.

**Comment by MichalD96** [comment]
You are welcome 😉

**Comment by jayirvinh** [comment]
madam nazar isnt showing up for me now on chrome
