### ISSUE TITLE
Not an issue, but a suggestion. 

### ISSUE THREAD

**Issue by Vitor-Borba72** [jeanropke/RDR2CollectorsMap#11]
It'd be cool if we could "select all" or "unselect all" kinds of treasure. 
Also, as a plus, if we could remove from the map the icons of treasures we have already picked up. 
And man, thank you very much for your effort on making this map.

**Comment by iligalodin** [comment]
i've created a pull request for the beta map

**Comment by jeanropke** [comment]
Added an option to remove markers from map. Remember to enable them again once finished on menu.
