### ISSUE TITLE
Possible updated item spawn

### ISSUE THREAD

**Issue by markonaoum** [jeanropke/RDR2CollectorsMap#1100]
Not completely sure if what I am saying is true, but here it goes anyways.

I was collecting the coins and found out that me and a friend were collecting the same exact coins. Not sure how the random spawn works and if it affects one person or all, and I may be completely wrong as I have no knowledge of this, but just thought i'd put it out there to be said that we were yielding the same coins from the same locations whilst collecting.

**Comment by MichalD96** [comment]
That is interesting. Could you write what coin you found and where? I will check that too in the game. You can open marker popup and click `Copy marker link`, that will give me the location

**Comment by markonaoum** [comment]
Not sure if what I said is valid or not, since after collecting every coin I did not collect the whole set, so may have had some randoms but will try to run some tests with a friend on collector runs when I can and will report back. Perhaps the random spawn is meant as a global randomizer and not individually, and that's what had me confused.
Will reply back with my results soon hopefully.
