### ISSUE TITLE
Correction to the Random Arrowhead #2 - Cycle 2 spot

### ISSUE THREAD

**Issue by cchovet** [jeanropke/RDR2CollectorsMap#1101]
Hello,
The spot for the  Random Arrowhead #2 - Cycle 2 is a dig site (shovel) and does not need a metal detector.
https://jeanropke.github.io/RDR2CollectorsMap/?m=arrowhead_random_2
Thanks a lot for these superb tools !

**Comment by MichalD96** [comment]
Thanks for reporting the bug. Fixed
