### ISSUE TITLE
Ground Eggs (Loon to be specific)

### ISSUE THREAD

**Issue by SadPlaY** [jeanropke/RDR2CollectorsMap#1104]
Ground eggs location are never there. Everytime I try and go to an egg location that is found on the ground, there is nothing there.

**Comment by MichalD96** [comment]
It is game bug, change the session or restart the game, and eggs will be there

**Comment by SadPlaY** [comment]
I realized I'm a dumb ass and had the max amount I can carry so they don't appear lmaooooo
