### ISSUE TITLE
Incorrect item Cycle: 6

### ISSUE THREAD

**Issue by Dumpster1845** [jeanropke/RDR2CollectorsMap#1107]
Bloodflower #2 - Cycle 6 is not appearing

**Comment by MichalD96** [comment]
It is very common game bug, change the session or restart the game, and flower will be there.

**Comment by MichalD96** [comment]
Make sure also you are in correct time, this flower spawn only between 22:00 and 5:00 game time

**Comment by Dumpster1845** [comment]
Thanks. Yeah I was there at the correct time and joined a new session but it didn’t appear.

**Comment by MichalD96** [comment]
Yeah, in most cases restart the game should solve that problem
