### ISSUE TITLE
Problem with Spoonbill Egg - Cycle 5

### ISSUE THREAD

**Issue by sigh-itsLJT** [jeanropke/RDR2CollectorsMap#1108]
Item location is correct, but egg never seems to drop out of tree. The nest and egg appear and you can shoot the nest, but the egg stays on the branch and glows. This location is consistently buggy and should probably be marked broken. Thank you!

**Comment by MichalD96** [comment]
I just removed it because it is possible to to get this egg. I added also detailed description how to do it: 
```
This egg in particular can often get stuck in the tree. If that happens, call for bounty wagon, 
climb on top of it, then shot the nest and egg with varmint rifle using the scope.
```
i know that bounty wagon is not standard equipment for collector, but everyone have it anyway.

**Comment by Dumpster1845** [comment]
This method using the bounty wagon does not work for me. I’m right next to the tree beach and can’t grab the egg
