### ISSUE TITLE
Only Show Low Count Items

### ISSUE THREAD

**Issue by progtronix** [jeanropke/RDR2CollectorsMap#1109]
was wondering if it was possible to add a feature to only show the low count items for the day... as maybe i dont want to collect the whole map but i have odd sets so if i want a quick day i can see just the low count items.

filter markers does not have an option for it.... but it may be more suited to be like a hidden option untill "show low count items" is enabled? i can see there is an animated glow now that is recent (or i  just didnt notice it before) but all of the effort to make them stand out around the other less important items when there could be an option to turn the less important ones off... even maybe have a depth option aswell to set what is considered low?

on a side note.... a bounty timer would be helpful at the top right maybe of the screen... very simple timer with stop/start/reset, as bounty hunting and collecting to run the timer down is a good way to play... it would make it so much easier if the colleector map had a small timer somewhere

**Comment by MichalD96** [comment]
I added option to show only items with amount < X in your inventory (inventory must be enabled)
![low_inv_items](https://user-images.githubusercontent.com/53737762/110270801-f3795780-7fc6-11eb-9e82-f894207f0ed5.jpg)
