### ISSUE TITLE
Missing Item Bluewater Marsh

### ISSUE THREAD

**Issue by huntermcdaniel1** [jeanropke/RDR2CollectorsMap#111]
- Cycle: Day 1

- Location: Bluewater Marsh, Lemoyne (lat: -70.361979484558,  lng: 150.6979169845581)

![Feldspar Arrowhead](https://user-images.githubusercontent.com/56137140/66164571-f701f580-e600-11e9-8929-439c1a930c17.png)

![Red Dead Redemption 2](https://user-images.githubusercontent.com/56137140/66165432-b4411d00-e602-11e9-8753-e41a1118f2a7.png)

- Feldspar Arrowhead (Non-Metal Detector Dig Spot)

**Comment by jeanropke** [comment]
I found Jade Hairpin.
Random item spot.
