### ISSUE TITLE
Incorrect item #50 Cycle 6: day ?

### ISSUE THREAD

**Issue by mago1337** [jeanropke/RDR2CollectorsMap#1110]
* What day cycle it is? Not sure?
* Coordinates or a clear image of the location: the same as shown on the map
* Include the item name: Carved Wooden Hairpin

I got it at a location where the loot table included in the map said it shouldn't happen. Not sure what's wrong here — just wanted to report it.

ETA: Upon further inspection, it is actually listed in the Wiki. Sorry.

**Comment by MichalD96** [comment]
Nice found, accidentally i removed too much when i made all heirlooms as static items.
Fixed
