### ISSUE TITLE
wrong cycle

### ISSUE THREAD

**Issue by franke420** [jeanropke/RDR2CollectorsMap#1111]
Things are not where the map says

**Comment by BrennonTWilliams** [comment]
I'm having the same problem. Tried with four different items, none were there. The cycle is off.

**Comment by MichalD96** [comment]
It is game bug, it happens from time to time. You can try to change the session 2 - 3 times or restart the game. 
If you play on PC you can close the game (important) and delete all `.dat` files from this location: `%localAppData%\Temp` (these are cache files)
If you play ont the console just turn it off, unplug power cable for 30 sec, that should also delete cache files
That always solve the problem
