### ISSUE TITLE
The website doesn't show the cycle numbers like before. 

### ISSUE THREAD

**Issue by elyaspacha1** [jeanropke/RDR2CollectorsMap#1113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by elyaspacha1** [comment]
the website doesn't show cycle numbers.

**Comment by MichalD96** [comment]
Yes, we removed it because for most people it is useless info. Map is always up to date.  You can still enable it in Customization tab => `Enable cycles display`
