### ISSUE TITLE
iPad Resolution/Zoom Issue

### ISSUE THREAD

**Issue by bostonxo** [jeanropke/RDR2CollectorsMap#1116]
Recently on my iPad, the map has been zooming out and to fix this I need to reload the map or leave in general. It is beyond frustrating and it would be great if this issue could be resolved. I also tried on another iPad and same issue happens.

Picture of proof attached, thanks!

![168E8FFF-A0FA-4B80-AB96-A8A58C641682](https://user-images.githubusercontent.com/77898032/105612451-4cc85700-5d8a-11eb-86d1-f8b8e3745e38.png)

**Comment by MichalD96** [comment]
iOS and mac OS cause many problems on the map. We can't do much about it. That bugs are related only with apple devices. You can try to use map on google chrome or mozilla firefox, on this browsers bugs are not that likely to occur like on safari
