### ISSUE TITLE
Incorrect item: Scotch Whisky Bottle

### ISSUE THREAD

**Issue by TexasP0onTappa** [jeanropke/RDR2CollectorsMap#1117]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? **01:12:30**
* Coordinates or a clear image of the location  **Latitude: -79.4063
Longitude: 137.7891**
* Include the item name  **Scotch Whisky Bottle**
_~ Didn't find a new location. But I did find a hairbrush, And a tarrot card in the cabin instead. I cannot tell you what I found because I disconnected almost immediately after._

**Comment by MichalD96** [comment]
it is game bug, in most cases change the session or restart the game should fix it
