### ISSUE TITLE
[QoL] Renaming "Utils" to "Utilities" in the item list.

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#112]
See title.

In addition to that, please change "Fast travel" to "Fast Travel". 

Very minor "issues", I know, but I saw it immediately. 

Thanks for reading.

**Comment by jeanropke** [comment]
Changed. It will take a few minutes to update the files.

**Comment by jeanropke** [comment]
Press Ctrl + F5 to force update https://jeanropke.github.io/RDR2CollectorsMap/langs/en-us.json

**Comment by Rakmarok** [comment]
Thank you.
