### ISSUE TITLE
Incorrect item Cycle: day # 3

### ISSUE THREAD

**Issue by CompulsiveCollector** [jeanropke/RDR2CollectorsMap#1122]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 3
* Coordinates or a clear image of the location Latitude: -56.0234
Longitude: 128.6563
* Include the item name rosewood hair brush

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by CompulsiveCollector** [comment]
It appears most, if not all, of the map is incorrect today.

**Comment by CompulsiveCollector** [comment]
Cycle 2
Latitude: -56.7266
Longitude: 129.4375
arrowhead

**Comment by CompulsiveCollector** [comment]
unmarked Nine of cups Tarot Card at 
Latitude: -77.9766
Longitude: 154.8672

**Comment by CompulsiveCollector** [comment]
Missing
Spoonbill egg  Cycle 1
Latitude: -74.9141
Longitude: 155.6094

**Comment by MichalD96** [comment]
It is very common game bug. To fix it you have to restart your game.
If you play on PC you can delete the cache files. go to this directory in Windows file explorer `%localAppData%\Temp` and delete all `.dat` files.
If you play on console, turn it off, unplug power cable for around 30 seconds.
It always solves the problem.

**Comment by Symbai** [comment]
Confirmed, what @MichalD96 said fixes it.

**Comment by CompulsiveCollector** [comment]
Indeed, that did work. Thank you! Been using that map for ages and never once encountered that issue before.
