### ISSUE TITLE
Not the right date

### ISSUE THREAD

**Issue by mariepierdg** [jeanropke/RDR2CollectorsMap#1127]
On the top of the screen the date is march 12th and we still are march 11th... east time .... ?

**Comment by MichalD96** [comment]
Map works in UTC/GMT time because cycles change exactly at 00:00 UTC time.
You can read more about it here in map wiki: [Wiki](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide#the-collection-cycles--collection-cycle-change-time)
