### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by W3Warp** [jeanropke/RDR2CollectorsMap#1128]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

I will be more accurate next time. But there are 3 collection items at Braithwaite Manor. One bottle downstairs on the dinner table. And one more Family Herlume upstars, on a fireplace. And one in a Big chest infront of the bed. 20210314

**Comment by MichalD96** [comment]
It is very common game bug, change the session or restart the game to fix it.

**Comment by W3Warp** [comment]
LOL fix what???

**Comment by MichalD96** [comment]
When you change the session or restart the game, then all items will be exactly where map says it should be.

**Comment by W3Warp** [comment]
> When you change the session or restart the game, then all items will be exactly where map says it should be.

Okey, GTK, but then I got more items then I should have today, so that's a win =)

**Comment by MichalD96** [comment]
Yes, but map shows cycles that are correct for everyone. If you can find something that is not on the map, then it is game bug - noone else can find this items except you. Collector cycles are very buggy and very often two players even in the same session have different cycles. We are not sure what cause that issue, but in most cases change the session reload items locations and everything is in place where map says it should be. Everything on the map is directly from game files so its almost impossible that map can be wrong.

**Comment by W3Warp** [comment]
> Yes, but map shows cycles that are correct for everyone. If you can find something that is not on the map, then it is game bug - noone else can find this items except you. Collector cycles are very buggy and very often two players even in the same session have different cycles. We are not sure what cause that issue, but in most cases change the session reload items locations and everything is in place where map says it should be. Everything on the map is directly from game files so its almost impossible that map can be wrong.

Well, then tell me this. How come the other items on the map around the area are correct? it don't bother me, i just wrote to help out.

**Comment by MichalD96** [comment]
It is just R* script failure. Cycles are random for each category, so one can be generated correctly and others not
