### ISSUE TITLE
social club site inventory synchronization

### ISSUE THREAD

**Issue by SajinX** [jeanropke/RDR2CollectorsMap#1129]
is that possible?
like on rockstar site you can see full inventory/roles/etc/etc...
could that be added as some kind of login to map feature?
was that thing already  requested and denied? or what?
because as i see if that feature possible.
it could add lot more than just inventory sync
but also auto collection counter(and slightly better route generation by auto knowing what items in inventory)
auto marker disabling(at least for known items)
and who knows what more it can give...

**Comment by MichalD96** [comment]
We tried since R* added inventory to social club, but for now it is not possible on any reasonable way that everyone would be able to do.

**Comment by SajinX** [comment]
> 
> 
> We tried since R* added inventory to social club, but for now it is not possible on any reasonable way that everyone would be able to do.

that's sad....
