### ISSUE TITLE
UI Issue on Map

### ISSUE THREAD

**Issue by huntermcdaniel1** [jeanropke/RDR2CollectorsMap#113]
I didn't know if anyone had caught this yet.  But the filter label for Lost Jewelry Earrings and Lost Jewelry Necklaces are reversed. The icons next to the text are correct and point you to the correct type of item. 

<img width="210" alt="rdr map error" src="https://user-images.githubusercontent.com/56137140/66167960-ca061080-e609-11e9-9fa1-b4f8d512f0fc.PNG">

**Comment by iligalodin** [comment]
i'll fix it in a second

**Comment by jeanropke** [comment]
I mess up with translation files
