### ISSUE TITLE
Incorrect item Cycle: day #5

### ISSUE THREAD

**Issue by SalmonClaus** [jeanropke/RDR2CollectorsMap#1133]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 5
* Coordinates or a clear image of the location; small island by Quaker Cove
* Include the item name; duck egg

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
It is egg encounter:
https://jeanropke.github.io/RDOMap/?q=egg_encounter
