### ISSUE TITLE
Map is blown out to bright yellow, cannot see details.

### ISSUE THREAD

**Issue by bukeau** [jeanropke/RDR2CollectorsMap#1139]
Map is blown out to bright yellow, cannot see details.

**Comment by MichalD96** [comment]
Can you send any photo where the problem is? Make sure your monitor settings are correct, and is not set too bright.
Also you can change map view to dark mode (check [Wiki](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide#basic-map-functionality))

**Comment by bukeau** [comment]
It only happens when I have RDR2 open, the same issue arises with any other browser items like the bbc news site, I will try the dark mode, having more detail will help to be more precise although if i need to I can generally open the videos that are provided which are excellent, I have donated and appreciate the effort that has gone into providing this awesome resource, very clever stuff.

**Comment by MichalD96** [comment]
Do you use Nvidia filters? or something that makes your game brighter? Map has fixed colors that should be displayed the same in every browser, so i guess it is some filter/extension/plugin/app that makes your screen brighter and it turns on with the game.

**Comment by bukeau** [comment]
I think it may have something to do with brightening the rdr2 settings, I have a large monitor and have both rdr2 and the collector map open at the same time, I make your map smaller and then I can quickly add markers to the rdr2 map.

**Comment by bukeau** [comment]
btw your map 'cannot be reached' atm.
