### ISSUE TITLE
anti virus phishing claims

### ISSUE THREAD

**Issue by hitobatosai** [jeanropke/RDR2CollectorsMap#1140]
your website is making my anti virus go crazy, claims the website its trying to phish me. i use Avast antivirus. had to turn off webshield.

**Comment by MichalD96** [comment]
Many people reported this issue today, it is false positive result from Avast and AVG antivirus. 
We ensure that both maps are safe.
For now you can exclude both maps from scanning: 
https://support.avast.com/en-ww/article/Antivirus-scan-exclusions

We are trying to find out what is the reason now

**Comment by whytheseaisboilinghot** [comment]
Flagging due to html.
