### ISSUE TITLE
Map shows collectors items for next day and setting time offset doesn't work

### ISSUE THREAD

**Issue by MrsTadertaut** [jeanropke/RDR2CollectorsMap#1145]
I have the time zone set to -5 and so it should be displaying data for May 15th but its still showing data for May 16th. I am unable to use the map because the game is still having collectable items be the May 15th items.

**Comment by MichalD96** [comment]
Cycles reset for everyone exactly at 00:00 UTC time, it is not a bug that map shows you May 16th, cycles has changed 1.5 hour ago for everyone, and it is cycles date not your local time zone date. Time zone offset should be set to 0 not matter from your time zone. Time zone offset has been added to adjust game clock on the map if you experienced that is wrong, and only then. If your map clock is correct, set it back to 0.

**Comment by MichalD96** [comment]
Check map Wiki: https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide

**Comment by MrsTadertaut** [comment]
no worries I figured it out, I close this issue 5 minutes after I made it.
