### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by R0CKZlLLA** [jeanropke/RDR2CollectorsMap#1147]
Hi, 

Today is Friday, June 11. I've had a couple things from the collector map not be there and since that's never happened to me not even once in 2-3 months I was curious if it night be something on my end or if it's a rare game glitch and/or if there's something I can do to possibly fix it and get these items.

The first one was a Spoonbill Egg, east of Lakay on a small island. The second one was a randon item, southwest of Tumbleweed, slightly left and above the letter N of "New Austin". 

Mostly just curious as I said this has never happened. Thank you, I love what you do here, it's second to none! Which reminds me, I got to go make that donation I've been meaning to make but forgot lol. Thanks again! : ) 

Tony T
aka ROCKZILLA

**Comment by MichalD96** [comment]
Hey, it is common game bug, items sometimes does not spawn where it should, in most cases change the session should fix it.
If you play on PC and changing the session haven't fixed it, you can close your game and delete all `.dat` files from this location: `%localAppData%\Temp`, that's temp files that sometimes cause problems. If you play on the console sometimes is required to turn it off permanently (unplug power cable for around 30 seconds), that also should delete the remaining cache and spawn items in correct spots.
