### ISSUE TITLE
Incorrect Cycle for June 20 

### ISSUE THREAD

**Issue by LaDorys** [jeanropke/RDR2CollectorsMap#1150]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
If you provide any info what is wrong would be easier to determine where the problem is. Probably your game is bugged - restart the game.
