### ISSUE TITLE
Map set to wrong day 

### ISSUE THREAD

**Issue by Renecade3** [jeanropke/RDR2CollectorsMap#1155]
I haven't figured out if I can change the day it's set for but today is the 24th and the map says it's the 25th
![Screenshot_20210724-185320_Google](https://user-images.githubusercontent.com/87919682/126885122-ef26604d-9e20-4a7c-a484-aa0d0dce8d8d.jpg)
![Screenshot_20210724-185335_Google](https://user-images.githubusercontent.com/87919682/126885124-0c4e81c7-df56-4976-85a9-eef6e2fd0d2f.jpg)

**Comment by JaySmaug** [comment]
Having the same problem. Inaccurate collectible locations along with it

**Comment by Renecade3** [comment]
So there is a way to change the cycle it is set too let me figure out the steps I used and I'll get back to you

**Comment by Renecade3** [comment]
So there is a show debug settings, then you go down to the bottom and enable day cycle changer, then enable manual cycle input, and finally scroll to the top and change the day.
![Screenshot_20210724-190504_Google](https://user-images.githubusercontent.com/87919682/126885329-54a4a629-583d-4122-9b94-42c9e891dea2.jpg)
![Screenshot_20210724-190512_Google](https://user-images.githubusercontent.com/87919682/126885330-920449fc-3da6-4d91-a5e2-15ea79d7b103.jpg)
![Screenshot_20210724-190519_Google](https://user-images.githubusercontent.com/87919682/126885332-7ef19ec0-263e-4ad9-9ca0-7ce8bcc87076.jpg)
![Screenshot_20210724-190623_Google](https://user-images.githubusercontent.com/87919682/126885334-89d33ad9-a89f-4cca-9dde-9a498f512153.jpg)
![Uploading Screenshot_20210724-190627_Google.jpg…]()

**Comment by Renecade3** [comment]
Turns out the map is off by 2 days, its the 23rd

**Comment by MichalD96** [comment]
Map is correct, time you see on top of the menu is UTC/GMT time, the day change when cycles change exactly at 00:00 UTC.
The steps you showed @Renecade3 to change the day is only for debugging purpose and shouldn't be normally used. If you have problem to find collectibles you should restart your game, in 99% of cases it is game fault. 
Highly recommend to read the map guide [here](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide)
