### ISSUE TITLE
madam nazar wrong location today

### ISSUE THREAD

**Issue by qwedsa274** [jeanropke/RDR2CollectorsMap#1159]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
Position is automatically updated up to 1 minute after she change location. 
if you open marker popup you can check if her position is correct, if it's not there is a button to update it manually:
![nazar](https://user-images.githubusercontent.com/53737762/130364850-4d8a395c-9488-4a46-a759-0a13fc9ac92f.jpg)
