### ISSUE TITLE
Dig items not there

### ISSUE THREAD

**Issue by bfrench55** [jeanropke/RDR2CollectorsMap#1163]
Hey guys, great app. Hoping you can help. None of the dig site items are there when I use the map. All the Tarot cards in the open are there. I've tried unplugging the Xbox to reset the cache. Also tried going to Online in the menu to generate a new session. Not sure what to do. Please help.

**Comment by bfrench55** [comment]
My issue seems to have resolved on it's own. I believe it was tied to the message I kept receiving when trying to open a collector map from my satchel. It's happened before. Said something like the map couldn't be opened, try obtaining a higher collector rank... blah, blah. I'm at Collector rank 20.

**Comment by MichalD96** [comment]
It is game bug. [Here](https://www.reddit.com/r/RedDeadCollector/comments/p5b70g/metal_detector_not_working_in_red_dead_online_fix/) is link to reddit post with solution.

**Comment by Nasr1234** [comment]
في خميس، 23 سبتمبر، 2021 في 1:26 ص، كتب bfrench55 ***@***.***
