### ISSUE TITLE
Twenty57?

### ISSUE THREAD

**Issue by PaveMentman** [jeanropke/RDR2CollectorsMap#1164]
- - -
This "Twenty57.net" popped-up on uMatrix within 48-hours.
And since ever the collectible-markers haven't been showing up on the RDR2CollectorsMap.

I have tried to search around what this "Twenty57" is:
They keep pretty much only telling that they "develops industrial strength applications for the financial service industry" and list numerous banks I haven't heard of ever as their clients
( it certainly helps that I live in Nordic-country to not know non-mega-banks ).

So is this script-thing is on purpose?
And if it is, is it some sort of database-hosting service or something is relation?

I just happen to be not lucky to find to needed info this time around.
- - -

**Comment by MichalD96** [comment]
Map is hosted on GitHub, nothing like that should appear, we don't use anything called "Twenty57.net". It may be a scam attempt. 
Use only map from this link: https://jeanropke.github.io/RDR2CollectorsMap/
I highly recommend to scan your PC with antivirus.

**Comment by PaveMentman** [comment]
- - -
This is how the map looks even after resetting all the filters and other settings.
On the uMatrix, the only thing I've left un-activated are anything relation to "Twenty57" which also is not present, well, anywhere else especially not on "RDOMap"
( https://jeanropke.github.io/RDOMap/ )
https://www.mediafire.com/view/d5hdrntc73a4cju/2021-09-28-04-22-40-620-chrome-Red_Dead_Online_-_Collectors_Map_-_Google_Chrome.png/file
https://www.mediafire.com/view/heqlmlutsd117iz/2021-09-28-04-26-12-104-chrome-Red_Dead_Online_-_Collectors_Map_-_Google_Chrome.png/file
- - -

**Comment by MichalD96** [comment]
Not loading the map is caused by this extension. Allow access to this API and everything will works normally.
