### ISSUE TITLE
Not able to  see item marking on the map. Even though the i have the items on the show option

### ISSUE THREAD

**Issue by Legendaryguyy** [jeanropke/RDR2CollectorsMap#1167]
![Screenshot_2021-11-11-20-58-08-178_com android chrome](https://user-images.githubusercontent.com/94126270/141324438-1aa6a963-cfb2-4bdf-b3d9-b86444723ac5.jpg)
![Screenshot_2021-11-11-20-58-28-684_com android chrome](https://user-images.githubusercontent.com/94126270/141324490-6341d7c7-8a06-4552-9bde-efd37844c202.jpg)

**Comment by MichalD96** [comment]
Try to close map tab, and reopen it. You can also click in menu to option "Reload map now".
If this will not work, you have to update your browser.

**Comment by Legendaryguyy** [comment]
Thanks for tryna help, but doesn't work
