### ISSUE TITLE
Bug: Map Fully Broken

### ISSUE THREAD

**Issue by Oxyliter** [jeanropke/RDR2CollectorsMap#1168]
The Map is fully grey, and all of the Items are from yesterday. I have tried refreshing and restarting and nothing has worked. Only the Caves have loaded in.
![rdo map bug](https://user-images.githubusercontent.com/94398212/141838696-a8e7b2f3-ac62-411c-8cfe-36bc26375c9a.PNG)

**Comment by Oxyliter** [comment]
Some of the Items are also Glitched out.

**Comment by MichalD96** [comment]
What browser do you use?
Try to reload the map by ctrl + F5
Open the console (F12 Key -> "Console" tab) and send here screenshot of this window.

**Comment by Oxyliter** [comment]
I use Google Chrome, but I got it working now, but thanks anyway.
