### ISSUE TITLE
Fossil collection map are problem need to fix

### ISSUE THREAD

**Issue by AsentrixX1** [jeanropke/RDR2CollectorsMap#1169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalD96** [comment]
Can you be more specific what the problem is?

**Comment by AsentrixX1** [comment]
So many fossil collections not in the map I think your map need to get
updated






Michal__d ***@***.***>:

**Comment by MichalD96** [comment]
All possible fossils locations are on the map. If you have any problems to find anything, change the session or restart your game. If you found something that is not on the map, it is game bug and only you can find it, it will not spawn for anyone else.

**Comment by AsentrixX1** [comment]
Like when i done the coastal fossil
After the pressing to megafauna fossil it’s shows same fossil that i did.

Michal__d ***@***.***>:

**Comment by MichalD96** [comment]
Fossils, coins, arrowheads are fully randomized collections, and you can not predict what type of item you get. It means that all 3 fossils categories needs to share the same spots. Map is correct

**Comment by AsentrixX1** [comment]
I really sorry for westing your time, for example I collected everything
that all was in the site map, after I restarting the game it will
respawning on there same locations ?

Michal__d ***@***.***>:

**Comment by MichalD96** [comment]
No, in top left corner of the map you have timer, that counting down. This counter shows when items change locations. Items changes locations every 24 hours, for everyone in the world at the same time. Never items are 2 days in the row in the same spots.
Here is [Map Wiki](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide) page, highly recommend to read about all map features :)

**Comment by AsentrixX1** [comment]
Okay thank you so much :)




No, in top left corner of the map you have timer, that counting down. This
counter shows when items change locations. Items changes locations every 24
hours, for everyone in the world at the same time. Never items are 2 days
in the row in the same spots.
