### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Nestares** [jeanropke/RDR2CollectorsMap#117]
A Spanish version would be fantastic!
Thanks!

**Comment by iligalodin** [comment]
we don't hacve a spanish translator yet, would you be able to translate? 💃

**Comment by Nestares** [comment]
Uff it take me much time... For free is a crazy thing!!

**Comment by iligalodin** [comment]
we're all doing it for free. a spanish translation will come once someone translates it thanks for the suggestion
