### ISSUE TITLE
Missing pin

### ISSUE THREAD

**Issue by MrSmithr** [jeanropke/RDR2CollectorsMap#1170]
https://jeanropke.github.io/RDR2CollectorsMap/?m=document_card_queen_cups

Near the Queen of Cups today (3/12/2021), inside the building on the fireplace was the Five of Pentacles but was not marked on the map.

**Comment by MichalD96** [comment]
Are you sure it was Five of Pentacles? There is a few cards on the fireplace, but not in this area, it shouldn't be possible. I will check that in next cycle 3

**Comment by MrSmithr** [comment]
I double-checked the recently collected items of the two tarot cards that
were there. It could have been a one-off but I'm willing to check again on
the next proposed cycle.

**Comment by MrSmithr** [comment]
Checked today (11/12/2021), no other card on the fireplace. I will continue to monitor this but my guess is it was just a one-off.

**Comment by MuchMoreMatt** [comment]
Sometimes when loading into a new lobby, all collectibles from each cycle will be available to collect within a certain proximity. Perhaps this is what you experienced.
