### ISSUE TITLE
I have been searching for the agarita flower for three days (between 10 pm - 5 am) using the map, but the flowers are not at those locations.  I can find all other items on the map with no issues.  What am I doing wrong.

### ISSUE THREAD

**Issue by Dabriga** [jeanropke/RDR2CollectorsMap#1172]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
First, make sure you use this map: https://jeanropke.github.io/RDR2CollectorsMap/
not some junk mobile app.

If you still have problem with not spawning agarita flower, try to do this steps, it mostly solves the problem:
- If you are on PC:
  - close your game
  - go to this directory in Windows file explorer: `%localAppData%\Temp`
  - delete all `.dat` files

- If you are on the console:
  - close your game
  - turn off your console permanently
  - unplug power cable for 30 seconds
  - connect everything again

**Comment by Dabriga** [comment]
Thank you for the solution.  I tried rebooting my PS5 a couple of days ago and the flower was available then.
