### ISSUE TITLE
Glitched spoonbill eggs

### ISSUE THREAD

**Issue by B3ans1** [jeanropke/RDR2CollectorsMap#1176]
I wanted to ask because I know a lot of people have had this issue too, but I was wondering if the spoonbill eggs are no longer something you can collect at this point?
The spoonbill eggs break no matter what I do, I tried using the small game arrows and the varmint rifle and neither worked.
I also tried what had been recommended: jumping on top of a bounty wagon to see it better, but that didn't help. The yellow marker for the eggs is still there but the nest isn't, is there anything official about this or is it permanently glitched?

**Comment by MichalD96** [comment]
Most of he eggs on trees are bugged. Sometimes change the session help. Some eggs are permanently bugged for some players (for me egret egg cycle 1 and 4). I don't know of any proven working solution. I noticed that eggs are stuck much more often on PC than on consoles.
Bounty wagon is used to shoot the nest as close as possible. Also always use the scope with max zoom and clean your weapon before the shot. If you play on PC you can try to experiment with fps cap - I found out that eggs will never fall if you have fps above 120 (but lower will not fix all eggs either). That's the only advice I can give.

**Comment by B3ans1** [comment]
I don't know what I might have done to mess it up, but I still can't get it. I can see the egg but there isn't a nest, I can't break it or knock it down. I don't know what to do at this point aside from not doing this collection, I'm not sure how the cycles work and I'm not sure how much they are a factor in this. Thank you for trying to help though, I do appreciate it.

**Comment by MichalD96** [comment]
Cycle means specific items locations. Cycles changes every 24 hours at 00:00 UTC/GMT time. You can try to get this egg in around 3 hours from another spot. Maybe tomorrow's location will not be bugged
