### ISSUE TITLE
Today's cycles are not updating, even after refreshing.

### ISSUE THREAD

**Issue by MuchMoreMatt** [jeanropke/RDR2CollectorsMap#1177]
The collector map has worked everyday just fine for nearly the entire year, until now. It's been nearly an hour without the cycles updating. Refreshing the page does not work.

**Comment by terribledork** [comment]
Having the same issue. Tried in both Firefox and Chrome.

**Comment by lovliey** [comment]
i was just having this problem for the past half hour but i just checked and its refreshed to the new cycle now, im on chrome

**Comment by MuchMoreMatt** [comment]
I also just checked, it's working again on Google Chrome.

**Comment by Viking22** [comment]
I got the same problem, Tryde Firefox, Chrome and edge. Non will work

**Comment by MichalD96** [comment]
The problem has been fixed. It was GitHub issue, independent of us and the map. Use ctrl + F5 to reload the map.
