### ISSUE TITLE
Collector map date

### ISSUE THREAD

**Issue by CygnisDragon** [jeanropke/RDR2CollectorsMap#1178]
In my irl timeline, my date is December 28. The interactive map is saying December 29 instead! And I can't even use my collector maps in the game too! So this interactive map is OUTDATED

**Comment by MichalD96** [comment]
Map is correct. Map works in UTC/GMT timezone, and date displayed on top of menu is not your local date. Highly recommend to read map wiki [here](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide)
