### ISSUE TITLE
Add/Remove from Map for entire Cycle

### ISSUE THREAD

**Issue by TinaNeedsCoffee** [jeanropke/RDR2CollectorsMap#1179]
I like the current add/remove feature on the map. However, it is frustrating when I've click "sell collection" and the things I have already collected return to the map. Especially when I've completed a large haul and left a few things behind to finish up the next day. It's hard to remember what you skipped over. I wish there was a way we could also have an add/remove collectibles from the map for the rest of the cycle. That way, when we've collected it within the 24 hour cycle, we'd have the option to remove it and not see it as an option until its actually collectable again. Thank you for your consideration and this amazing map.

**Comment by MichalD96** [comment]
Already made a few changes on the map from your suggestion.
In inventory settings disable "Automatically enable sold items"
![image](https://user-images.githubusercontent.com/53737762/148133542-1cd4fc5d-7c57-44d3-b38e-fe529b925bf2.png)

Items with amount 0 in your inventory will be automatically enabled on cycles reset.
Also added "Disable collected items" in inventory settings, so you can hide all items with amount > 0 in your inventory at once, without clicking it in each category.

**Comment by TinaNeedsCoffee** [comment]
Thank you so much! Also, the "Disable collected items" feature you added is awesome! Not having to manually click that for each group is very nice. Great job, keep up the amazing work.
