### ISSUE TITLE
Option to make removed markers fully transparent

### ISSUE THREAD

**Issue by Darkshadows9** [jeanropke/RDR2CollectorsMap#1183]
**Is your feature request related to a problem? Please describe.**
I find it a little cluttered when I have a lot of items that I've crossed off on my route, when the items I want removed are still visible.

**Describe the solution you'd like**
I'd like a tickbox option or a selector menu to make removed markers fully transparent.

**Describe alternatives you've considered**
I found that reducing opacity of all markers to 20% effectively makes all the faded markers invisible, but then it's harder to see the ones I want to see.

**Additional context**
I just started using the program, so I don't know if there's anything I missed in the settings

**Comment by CPStalker** [comment]
Great suggestion. supported.
