### ISSUE TITLE
Problem getting map

### ISSUE THREAD

**Issue by Lsu2878** [jeanropke/RDR2CollectorsMap#1185]
Hello.
I know this is a stupid question but I'm having trouble finding the map ? 

I can see the black screen saying 0/238 collectibles and $$$ earned 

And the 3 things madam wants ( bottles ) 

And then all collectibles 
Some white some gold 

And legendary animals area 

Scroll down and see import/ export 
Customized routes 

Scroll down and see RDO map 
Report problems ( where I am now ) 
Donate 
Sponsors 

But can't load map ? 
If I hit RDO map it takes me to another place ( exactly same with different options ( boats , camps , etc ) 
Collector map 

How do I see the map with actual collectibles? 

I'm on my phone also ! Does that make a difference? 

Do I have to donate first ? 

Thx

**Comment by MichalD96** [comment]
You need to close map menu - click X in top left corner of the screen
![image](https://user-images.githubusercontent.com/53737762/149210918-ee5009f9-7350-45fe-8067-7172bd057d5e.png)

**Comment by Lsu2878** [comment]
Omg .. Gees.. did everything but that !!

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 12, 2022 at 1:47 PM, ***@***.***> wrote:   


You need to close map menu - click X in top left corner of the screen


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
