### ISSUE TITLE
having difficulty importing my inventory.

### ISSUE THREAD

**Issue by warmit1961** [jeanropke/RDR2CollectorsMap#1186]
when I cut and paste the commands and hit enter, I get this   

VM87:119 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at eval (eval at <anonymous> (/unknown source), <anonymous>:119:85)
    at eval (<anonymous>)

**Comment by MichalD96** [comment]
The error suggest that you paste the script on the wrong site or you are not logged in to SocialClub. 

open this link: https://socialclub.rockstargames.com/games/rdo/overview
and make sure you are logged in (you see your game stats)
then press F12, click "Console" tab, and paste the script: 
```javascript
fetch('https://jeanropke.github.io/RDR2CollectorsMap/assets/js/rdo-inventory.js').then(data => data.text()).then(eval);
```

You need to do this steps in browser tab where you have opened SocialClub site, not Collectors map.

**Comment by warmit1961** [comment]
thank you. i added the chrome app instead... works great.

**Comment by warmit1961** [comment]
got it. tyvm

    On Thursday, January 13, 2022, 03:34:33 p.m. PST, Michal__d ***@***.***> wrote:  
 
 


The error suggest that you paste the script on the wrong site or you are not logged in to SocialClub.

open this link: https://socialclub.rockstargames.com/games/rdo/overview
and make sure you are logged in (you see your game stats)
then press F12, click "Console" tab, and paste the script:
fetch('https://jeanropke.github.io/RDR2CollectorsMap/assets/js/rdo-inventory.js').then(data => data.text()).then(eval);
You need to do this steps in browser tab where you have opened SocialClub site, not Collectors map.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
