### ISSUE TITLE
Wrong date on map.

### ISSUE THREAD

**Issue by Ryan1991D** [jeanropke/RDR2CollectorsMap#1188]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by Ryan1991D** [comment]
And yesterday it said it was January 23rd but it was really the 22nd.

**Comment by MichalD96** [comment]
Date is correct. It is UTC/GMT time, not your local time.
I recommend to read map wiki [here](https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide#side-bar-menu).

**Comment by Ryan1991D** [comment]
It was ever like it before it only started doing it yesterday.

**Comment by MichalD96** [comment]
It is like that since 2 years. Maybe you didn't notice earlier.

**Comment by Ryan1991D** [comment]
Nope it always said the right date on it even my friends and talking about it because yesterday we couldn't collect anything and i have been using the map since it was made.
________________________________

**Comment by MichalD96** [comment]
I am developer of this map and i added showing date in menu in November 2019. Nothing changed since this time

**Comment by Ryan1991D** [comment]
I'm done with this I guess all my friends can't read oh well.

________________________________

**Comment by Ryan1991D** [comment]
One last thing I post Madam Nazar's location everyday on my discord and psn and this is todays.

________________________________
