### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by chuanki** [jeanropke/RDR2CollectorsMap#1190]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?  ---------i dont know how to figure that out sorry
* Coordinates or a clear image of the location  Latitude: -108.3125 / Longitude: 25.8046875 
* Include the item name   *Queen of Pentacles

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
It is game issue, not the map. Sometimes game is stuck on previous day cycle, you need to change the session or restart your game to fix it.

**Comment by chuanki** [comment]
okay, thanks
