### ISSUE TITLE
Hello, I am new to the role of the collector. I want to collect fossils, but they do not appear to me of all kinds, even the metal detector does not mark, and I follow your site to collect treasures. I hope to answer. What is the solution to this problem??!!Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by Omarhameed860** [jeanropke/RDR2CollectorsMap#1192]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`
Hello, I am new to the role of the collector. I want to collect fossils, but they do not appear to me of all kinds, even the metal detector does not mark, and I follow your site to collect treasures. I hope to answer. What is the solution to this problem??!!

**Comment by MichalD96** [comment]
Make sure you have at least 12 collector role level. Some collectibles like fossils and jewelry you can pick up only if you have enough high role level.
Make sure your metal detector is not broken (if you can find other items with metal detector is probably fine) if is not let me know if you play on PC or console.
Also maybe stupid question, but do you have a shovel? it is also required to pick up fossils.
