### ISSUE TITLE
New item Location   Cycle: day #

### ISSUE THREAD

**Issue by chuanki** [jeanropke/RDR2CollectorsMap#1193]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? sorry i dont know,it happened just know
* Coordinates or a clear image of the location  

Latitude: -78.078125 / Longitude: 130.09765625

* Include the item name

random (i got arrow )

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
It is spot that remained from previous day, noone else can find this item. It is just a game bug.
