### ISSUE TITLE
Please restore the separate flower pile to the inventory

### ISSUE THREAD

**Issue by CPStalker** [jeanropke/RDR2CollectorsMap#1194]
Why was the separate flower pile removed from inventory options? It was very useful, since flowers are the only items you can make more than one collection per day.

**Comment by MichalD96** [comment]
It has been removed, because it didn't work properly with the latest map updates. It will be added back soon.

**Comment by CPStalker** [comment]
Thanks for the reply, friend. I'll be waiting.

**Comment by MichalD96** [comment]
Added the setting back
