### ISSUE TITLE
Hi, the cycle is out of sync for arrowheads, jewelry, coins and fossils 

### ISSUE THREAD

**Issue by Padamonkey** [jeanropke/RDR2CollectorsMap#1195]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
Map is always correct. Do you have metal detector and shovel? If you have and still have problem to find the item, change the session or restart your game, it usually fixes the problem.
