### ISSUE TITLE
Invisible objectives

### ISSUE THREAD

**Issue by User12423413** [jeanropke/RDR2CollectorsMap#1196]
![FB2CB4E5-029F-4C9B-B70C-9B735EE71887](https://user-images.githubusercontent.com/100509686/155874390-ef3463a1-dadc-47d5-9227-ed7d16553027.png)

As seen here Tarot cards and antique bottles are unavailable, it may be something in my settings although I have compared them to the settings on my phone and they are identical.

**Comment by MichalD96** [comment]
Yoy changed "Tool type" setting to shovel only spots. Change it back to "All".

**Comment by User12423413** [comment]
Thanks!

Kind regards,

Nathan Cole
________________________________
