### ISSUE TITLE
Incorrect item Cycle: day # ?

### ISSUE THREAD

**Issue by chuanki** [jeanropke/RDR2CollectorsMap#1198]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)

* What day cycle it is? Sry i dont know 

* Coordinates or a clear image of the location 
Latitude: -81.234375 / Longitude: 131.78515625
on the barrel.

* Include the item name
Wand V   
It's here in this cycle but not shown in our CollectorsMap
Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
This is common bug in game. Only you can see/pick up that card, and also it will disappear if you change the session.
