### ISSUE TITLE
Translating item windows & search bar

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#120]
The correct translations for the German version for the item window (that opens when clicking symbols) and the search bar are missing. I don't know how to access them so I thought I would just translate them here and you can implement them where they need to be.

![image](https://user-images.githubusercontent.com/55949253/66217673-08620500-e6c8-11e9-938c-c50adb4102a4.png)
This translates to: " Von Karte entfernen/hinzufügen " 
Also "Day" translates to " Tag ". Tag 1, Tag 2, Tag 3.

![image](https://user-images.githubusercontent.com/55949253/66217723-1fa0f280-e6c8-11e9-930f-7ad898dafb26.png)
This translates to: " Gegenstände suchen. Getrennt durch ; "

Thank you.

**Comment by jeanropke** [comment]
Done.
![de-de menu](https://user-images.githubusercontent.com/6243818/66220915-4cdba980-e6a4-11e9-9dc8-c25bb1721d9f.png)
