### ISSUE TITLE
Incorrect item Cycle

### ISSUE THREAD

**Issue by karnst** [jeanropke/RDR2CollectorsMap#1200]
I believe the wild flowers have the incorrect cycle, that or rdo is bugged out. I haven't been able to collect any today, everywhere I go that claims where the flowers are, they aren't there. I'm not sure which the cycle is though. 

![image](https://user-images.githubusercontent.com/103188841/162225902-e5c9e73c-0c89-4ea0-a139-716a6fa81417.png)
![image](https://user-images.githubusercontent.com/103188841/162225927-401d12fc-5ac4-4d4c-a030-0ac460732f74.png)
![image](https://user-images.githubusercontent.com/103188841/162225954-41c0392d-3695-4b7d-8867-707d3e2092b9.png)

**Comment by karnst** [comment]
Tried restarting my game, leaving and joining new session and following something from another post on here; "If it is still wrong you can clear the game cache files. Go to this location in Windows file explorer %localAppData%\Temp delete all .dat files.".
However still nothing in the supposed spots for the flowers.

**Comment by MichalD96** [comment]
Are you sure you don't have 10 flowers of each type in your inventory? This is cardinal flower spot that is easy to collect 10 in two days.

If not, close your game and launcher, open this location in Windows file explorer:
`%UserProfile%/Documents/Rockstar Games/Red Dead Redemption 2/Profiles/<your profile ID>`
and delete "`Player`" file.

When you launch the game you will get popup that files are not synchronized, click to use local changes, and override "Player" file saved in the cloud by local changes. 
Game will create new "Player" file when you log in to online.

**Comment by karnst** [comment]
"%UserProfile%/Documents/Rockstar Games/Red Dead Redemption 2/Profiles/<your profile ID>
and delete "Player" file." worked, thank you so much :))
