### ISSUE TITLE
My entire map is set for, what im assuming is the next day collections

### ISSUE THREAD

**Issue by Blexican420** [jeanropke/RDR2CollectorsMap#1209]
I was sitting on your website right before 7pm central time at location where their was supposed to be 3 collectibles... after 7pm the map changed. The other day same issue was happening.. I was trying to go go collect the collectibles,  but they weren't in the right spot. Next day I woke up and they were in the correct position.

**Comment by MichalD96** [comment]
Items will not spawn if you are too close to them. Safe distance is a bit more than 2x of extended radar. Map is correct. If you can not find something that is on the map, you need to change the session or restart your game. It always fixes missing items problem.
