### ISSUE TITLE
"Ignore collected items" does not work.

### ISSUE THREAD

**Issue by nimmey** [jeanropke/RDR2CollectorsMap#1211]
Here's a video.

[https://www.youtube.com/watch?v=N_QZKwjFqG8](url)

P.S.: when generating a new route, the window that pops up seems to skip the first item in the route.

**Comment by MichalD96** [comment]
"Collected item" is a bit misleading name, it is not item you have in your inventory, but item you collected and its marker is transparent.
However there is a workaround to make route only between markers with amount of 0 in your inventory.
Go to menu "Filter markers" setting and chose "Only low inventory items", beneath you can chose max amount in your inventory (1 or more, up to you),
then go to route generator, make a route. 
Back to the "Filter markers" setting and set it to "None"

This will draw the route only between items you have 0 (or value you chose) in your inventory, and show all other markers without drawing route to them.

**Comment by xXxMountainJewritos42069xXx** [comment]
That's exactly what I needed, cheers mate. :)
