### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by CarolCampello** [jeanropke/RDR2CollectorsMap#1213]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182

the item “Tarot Card: Four of Wands” is not on the table but in the window, I also found an old drink (Tennessee Whiskey) behind the counter inside the Saloon (but I don't know if it's some random item)
Location: https://jeanropke.github.io/RDR2CollectorsMap/?m=document_card_four_wands

**Comment by MichalD96** [comment]
Four of Wands was on the table long time ago, R* moved this card on the windowsill. Seems that in some languages description has not been updated. Which map language you use? You can correct it by yourself on [Crowdin](https://translate.rdo.gg/).

Many items spawns randomly in spots where they not supposed to be. Only you were able to pick up this whiskey, it will not spawn for other players. It is just bug in game, when you change the session (or sometimes fast travel) game spawns all items from all cycles, in the area of around 2x extended radar.

**Comment by whytheseaisboilinghot** [comment]
> #### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182
> 
> the item “Tarot Card: Four of Wands” is not on the table but in the window, I also found an old drink (Tennessee Whiskey) behind the counter inside the Saloon (but I don't know if it's some random item)
> Location: https://jeanropke.github.io/RDR2CollectorsMap/?m=document_card_four_wands

Close your game and clean your cache, if you haven't restarted the game in a while and we're also in the lobby as the dailies changed your cycle can get messed up, you have two options either go collect those items by finding out the cycle day that they are on then restart your game and collect as usual or just restart your game.
