### ISSUE TITLE
Route for low quantity items

### ISSUE THREAD

**Issue by CPStalker** [jeanropke/RDR2CollectorsMap#1214]
It would be very useful to have the option to generate route only for low quantity items.

**Comment by MichalD96** [comment]
You can use map filters to achieve that. In "Filter markers" setting, chose only low inventory items, then generate route between all remaining markers, and change back "Filter markers" setting to none.
You will see all markers on the map, but route will be only between low inventory items.

**Comment by CPStalker** [comment]
> You can use map filters to achieve that. In "Filter markers" setting, chose only low inventory items, then generate route between all remaining markers, and change back "Filter markers" setting to none.
> You will see all markers on the map, but route will be only between low inventory items.

It would be easier to be able to do it directly in the route generator, but anyway there's this way of doing it by maneuvering the filters. Thanks for the feedback.

**Comment by CPStalker** [comment]
And by only filtering out lesser items, random items are still shown on the map, unfortunately.

**Comment by MichalD96** [comment]
We implemented map filters to create countless amount of combinations with which you can arrange map as you want. We try to not duplicate settings, as long as possible. I know it takes a few clicks, but it is much more powerful option, than just a button that do one thing. I am not saying that your idea is bad, but if we implement button for every setting, menu would be 10x longer.
Most of the users never even scrolled to the bottom of the menu.

> And by only filtering out lesser items, random items are still shown on the map, unfortunately.

yes, it is intended behavior. Map shows you only random spots from witch you can get any item that is low in your inventory. If from particular random spot you can not get anything that is low in your inventory, spot will not be visible.

**Comment by CPStalker** [comment]
> We implemented map filters to create countless amount of combinations with which you can arrange map as you want. We try to not duplicate settings, as long as possible. I know it takes a few clicks, but it is much more powerful option, than just a button that do one thing. I am not saying that your idea is bad, but if we implement button for every setting, menu would be 10x longer. Most of the users never even scrolled to the bottom of the menu.
> 
> > And by only filtering out lesser items, random items are still shown on the map, unfortunately.
> 
> yes, it is intended behavior. Map shows you only random spots from witch you can get any item that is low in your inventory. If from particular random spot you can not get anything that is low in your inventory, spot will not be visible.

I understood. Still should have an option to show only low quantity items without random ones. For those who want to search only for exact items, to save time.

**Comment by MichalD96** [comment]
> I understood. Still should have an option to show only low quantity items without random ones. For those who want to search only for exact items, to save time.

yes, you are right. I will add this option to the filters.
It was like that earlier, but the vast majority people that used this filter complained that random spots are not visible.

**Comment by CPStalker** [comment]
> > I understood. Still should have an option to show only low quantity items without random ones. For those who want to search only for exact items, to save time.
> 
> yes, you are right. I will add this option to the filters. It was like that earlier, but the vast majority people that used this filter complained that random spots are not visible.

Thank you very much. So it speeds up a lot.

**Comment by MichalD96** [comment]
Added:
![image](https://user-images.githubusercontent.com/53737762/200146684-b4f72ef2-b547-4263-90dc-8e4d9dcaff87.png)

**Comment by CPStalker** [comment]
> Adicionado: ![imagem](https://user-images.githubusercontent.com/53737762/200146684-b4f72ef2-b547-4263-90dc-8e4d9dcaff87.png)

Great. Very useful. Thanks for the improvement.
