### ISSUE TITLE
I can't seem to be able to link my inventory

### ISSUE THREAD

**Issue by booGh0stie** [jeanropke/RDR2CollectorsMap#1216]
I can't link my inventory and I already looked at the post about it and it didn't help
[Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-axa3qZOXcFDHq5Pnc8ILqBBnpTX7QU8rcVlIatz7W54=' 'report-sample' *.rockstargames.com analytics.twitter.com connect.facebook.net fast.fonts.net s.rsg.sc static.ads-twitter.com".

VM223:119 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at eval (eval at <anonymous> (unknown source), <anonymous>:119:85)
    at eval (<anonymous>)
eval @ VM223:119
Promise.then (async)
(anonymous) @ VM222:1
this is what I get in response to putting in the link to get the file for the inventory

**Comment by MichalD96** [comment]
What browser do you use?
Do you have any extensions/plugins in your browser that improve security?

As a temporary solution you can install [browser extension](https://chrome.google.com/webstore/detail/red-dead-online-collector/ppkogdbkpfkienlkjoicbpogdeonalih), or you can can try to copy everything from [here](https://raw.githubusercontent.com/jeanropke/RDR2CollectorsMap/master/assets/js/rdo-inventory.js) and paste it in browser console on [this page](https://socialclub.rockstargames.com/games/rdo/overview). This should work, because doesn't have the eval function.

**Comment by booGh0stie** [comment]
I use google chrome with no security extensions

**Comment by booGh0stie** [comment]
> What browser do you use? Do you have any extensions/plugins in your browser that improve security?
> 
> As a temporary solution you can install [browser extension](https://chrome.google.com/webstore/detail/red-dead-online-collector/ppkogdbkpfkienlkjoicbpogdeonalih), or you can can try to copy everything from [here](https://raw.githubusercontent.com/jeanropke/RDR2CollectorsMap/master/assets/js/rdo-inventory.js) and paste it in browser console on [this page](https://socialclub.rockstargames.com/games/rdo/overview). This should work, because doesn't have the eval function.

I also just put in that text and it said:
Uncaught TypeError: Cannot read properties of null (reading 'value')
    at <anonymous>:119:85
(anonymous) @ VM59:119

**Comment by MichalD96** [comment]
It looks like problem with your browser. I can't reproduce this error on my chrome. 
I need to be sure, where exactly you paste this code? On SocialClub website or map?

**Comment by booGh0stie** [comment]
I put it on the social club website
![Screenshot_20230119_054622](https://user-images.githubusercontent.com/123125085/213579141-a13d9be0-28fb-4f5e-9c83-b61c8a8aca1b.png)

**Comment by MichalD96** [comment]
This error clearly says that you are on the wrong website, because platform selector does not exists.
Open this page: https://socialclub.rockstargames.com/games/rdo/overview
then open console (F12) and paste the script.

**Comment by booGh0stie** [comment]
I clicked that link and it seemed to have the same error, I'm sorry for bothering you with this though

**Comment by MichalD96** [comment]
no problem, i am trying to figure out why this selector is null if you are on correct website.
paste this to the console please:
```javascript
console.log(location.href, document.querySelector('select[data-ui-name="toggleMenu--dropdown"]'))
```

**Comment by booGh0stie** [comment]
![Screenshot_20230119_060754](https://user-images.githubusercontent.com/123125085/213582248-c44e5218-9d11-48be-8c9c-580e5a2c46e8.png)

**Comment by MichalD96** [comment]
you are on the wrong website
Script will work ONLY here: https://socialclub.rockstargames.com/games/rdo/overview

**Comment by booGh0stie** [comment]
But i am clicking that site

**Comment by booGh0stie** [comment]
It switches to ineligible

**Comment by MichalD96** [comment]
Are you logged in? Do you have RDR2 purchased on this account? Can you see your RDR2 stats?

**Comment by booGh0stie** [comment]
I have it purchased on Xbox with my SocialClub account connected to my Xbox account and it shows that ineligible thing for every game

**Comment by booGh0stie** [comment]
It even changes the site title to ineligible on Microsoft Edge

**Comment by MichalD96** [comment]
So you don't have RDR2 connected to this account. SC redirects you to `ineligible/` because there is no game.

**Comment by booGh0stie** [comment]
Oh, but i have my Xbox account connected to my SC account

**Comment by MichalD96** [comment]
SocialClub says something different. But as far as i know it is common problem that this accounts are not linked properly. Can you see your RDR2 stats anywhere on SC? If you can't, it means the accounts are not linked. I would recommend you to write to R* support. I know they are usually useless, but if you will have enough patience, maybe they will fix it for you.

**Comment by booGh0stie** [comment]
Ok thank you

**Comment by MichalD96** [comment]
You are welcome 👍
