### ISSUE TITLE
Import inventory 

### ISSUE THREAD

**Issue by Shadow25773** [jeanropke/RDR2CollectorsMap#1217]
I am just an RDO player and I consider myself to be more than computer novice but no where near expert. I have been wracking my brain trying to figure out the instructions to import rdo collectable inventory from social club to the collector map and I cannot find the paste location. Can you please help? I am an Xbox user.

**Comment by MichalD96** [comment]
You can open browser console only on PC. If you click F12 key, will open new window on the side of your browser, click "Console" tab, and paste link to the script and click enter. 
Like here:
![image](https://user-images.githubusercontent.com/53737762/219066653-7c972585-a1e6-4d41-80ec-036900378c27.png)

It will work ONLY on this address: https://socialclub.rockstargames.com/games/rdo/overview
