### ISSUE TITLE
Trouble with Fossils spawn 

### ISSUE THREAD

**Issue by FresKainsalata** [jeanropke/RDR2CollectorsMap#1219]
Hi there ! I’m starting right now the collector role, but, even with metal detector i can’t find the fossils, i go where the map tells me to, but they just don’t spawn and I can’t even dig, simply they don’t exist. What is the problem ? What can i do ? Thank u!!

**Comment by MichalD96** [comment]
You need at least 10th level of collector role, to be able to pick up fossils.

**Comment by FresKainsalata** [comment]
Thank you so much !!!❤️
