### ISSUE TITLE
After completing link -keeps marking collect 

### ISSUE THREAD

**Issue by MummaKay** [jeanropke/RDR2CollectorsMap#1220]
After making the link between the collector's map and my Red dead online account I am now finding it difficult and very frustrating to do daily collecting as it continuously marks items as collected when they haven't been.. I have been trying to reverse this with no luck especially this month being May this is ultra frustrating.

Would love some guidance on how to fix this.

**Comment by MichalD96** [comment]
You probably set "Item stack size" setting in menu to some low value.
Make sure it is set to 10
