### ISSUE TITLE
Is the map still working? 

### ISSUE THREAD

**Issue by Iced57** [jeanropke/RDR2CollectorsMap#1225]
Im not able to find any american wild flowers with the current version, can someone pls tell me if still working? or if there another option to continue collecting these items. If there is something else from my end pls tell me

**Comment by MichalD96** [comment]
I guess you also have problem with metal detector items, that is related.

  Fix for PC:
  - Turn off your game, and Rockstar Games Launcher.
  - Go to this location in Windows file explorer:
    `%UserProfile%/Documents/Rockstar Games/Red Dead Redemption 2/Profiles/<your profile ID>`
    and delete "Player" file. When game ask you to create new file or download existing one from the cloud, select option to create new file. (file in the cloud is already broken too).
  - Launch the game.

  Fix for consoles:
  - Permanently turn off your console (you can unplug power cable for at least 30 seconds).
  - Turn on your console.
  - Go to RDR2 Home screen, launch the game and when screen turn black immediately hold (PS: L1 + R1) / (Xbox: RB  + LB) on your controller.
  - When main menu will be loaded release (PS: L1 + R1) / (Xbox: RB  + LB) buttons.
  - Readjust your game settings that has been changed to default.
