### ISSUE TITLE
import custom pins not working

### ISSUE THREAD

**Issue by Floralfoxes** [jeanropke/RDR2CollectorsMap#1226]
I cannot upload them and so have lost all my custom pins and cannot upload the pins of others either.

**Comment by MichalD96** [comment]
Post here "pinned-items.txt" file that you tried to import.

**Comment by Floralfoxes** [comment]
[Herbalism filesMAP.txt](https://github.com/jeanropke/RDR2CollectorsMap/files/11378602/Herbalism.filesMAP.txt)

**Comment by MichalD96** [comment]
It uploaded your pins to my map without any problem:
![image](https://user-images.githubusercontent.com/53737762/235814278-5900274a-a1e5-4df1-8766-9b54524e1e5a.png)

What browser are you using?

**Comment by Floralfoxes** [comment]
I tried it in brave and chrome but neither work

**Comment by MichalD96** [comment]
I tried in chrome, and can not reproduce this bug. Make sure any browser extension is not blocking file import. 
You can try to open browser console (click F12) then chose "Console" tab, and then try to import your pins file. Any error should be displayed in this window. If there will be any error, you can post it here, maybe that will give me an idea why it doesn't work for you.
