### ISSUE TITLE
Timer untill next cycle

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#123]
Hey i would like to have a timer when we're close to the next cycle lets say the last hour of the day it would count down to the switch

**Comment by iligalodin** [comment]
possibly even refresh the page

**Comment by jeanropke** [comment]
I'll test this before releasing.
![countdown](https://user-images.githubusercontent.com/6243818/66245215-c98d7880-e6e2-11e9-8528-50ece4c82cff.png)

**Comment by iligalodin** [comment]
The timer should be visible with the menu closed though
