### ISSUE TITLE
Automatically set the map display language based on visitor’s location

### ISSUE THREAD

**Issue by gebederry** [jeanropke/RDR2CollectorsMap#1230]
It would be useful.

**Comment by MichalD96** [comment]
Map already has that functionality. Map initial language is set base on your browser language, so if you use english browser, your map language will be english. Another possibility is that map does not support your browser language, and sets language to default english.
You can check that clicking F12, then clik on "Console" tab, type
```javaScript
navigator.language;
```
you will get your locale looking like this: "en-US"

send here what is your locale
