### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by musiqrocks** [jeanropke/RDR2CollectorsMap#1237]
No items in any of the locations shown. Recurring bug please fix.

**Comment by MichalD96** [comment]
It is game bug, restart your game.

**Comment by MarriedMan56** [comment]
No it is not a game bug, this needs to be updated

**Comment by MichalD96** [comment]
If you play on PC
1. Change the session,
2. Restart the game,
3. Clear game cache:
    - Close game and Rockstar game launcher. (important)
    - Go to this location in Windows file explorer `%localAppData%\Temp` and delete all files with .dat extension.
    - Launch the game again.

If you play on console, unplug power cable for 30 seconds - that will delete the cache.
