### ISSUE TITLE
Incorrect item: 30 October Cycle 1 of Pentavle cards

### ISSUE THREAD

**Issue by MajesticJellyBean** [jeanropke/RDR2CollectorsMap#1238]
![Screenshot_20231030_234549_Chrome](https://github.com/jeanropke/RDR2CollectorsMap/assets/149437428/b24fc074-d7e1-4c8c-8ad6-639e22878f49)

King of pentacles Cycle 1.
Card cannot be found where the map indicates it should be.

**Comment by MichalD96** [comment]
it is common game bug, change the session, or restart your game.
