### ISSUE TITLE
items not at location on the map Day 3

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#124]
Day 3
egret egg and spoonbill egg
is not where it should be
tried it with multiple people they all cant see

**Comment by jeanropke** [comment]
I found these eggs. Uploading a video...

![monkaHmm](https://user-images.githubusercontent.com/6243818/66245495-95b35280-e6e4-11e9-85a7-5e347b9455dd.png)

**Comment by jeanropke** [comment]
Egret egg: https://youtu.be/9SK4q5llctw?t=156
Spoonbill egg: https://youtu.be/QSeKGT4fHtc?t=59

**Comment by iligalodin** [comment]
100 % was not  there for me and my posse mates. We ran the whole route just to check all the items ill check the next time its at cycle three
