### ISSUE TITLE
Collector map not updating

### ISSUE THREAD

**Issue by Rdrdan** [jeanropke/RDR2CollectorsMap#1243]
For the last week my collector map has not been updating the items, there's a message at the bottom of the page that says todays cycles have not been updated and to refresh page, i tried but its still the same. What do i need to do? I deleted the app and for the last 3 days I've been using the website instead but today i'm getting the same todays items have not been updated message there too.

**Comment by MichalD96** [comment]
We don't have any official app. We support only this website:
https://jeanropke.github.io/RDR2CollectorsMap/
What app do you use?

**Comment by winterfall01** [comment]
I was having this issue as well, and finally figured it out.

If you google "Jean Ropke collector's map", the site that comes up is "jeanropke.github.io", there's a Collector's map there, but it's not being updated. If you use the link provided by MichalD96 "jeanropke.github.io/RDR2CollectorsMap/", there's a collector's map, and it IS updated. I'm not sure why there's a map visible on both links, and it is confusing if you just click on the google search result, or if you're using a mobile browser and can't see the whole link, or if it's just something you don't think about.

Maybe it's something that can be changed or updated? Just to avoid confusion

**Comment by MichalD96** [comment]
@winterfall01 You are right, it shouldn't be there, or it should redirect to updated map. We will take care of it as soon as possible.

**Comment by MichalD96** [comment]
It should redirect now to correct URL

**Comment by Rdrdan** [comment]
Thank you! Appears to be fixed today, new items have been updated and the message at the bottom is no longer there. When i said i used the app it automatically asks if you want to download when you use the website. Thanks again!
