### ISSUE TITLE
The difference in zoom scrolling speed between the 2 maps.

### ISSUE THREAD

**Issue by xtmal91** [jeanropke/RDR2CollectorsMap#1252]
Intro:
The scrolling speed for zooming in and out on the "collectors" map is much slower than on the "interactive" map. 

**Is your feature request related to a problem? Please describe.**

I don't know if I'd call it a problem, maybe you coded it this way on purpose, but a month or two ago the speed of using the scroll wheel on my PC mouse to zoom in and out on the map was the exact same when viewing the "Collectors" map and the "Interactive" map. Then one day, zoom scrolling speed on the "Collectors" map slowed down by around half (if I had to guess). This can be a bit tiresome sometimes when I need to zoom in and out a lot when hunting for collectables in Red Dead Online. It takes several full swipes of the scroll wheel on my mouse to zoom the page all the way in or out. With the "Interactive" map, in only takes a few clicks of the scroll wheel to fully zoom in and out on the page. A big difference. If anything, I would prefer the speeds to be flipped, but I think making them match would be best.

**Describe the solution you'd like**

The solution I would like is for the zoom scrolling speed to be the same on both the "Collectors" map and the "Interactive" map. I believe finding a balance between the speed of the "Interactive" map and the "Collectors" map

**Describe alternatives you've considered**

We'll, the only alternative is for the zoom scrolling speed to be left the way it is. Maybe this was done on purpose for a reason I am not aware of.

**Additional context**
I absolutely love this website you've built. It has been enormously helpful to my friends and I. In no way am I trying to be negative about your site. Just thought I'd at least try to get the zoom scrolling speed back to how it was before.
If you've read this, thank you for taking the time.
Have a good one!

**Comment by MichalD96** [comment]
Hey, yes, i changed scroll zoom speed because many people complained, that one mouse roller click zooms at least two map levels. It seems the problem is different default mouse sensitivity on windows 10 and 11.
It is problematic to set zoom sensitivity to fit each person settings.
I have a potential fix for that issue, but it will be added after #1251 PR merge. Current version of leaflet.js does not support that setting. Zoom will be faster and much smoother.
