### ISSUE TITLE
Custom route not working at this time (2019-10-05 ~ 05:00 UTC)

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#126]

**Comment by Shaftoe62** [comment]
Oh, wait, this is going to work in a different way?

Like you add a waypoint when you click an item?

In that case you should perhaps be able to deselect by clicking the item again?

**Comment by jeanropke** [comment]
Only undo the last marker added using Left Control + Left Click

**Comment by jeanropke** [comment]
Now when pressing left control + left click on marker, the marker is removed.

**Comment by jeanropke** [comment]
Here an example:
https://gyazo.com/41183c2be8a3e750b74f5592f2ece78c

**Comment by Shaftoe62** [comment]
Ah, much better.

But if you remove an item halfway on the route, and you add it again later, its added at the end of the route again. It would be nice if the route were to be optimized again after each add and/or remove.

Not a real problem. I can work with this just fine ;-)

Also, Ctrl Click works on PC but not on touch screens like smartphones and tablets. Why not a simple left click toggle?
