### ISSUE TITLE
Missing tag on map

### ISSUE THREAD

**Issue by iPURGE93** [jeanropke/RDR2CollectorsMap#1263]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Day or Night
Latitude -1014297
Longitude 75.4375
(MACFARLANE’S RANCH)
Rough Arrowhead

**Comment by MichalD96** [comment]
It is [Random Item #17 - Cycle 2](https://jeanropke.github.io/RDR2CollectorsMap/?m=random_item_17)
