### ISSUE TITLE
Is this a time zone error?

### ISSUE THREAD

**Issue by SirPacifier** [jeanropke/RDR2CollectorsMap#1267]
For me the map says august 11, yet where am at we're still in august 10th. Is there anything I can do to fix this?

**Comment by MichalD96** [comment]
This is not a bug. It is map day not your local day. Map works in UTC/GMT timezone and exactly on midnight in that timezone collectibles change locations for everyone around the world.
Map has a few mechanisms to prevent time inaccuracy. Everything works until you see big warning message on the bottom of the map
