### ISSUE TITLE
Inventory control.

### ISSUE THREAD

**Issue by makimanson** [jeanropke/RDR2CollectorsMap#1268]
Hello!
First of all, congratulations on your work.
I would like to report an error regarding inventory control.
I will detail the steps I took to detect it.

- I have deleted the inventory
- I have imported the inventory
- I have filtered the objects by quantity: 2
- I have collected and marked the objects to complete the collections
- I have sold the collections

Immediately after, the objects whose quantity after selling the collections returns to 0 (zero) are again enabled on the map as if I had not collected them and there are still 17 hours left for it to reset

Regards

**Comment by MichalD96** [comment]
Hey.
This is not a bug, we don't store information when item has been collected, so map automatically enables all items with amount of 0 in your inventory.
You can disable that by unchecking "Automatically enable sold items" in menu. But you need to keep track by yourself of disabled items with amount of 0 in your inventory.
As far as i remember it was workaround for another inventory issue. 
After last map improvements we fixed a few bugs and can try to make that functionality, to also save pickup time.
