### ISSUE TITLE
Inventory problem 

### ISSUE THREAD

**Issue by Tommytatts** [jeanropke/RDR2CollectorsMap#1277]
How come my inventory always reseats the next day. Maybe I’m just missing a setting but I’ve tried a few and still when the map resets next day, items found still show the next day (duplicates) instead of staying faded out so I’m not going after the same thing twice. The amount of items starts the same, so I just have to go back and one by one cross them out but it’s annoying to have to day everyday. Can someone help me with this please.

**Comment by Tommytatts** [comment]
How come my inventory always reseats the next day. Maybe I’m just missing a setting but I’ve tried a few and still when the map resets next day, items found still show the next day (duplicates) instead of staying faded out so I’m not going after the same thing twice. The amount of items starts the same, so I just have to go back and one by one cross them out but it’s annoying to have to day everyday. Can someone help me with this please.

**Comment by MichalD96** [comment]
Uncheck Reset markers daily option:
![image](https://github.com/user-attachments/assets/312897cd-120a-43e6-a226-17ef7fbe4c91)
