### ISSUE TITLE
Help with French translation

### ISSUE THREAD

**Issue by Gromino** [jeanropke/RDR2CollectorsMap#128]
Hello, i'm just reporting wrong item name of the french version, if possible, do not close this thread, i will update it every time i see a wrong name.

Fleurs sauvages d'Amérique

_Petite Barbane - Jour 1_ wrong, correct is **Petite Bardane - Jour 1**

Alcools Anciens 

_Whisky d'Écosse_ is wrong, correct is **Whisky Écossais**

Objets de Famille 

_Brosse eb Palissandre de Nouvelle-Guinée - Jour 1_ just a little mistake here is **Brosse en Palissandre de Nouvelle-Guinée - Jour 1**

Bijoux égarés - Bracelets 

_Bracelet en Perles Durant - Jour 1_ is **Bracelet de Perles Durant**

Bijoux égarés - Bagues

_Bague Sertie de Diamand Sackville - Jour 1_ is **Bague Sertie de Diamant Sackville - Jour 1**

**Comment by jeanropke** [comment]
Updated.

**Comment by Gromino** [comment]
Finally I checked all the objects and made a list of all the errors
