### ISSUE TITLE
Trade Route messed up 

### ISSUE THREAD

**Issue by XenaWarrior66** [jeanropke/RDR2CollectorsMap#1280]
Went to join trade route and when it took us in it was already showing it was over and we got no XP and no money. No credit for anything.

**Comment by XenaWarrior66** [comment]
The video is down to 17 seconds and it’s still says it’s too big. What a joke

**Comment by MichalD96** [comment]
A couple of days ago R* broke absolutely everything what was possible to break in this game. Collector role was totally messed up. From one spot game were dropping 1 - 8 items, treasure hunter was giving 15 treasure maps not 1 as always. All game modes doesn't work.
R* is working on the fix, but it may take a few days. They fixed collector related bugs so far.
