### ISSUE TITLE
Treasure map locations

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#130]
This has nothing to do with the collector role, but would be very useful.

I carry around with me a pile of treasure maps. And I've been around the map (using your map) four times now to collect all items. so I've passed all those treasure map locations just as many times but totally forgot about them whilst on that location.

Now I have to go around again just for the treasure maps!! Argh...

So I would suggest a list of selectable treasure map locations just like the collections/items (but not as part of the route) so users can have a visual cue when they are near a treasure location they have in their satchel.

**Comment by Shaftoe62** [comment]
In the meanwhile I've been searching the internet and I've compiled a list and a map of treasure maps. 

If you're interested I can work out the coordinates and the diameter or radius of the search areas. 
For the latter I will need some sort of measurement reference.

I have found 28 treasure maps in total:

Bard's Crossing
Benedict Point
Black Bone Forest
Bluewater Marsh
Brandywine Drop
Calumet Ravine
Cattail Pond
Citadel Rock
Civil War Battlefield
Cumberland Forest West
Dakota River Bend
Diablo Ridge
East Watsons
Gaptooth Breach
Hanging Rock
Hawk's Eye Creek
Hennigan's Stead (Central)
Hennigan's Stead (North)
Kamassa River
Lake Isabella
Little Creek
North Clingman
North Ridgewood
North Tumbleweed
O'Creagh's Run
San Luis Shore
Southern Roanoke
West Hill Haven

Map:
[RedDeadOnlineTreasureMaps.pdf](https://github.com/jeanropke/RDR2CollectorsMap/files/3693381/RedDeadOnlineTreasureMaps.pdf)

**Comment by Shaftoe62** [comment]
P.S. The grid you see in the background image of the map are miles as far as I have been able to work that out based on the very few achievements or challenges where actual miles are mentioned. Like driving a train so many miles.

**Comment by jeanropke** [comment]
I started to add treasures ![treasures](https://user-images.githubusercontent.com/6243818/66443735-8dc21e00-ea16-11e9-81b7-e0fb5b4e3c74.png)

**Comment by Shaftoe62** [comment]
Yeah, great! 

Would be nice if you could switch on and off individual treasures just like the collection items.
