### ISSUE TITLE
Italian language !

### ISSUE THREAD

**Issue by alimouti** [jeanropke/RDR2CollectorsMap#133]
Thanks for the featured website

I've got a request why there is no Italian language

Please add Italian language

Thanks

**Comment by jeanropke** [comment]
No one has translated yet.
https://github.com/jeanropke/RDR2CollectorsMap/blob/master/langs/it-it.json

**Comment by Rakmarok** [comment]
I could set my console to Italian and transcribe everything, as well as use Google translate for all other UI elements. But I guess a native speaker would be better.

Thoughts?
