### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by glaseca** [jeanropke/RDR2CollectorsMap#135]
Hello here,

I opened an issue to complete the Spanish translation to this project.

I am going to translate /langs/es-es.json file through a pull request.

Regards!

**Comment by iligalodin** [comment]
Thank you for your effort ill check your pull and merge whenever the time comes

**Comment by glaseca** [comment]
Here there is the Spanish translation https://github.com/jeanropke/RDR2CollectorsMap/pull/141
