### ISSUE TITLE
Clock - Timed items (night flowers)

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#136]
I see you have built in a countdown for the next day in the cycle.

Ever since I worked out how the online game time worked I've been playing around with the online game time and timed events like the free roam events.

That resulted in my (quasi analog) Red Dead Online Clock. 

Have a look: https://www.reddeadonlineclock.com

It illustrates that you can calculate the exact game time. 

So, if you want, you can show on the map in real time whether a a night flower like the Blood Flower is spawning or not. 

You'll be doing a lot of people a big favor with that.

A game time clock would be a nice addition to your map anyway. Feel free to cherry pick from my clock.

But keep it analog please.

**Comment by githb123** [comment]
If this is going to be implemented then please don't remove the icons from the map during the time when it doesn't spawn. Some people may want to plan the destinations and need to see the icons anyway. Like I know that this flower/etc will spawn at a place in 10-15-20 minutes and I'm just riding over there collecting other things on the way and arriving at the spawn time.

**Comment by Jugrnot8** [comment]
I love the clock in the corner that was added.

**Comment by Shaftoe62** [comment]
Of course the icon should not be removed. On the contrary, it should be highlighted in some way to warn you.

**Comment by Shaftoe62** [comment]
Calculating the game time is actually quite easy. It is synced to 00:00 UTC time and is sped up 30x. So, one real time 24 hour day contains 30 game days.

**Comment by githb123** [comment]
@jeanropke What is the clock/countdown counting? Currently it counts down to 2 am GMT+1. Is this when it's supposed to reset? The daillies reset at 8 am GMT+1, don't the collectibles reset at the same time?

**Comment by Shaftoe62** [comment]
@githb123 No, they reset at 00:00 UTC. Which is 02:00 at GMT +1. (UTC +2)

**Comment by githb123** [comment]
ah ok. Didn't know that. Thanks.

**Comment by Shaftoe62** [comment]
@githb123  It's rather important. If you want to do the full collectible run you have to finish before that time. Otherwise you got to do map all over again :-)

**Comment by SSSidekick** [comment]
I too would appreciate being able to see what the time in game is from the map... When I am planning my routes just before I get home and hop on, I'd love to know ahead of time what time it'll be when I get there.

**Comment by MichalD96** [comment]
Clock with game time is very good idea, i wrote this timer by myself a few weeks ago, to know when log in.
you can use my code, i hope will be correct for everyone (i mean time zones)
```
        function displayGameTime() {
            let newDate = new Date();
            let startTime = newDate.valueOf();
            let offset = newDate.getTimezoneOffset();
            let correctTime = new Date(startTime * 30);

            correctTime.setMinutes(correctTime.getMinutes() + offset);

            padding = (e, s) => (1e3 + e + "").slice(-s);
            
            document.getElementById('clockBox').innerHTML = `TIME: ${correctTime.getHours() + ":" + padding(correctTime.getMinutes(), 2)}`;
        }

        displayGameTime();
        setInterval(displayGameTime, 2000);

**Comment by Shaftoe62** [comment]
@MichalD96 you can also use my clock: 

Have a look: [https://www.reddeadonlineclock.com](url)

**Comment by jeanropke** [comment]
Clicking on countdown shows the in game time
http://prntscr.com/qkbipp
