### ISSUE TITLE
Update timed events and external dependencies by interval (Madam Nazar Location)

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#138]
I can see in your code that you are using an external source for Madam Nazar's location.

I wonder, is this updated by an interval or do I have to refresh the page?

**Comment by jeanropke** [comment]
I'm not using yet. I set the position manually.

**Comment by Shaftoe62** [comment]
Ok, but keep that in mind. Best make a structured setup for all time related events.

**Comment by Shaftoe62** [comment]
Can we chat?

**Comment by ArthurMorganRDR** [comment]
New location for madam Nazar (just now). @jeanropke 

![Red Dead Redemption II Collector Map](https://user-images.githubusercontent.com/56277710/66347654-82f78280-e95d-11e9-9eb4-f87f62dc604c.png)

**Comment by jeanropke** [comment]
![madam nazar](https://user-images.githubusercontent.com/6243818/66347776-7bb78100-e92b-11e9-9f06-be61998648fe.png)
