### ISSUE TITLE
Arrowheads Location

### ISSUE THREAD

**Issue by awaisi88** [jeanropke/RDR2CollectorsMap#139]
good greeting
![٢٠١٩١٠٠٦_٠٢٤١١٠](https://user-images.githubusercontent.com/56034744/66262185-51a77700-e7e4-11e9-8817-2fd4dacda4ad.jpg)
![٢٠١٩١٠٠٦_٠٢٤٠٣٤](https://user-images.githubusercontent.com/56034744/66262186-54a26780-e7e4-11e9-88e9-c542c482e6df.jpg)
![٢٠١٩١٠٠٦_٠٢٤٠٠٣](https://user-images.githubusercontent.com/56034744/66262187-5704c180-e7e4-11e9-850e-fea37560bc9f.jpg)

**Comment by jeanropke** [comment]
I think it's day 1?

**Comment by IronJeff80** [comment]
Static Dig Bump/Random Item, Map 3
I pulled the Ivory Hairpin 
https://youtu.be/89sGX7KqBlQ

**Comment by iligalodin** [comment]
Would have loved if you submitted this to the form in the pinned issue

**Comment by jeanropke** [comment]
Added this random spot
