### ISSUE TITLE
How about tomorrow?

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#140]
It's nice the map "knows" which "Day" it is today. Or now. 

But I would also like to know what day tomorrow is. What the next cycle will be. So I can plan ahead without having to figure out how this cycle thing works everytime.

today (wednesday) cycle = 2 
tomorrow (thursday) cycle = 1 (out of 3)
day after (friday) cycle = 3 (out of 3)

wtf?

saturday 1 again?

That's not very logical but that is apparently the way it works. But I don't have that in my head.

So now I need to look it up first.

**Comment by Rakmarok** [comment]
Just reload the map, look at the day and use the small arrows next to the number to change the day. 
Right this moment while writing this comment is Day 2. It was and will always be 1 > 2 > 3 > 1 and so on.

- Day 2: Sunday.
- Day 3: Monday.
- Day 1: Tuesday.

The map changes days automatically for you. What else do you want?

**Comment by Shaftoe62** [comment]
No, the sequence is not always 1 - 2 - 3.

Its:

monday 3
tuesday 1
wednesday 2
thursday 1
friday 3
saturday 1
sunday 2



Your own code says so:


function setCurrentDayCycle()
{
    //day1: 2 4 6
    //day2: 0 3
    //day3: 1 5
    var weekDay = new Date().getUTCDay();
    switch(weekDay)
    {
        case 2: //tuesday
        case 4: //thursday
        case 6: //saturday
            day = 1;
            break;

        case 0: //sunday
        case 3: //wednesday
            day = 2;
            break;

        case 1: //monday
        case 5: //friday
            day = 3;
            break;
    }

**Comment by Rakmarok** [comment]
I don't know anything about the code as I only supply translations and bug reports, but since using the map (almost a week now) it has always been 1 > 2 > 3 > 1.

**Comment by Shaftoe62** [comment]
Well, you must be mistaken. It's impossible to have a weekly cycle of 3 spawn maps.

**Comment by Rakmarok** [comment]
> Well, you must be mistaken. It's impossible to have a weekly cycle of 3 spawn maps.

The cycle isn't bound to a seven day cycle. It continues in perpetuity. Please inform yourself before telling others they're mistaken. Thanks.

**Comment by Shaftoe62** [comment]
How to better inform myself than the source code of the actual map application?

But listen, no need to argue about this. Thursday our "predictions" will start to divert. Let's just wait and see.

You say: 

Sunday (2019-10-07) = 2
Monday (2019-10-08)  = 3
Tuesday (2019-10-09) = 1
Wednesday (2019-10-10) = 2
Thursday (2019-10-11) = 3 <<
Friday (2019-10-12) = 1
Saturday (2019-10-13) = 2

Code says:

Sunday (2019-10-07) = 2
Monday (2019-10-08)  = 3
Tuesday (2019-10-09) = 1
Wednesday (2019-10-10) = 2
Thursday (2019-10-11) = 1 <<
Friday (2019-10-12) = 3
Saturday (2019-10-13) = 2

Peace

**Comment by Shaftoe62** [comment]
Code reference:

RDR2CollectorsMap/assets/js/scripts.js

line 260 to 283

**Comment by Rakmarok** [comment]
I'm curious to see what happens. Like I said before, I have no clue about the inner workings. I can just tell you that it has worked _so far._

If it will work going forward, has to be seen. But I'm pretty certain it will be. 

Thanks for participating and looking into this.

**Comment by Rakmarok** [comment]
@jeanropke @iligalodin any knowledge on this?

**Comment by jeanropke** [comment]
Sunday to Saturday:
2 3 1 2 1 3 1

**Comment by Shaftoe62** [comment]
@Rakmarok Convinced now?

**Comment by Rakmarok** [comment]
> @Rakmarok Convinced now?

Yes, I was wrong. Thanks for clearing it up.

**Comment by Shaftoe62** [comment]
@Rakmarok I made the same (wrong) assumption as you at first. That's why I made this "issue" in the first place. Because it is so illogical with the 1,2, 3 "cycle" as it is called. It isn't a cycle. Somehow it got named that way. 

Its a 7 day cycle of 3 different spawn maps.

I now made a new issue to see if this can be made more logical for casual users: #176 

Perhaps you have any suggestions on that?

Thanks

**Comment by CaliMeatWagon** [comment]
> @Rakmarok I made the same (wrong) assumption as you at first. That's why I made this "issue" in the first place. Because it is so illogical with the 1,2, 3 "cycle" as it is called. It isn't a cycle. Somehow it got named that way.
> 
> Its a 7 day cycle of 3 different spawn maps.
> 
> I now made a new issue to see if this can be made more logical for casual users: #176
> 
> Perhaps you have any suggestions on that?
> 
> Thanks

I've been saying this since the for almost a month now, it needs to be called "Set" Collection Set, not Day, not Cycle. Those lead to the wrong idea of how it works.

**Comment by Shaftoe62** [comment]
@CaliMeatWagon It's now all explained on the "help" page:

https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-User-Guide-(English)

**Comment by Rakmarok** [comment]
> > @Rakmarok I made the same (wrong) assumption as you at first. That's why I made this "issue" in the first place. Because it is so illogical with the 1,2, 3 "cycle" as it is called. It isn't a cycle. Somehow it got named that way.
> > Its a 7 day cycle of 3 different spawn maps.
> > I now made a new issue to see if this can be made more logical for casual users: #176
> > Perhaps you have any suggestions on that?
> > Thanks
> 
> I've been saying this since the for almost a month now, it needs to be called "Set" Collection Set, not Day, not Cycle. Those lead to the wrong idea of how it works.

We call them `Collection map` now. You can see how it works in the wiki (thanks @Shaftoe62 ).

**Comment by Shaftoe62** [comment]
@Rakmarok Excellent. Now it all makes sense.

**Comment by Shaftoe62** [comment]
@Rakmarok I noticed that in most other languages "Day" has not been replaced by "Collection map" yet. Should there perhaps be a sticky issue for the other translators? 

How is this coordinated?

**Comment by jeanropke** [comment]
Removed day field. No need this settings if the code set the correct day

**Comment by Shaftoe62** [comment]
NOoooo, now I can't plan ahead anymore for tomorrow!! :-(

**Comment by Shaftoe62** [comment]
Ok, but it was fine when "Day (1-2-3)" was changed in "Collector Map (1-2-3)" as @Rakmarok had made it. That was logical.

**Comment by iligalodin** [comment]
What do you want?

**Comment by iligalodin** [comment]
Credits? We’ll give you credits even collaborator status

**Comment by Shaftoe62** [comment]
Don't need credit or special status. Just trying to help. @Rakmarok had just changed that and modified the wiki accordingly:

![image](https://user-images.githubusercontent.com/53898212/66792569-a2f8ea00-eef9-11e9-965a-bbedf42e8543.png)
