### ISSUE TITLE
[Bug Report] 1800 Gold Dollar Coin not connected to route

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#142]
* The cycle is Day 2.
* Coordinates and a clear image of the location:
![image](https://user-images.githubusercontent.com/55949253/66262834-a816b480-e7e8-11e9-97cf-a888c2ac982a.png)

* 1800 Gold Dollar Coin.

Coordinates can be found by setting the `Show coordinates on click` to `Yes`.

**Comment by jeanropke** [comment]
Fixed
