### ISSUE TITLE
 Custom markers for Unspecified digsites

### ISSUE THREAD

**Issue by AnuKaro** [jeanropke/RDR2CollectorsMap#144]
Suggestion 1). To enable costum marks. One for dirtpiles and one for sites where the Metal detector is needed.

And if youve enabled to dynamic or costum route. The two closest marks will automatically link to the mark you've added yourself.))

Suggestion 2). If you've enabled either dynamic or costum route. And you remove a mark (disabling it) the website will automatically selfcenter on the next link in the chain. (don't know if that'll be possible).

**Comment by Senexis** [comment]
Just added pins which allow you to make a marker with a title and a description. I'll look into icon choices and tool type selection in the near future.

**Comment by Senexis** [comment]
I just added an icon option to user markers, with the option to set it to a spade or metal detector icon too.
