### ISSUE TITLE
Help with Italian translation

### ISSUE THREAD

**Issue by alimouti** [jeanropke/RDR2CollectorsMap#148]
Help with Italian translation

I want someone to help me in translation into Italian

Thanks

**Comment by Nopitch** [comment]
What Kind of help do you need ?

**Comment by alimouti** [comment]
Anyone who knows Italian helps me in translation because there are so many words to translate

**Comment by Nopitch** [comment]
First things first, let’s focus on the collectables and for that the only thing you have to do is put your red dead redemption in Italian and list every names as they are in the game. You don’t want  to translate it on your own because people will look after them as they are spelled in their game.

**Comment by alimouti** [comment]
ok.

**Comment by Raffox97** [comment]
I've finished the translation just today (#189) :D

**Comment by alimouti** [comment]
> I've finished the translation just today (#189) :D

Good I was starting but not finished yet
But thank you for finishing the translation now would be good for those who speak Italian
