### ISSUE TITLE
splintered arrow head day 1 location

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#15]
I found this item right next to the MacFarlane's Ranch under the bridge on the road eastbound in the center on cycle day 1.

**Comment by iligalodin** [comment]
could you get a screenshot of the exact location?

**Comment by jeanropke** [comment]
See the video and confirm the place. I found a ring in this place.
https://www.youtube.com/watch?v=ARcMG5m28x0&feature=youtu.be

**Comment by githb123** [comment]
Yes, I can confirm. It’s the location from this video.

**Comment by githb123** [comment]
You need a shovel for this one. It’s in a mound.

**Comment by iligalodin** [comment]
random item location
