### ISSUE TITLE
New Location 

### ISSUE THREAD

**Issue by txkels13** [jeanropke/RDR2CollectorsMap#151]
Just found the Ojeda Rose Gold Bangle Bracelet at this location. 9:50am EST, 10/6. Exactly where my player is. 

![20191006_094607](https://user-images.githubusercontent.com/56225701/66270238-f9da3180-e81e-11e9-8c7e-21f3b6234ea9.jpg)

**Comment by jeanropke** [comment]
Found a 1787 One Cent Token.
Day 2.
