### ISSUE TITLE
Import/Export not working

### ISSUE THREAD

**Issue by Jelbrehir8** [jeanropke/RDR2CollectorsMap#153]
I just made a custom route and when I export, I am only generating the map address. i.e https://jeanropke.github.io/RDR2CollectorsMap/

Edit: now seems to be working

**Comment by Jelbrehir8** [comment]
Can export but file is still invalid to import

**Comment by jeanropke** [comment]
Can you send the code?

**Comment by Jelbrehir8** [comment]
earring_josephine_pearl,coin_gold_quarter,pentacles_t

wo,bottle_irish_whiskey,pentacles_nine,coin_half_dim

e,earring_beauchene_ruby,ring_beaulieux_diamond,swo

rds_ace,ring_sackville_diamond,bracelet_infanta_turqu

oise,swords_ten,swords_page,earring_royal_victoria,coi

n_half_eagle,arrowhead_obsidian,necklace_ainsworth_

cross,pentacles_five,earring_ursula_citrine,bottle_old_t

om_gin,arrowhead_crude,wands_four,swords_six,egg_h

eron,cups_page,bottle_gran_corazon_madeira,earring_e

ndicott_diamond,wands_queen,arrowhead_chipped,wa

nds_nine,swords_king,flower_wisteria,earring_duchess

_emerald,arrowhead_quartz,pentacles_queen,heirlooms

_boxwood_comb,pentacles_eight,wands_knight,heirloo

ms_cherrywood_comb,egg_spoonbill,egg_egret,earring_

orchidee_diamond,flower_cardinal,flower_creek_plum,

heirlooms_rosewood_hairbrush,flower_chocolate_dais

y,coin_five_dollar_bechtler,cups_seven,pentacles_page,r

ing_aubrey_onyx,wands_five,coin_quarter,wands_three

**Comment by Jelbrehir8** [comment]
perhaps it is an issue with Incognito mode? because I exported from regular Chrome tab and it imported fine

**Comment by Jelbrehir8** [comment]
and now, not exporting at all

**Comment by jeanropke** [comment]
I was not supposed to have breaklines.

**Comment by jeanropke** [comment]
Added a code to remove breaklines/spaces.
