### ISSUE TITLE
Texas Bluebonnet cycle 2 missing in the described location, found in another

### ISSUE THREAD

**Issue by Ctlz21** [jeanropke/RDR2CollectorsMap#154]
* Second cycle
* lat: -118.28125
  lng: 12.828125
* Texas Bluebonnet
![texas bluebonnet 2](https://user-images.githubusercontent.com/16960632/66272422-3125fe00-e872-11e9-93a9-bbede1f22aa7.png)

**Comment by jeanropke** [comment]
I found the flower in the map location. Also I found in the image location.

**Comment by Ctlz21** [comment]
cool, good that it spawned for you in the original location, I had to reload my game twice and go to other cycles locations even. Rockstar and its tricks...

**Comment by IronJeff80** [comment]
Looks like all the flowers have 6 spawn locations daily. All have been dded to the Random Item spreadsheet: https://docs.google.com/spreadsheets/d/1lvKU2381F8pQQY52hqFQKpVTJnrdoIITYppOm3Zv7z8/edit#gid=1235291651
