### ISSUE TITLE
Missing Heron egg [Day 2]

### ISSUE THREAD

**Issue by Daryan97** [jeanropke/RDR2CollectorsMap#155]
* What day cycle it is?
Answer: Day 2
* Coordinates and a clear image of the location
lat: -71.11058902521644
lng: 144.38124990463257
![image](https://user-images.githubusercontent.com/29106122/66273111-af39d300-e879-11e9-8274-6bf29b9c4ad9.png)
* Include the item name
Heron egg

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
I found the egg in this location.
Last night I see a duck removing an egg from the nest. 
Maybe this occurred with this egg?

**Comment by Daryan97** [comment]
@jeanropke 2 other friend of me confirmed that they couldn't see or find the egg in this location

**Comment by jeanropke** [comment]
That's weird. 
Sometimes I find the eggs on the floor, nest destroyed.
Eggs & Plants are so inconsistent.

**Comment by Jugrnot8** [comment]
> That's weird.
> Sometimes I find the eggs on the floor, nest destroyed.
> Eggs & Plants are so inconsistent.

Ive had a couple times Ive needed to hobby lob for an item to show up. Those particular times other active content was happening in the area. I wonder if that could be the cause of why sometimes this happens. Its very rare tho.

**Comment by Daryan97** [comment]
@jeanropke i really don't know, that's the only item i had issue with, i collected everything else but that egg

**Comment by iligalodin** [comment]
i've had issues with eggs where the nest and glow would not show up but the egg would still be on a branch or on the ground

**Comment by iligalodin** [comment]
also it seems when i was running with 8 people yesterday that a couple of em could not pickup eggs, coins or arrowheads when others already picked them up, however if it was a card or a bottle all could pick em up

**Comment by IronJeff80** [comment]
I have seen a coyote take the egg.  after skinning the coyote, I retrieved the egg.

**Comment by IronJeff80** [comment]
I saw the Coyote going for the egg again but, shot it before thinking about watching what it does. 
https://youtu.be/Kdbe4VhmeVA
