### ISSUE TITLE
Day 2 Lemoyne

### ISSUE THREAD

**Issue by Jugrnot8** [jeanropke/RDR2CollectorsMap#156]
Day 2 Lemoyne

Arrowhead 
lat: -84.28125
lng: 125.546875

Arrowhead (Near this area)
lat: -83.09375
lng: 137.15625

Braxton Necklace
lat: -83.4140625
lng: 122.3125

Hairdresser set
lat: -91.953125
lng: 121.9296875

R* Disconnected me b4 I discovered
lat: -99.125
lng: 133.078125

**Comment by Alfakennyone** [comment]
Found another dig site for a lost jewelry today

Latitude: -121.8047
Longitude: 20.5391

**Comment by jeanropke** [comment]
@Alfakennyone Random item spot #56
