### ISSUE TITLE
Day 2 Scarlett Meadows, Lemoyne

### ISSUE THREAD

**Issue by Jugrnot8** [jeanropke/RDR2CollectorsMap#157]
Can you please give me feedback. I missed some names but getting better at this and will continue if I understand that these will be added to the app and when so that I know im not wasting mytime. 

Please and Thanks

Phil Rewa

Tamateu Necklace
lat: -95.78125
lng: 137.578125

Arrowhead
lat: -89.09375
lng: 144.59375

Cardinal flower
lat: -88.4921875
lng: 142.8203125

lat: -87.6484375
lng: 142.5859375

1789 Penny
lat: -90.453125
lng: 134.53125

Durant Bracelet
lat: -64.7109375
lng: 139.59375

Slate Arrow Head
lat: -68.8125
lng: 142.078125

Thorborn Ring
lat: -69.046875
lng: 136.3671875

Bone Arrowhead
lat: -68.828125
lng: 128.75

1800 Gold Dollar
lat: -66.6796875
lng: 127.0078125

Gosseling Necklace
lat: -76.6875
lng: 123.015625

Chocolate daisy
lat: -77.375
lng: 122.3828125 

1700 New York Coin
lat: -77.703125
lng: 130.28125

Pell Necklace
lat: -80
lng: 129.171875

Feldspar Arrowhead
lat: -80.453125
lng: 135.265625

Ainsworth Necklace
lat: -83.34375
lng: 137.96875

Carved Hairpin
lat: -86.515625
lng: 137.40625

**Comment by iligalodin** [comment]
could you by chance remember on what cycle you fond these items ?
