### ISSUE TITLE
Flor de sangre, el lugar no es correcto. 

### ISSUE THREAD

**Issue by AldeanosGamer** [jeanropke/RDR2CollectorsMap#158]
Los dos lugares de flor de sangre del día 3 No son correctos como muestra en el mapa, solucionarlo por favor.

**Comment by Jugrnot8** [comment]
Solo llegan de noche. Después de los juegos a las 10 p.m. y antes de las 4 a.m. o algo parecido


In English: his questions and my answer:

The two places of blood flower on day 3 are not correct as shown on the map, please fix it.

They only arrive at night. After the the games 10 pm and before 4am or something close to that

**Comment by Vitor-Borba72** [comment]
The map creator speaks English. Be considerate to him and all his good work and post your issues in English.

**Comment by jeanropke** [comment]
Agarita & Flor de sangre solo aparecen de noche
