### ISSUE TITLE
Idea for the items that are not consistent

### ISSUE THREAD

**Issue by Jugrnot8** [jeanropke/RDR2CollectorsMap#159]
Have a filter/layer for locations where the item is not consistent. Then with in the popup on the map leave a link to a page that they can share what they found there so data can be collected. 

Just a thought bc I see how many spots there are that are not consistent.

**Comment by IronJeff80** [comment]
Seems the locations are static, just a random item. Maybe include them with a "?" icon and category for Random Item.

**Comment by iligalodin** [comment]
We're collecting data for this, if you find these spots could you submit them via the form in the pinned issue?
