### ISSUE TITLE
Today's MP day 3 Some items were already greyed out..? 

### ISSUE THREAD

**Issue by potestus** [jeanropke/RDR2CollectorsMap#161]
I'm in the UK. Timer shows reset at midnight when it's actually 7 am locally.

**Comment by Rakmarok** [comment]
Can you add a screenshot of this particular issue or explain it in more detail, please?

Thank you.

**Comment by potestus** [comment]
Ok
I've reset the map so can't give you a picture.. Thanks for this by the
way..

1/ On opening today's map some of the items were ready flagged.. It was
just a few and I'm sure not as many as the last time I did day 3.

2/ The timer is set to midnight yet in the UK we reset at 7am BST. . I
havn't looked after midnight and before 7am yet to see th map


Terry

Mobile 07703476261

**Comment by Rakmarok** [comment]
Nice to meet you, Terry.

You should delete your mobile phone number. The internet can be a ruthless place. (It seems like your email program added it automatically.)

- On topic: Currently the automatic removal of previously hidden markers isn't working, that is why your markers still had the same state as when you last used the map. A fix is in the works. In the meantime, use this option:
![Daily marker reset](https://user-images.githubusercontent.com/55949253/66317669-4191b380-e91a-11e9-8c08-3fad2573e99b.png)

- The map (and all collectibles on Rockstar servers) resets at 00:00 UTC, which is 01:00am BST (British Summer Time).

I hope I could help.

**Comment by potestus** [comment]
Thanks,

I already reset the map. Our daily reset for challenges is 7am. So
collector's is different?


Terry

**Comment by Rakmarok** [comment]
Yes, the collectibles are indeed different from the challenges.
