### ISSUE TITLE
[QoL] Adding chosen map mode (Default/Detailed/Dark) to cookie/saving it

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#162]
**Is your feature request related to a problem? Please describe.**
The map resets the mode every time you reload it.

**Describe the solution you'd like**
Saving the chosen map mode/look in the cookie (or where ever the markers are saved).

**Describe alternatives you've considered**
Nothing applicable? 🤔

**Additional context**
![image](https://user-images.githubusercontent.com/55949253/66298807-a0dbcd80-e8f2-11e9-8629-6ae170ffdeb2.png)

**Comment by iligalodin** [comment]
will look into it!

**Comment by iligalodin** [comment]
the source of the api we're currently using is minified and obfuscated so hard i cant make sense of it 
i would like to request that we start using the readable javascript so we have more controlability over the map and possible future modifications

**Comment by jeanropke** [comment]
Map style saved in cookies now
