### ISSUE TITLE
Blakely Miniature Necklace - Incorrect Spelling (Missing 'R')

### ISSUE THREAD

**Issue by B9253021** [jeanropke/RDR2CollectorsMap#164]
All Cycles, Item is in correct location but has incorrect spelling.

Current Spelling: Blakely Miniatue Necklace
Correct Spelling: Blakely Miniature Necklace

**Comment by iligalodin** [comment]
we already have it to miniature in the english localisation, what translation are you refering to?

**Comment by B9253021** [comment]
My apologies, I had not refreshed my browser in a few days. I can see now that the spelling has been corrected. Thank you.
