### ISSUE TITLE
Portuguese translation: the word for "goose" is "ganso", not "ganço". 

### ISSUE THREAD

**Issue by Vitor-Borba72** [jeanropke/RDR2CollectorsMap#166]
Just willing to help, not to be annoying. 
Source: I'm a native portuguese speaker.

**Comment by Rakmarok** [comment]
Thank you, I will create a pull request. 

#167

**Comment by Rakmarok** [comment]
Thank you, I will change it and create a pull request.

**Comment by Rakmarok** [comment]
#167

**Comment by Rakmarok** [comment]
> Just willing to help, not to be annoying.
> Source: I'm a native portuguese speaker.

How is it spelled in-game?

**Comment by iligalodin** [comment]
thanks for pointing this out!

**Comment by jeanropke** [comment]
Esse é o motivo de não fazer as coisas com sono.
