### ISSUE TITLE
Missing item

### ISSUE THREAD

**Issue by Sluggr29** [jeanropke/RDR2CollectorsMap#168]
* day 1
* lat: -97.485595703125
lng: 85.78173828125
* 1797 Gold Eagle Coin

No coin in that area

**Comment by Jugrnot8** [comment]
I just verified that it was there for me. Try leaving the lobby and going to a new one. 


Side note


Should have a discord for users to help one another out and collect treasures together. That would be cool to see a bunch of people all working together.

**Comment by Sluggr29** [comment]
https://discord.gg/5rKE2cb

There already is one! Come join us!
