### ISSUE TITLE
burdock location day 1

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#17]
Right at the southern track, south to Stillwater Creek, just below the 5th dot on the track counting from west to east.

**Comment by iligalodin** [comment]
could you get a screenshot of the exact location?

**Comment by githb123** [comment]
Screenshot in attachment.

It's a flower so no tools needed.

![burdock](https://user-images.githubusercontent.com/55925524/65828954-ce949700-e2a0-11e9-8548-1da62b2c4d08.png)

**Comment by iligalodin** [comment]
just noticed this is not a "collectible" it's just a regular flower
