### ISSUE TITLE
1795 Half Eagle

### ISSUE THREAD

**Issue by DaveB93** [jeanropke/RDR2CollectorsMap#171]
* What day cycle it is? day1
* Coordinates or a clear image of the location lat: -69.0703125
lng: 74.5625
* Include the item name 1795 half eagle

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by DaveB93** [comment]
out of curiosity, is there a way to know this is a random item location beforehand?  did it just not show up for you or you got a different thing  from it ?   is the purpose of your map to get a person a complete set ?    

personally I'd like a layer with 'random items'  but wondering what your goal is.

**Comment by jeanropke** [comment]
I found another item in this spot.
If the map contains over 300 markers at same time, will be a performance issue.
Maybe in future I add an option to enable random spots.
