### ISSUE TITLE
Add our own pins

### ISSUE THREAD

**Issue by Jugrnot8** [jeanropke/RDR2CollectorsMap#174]
With so many spots that are not consistent yet they have items it would be great to be able to add our own pins. So we select which days pins we have saved personally that want to see. 

There are so many spots that aren't included in the app it's crazy. I understand they are not consistent with the contents but it's money we are all traveling past anyways. 

*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrissydewet** [comment]
I second this . Even add a way for us to register pin selection per char. Eg where the timer is running out have our names next to it @chrissydewet with options of "extra pins " enabled/disabled.

**Comment by iligalodin** [comment]
we're looking into the random locations, we would love more data for them. 

we have a way of creating debugmarkers but not yet on saving them. because we're using github this means we cant create a database for users to save stuff in, that's why we're using cookies to store the data and load them... this method is quite slow for large datasets

**Comment by CaliMeatWagon** [comment]
> we're looking into the random locations, we would love more data for them.
> 
> we have a way of creating debugmarkers but not yet on saving them. because we're using github this means we cant create a database for users to save stuff in, that's why we're using cookies to store the data and load them... this method is quite slow for large datasets

Why not have it to where it saves on our browser? Have a save file that we can import and export. I know different game, but something like this: 
https://coriolis.io/

**Comment by Senexis** [comment]
This was just added with import/export functionality. Possible future improvements include a better editing system, icon choices, and tool type choices.

Let me know what you think!
