### ISSUE TITLE
confusion about weekdays and cycle days

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#176]
As you can see in my previous issue #140 there is a lot of confusion about how the collector cycle actually works.

Some people think its a repeating three day cycle (1 - 2 - 3) while it actually is a weekly cycle.

Perhaps this can be clarified in some way so one can plan in advance for the next day.

The input #day could just as easy be a select with the weekday names as options and the appropriate cycle days as values. Like:

Monday (3)
Tuesday (1)
Wednesday (2)
Thursday (1)
Friday (3)
Saturday (1)
Sunday (2)

That would be much more user friendly

**Comment by Shaftoe62** [comment]
Perhaps this as an interface idea?

![image](https://user-images.githubusercontent.com/53898212/66477695-f4881b80-ea98-11e9-9088-1764f3748dc7.png)

**Comment by Shaftoe62** [comment]
Or maybe:
![image](https://user-images.githubusercontent.com/53898212/66481001-37012680-eaa0-11e9-90a5-99a5a175d5ef.png)

**Comment by Rakmarok** [comment]
> Or maybe:
> ![image](https://user-images.githubusercontent.com/53898212/66481001-37012680-eaa0-11e9-90a5-99a5a175d5ef.png)

I think this fits better with the game, as the title also uses "II" instead of "2".

**Comment by Shaftoe62** [comment]
Actually, it could have been A, B, C or any other symbol rather than 1, 2, 3. It's the numbers that make it so confusing. And the word "cycle" everybody is using. 

♦ - ♣ - ♠ would be nice as well.

**Comment by iligalodin** [comment]
In my oppinion it should be 1 2 and 3 to be concistent with the reddit page

**Comment by Shaftoe62** [comment]
Which Reddit page is that?

**Comment by iligalodin** [comment]
Reddit.com/r/reddeadcollectible and online

**Comment by Shaftoe62** [comment]
@iligalodin Do you perhaps have a working link for that? I'm getting nowhere with that.

**Comment by iligalodin** [comment]
[https://www.reddit.com/r/RedDeadCollector/](url)

**Comment by Shaftoe62** [comment]
Somehow the link doesn't work but I've found the page.

The page is like a community page where anybody can post anything. Why should that be "compulsory" for anybody?

In my view the @jeanropke map is now THE authority on the collectible spawn cycle. He can do whatever he wants.

**Comment by iligalodin** [comment]
Its one of the main sources of information for a lot of players and other outlets, so again we should follow the standart instead of setting one

**Comment by Shaftoe62** [comment]
Well, that is a matter for another discussion entirely.

What I'm trying to achieve here is to clarify for everybody how the three different collectible spawn maps (your 1 - 2 - 3) make up a weekly cycle!

Monday (3)
Tuesday (1)
Wednesday (2)
Thursday (1)
Friday (3)
Saturday (1)
Sunday (2)

If you search the word "cycle" in the reddit page you mentioned you will see that the most common question is:

What's the cycle today??

**Comment by Rakmarok** [comment]
I was bamboozled by it too, and I'm not an idiot (most of the time).

**Comment by iligalodin** [comment]
would be a nice addition for the wiki😉
