### ISSUE TITLE
Madam Nazar relocates at 06:00 UTC

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#177]
The collectible cycle resets at 00:00 UTC but Madam Nazar relocates 6 hours later together with the daily challenges.

Perhaps this can be clarified in some way? Might be confusing for some users.

**Comment by ArthurMorganRDR** [comment]
@jeanropke Just found Madame Nazar right now. She's at these coordinates:

lat: -90.078125
lng: 135.6875
