### ISSUE TITLE
Treasure Maps

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#181]
I would love to see the possibility to SHOW all treasure maps, then CHECK THEM ALL (so they are greyed out), then just UNCHECK the maps I have with me.
By doing so I would always be aware of an active treasure map in or nearby the area I am collecting stuff.

**Comment by iligalodin** [comment]
so you wnd a submenu for the treasuremaps?

**Comment by DaveB93** [comment]
Duplicate of #130
