### ISSUE TITLE
Missing Item location Form

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#182]
Hello guys if you find a random item location please submit it to this form

https://forms.gle/xqKHMTWvqBt2v5eK7

This makes it easier for us to validate if a location is a fixed or random item
Once we have enough i would like to add them to the map,

make sure you check the responses to know if the location already has been submitted!
responses: http://tiny.cc/mapresponse

thanks!

**Comment by iligalodin** [comment]
i've also created a discord for Jeanropke and the other contributors to converse easier

invite link: https://discord.gg/2Wwj2q

**Comment by MilkedRips** [comment]
2nd Chipped Arrowhead (Blue Cycle). Next to the house with the dotted trail leading up to it is a dig spot, near the chocolate daisy location in Lemoyne.

**Comment by iligalodin** [comment]
M8 click on the link

**Comment by ArthurMorganRDR** [comment]
![Red Dead Redemption II Collector Map (1)](https://user-images.githubusercontent.com/56277710/66720718-330b3680-ee09-11e9-87fb-8693e015805c.png)
New item found, but don't know yet which day. I will use the form when I know exactly

**Comment by ArthurMorganRDR** [comment]
It's day 2

**Comment by Ootat** [comment]
It’s a day 2 shovel location but the loot is random. I collected a Rou Pearl Necklace from it.

**Comment by LukyVj** [comment]
Hello, thanks for what you do! 

Question: Will you plan on adding the random item locations on the map? I've heard that you were not interested in doing such?

**Comment by jeanropke** [comment]
I'm interested, just worrying about the performance with a ton of markers

**Comment by JaguarSF** [comment]
[https://ibb.co/TWR3M14](url)
[https://ibb.co/HC964Bj](url)
found a new egg, Day 2 Cycle

**Comment by Ootat** [comment]
That bird nest is already shown in the map

**Comment by JaguarSF** [comment]
my bad, you're right it's an egg encounter and it is there on the map

**Comment by Kamiikaze** [comment]
Arrow on

lat: -60.234375
lng: 122.71875

isnt correct, havent collected the item today and its not in my collection but cant be found there

**Comment by ilinyzili** [comment]
not sure how to get the screenshot to link to the form. so im assuming im not the only one. how does one do this?

**Comment by NF13** [comment]
#515

**Comment by whoispmb** [comment]
New location for QUARTZ ARROWHEAD:

Coordinates:
lat: -65.73147583007812
lng: 68.39437866210938

Found using metal detector along side of the road

**Comment by whoispmb** [comment]
New location OBSIDIAN ARROWHEAD; 

Coordinates:
lat: -114.93121337890625
lng: 24.653594970703125

Found using metal detector along side of the road

**Comment by whoispmb** [comment]
New location 1792 Quarter: 

Coordinates: 

lat: -112.609375
lng: 51.5546875

Found using metal detector right in between the cannons, shovel required

**Comment by whoispmb** [comment]
New location Eight of Swords Tarot Card: 

Coordinates:
lat: -93.671875
lng: 92.6171875

Inside the shack before the pier on the table across from the door

**Comment by whoispmb** [comment]
New location WISTERIA: 

Coordinates: 
lat: -80.89111328125
lng: 83.599853515625

Found with map from M.L. on top of the rock by the small water drop

**Comment by thiccolai** [comment]
Ten Of Wands location In Doverhill laboratory N/E corner by a typewriter
lat: -28.1328125 
lng: 150.3671875

**Comment by TheTallifer** [comment]
Cycle 5
Seven of swords Tarot
Two of wands Tarot
Both missing in marked locations. Does not say they require metal detector or shovel. I have shovel.

**Comment by TheTallifer** [comment]
Madam Nazar is up at Window Rock for 24th decem,ber, map has her south opf theives landing

**Comment by mi5hmash** [comment]
Cycle 6 - 15th Coin
lat: -63.8515625
lng: 116.8046875
Down the pit.

**Comment by whoispmb** [comment]
New location TEXAS BLUEBONNET:

Coordinates:
lat: -89.1171875
lng: 98.6015625

Not sure the cycle but I have the map set for today, American Wild Flowers 7

**Comment by ilinyzili** [comment]
lat: -110.0445298019169
lng: 35.46875

Wild Rhubarb location

**Comment by BE3dARt** [comment]
Random item #74 - Cycle 2

Latitude: -107.0859
Longitude: 74.2344

Just a bit off, like 20 meters.

**Comment by Senexis** [comment]
Closing for now as all or by far most locations have been extracted and the form is outdated since moonshiners.
