### ISSUE TITLE
To jeanropke (Just a message)

### ISSUE THREAD

**Issue by Legendary-Lord** [jeanropke/RDR2CollectorsMap#188]
I'm unable to message you anyway..

But please don't make it paid membership like rdr2map website where half of the collections are paid membership only.

Quick question
Are you gonna keep updating it for RDR2Collectors? Like when RDR2 update come out in December or whatever...

but thanks for the open source of RDR2Collector Map

**Comment by jeanropke** [comment]
1. I won't make any type of membership (that's why there is a donate button)
2. I'll keep updating if necessary.
