### ISSUE TITLE
Question: Autosave and Days

### ISSUE THREAD

**Issue by Kettenknecht** [jeanropke/RDR2CollectorsMap#19]
Hello,

Please allow two questions. First: Is the map autosaved (found and then hidden items) if I close the browser window? And, what is the days field meaning?

Thank you very much for your work. This map helps a lot

**Comment by jeanropke** [comment]
The map is saved when you click on 'Remove from map'.
The day field is to show which day is. Or when the day is wrong, you can set manually.

**Comment by rbcunhadesign** [comment]
Cycle is as follows:
Day 1 - Tuesday Thursday and Saturday GMT

Day 2 - Wednesday and Sunday GMT

Day 3 - Monday and Friday GMT
