### ISSUE TITLE
INCLUSÃO DE ITENS

### ISSUE THREAD

**Issue by deividkc** [jeanropke/RDR2CollectorsMap#190]
**Is your feature request related to a problem? Please describe.**
A clear and concise description o
![MAPA ESCONDERIJOS DE GUANGUES RDR ONLINE](https://user-images.githubusercontent.com/56399187/66575696-c237f600-eb4c-11e9-96bb-dfdd3b7ce65b.jpg)
f what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
sugestão para inclusão destes itens no mapa

**Describe alternatives you've considered**

**Additional context**

**Comment by deividkc** [comment]
Sugestão de inserção destes itens

**Comment by jeanropke** [comment]
Caso esteja interessado, aqui ta o projeto: https://jeanropke.github.io/RDOMap/

**Comment by deividkc** [comment]
Very good!

Em sáb, 19 de out de 2019 20:09, jeanropke <notifications@github.com>
escreveu:
