### ISSUE TITLE
Select multiple tools

### ISSUE THREAD

**Issue by IronJeff80** [jeanropke/RDR2CollectorsMap#194]
Can you make the tools list "select multiple? 

Example, The collector who doesn't have a metal detector, whats to finds all items with "No Tools, and Shovel"

Currently, they can choose No tools, then change to Shovel, but cannot have both together

**Comment by jeanropke** [comment]
When selecting 'Shovel', will enable 'No tools' and 'Shovel'.
Selecting 'Metal detector', will enable 'No tools', 'Shovel' and 'Metal detector'
