### ISSUE TITLE
treaure

### ISSUE THREAD

**Issue by bonefish04** [jeanropke/RDR2CollectorsMap#195]
show possible locations of random treasure hunter spawns with times etc and treasure maps on trees

**Comment by iligalodin** [comment]
Wait thats a thing? Do you have data for that?

**Comment by IronJeff80** [comment]
Definitely a thing. Treasure Hunter are out there and you can steal their maps or buy them. I've only came across about 5, all in completely different locations. I'd be willing the locations are as static as gang hideouts. Also, I have 2 locations were Treasure maps spawn on trees. They always spawn at night. They are stuck to a tree with a knife and a lantern.

Treasure Hunter 1:  On the cliff's edge around dusk Monday :
lat: -66.37510692265303 
lng: 114.578125
https://youtu.be/9bhPMTCq_uk

Treasure Hunter 2: on cliff edge near Cumberland Falls around afternoon Wednesday. 
lat: -57.20290953465374
lng: 93.96875
https://youtu.be/B6-dUHzeq50

Map on Tree: Night time near burned area, look for lantern light. 
lat: -119.39959906882154
lng: 53.5078125

Map on Tree: Night time on hills above Valentine, near Cumberland Forrest. Look for lantern light. lat: -49.21028948392104
lng: 110.5859375

**Comment by bonefish04** [comment]
Thanks for that

**Comment by IronJeff80** [comment]
Duplicate #271
