### ISSUE TITLE
RDO Collectors Map User Guide (English)

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#198]
### _Welcome to the unofficial Red Dead Online Collectors Map and official User Guide!_

_Written by Rakmarok._

This guide will help you understand _when_ you can find _what_ and _where_, as well as basic understanding of all functions the map is able to perform.

***

### Map Marker Colours:

**Map Marker Colours**:
- Blue map markers: Map 1 collection.
- Orange map markers: Map 2 collection.
- Purple map markers: Map 3 collection.
- Green map markers (max. 3 items): Madam Nazar's weekly collection.

***

### The Collection Maps & Collection Map Change:

**The collection maps**:
- The collection maps work according to this logic:
1. Monday (Collection map 3)
2. Tuesday (Collection map 1)
3. Wednesday (Collection map 2)
4. Thursday (Collection map 1)
5. Friday (Collection map 3)
6. Saturday (Collection map 1)
7. Sunday (Collection map 2)
- Please note: The site will _always_ use the correct collection map automatically.

**Collection map change**:
Collection maps change every day at 00:00 UTC/GMT which is:
- 07:00pm EST/08:00pm EDT (New York, UTC -4)
- 04:00pm PT/05:00pm PDT (Los Angeles, UTC -7)
- Please note: Collectibles in-game will _immediately_ change location at this time according to the new collection map. No server change is necessary.

**Madam Nazar's Location**:
- Madam Nazar's location changes every day at 06:00 UTC/GMT (the same time as daily challenges), which is:
- 01:00am EST/02:00am EDT (New York, UTC-4)
- 10:00pm PT/11:00pm PDT (Los Angeles, UTC-7)

***

### Basic Map Functionality:

**In the upper right corner is the map mode select, including these options:** 

![RDO Collectors Map Dark Map Mode Map Mode Select](https://user-images.githubusercontent.com/55949253/66665106-21316400-ec4e-11e9-9b1d-f4e0b21c71b9.png)
![Annotation 2019-10-12 032805](https://user-images.githubusercontent.com/55949253/66692655-caa14580-eca0-11e9-9f44-a0c7df828cfa.png)

> Default: Map with details like roads, paths and train tracks having lower opacity.

> ![Annotation 2019-10-11 174643 Cropped](https://user-images.githubusercontent.com/55949253/66665636-3b1f7680-ec4f-11e9-8ccd-cacedc977e44.png)

> Detailed: Map with details like roads, paths and train tracks having standard opacity. Identical to the in-game map. This is the default. 

> ![Annotation 2019-10-11 174337 Cropped](https://user-images.githubusercontent.com/55949253/66665509-ff84ac80-ec4e-11e9-9f45-8d62c84bd495.png)

> Dark: Map with details like roads, paths and train tracks drawn in white, with the map background being dark gray. Great for night viewing.

> ![Annotation 2019-10-11 174350 Cropped](https://user-images.githubusercontent.com/55949253/66665527-07dce780-ec4f-11e9-8447-049828e26a62.png)

**In the upper left corner is the timer, showing the remaining time until daily reset; next to it is the button that opens the side bar menu.**

![RDO Collectors Map Dark Map Mode Timer](https://user-images.githubusercontent.com/55949253/66665128-2e4e5300-ec4e-11e9-825c-6dfa8e0eab4c.png)

**Marker Pop-up menu when clicked/tapped**:

![Annotation 2019-10-12 172147](https://user-images.githubusercontent.com/55949253/66703653-260d1b00-ed15-11e9-97e3-5f5c6673cbaf.png)

- This is the pop-up menu that appears after clicking/tapping a map marker.
- On the top is the collectible name and next to it the current Day.
- Underneath will be a symbol describing what tool is needed if applicable, including:
⛏ for the shovel;
🧲 for the metal detector.

- Next to the symbol will be a short description of the precise location, if applicable.
- `Remove/add from map` lowers the opacity of the map marker and removes it from the dynamic route, helping you to keep track of already collected items. You can add them back anytime by clicking/tapping it again.

***

### Side Bar Menu:

> **Collectibles**:

> ![Annotation 2019-10-11 182857](https://user-images.githubusercontent.com/55949253/66668236-0ca49a00-ec55-11e9-83bb-d018f2650921.png)

- `Hide all` hides all symbols. 
- `Show all` shows all symbols. 
- Clicking/tapping on a set name will hide/show it from the map.
- Clicking/tapping the arrow next to set name will open/close the drop down menu.

> **Collectibles drop down menu**:

> ![RDO Collectors Map Side Bar Menu Collection Details](https://user-images.githubusercontent.com/55949253/66672903-b9841480-ec5f-11e9-9e8c-8856109788fe.png)

- The value of each set is stated at the top.
- Clicking/tapping on an item will hide/add it from the map and cross them out here.
- This has the same effect as using `Remove/add from map` directly on the map; lowering their opacity and excluding them from the dynamic route. Click/tap again to reactivate them.

> **Utilities, Search, Settings, Custom Routes & Issues**:

> ![RDO Collectors Map Side Bar Menu Utilities   Settings](https://user-images.githubusercontent.com/55949253/66666708-8cc90080-ec51-11e9-898d-1fcbf4c8c6c8.png)

> **Utilities**:

- `Madam Nazar` will hide/show her daily location on the map.
- `Fast Travel` will hide/show all fast travel points on the map.
- `Treasure Maps` will hide/show the search area of a treasure map (which is only seen in-game after activating the corresponding map, allowing you to plan your routes to include maps while collecting items).

> **Search**:

- `Search` allows you to search collectibles by name. Separate items by `;`. (Example: flint arrowhead;obsidian arrowhead;ivory hairpin etc.)

> **Settings**:

- `Day` will change the current collection day. It is set to the correct day automatically.
- `Tool type` allows you to only highlight map markers that require a specific tool to collect.
- `Language` allows you to change the language. 
- `Enable dynamic route` will enable the most efficient route between all chosen collectibles and/or collectible sets. It will change dynamically once you add/hide markers.
- `Show coordinates on click` will show the coordinates of your current click point on the bottom of the map. Great for reporting items or correcting their positions!
- `Reset markers daily` will automatically show all markers you hid before the daily reset. It also includes an option to show them manually, using `Reset`.

> **Custom Routes**:

- `Import route` enables you to import a shared route using the correct format.
- `Export route` enables you to export your currently created custom route in the correct format for others to copy into their own map.
- `Enable custom route` enables you to place a custom route line between collectible markers. Click the start of your route first, and then any marker you want to route to. This will create a line between those two points. To delete the line, click the last clicked marker again. You can also use `Clear` to delete all placed lines at once.

> **Issues**:

- `Report issues here!` will open a new tab to our GitHub project page where you can file a bug or issue report for us to look into!
- `Return to legacy version!` will return you to the very first version of this map, without any advanced functionality. 
- `Donate` allows you to perform a one-time or monthly donation, if you want to thank Jean Ropke for his work on the map. It is highly appreciated!

**Comment by elgydium** [comment]
You guys did sth to the map and not I can't pan it just zooms. Very very annoying.

**Comment by jeanropke** [comment]
Latest update on map was 2 days ago http://prntscr.com/psj8o9

Also, if you have a problem, create an issue.

**Comment by Fid13** [comment]
ive been using the map for a while , thanks for that, but just yesterday it was blocked by my laptop antivirus saying it had the phishing URL. i know this is not the case as it has been working fine, is there a way around this?

**Comment by MichalD96** [comment]
If you use AVG antivirus, problem is solved, if you use Avast, should be solved within a few days. For now you can exclude maps from scanning. It is false positive result. 
If you will have any problems/questions, ask it in #1140 issue

**Comment by Fid13** [comment]
Thanks..it's working fine now.
Computers are great but sometimes really annoying.
