### ISSUE TITLE
Incorrect item Cycle: day #3 - Just make note by flower "in between 4 trees"

### ISSUE THREAD

**Issue by chrissydewet** [jeanropke/RDR2CollectorsMap#199]
* What day cycle it is? day 3
* Coordinates or a clear image of the location blood flower location lemoyne
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by iligalodin** [comment]
Could you reformat, this issue makes no sense

**Comment by chrissydewet** [comment]
What i mean is the notes you put on the markers. Just put a note on the marker saying "The flower is between the 4 trees" . It took me a good 10 mins to find it. The note on the location pin will help others to find the right spot for the flower faster.

**Comment by iligalodin** [comment]
will do
