### ISSUE TITLE
Garbage collection for markers that have been removed from map

### ISSUE THREAD

**Issue by rbcunhadesign** [jeanropke/RDR2CollectorsMap#20]
Markers that have been removed from the map by users need to be reset at some point. Right now if you mark an item as "complete" from the map, it stays like that forever.

**Proposed functionality**
Markers get reset every day
OR
Markers get reset once every 2 days(Tuesday and Thursday have the same cycle)

<hr>

There should also be a way to unmark an item as "complete".

**Comment by jeanropke** [comment]
Markers reset every day and added option to re-enable markers.
