### ISSUE TITLE
Additional wisteria locations

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#201]
Additional Wisteria that I’ve found @ or near these locations. They need verification of their location and cycle.
Cycle 1
La 61.1 Lo 85.2
La -36.7 Lo 149.0
La -35.5 Lo 152
La -31.6 Lo 154.1
Cycle 2
La -84.8 Lo 72.4
La -49.1 Lo 146.5
La - 29.9 Lo 153.5
Cycle 3 
La -39.3 Lo 149.1

**Comment by iligalodin** [comment]
Could you use the form from now on?

**Comment by iligalodin** [comment]
could you use the form? [https://forms.gle/xqKHMTWvqBt2v5eK7](https://forms.gle/xqKHMTWvqBt2v5eK7) it makes it easier for us to verify the locations if they are random or an actual missing item
