### ISSUE TITLE
Additional Blood Flower Location

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#202]
Additional Blood Flower that I’ve found @ or near this location. It needs verification of location and cycle.
Cycle 3 
La -74.1 Lo 137.8
Can’t remember if it’s on the south or north bank of the Kamassa river.

**Comment by iligalodin** [comment]
could you use the form? [https://forms.gle/xqKHMTWvqBt2v5eK7](https://forms.gle/xqKHMTWvqBt2v5eK7) it makes it easier for us to verify the locations if they are random or an actual missing item

**Comment by jeanropke** [comment]
Flower added.
