### ISSUE TITLE
Personal Map To Customize

### ISSUE THREAD

**Issue by MilkedRips** [jeanropke/RDR2CollectorsMap#205]
I think it would be a good touch for people to customize their own personal maps with new markers and their own custom tidbits. Otherwise would you be able to explain how you were able to make this map so I can make my own? Would appreciate either or! :)

**Comment by iligalodin** [comment]
What do you have in mind?

**Comment by MilkedRips** [comment]
Treasure hunter locations, just to add and remove personal pins, the ability to customize the color scheme of the markers or to be able to color coordinate by category instead of by cycle (i.e. American Fowers = green, coins = blue, etc.). Just a few ideas that come to mind. This map is amazing by the way, fantastic job on it so far, the treasure map search areas was a great addition.

**Comment by CaliMeatWagon** [comment]
I would like this feature as well. It would be great to add favorite areas for hunting, gang hideouts, bounty hunter boards, prison wagons.

What would be even better is if I could upload my own map and use this wonderful tool for a wide variety of games.

**Comment by MilkedRips** [comment]
Or an idea: make it so you can pick and choose which markers you want to show up instead of adding your own (for example: you can have a coin, bottle, 3 heirlooms, and an egg that you’re specifically looking for and those are the only items that show up) it would also help with the route feature

**Comment by Rakmarok** [comment]
> Or an idea: make it so you can pick and choose which markers you want to show up instead of adding your own (for example: you can have a coin, bottle, 3 heirlooms, and an egg that you’re specifically looking for and those are the only items that show up) it would also help with the route feature

It already works like this. Take a look at the wiki.

**Comment by Senexis** [comment]
You can now also import and export custom markers. See the bottom of the menu for the newly added options.
