### ISSUE TITLE
Marker For Treasure Hunter Locations

### ISSUE THREAD

**Issue by MilkedRips** [jeanropke/RDR2CollectorsMap#207]
Spot for treasure hunter locations

**Comment by IronJeff80** [comment]
Treasure Hunter Locations: always found on cliff edges near treasure map search areas.
Treasure Hunter, The Heartlands: On the cliff's edge around dusk Monday :
lat: -66.37510692265303
lng: 114.578125
https://youtu.be/9bhPMTCq_uk
Treasure Hunter, Cumberland Falls: on cliff edge near Cumberland Falls around afternoon Wednesday.
lat: -57.20290953465374
lng: 93.96875
https://youtu.be/B6-dUHzeq50
Treasure Hunter, Little Creek: On a cliff by little creek river near Wallace station
lat: -59.17067722335054 
lng: 89.9765625

Treasure Hunter, Riggs Station: on a cliff looking toward Riggs Station
lat: -69.921875 
lng: 94.5078125

Treasure Hunter, Dakota River: on a cliff looking toward Dakota river
lat: -61.28125 
lng: 91.2734375

Treasure Hunter, Monto’s Nest: on a cliff looking toward Monto’s Nest 8pm in game time
lat: -65.2734375 
lng: 85.734375

Treasure Map Locations, found at night, stuck to trees. Look for lantern light

Treasure Map, Del Lobo Rock:
lat: -119.39959906882154
lng: 53.5078125

Treasure Map, Cumberland Forrest: 
lat: -47.6171875 
lng: 112.2109375

Treasure Map, The Heartlands
lat: -63.328125 
lng: 128.328125


Treasure Map, Hanging Rock
lat: -98.6328125 
lng: 57.71875

Treasure Map: Dewberry Creek
lat: -63.1796875 
lng: 128.1640625

Grave Digger Treasure Map Hunts:

Grave Digger, Saint Denis
lat: -80.265625 
lng: 154.0546875

Grave Digger, Strawberry
lat: -67.21875 
lng: 83.9765625

Grave Digger, Valentine
lat: -50.8984375 
lng: 107.8046875
