### ISSUE TITLE
No straight routes

### ISSUE THREAD

**Issue by MateSpianSVK** [jeanropke/RDR2CollectorsMap#21]
Hello,
thank you for your interactive map, it is very helpfull, but is possible to make straight lines? Because when I choose for example only coins, there are not straight line routes.. 
Thank you..

![obrázok](https://user-images.githubusercontent.com/55940675/65828239-f5e76600-e298-11e9-8f76-99e27001cd34.png)

**Comment by jeanropke** [comment]
Its complex to generate routes. I tried with salesman algorithm and not worked well.

**Comment by iligalodin** [comment]
#8
