### ISSUE TITLE
Rename Settings "Day" (1-2-3)  in "Collection map" (1-2-3) to be in line with the Wiki page?

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#216]
The wiki is now very clear. Great.

Maybe a good reason to change the settings text "Day" to "Collection map" accordingly?

**Comment by Rakmarok** [comment]
Will do. Thanks for the heads up.

**Comment by Shaftoe62** [comment]
Also, the link to the wiki is now a very understated question mark. Easy to miss.
I knew it had to be somewhere because of the references to it in several "issues". 
But it took until today for the penny to drop. :-)

**Comment by Rakmarok** [comment]
- Changed `Day` to `Collection maps` to bring the map in line with the wiki

Please create a separate suggestion for your ideas about the help button.

**Comment by Rakmarok** [comment]
- Changed in the German and English versions of the map.

**Comment by Shaftoe62** [comment]
@Rakmarok Someone changed it back to "Day" in English:

![image](https://user-images.githubusercontent.com/53898212/66827704-88516000-ef4f-11e9-9315-10f2d60a9407.png)

**Comment by Rakmarok** [comment]
Fixed.

Thanks for the heads up.
