### ISSUE TITLE
Favicon is treasure map icon?

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#217]
I noticed the favicon (icon of the browser tab) of the collectors map is the icon used for the treasure maps. Is this intentionally?

**Comment by iligalodin** [comment]
Yup

**Comment by Shaftoe62** [comment]
I also recognize it as my design from
[https://www.reddeadonlineclock.com/resources/RedDeadOnlineTreasureMaps.pdf](https://www.reddeadonlineclock.com/resources/RedDeadOnlineTreasureMaps.pdf)
I'm honoured...

:-)
