### ISSUE TITLE
Alternative treasure map display format

### ISSUE THREAD

**Issue by powderkegger** [jeanropke/RDR2CollectorsMap#218]
If the treasure map selection was "individually clickable" like the collectible items are, then they could match the maps in the players satchel.

If addable to the route, sparser collection routes could benefit.

If the "yellow circle graphic" for the map included the four locations to search, or a link to an image of the four locations, it would be beneficial.

**Comment by Shaftoe62** [comment]
Priority here (imho) should be the individually selecteability of each map. That really adds to the effectiveness of your collecting route.

Finding the actual treasure spot within the area is guided by your controller, so not very difficult. 

I simply circle the area and than work inward to the center.

This actually is much faster than checking multiple individual spots.

**Comment by jeanropke** [comment]
Treasures can be enabled/disabled individually.
All treasures are disabled by default.

**Comment by Shaftoe62** [comment]
Fantastic!
