### ISSUE TITLE
RDO Sammler Landkarte Benutzerhandbuch (Deutsch)

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#223]
### _Willkommen zur inoffiziellen Sammler Landkarte und zum offiziellen Benutzerhandbuch!_

_Verfasst und übersetzt von Rakmarok._

Dieses Benutzerhandbuch wird euch dabei helfen zu verstehen _wann_ ihr _was_ und _wo_ findet könnt, sowohl über welche Funktionen die Karte verfügt.

***

### Farben der Kartenmarkierungen:

**Farben der Kartenmarkierungen**:
- Blaue Kartenmarkierungen: Landkarte 1.
- Orange Kartenmarkierungen: Landkarte 2.
- Lila Kartenmarkierungen: Landkarte 3.
- Grüne Kartenmarkierungen (max. 3 Gegenstände): Madam Nazar's wöchentliche Sammlung.

***

### Die Sammler Landkarte, der tägliche Landkarten-Wechsel & Madam Nazar's täglicher Standort:

**Die Sammler Landkarte**:
- Die Sammler Landkarte funktionieren aufgrund dieser Logik:
1. Montag (Landkarte 3)
2. Dienstag (Landkarte 1)
3. Mittwoch (Landkarte 2)
4. Donnerstag (Landkarte 1)
5. Freitag (Landkarte 3)
6. Samstag (Landkarte 1)
7. Sonntag (Landkarte 2)
- Bitte beachtet: Die `Red Dead Redemption II Sammler Karte` wird immer automatisch die richtige Landkarte wählen.

**Landkarten-Wechsel**:
Die Landkarte ändert sich jeden Tag um 00:00 UTC/GMT also:
- um 02:00 Sommerzeit (UTC+2)
- um 01:00 Winterzeit (UTC+1)
- Bitte beachtet: Sammelstücke im Spiel ändern ihren Standort _sofort_ zu diesem Zeitpunkt zur nächsten Landkarte. Den aktuellen Server zu wechseln ist nicht nötig.

**Madam Nazars Standort**:
- Madam Nazars Standort ändert sich jeden Tag um 06:00 UTC/GMT (zur selben Zeit wie tägliche Herausforderungen), also:
- um 08:00 Sommerzeit (UTC+2)
- um 07:00 Winterzeit (UTC+1)

***

### Grundfunktionen der Karte:

**In der rechten oberen Ecke findet ihr die Karten-Anzeige-Optionen, mit den folgenden Einstellungen:** 

![RDO Collectors Map Dark Map Mode Map Mode Select](https://user-images.githubusercontent.com/55949253/66665106-21316400-ec4e-11e9-9b1d-f4e0b21c71b9.png)
![Annotation 2019-10-12 032805](https://user-images.githubusercontent.com/55949253/66692655-caa14580-eca0-11e9-9f44-a0c7df828cfa.png)

> Standard (Default): Karte mit Details wie Straßen, Pfaden und Zugstrecken in geringerer Sichtbarkeit.

> ![Annotation 2019-10-11 174643 Cropped](https://user-images.githubusercontent.com/55949253/66665636-3b1f7680-ec4f-11e9-8ccd-cacedc977e44.png)

> Detailliert (Detailed): Karte mit Details wie Straßen, Pfaden und Zugstrecken in standard Sichtbarkeit. Identisch mit der Karte im Spiel. Dies ist standardmäßig ausgewählt. 

> ![Annotation 2019-10-11 174337 Cropped](https://user-images.githubusercontent.com/55949253/66665509-ff84ac80-ec4e-11e9-9f45-8d62c84bd495.png)

> Dunkel (Dark): Karte mit Details wie Straßen, Pfaden und Zugstrecken in weiß abgebildet, während der Kartenhintergrund dunkelgrau dargestellt wird. Gut für die nächtliche Schatzsuche geeignet.

> ![Annotation 2019-10-11 174350 Cropped](https://user-images.githubusercontent.com/55949253/66665527-07dce780-ec4f-11e9-8447-049828e26a62.png)

**In der oberen oberen Ecke findet ihr den Timer, der die restliche Zeit bis zum täglichen Landkarten-Wechsel anzeigt. Daneben befindet sich die Schaltfläche für das Seitenleistenmenü.**

![RDO Collectors Map Dark Map Mode Timer](https://user-images.githubusercontent.com/55949253/66665128-2e4e5300-ec4e-11e9-825c-6dfa8e0eab4c.png)

**Popup-Menü der Kartenmarkierungen**:

![Annotation 2019-10-14 215034](https://user-images.githubusercontent.com/55949253/66779155-cb6aef00-eecd-11e9-870d-9744086baf05.png)

- Dies ist das Popup-Menü das erscheint, sobald ihr eine der Kartenmarkierungen anklickt oder tippt.
- Oben ist der Name des Sammelstücks und rechts daneben die aktuelle Landkarte.
- Darunter findet ihr welches Werkzeug nötig ist (falls anwendbar):
⛏ für die Schaufel;
🧲 für den Metall Detektor.

- Daneben findet ihr eine kurze Beschreibung des genauen Fundortes (falls anwendbar).
- `Von Karte entfernen/hinzufügen` verringert die Sichtbarkeit der Markierung und entfernt diese von der dynamischen Route, was euch den Überblick über bereits gesammelte Sammelstücke erleichtert. Ihr könnt die Markierung jederzeit wieder hinzufügen indem ihr noch einmal klickt oder tippt.

***

### Seitenleistenmenü:

> **Sammlungen**:

> ![Annotation 2019-10-14 215130](https://user-images.githubusercontent.com/55949253/66779222-eccbdb00-eecd-11e9-92f5-8f26f9d70286.png)

- `Alle verbergen` versteckt alle Kartenmarkierungen der nachfolgenden Sammlungen. 
- `Alle anzeigen` zeigt alle Kartenmarkierungen der nachfolgenden Sammlungen an. 
- Sammlungen werden durch einen klick/tipp auf deren Namen versteckt/angezeigt.
- Das Untermenü der Sammlungen öffnet/schließt sich durch einen klick/tipp auf den Pfeil rechts.

> **Sammlungen Untermenü**:

> ![Annotation 2019-10-14 215423](https://user-images.githubusercontent.com/55949253/66779281-ffdeab00-eecd-11e9-944f-f277d1dda6d8.png)

- Der Wert jeder Sammlung wird oben unter dem Namen angezeigt.
- Durch klicken/tippen auf ein Sammelstück wird der Name durchgestrichen.
- Dies hat den selben Effekt wie `Von Karte entfernen/anzeigen`; es verringert ihre Sichtbarkeit und schließt sie von der dynamischen Route aus. Klicken/tippen um es wieder zu aktivieren.

> **Werkzeuge, Suche, Einstellungen, Benutzerdefinierte Route & Fehlermeldungen**:

> ![Annotation 2019-10-14 215543](https://user-images.githubusercontent.com/55949253/66779302-0c630380-eece-11e9-85fa-cfc38bc32acb.png)

> **Werkzeuge**:

- `Madam Nazar` versteckt/zeigt ihren täglichen Standort auf der Karte.
- `Schnellreise` versteckt/zeigt alle Schnellreiseorte auf der Karte.
- `Schatzkarten` versteckt/zeigt das Suchgebiet einer aktivierten Schatzkarte (dazu müsst ihr im Spiel die gleichnamige Karte aktivieren. Dies hilft euch, eure Route effizient zu planen).

> **Suche**:

- `Suche` erlaubt es euch Sammelstücke nach ihrem Namen zu suchen. Unterteilt sie durch `;`. (Beispiel: feldspat-pfeilspitze;obsidian-pfeilspitze;elfenbein-haarnadel etc.)

> **Einstellungen**:

- `Landkarte` ändert die auf der Karte angezeigte Sammler Landkarte. Diese Option ist automatisch auf die zutreffende Karte eingestellt.
- `Werkzeug-Typ` erlaubt es euch ausschließlich Kartenmarkierungen anzeigen zu lassen, die ein spezifisches Werkzeug benötigen.
- `Sprache` ändert die von der Karte benutzte Sprache. 
- `Dynamische Route aktivieren` aktiviert die Dynamische Route. Sie zeigt euch den effizientesten Weg um alle nicht deaktivierten Sammelstücke zu finden. Durch das aktivieren/deaktivieren von Kartenmarkierungen ändert sie sich dynamisch.
- `Koordinaten bei Klick anzeigen` zeigt euch die Koordinaten des letzten Punktes an, auf den ihr geklickt habt. Gut geeignet um falsch platzierte oder unbekannte Gegenstände zu melden!
- `Markierungen täglich zurücksetzen` zeigt automatisch alle Kartenmarkierungen wieder an die ihr vor dem täglichen Landkarten-Wechsel versteckt habt. Es beinhaltet auch eine Option diese manuell wieder anzuzeigen, nutzt dazu `Zurücksetzen`.

> **Benutzerdefinierte Route**:

- `Route importieren` erlaubt es euch eine fremd erstellte Route in die Karte zu importieren, sofern sie im richtigen Format gespeichert wurde.
- `Route exportieren` erlaubt es euch eure gegenwärtige Benutzerdefinierte Route im richtigen Format zu exportieren.
- `Benutzerdefinierte Route aktivieren` erlaubt es euch eine Navigations-Linie zwischen zwei Kartenmarkierungen zu platzieren. Klickt auf eine Markierung um sie als Startpunkt auszuwählen; klickt dann auf den zweiten Punkt. Dadurch entsteht zwischen beiden Punkten eine Linie. Diese kann durch weitere Klicke auf andere Markierungen verlängert werden. Um die Linie wieder zu löschen, klickt nochmals auf die letzte geklickte Markierung. `Löschen` entfernt alle platzierten Linien auf einmal. 

> **Fehlermeldungen**:

- `Fehler hier melden! (Englisch)` öffnet einen neuen Tab zu unserer Projektseite auf GitHub, was euch erlaubt Fehler und Vorschläge direkt an das Team zu schicken! (Englisch ist bevorzugt, stellt aber auch ruhig deutsch-sprachige Tickets.)
- `Zur Originalversion zurückkehren!` bringt euch zur allerersten Version der Karte zurück, ohne jeglichen erweiterten Funktionen. 
- `Donate` erlaubt es euch eine einmalige oder monatliche Spende an den Ersteller der Karte, Jean Ropke, zu senden. Er ist sehr dankbar!

**Comment by githb123** [comment]
Is this a translation of an existing user guide or is it just your free proposal? i mean is it "the one" to translate to other languages?

**Comment by Rakmarok** [comment]
It is my German translation of the existing English user guide you can find when clicking "Wiki" at the top of the page. 

The English wiki is the template for all other languages.
