### ISSUE TITLE
Physical treasure maps locations

### ISSUE THREAD

**Issue by ArthurMorganRDR** [jeanropke/RDR2CollectorsMap#225]
Hello ! I would like to thank you first for your idea and the work you put in this map. It is an amazing tool !

I noticed that recently you've published some treasure maps locations. At first, I was not sure if it was the prize from the map or if it was the map itself. Now I know and I was thinking that it would be great if we could start contributing on finding the physical maps and add them as pins on the RDR2 map. Because I remember that one day I randomly found a lost treasure map on a tree. Maybe it is always there. Of course, the ones from the gangs might not be consistent, but we could try to find a rule for them.

What do you guys think ? Thanks

**Comment by Rakmarok** [comment]
If you're able to consistently find treasure maps at the same spots that would help a lot.

**Comment by Senexis** [comment]
Not sure if it works like that. Yesterday I found 2 treasure maps in the same area at East Watsons but they were in different spots. It was a large search area though, so maybe for small search areas it'll work?

**Comment by IronJeff80** [comment]
Treasure Hunter Locations, always found on cliff edges near treasure map search areas.

Treasure Hunter, The Heartlands: On the cliff's edge around dusk Monday :
lat: -66.37510692265303
lng: 114.578125
https://youtu.be/9bhPMTCq_uk

Treasure Hunter, Cumberland Falls: on cliff edge near Cumberland Falls around afternoon Wednesday.
lat: -57.20290953465374
lng: 93.96875
https://youtu.be/B6-dUHzeq50

Treasure Hunter, Little Creek: On a cliff by little creek river near Wallace station
lat: -59.17067722335054 
lng: 89.9765625

Treasure Hunter, Dakota River: on a cliff looking toward Dakota river
lat: -69.921875 
lng: 94.5078125

Treasure Map Locations, found at night, stuck to trees. Look for lantern light

Treasure Map, Del Lobo Rock:
lat: -119.39959906882154
lng: 53.5078125

Treasure Map, Cumberland Forrest: 
lat: -49.21028948392104
lng: 110.5859375

Treasure Map, The Heartlands
lat: -63.328125 
lng: 128.328125

Treasure Map, Hanging Rock
lat: -98.6328125 
lng: 57.71875

I also found a grave robber in the valentine cemetery and he had me help dig up graves and I found a Treasure Map. As I approached to cemetery to collect a glowing collectable near a tombstone, the Guy appeared from the back of the Church. I think you need to enter the cemetery at night to trigger.
