### ISSUE TITLE
Add more locations of collectibles

### ISSUE THREAD

**Issue by Arthurm16a2** [jeanropke/RDR2CollectorsMap#227]
**Is your feature request related to a problem? Please describe.**
it's not an issue it more like i've already found more locations of one item and it's not marked may be i can contrib by send you the locations or how? also many people dont know where is a plant like ginseng or alaskan ginseng i have a few locations so the map could be more complete.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rakmarok** [comment]
Can you please re-write this suggestion? It is very unclear.

**Comment by jeanropke** [comment]
Added random items spots
