### ISSUE TITLE
[Suggestion]Prefix for all the items

### ISSUE THREAD

**Issue by flameango** [jeanropke/RDR2CollectorsMap#23]
The problem is, that a lot of players don't play the game on english language (like myself). If you look for a specific item, you need to know the english name for it. Some items kinda have the same name, but some don't. That's why I suggest a prefix for each item, that acts like an id.

Currently, there are 14 collections with changing amounts of items. The good thing is, each of these collections and items are in the same order, no matter what language your console is set.

Let me show you an example:
First collection would be American Wild Flowers with Texas Bluebonnet being the first item. So rather than just naming the item:

- "Texas Bluebonnet Flower - Day 2",

a prefix like:

- "**#0101** Texas Bluebonnet Flower - Day 2"

would help to find the item you're looking for across all languages.

**Comment by iligalodin** [comment]
good suggestion, will send a pull request soon

**Comment by iligalodin** [comment]
could/would you be able to give the translated names of the items?

**Comment by flameango** [comment]
You mean with the ID?

**Comment by githb123** [comment]
I'd consider internalization in the code/names itself instead of numbering the item.

I could provide some polish translations... I'd just need the screenshots of the english lists. Don't want to mess up the languages on my console.

**Comment by iligalodin** [comment]
@githb123 look in the main directory for the items.json to see all the english names

**Comment by jeanropke** [comment]
Started multiple language support https://gyazo.com/11c0ae780bc1368c84a5bb20f7f79632

**Comment by iligalodin** [comment]
> Started multiple language support https://gyazo.com/11c0ae780bc1368c84a5bb20f7f79632

how did you implement it? via a sepperate json or still in the items.json?

**Comment by jeanropke** [comment]
Separated. I added a new key called 'text' on items.json.
`{"text": "cups_ace", "day": "1", "tool": "0", "icon": "card-cups","name": "Ace of Cups","desc":"","x": "-26.421875","y": "90.65625"},`

And this is the lang file
`{"key": "cups_ace.name", "value": "Ace of cups"},
{"key": "cups_ace_1.desc", "value": "desc day 1"},
{"key": "cups_ace_2.desc", "value": "desc day 2"},
{"key": "cups_ace_3.desc", "value": "desc day 3"}`

**Comment by iligalodin** [comment]
okay cool that's easy enough to port the 40+ descriptions i wrote today xD

**Comment by githb123** [comment]
@jeanropke 
Why separate descriptions for each day?? Any specific reason?

Also I haven't really worked with git. Do I need to create a special branch or can I just clone the master and request a merge into that? I'm sorry for any incovenience in upfront. :)

**Comment by iligalodin** [comment]
the reason why there is a separate description for each day is because the items are located in a different place, as example. the six of cups 
day 1: inside on the eastern windowsil.
day 2: inside the bedroom on the nightstand behind the door.

**Comment by flameango** [comment]
Language support would be nice. Would be happy to help with translation.

**Comment by githb123** [comment]
> the reason why there is a separate description for each day is because the items are located in a different place, as example. the six of cups
> day 1: inside on the eastern windowsil.
> day 2: inside the bedroom on the nightstand behind the door.

Yeah I thought about that after submitig the comment. Good point.

**Comment by githb123** [comment]
All we need now is all the keys for the items. And how do I name the lang file?

**Comment by iligalodin** [comment]
@githb123 i believe @jeanropke is currently enrolling the localisation update. hold just a second and i'm sure it will be there in no time

**Comment by jeanropke** [comment]
Added english language  https://github.com/jeanropke/RDR2CollectorsMap/blob/master/langs/en-us.json

**Comment by iligalodin** [comment]
may i reformat it so the descriptions are below the item key / name

**Comment by jeanropke** [comment]
You can reformat, any conflits.

**Comment by iligalodin** [comment]
just so we're clear, it can be like this in the json right? 
```
	{"key": "cups_ace.name", "value": "Ace of Cups"},
	{"key": "cups_ace_1.desc", "value": ""},
	{"key": "cups_ace_2.desc", "value": ""},
	{"key": "cups_ace_3.desc", "value": ""},

	{"key": "cups_two.name", "value": "Two of Cups"},
	{"key": "cups_two_1.desc", "value": ""},
	{"key": "cups_two_2.desc", "value": ""},
	{"key": "cups_two_3.desc", "value": ""},
```

**Comment by jeanropke** [comment]
Yes.
And search by 'hajnal garnet bangle', replace the spaces by '_'

**Comment by iligalodin** [comment]
i'll be updating the en_us.json in a short moment

**Comment by iligalodin** [comment]
uh oh... what about duplicate items? like the flowers and such? i just noticed there were only eggs #1 and not #2

**Comment by jeanropke** [comment]
For now remove #1 and #2

**Comment by iligalodin** [comment]
i would suggest doing something like this

```
	{"key": "flower_blood_flower.name", "value": "Blood Flower #1"},
	{"key": "flower_blood_flower_1.desc", "value": ""},
	{"key": "flower_blood_flower_2.desc", "value": ""},
	{"key": "flower_blood_flower_3.desc", "value": ""},

	{"key": "flower_blood_flower_2.name", "value": "Blood Flower #2"},
	{"key": "flower_blood_flower_2_1.desc", "value": ""},
	{"key": "flower_blood_flower_2_2.desc", "value": ""},
	{"key": "flower_blood_flower_2_3.desc", "value": ""},
```

**Comment by jeanropke** [comment]
Okay. And I think is better use 'flower_blood_flower_1.name' intead of 'flower_blood_flower.name', for descriptions too

**Comment by iligalodin** [comment]
could also jsut have something like this
```
	{"key": "flower_blood_flower.name", "value": "Blood Flower "},
	{"key": "flower_blood_flower_1.desc", "value": ""},
	{"key": "flower_blood_flower_2.desc", "value": ""},
	{"key": "flower_blood_flower_3.desc", "value": ""},
	{"key": "flower_blood_flower_2_1.desc", "value": ""},
	{"key": "flower_blood_flower_2_2.desc", "value": ""},
	{"key": "flower_blood_flower_2_3.desc", "value": ""},
```

**Comment by jeanropke** [comment]
Not work, 'lang.key' needs match 'item.text' + '.name' or '.desc'
Eg:
Items.json:
 `{"text": "flower_blood_flower", ...}`

en-us.json:
`{"key": "flower_blood_flower.name", ...}`

**Comment by iligalodin** [comment]
okay good to know lets do the flower_blood_1 etc...

**Comment by iligalodin** [comment]
for anyone who wants to help with the localisation, i've created empty localisation files for each language in the game.
[https://github.com/jeanropke/RDR2CollectorsMap/blob/master/langs/](https://github.com/jeanropke/RDR2CollectorsMap/blob/master/langs/)

**Comment by githb123** [comment]
@iligalodin 
I have the polish translation now. How do I commit? I seem not to be able to create a branch and as far as i understood I need one for a pull request. Or can I just edit the file here in GUI and commit it? Sorry but haven't took part in any github cooperation until now.

You can do it for me if I shall have no rights but then you would be bothered each time there is a change in the file... :( And also I'd like learn how to use this git. :)

I've just taken the en-us file and edited the translations there.

The file is also here as attachment if you need to commit. As a GZ archive as .json didn't work.

[rdo_collector_pl.json.gz](https://github.com/jeanropke/RDR2CollectorsMap/files/3670969/rdo_collector_pl.json.gz)

**Comment by githb123** [comment]
BTW how about translating also the whole menu and presenting it according to the browser language preferences? Also the items could be in a language of the browser.

However the possibility to set the language manually should still be there.

**Comment by iligalodin** [comment]
> @iligalodin
> I have the polish translation now. How do I commit? I seem not to be able to create a branch and as far as i understood I need one for a pull request. Or can I just edit the file here in GUI and commit it? Sorry but haven't took part in any github cooperation until now.
> 
> You can do it for me if I shall have no rights but then you would be bothered each time there is a change in the file... :( And also I'd like learn how to use this git. :)
> 
> I've just taken the en-us file and edited the translations there.
> 
> The file is also here as attachment if you need to commit. As a GZ archive as .json didn't work.
> 
> [rdo_collector_pl.json.gz](https://github.com/jeanropke/RDR2CollectorsMap/files/3670969/rdo_collector_pl.json.gz)

so what you do is you edit the file in the gui and when done press suggest file change, after that click on create pull request!

**Comment by iligalodin** [comment]
> BTW how about translating also the whole menu and presenting it according to the browser language preferences? Also the items could be in a language of the browser.
> 
> However the possibility to set the language manually should still be there.

there is only a certain amount of languagesavailable in game. i feel we should stick to those languages, however the menu thing is a nice suggestion.

could you create a new issue about translating the menu?

**Comment by githb123** [comment]
done. Yeah I just wasn't sure if I may edit the file just like that. Didn't want to break anything. ;)

BTW When does the merge go live? Tried to reload the page but didn't get my translation. Some automation once an hour?

**Comment by jeanropke** [comment]
Added now.

**Comment by githb123** [comment]
Cool thanks. Just wanted to make sure about the polish font enconding. Looks good.
