### ISSUE TITLE
Make the map clickable to add a missing item location

### ISSUE THREAD

**Issue by jerodwaldman** [jeanropke/RDR2CollectorsMap#231]
**Is your feature request related to a problem? Please describe.**
I'm finding numerous items not on the map, but the process of screenshots and going through the form is tedious. 

**Describe the solution you'd like**
I'd like to be able to zoom in on the map, click the spot where I found the item and provide the basics (cycle day, item, tool utilized).

**Describe alternatives you've considered**
I've tried using the form, and it's not that the form is bad, it's just a hassle to toggle off to a different tab or browser window when i'm on my tablet or laptop.

**Additional context**
No additional context required.

**Comment by IronJeff80** [comment]
Is there anyway to make a map where we can right click to submit item location.
Maybe just a new map with that feature, so everyone can easily submit data.
