### ISSUE TITLE
Rou Pearl Necklace Cycle: day 2

### ISSUE THREAD

**Issue by Vitor-Borba72** [jeanropke/RDR2CollectorsMap#232]
* What day cycle it is? Day 2
* Coordinates or a clear image of the location: lat: -109.125 lng: 84.109375
* Include the item name: **Rou Pearl Necklace**

In this place where it's supposed to be the Rou Pearl Necklace, instead I found a coin. I don't know which coin it was, sorry.

**Comment by jeanropke** [comment]
I found the Rou Pearl Necklace.

**Comment by Vitor-Borba72** [comment]
Oh this is weird. Sorry.
