### ISSUE TITLE
Highlight Important Items

### ISSUE THREAD

**Issue by GameMatchSet** [jeanropke/RDR2CollectorsMap#235]
**Is your feature request related to a problem? Please describe.**
As follow the maps and my inventory fills I've noticed that it's usually a select one or two items I'm missing. So those become the ones I need to get yet with the map open I often like to work my towards those things collecting things on my path.

**Describe the solution you'd like**
There should be an option to favorite/highlight specific items and it would change their color or icon border to make them easily distinguishable.

**Describe alternatives you've considered**
I've tried using the custom routes to do this easier and even keep a pen and paper list but it seems like a highlight ability would increase ease of use, especially for experienced collectors.

**Comment by iligalodin** [comment]
I like this ill take a look

**Comment by q1k** [comment]
I'd really appreciate this being added.
In the meantime I'll create my own userstyle in stylus ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/), [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)) to mark the items I have less of

```
/*different color each cycle for better visibility*/
img.leaflet-marker-icon[src*="_blue.png"][data-marker*="flower_blood"] {
    filter: drop-shadow(0px 0px 6px red); /*cycle one - red*/
}
img.leaflet-marker-icon[src*="_orange.png"][data-marker*="flower_blood"] {
    filter: drop-shadow(0px 0px 6px #00ffff); /*cycle two - cyan*/
}
img.leaflet-marker-icon[src*="_purple.png"][data-marker*="flower_blood"] {
    filter: drop-shadow(0px 0px 6px #00ff00); /*cycle three - lime*/
}
```

**Comment by q1k** [comment]
I'd really appreciate this being added.
In the meantime I'll create my own userstyle in stylus ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/), [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)) to mark the items I have less of

```
/*different color each cycle for better visibility*/
img.leaflet-marker-icon[src*="_blue.png"][data-marker*="flower_blood"] {
    filter: drop-shadow(0px 0px 6px #ff0000); /*cycle one - red*/
}
img.leaflet-marker-icon[src*="_orange.png"][data-marker*="flower_blood"] {
    filter: drop-shadow(0px 0px 6px #00ffff); /*cycle two - cyan*/
}
img.leaflet-marker-icon[src*="_purple.png"][data-marker*="flower_blood"] {
    filter: drop-shadow(0px 0px 6px #00ff00); /*cycle three - lime*/
}
```
