### ISSUE TITLE
Tracking 

### ISSUE THREAD

**Issue by doubleohdan** [jeanropke/RDR2CollectorsMap#238]
It would be nive if you could log in to this map and actually track the ones you've found so this mao just shows the ones you need, i see you can 
Add/remove the collectables but if you dont do it all in one go it resets showing them all again which is kind of a pain

**Comment by IronJeff80** [comment]
set "Rest Markers Daily" to No.

**Comment by doubleohdan** [comment]
Hey thanks i seen that but then i do it, and if i close my browser on my cell or tablet and seem to open my favorites the next day everythings back


-------- Original message --------
