### ISSUE TITLE
Ursula Citrine Earrings Day 2 (Sunday 29th September)

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#24]
I found this item between Annesburg and O'Creighs Run.

![earrings_ursula_lemon](https://user-images.githubusercontent.com/55925524/65829670-07843a00-e2a8-11e9-823f-eb68cc5eb478.png)

**Comment by iligalodin** [comment]
what tools do you need?

**Comment by iligalodin** [comment]
strange, i just checked the location and i got a sackville diamond earring @jeanropke should we still log these locations?

**Comment by githb123** [comment]
Shovel is needed.

Well I would still log these locations because some item will be there. And otherwise it won't be complete.

**Comment by iligalodin** [comment]
random item location
