### ISSUE TITLE
Statistics of visits per country and the browser language

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#240]
Hi,

Any chance for adding this? So we know our work is needed at all ;) I mean I won't be translating the user guide if there are 3 visits with the polish language per week/month ;)

It may also be protected by some authentication if you'd prefer that.

Just a low prio thought.

I think the statistics should be distinct by the visitor's IP/address and per day and week and month. I mean If someone is refreshing the page every couple of minutes then it counts as 1 visitor. Or the same IP every day counts as 1 visitor per month but then X hits per month. i hope it's kind of clear ;)

**Comment by jeanropke** [comment]
I can't add this features because GitHub only works with static pages (client-side). 
Last week access from Poland http://prntscr.com/pliwlr
