### ISSUE TITLE
Incorrect item Cycle: day 1

### ISSUE THREAD

**Issue by ArthurMorganRDR** [jeanropke/RDR2CollectorsMap#241]
Hi,

I went to the Window Rock today to pick up the **Ten of Swords** card, but it wasn't there. If I get the metal detector, I feel some distant vibes, not sure if there's something else here or not, but will check.

The coordinates of the card that was supposed to be there are: 

lat: -40.5390625
lng: 108.9140625

The cycle day is: Day 1

I'll get back to you if I find the item that's causing the metal detector to vibrate.

**Comment by ArthurMorganRDR** [comment]
UPDATE: I found the metal detector item that was nearby, but not present on the map: 

lat: -40.078125
lng: 109.9609375

Agate Arrowhead. But the card is still not there.

**Comment by ArthurMorganRDR** [comment]
![Red Dead Redemption II Collector Map (2)](https://user-images.githubusercontent.com/56277710/67147784-caa4d500-f2a0-11e9-9358-bc31df48717c.png)

**Comment by ArthurMorganRDR** [comment]
I am not sure about the card, maybe it's a game problem cause after I went to the egg, and I didn't find it either, so I will restart my game just in case.

**Comment by jeanropke** [comment]
This card was there for me.
![EHQOEUCXYAAGezv (1)](https://user-images.githubusercontent.com/6243818/67148068-674f7e80-f271-11e9-8ad3-99f652edc80e.jpg)

However, last week this card did not spawned to me in Van Horn.
![missing card](https://user-images.githubusercontent.com/6243818/67148087-a5e53900-f271-11e9-9dac-1a1eb1f4a8da.png)

**Comment by ArthurMorganRDR** [comment]
Thanks for the feedback ! Good to know that it happened for you with another card. I restarted my game anyway because it was getting weird to have two items missing. I spawned somewhere else, so I didn't try again yet to check if now they appear. I'll let you know if I try again.

**Comment by ArthurMorganRDR** [comment]
sorry for the out of subject, but: OMG !! Did y'all know that you can sell collections through mail ? :open_mouth: :open_mouth: damn .. I didn't know !! Now I don't need to find Madame Nazar for this anymore haha. If I am the one that didn't know, that sucks, but if this information is useful for other people, maybe it can be spread. :smile:
