### ISSUE TITLE
Map doesn't work on Tablet

### ISSUE THREAD

**Issue by babality** [jeanropke/RDR2CollectorsMap#243]
Hello.
While i can see the legacy map on my tablet i can't see the new version. It's just a blank page with the tooltip button in the up left corner. Any ideas?

**Comment by jeanropke** [comment]
Which tablet/OS are you using?

**Comment by babality** [comment]
Tablet: ipad2
Os: 9.3.5

**Comment by jeanropke** [comment]
There are incompatibilities with some versions of Safari.
Can you check which version is?
https://www.whatismybrowser.com/

**Comment by babality** [comment]
Safari 9

**Comment by jeanropke** [comment]
jQuery only supports Safari 11 & 12.
https://jquery.com/browser-support/

**Comment by babality** [comment]
ok thanx for your time.
