### ISSUE TITLE
No symbols on my map

### ISSUE THREAD

**Issue by WalkerBait1768** [jeanropke/RDR2CollectorsMap#246]
My map does not show any of the symbols

**Comment by jeanropke** [comment]
Can you check the browser console? (F12 or Shift + Control + i)

**Comment by WalkerBait1768** [comment]
I use my phone...iPhone X

**Comment by WalkerBait1768** [comment]
I use Safari as my web browser

**Comment by jeanropke** [comment]
There are incompatibilities with some versions of Safari.
Can you check which version is? 
https://www.whatismybrowser.com/

**Comment by OblivianS** [comment]
same the map does not show any of the symbols

**Comment by jeanropke** [comment]
@OblivianS https://www.whatismybrowser.com/

**Comment by Benasmokin** [comment]
I just opened my browser (Chrome 78 on Android/"Nougat") and there's no symbols on my map except Madam Nazar's location, and when I open the side menu there are no items listed underneath any collection when I click on the down arrow. It's been working fine on my browser until tonight, I'm not sure what's going on

**Comment by Benasmokin** [comment]
![Screenshot_2019-11-09-23-06-17](https://user-images.githubusercontent.com/57581709/68539224-ae4b0400-0345-11ea-9b0e-d59db48a8d04.png)

**Comment by Benasmokin** [comment]
![Screenshot_2019-11-09-23-06-33](https://user-images.githubusercontent.com/57581709/68539230-bf941080-0345-11ea-93d0-02a6aea9b6e7.png)
