### ISSUE TITLE
Move video link away from bottom and make it translatable

### ISSUE THREAD

**Issue by Senexis** [jeanropke/RDR2CollectorsMap#247]
**Is your feature request related to a problem? Please describe.**
I know this feature was just added, but I'm already getting pretty frustrated by the video link being on the bottom. I've gotten really used to the add/remove link being on the bottom of the popups and now I constantly miss-click (I'm zoomed to about 90% so it's really close together). Also, it seems the link itself is currently not translated.

**Describe the solution you'd like**
Please move the link away from the bottom. Maybe have an icon next to the title or have the link above the add/remove link instead, directly after the description.

**Additional context**
This is at 90%, it's already pretty close together. When zooming to 80% it gets even closer, at least the add/remove link is big enough to hit it, but it's still easy to hit the video link instead which is undesirable.

![image](https://user-images.githubusercontent.com/6360733/67163414-d1018280-f36e-11e9-89c5-3b0ae3401422.png)

**Comment by jeanropke** [comment]
Changed the position and added a padding. Tell me what you think.
http://prntscr.com/plx0ek

**Comment by Senexis** [comment]
Much better. Will probably help a lot. Thank you.
