### ISSUE TITLE
Missing Duck Eggs (Day 2)

### ISSUE THREAD

**Issue by ArthurMorganRDR** [jeanropke/RDR2CollectorsMap#248]
Hi,

I went today to grab the **Abello Ruby Bangle Bracelet** next to Quaker's Cove and found it, but I also found some **Duck Eggs** next to it.

lat: -93.5078125
lng: 94.625

![Red Dead Redemption II Collector Map (3)](https://user-images.githubusercontent.com/56277710/67165547-0ae28100-f38f-11e9-9e5f-dde09eab0c55.png)

**Comment by IronJeff80** [comment]
I did not see the duck eggs on 8 visits during this cycle. Most likely a random encounter.

**Comment by ArthurMorganRDR** [comment]
weird :D oki
