### ISSUE TITLE
1798 Draped Bust Silver Dollar Coin - Day 2 (September 29th)

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#25]
Found this one near O'Creighs Run
![silver_coin_1798](https://user-images.githubusercontent.com/55925524/65829841-dc9ae580-e2a9-11e9-9c1f-d34948a08089.png)

**Comment by iligalodin** [comment]
need metal detector i susspect?

**Comment by iligalodin** [comment]
strange again i got another item in this location. for me it was the Emmeline Coral Earrings at the co-ords "x": "-41.859375","y": "141.140625"

**Comment by githb123** [comment]
Yes, metal detector needed. Sorry.

I've got a feeling it might still be a bit randomized between individual players. To prevent having a map like this one and farming. Or it might be buggy.

**Comment by githb123** [comment]
October 9th, 2nd day - quartz arrowhead.
