### ISSUE TITLE
Remove/Add item issue

### ISSUE THREAD

**Issue by ctb0480** [jeanropke/RDR2CollectorsMap#251]
I have noticed today on Day 2 that when you click on items on the map to add/remove the item opens the youtube link instead of toggling on/off the item.  I am not sure if this was done on purpose or on all maps, but the video link should only open if there is a "video" option that is clicked on.

**Comment by jeanropke** [comment]
I changed this already. The script file are cached.
Should update in next minutes or try clearing the cache.
