### ISSUE TITLE
RDO Collectors Map Guide d'Utilisateur (French)

### ISSUE THREAD

**Issue by Nopitch** [jeanropke/RDR2CollectorsMap#256]
### _Bienvenue sur la carte de collectionneur non officielle de Red Dead Online et son guide d’utilisateur officiel!_

_Ecrit par Nopitch._

Ce guide vous aidera à comprendre _Quoi_  trouver _Quand_  et  _Où_, ainsi qu’une explication simplifiée de toutes les fonctionnalitées que la carte propose.

Vous trouverez la carte ici : https://jeanropke.github.io/RDR2CollectorsMap/

***

### Les couleurs des balises de la carte:

**Couleurs des balises de la carte**:
- Balises bleues: Carte 1.
- Balises oranges: Carte 2.
- Balises violettes: Carte 3.
- Balises vertes (max. 3 objets): Collection hebdomadaire de Madame Nazar.

***

### Les cartes de collection & rotation:

**Les cartes de collection**:
- Les cartes de collection effectuent une rotation de la façon suivante:
1. Lundi (Carte 3)
2. Mardi (Carte 1)
3. Mercredi (Carte 2)
4. Jeudi (Carte 1)
5. Vendredi (Carte 3)
6. Samedi (Carte 1)
7. Dimanche (Carte 2)
- Notez que: La `Carte des Collections Red Dead Redemption II ` utilisera _toujours_ la bonne carte automatiquement.

**Le Changement de Carte**:
Les carte changent tous les jours à 00:00 UTC/GMT ce qui correspond à:
- 02:00 CEST (Paris, Bruxelle, Genève, GMT +2) Heures d'été.
- 01:00 CET (Paris, Bruxelle, Genève, GMT +1) Heures d'hiver.
- 07:00pm EST / 08:00pm EDT (Québec, UTC -4)
- Notez que: En jeux, les objets changent _immediatement_ de position à ces horraires. Il n'est pas nécéssaire de changer de serveur.

**La Position de Madame Nazar**:
- La Position de Madame Nazar change tous les jours à 06:00 UTC/GMT (A la même heure que les défis journalier), ce qui correspond à:
- 08:00 CEST (Paris, Bruxelle, Genève, GMT +2) Heures d'été.
- 07:00 CET (Paris, Bruxelle, Genève, GMT +1) Heures d'hiver.
- 01:00am CEST / 02:00am EDT (Québec, UTC-4)

***

### Les fonctionnalités de la carte:

**Dans le coin supérieur droit vous trouverez l'option de sélection de la carte du jeu:**

![RDO Collectors Map Dark Map Mode Map Mode Select](https://user-images.githubusercontent.com/55949253/66665106-21316400-ec4e-11e9-9b1d-f4e0b21c71b9.png)
![Annotation 2019-10-12 032805](https://user-images.githubusercontent.com/55949253/66692655-caa14580-eca0-11e9-9f44-a0c7df828cfa.png)

> Default: Carte où les détails comme les routes, chemins, voies ferrées sont affichés avec une opacité basse.

> ![Annotation 2019-10-11 174643 Cropped](https://user-images.githubusercontent.com/55949253/66665636-3b1f7680-ec4f-11e9-8ccd-cacedc977e44.png)

> Detailed: Carte où les détails comme les routes, chemins, voies ferrées sont affichés avec une opacité normal. Identique à la carte en jeu. C'est l'option par default.

> ![Annotation 2019-10-11 174337 Cropped](https://user-images.githubusercontent.com/55949253/66665509-ff84ac80-ec4e-11e9-9f45-8d62c84bd495.png)

> Dark: Carte où les détails comme les routes, chemins, voies ferrées sont affichés en blanc, avec l'arrière-plan en gris foncé. Pratique pour les collectionneurs nocturnes.

> ![Annotation 2019-10-11 174350 Cropped](https://user-images.githubusercontent.com/55949253/66665527-07dce780-ec4f-11e9-8447-049828e26a62.png)

**Dans le coin supérieur gauche, est affiché le temps qu'il reste avant la prochaine rotation de carte; à coté se trouve le bouton qui permet d'ouvrir le menu.**

![RDO Collectors Map Dark Map Mode Timer](https://user-images.githubusercontent.com/55949253/66665128-2e4e5300-ec4e-11e9-825c-6dfa8e0eab4c.png)

**Les fenêtres de balise sur cliquer/tapoter**:

![RDO Collectors Map PopUPFrench](https://user-images.githubusercontent.com/51863128/67286228-50ab6080-f4d9-11e9-959e-e11a280bcc7a.PNG)

- Cette fênetre s'affiche apres avoir cliqué/tapoté une balise de carte.
- En haut se trouve le nom de l'objet à collectionner ainsi que le numéro de la carte.
- Si besoin, en dessous du nom, sera affiché un symbole décrivant quel outil est nécéssaire à la collecte:
⛏ Pour la pelle;
🧲 Pour le détecteur de métaux.

- A coté du symbole se trouve une petite description de l'emplacement de l'objet et/ou un lien vers une video d'explication.
- `Ajouter/Supprimer de la Carte` baisse l'opacité de la balise et la supprime de la route dynamique afin de vous aider à garder la trace des objets déjà collectés. Vous pouvez les faire réapparaitre à tout moment en cliquant/tapotant une nouvelle fois sur le bouton `Ajouter/Supprimer de la Carte`.

***

### Le menu latéral :

> **Collections**:

> ![RDO Collectors Map Side Bar Menu Collectables French](https://user-images.githubusercontent.com/51863128/67286120-1f329500-f4d9-11e9-976a-f82a3576c891.PNG)

- `Tout cacher` cache toutes les balises.
- `Tout montrer` montre toutes les balises.
- Cliqué/tapoté sur le nom d'une collection là cachera/montrera de la carte.
- Cliqué/tapoté sur la flèche à droite d'une collection ouvre/ferme le menu déroulant des objets de la collection.

> **Le menu déroulant des objets de la collection**:

> ![RDO Collectors Map Side Bar Menu Collection Details French](https://user-images.githubusercontent.com/51863128/67285905-b1866900-f4d8-11e9-83a1-be6cddf24cbd.PNG)

- La valeur de chaque collections est afficher en haut.
- Cliqué/tapoté sur un objet de collection le cachera/montrera de la carte et son nom sera barré dans le menu.
- Cette fonction à le même éffet que le bouton `Ajouter/Supprimer de la Carte`; baisse l'opacité de la balise et la supprime de la route dynamique. Cliqué/tapoté à nouveau pour les réactiver.

> **Utilitaires, Recherche, Paramètres, Routes Personnalisées & Problèmes**:

>![RDO Collectors Map Side Bar Menu Utilities Settings French](https://user-images.githubusercontent.com/51863128/67285497-f6f66680-f4d7-11e9-89c4-cc0d3a3e03dd.PNG)

> **Utilitaires**:

- `Madame Nazar` cachera/montrera sa position sur la carte.
- `Fast Travel` cachera/montrera toutes les balises de Voyage Rapide sur la carte.
- `Trésors` cachera/montrera la zone de recherche d'un trésor (Zone qui s'affiche en jeux après avoir activé la carte correspondante, vous permettant de planifier vos routes en y incluant les trésors.

> **Recherche**:

- `Recherche` Vous permet de chercher des objects de collections par nom. Séparer les noms par un `;`. (Exemple: Pointe de Flèche en Silex;Pointe de Flèche en Obsidienne;Peigne en Ivoire etc.)

> **Paramètres**:

- `Jour` change le numéro de carte (1,2,3). Par default affiche la carte actuelle dans la rotation.
- `Outils` permet de n'afficher que les objets collectables avec un outil spécifique.
- `Langue` permet de changer la langue.
- `Activer route` permet d'activer la route dynamique qui affiche le tracé le plus efficace entre les objects affichés sur la carte. Le tracé est actualisé automatiquement si vous afficher/cacher une balise.
- `Afficher les coordonées` permet d'afficher les coordonées sur un clique sur la carte. Pratique pour remonter l'emplacement d'un nouvel objets où soumettre une correction!
- `Rénitilaliser tous les jours` permet de réinitialisé la carte à chaque rotation. Permet aussi de rétablir la carte manuellement avec l'option `Rétablir`.

> **Routes Personnalisées**:

- `Importer route` permet d'importer une route partagée en utilisant le bon format.
- `Exporter route` permet d'exporter votre route personnalisée dans le bon format afin de la partager.
- `Activer route pers.` permet de tracer une route entre deux balises d'objets à collectionner. Cliquez sur une balise puis cliquez sur une seconde balise pour afficher une route les deux. Afin d'effacer une route cliquez à nouveau sur la dernière balise utilisée. Vous pouvez aussi `Effacer` tout le tracer en une seule fois.

> **Problèmes**:

- `Remonter un problème ici!` ouvre dans un nouvel onglet la page GitHub du projet où vous pouvez nous remonter un bug ou un problème!
- `Retour à la version originale!` affichera la toute première version de la carte, sans les fonctionnalités avancées.
- `Donate` Vous permez de faire un don mensuel ou ponctuel, une façon de remercier Jean Ropke pour son travail sur la carte. Cela fait toujours plaisir!

**Comment by jeanropke** [comment]
Added to wiki. Thanks :)
https://github.com/jeanropke/RDR2CollectorsMap/wiki/RDO-Collectors-Map-Guide-d'Utilisateur-(French)
