### ISSUE TITLE
[suggestion] being able to map out your own route

### ISSUE THREAD

**Issue by SSSidekick** [jeanropke/RDR2CollectorsMap#26]
First, I'm very new to github, so please pardon me if this isn't the proper place for this or I sound like the total noob I am! Thx!

That said, when I was playing with the beta version earlier I was able to double click and set my own route between collectibles. If this is intended behavior, it's a bit buggy as I'm not able to get it to do that again.... also, if this a feature, having the option to delete the last point set would really be great. 

If it's not intended behavior, it would be a great addition to this project!

As I've said, I'm a total noob here and I'm not sure if there's anything else i should add or if, in the future, i should try and get screenshots... 

Also, what can i do to help? i have a way of accurately pinpointing and sharing any location in RDR2O and i am starting to save markers where I've found collectibles. i'm totally willing to share what i find if you'd like it!

Thanks for making a great tool!

**Comment by jeanropke** [comment]
I used this feature to create the routes. Its very buggy and need some coding.

**Comment by jeanropke** [comment]
Added option to enable/disable custom routes.
Left Control + Left Click to remove last node added on routes.
