### ISSUE TITLE
Custom Routes not functioning

### ISSUE THREAD

**Issue by BrickManifest** [jeanropke/RDR2CollectorsMap#263]
I cannot get the custom route feature to work. I did as the guide says and clicked on one collectible and then clicked on the next but it just pops up with the window for that collectible. It is enabled but nothing I click on in the map creates a custom route.

**Comment by manfreygordon** [comment]
also being affected by this issue.

**Comment by Rakmarok** [comment]
Same here. It will be looked into. Thanks for the report.

**Comment by jeanropke** [comment]
Fixed. It should be working in a few minutes.

**Comment by BrickManifest** [comment]
Thank you for such a quick response. Every day I get on there are new features so I just want to say thank you so much. Everybody using this should donate so it's worth your time to keep up with all that you're doing.

**Comment by Rakmarok** [comment]
Thank you. We appreciate it. :-)
