### ISSUE TITLE
Incorrect location of the Abello Ruby Bangle Bracelet (Day 2)

### ISSUE THREAD

**Issue by xsimtomx** [jeanropke/RDR2CollectorsMap#264]
According to the map it's at lat: -93.6875 lng: 94.6640625 (right to Quaker's Cove) but I found it at lat: -35.6953125 lng: 150.2734375 (close to the Wisteria Flower on Day 2).

So far, very impressed with your map!

EDIT: it appears as if the locations have either changed or that locations have been added because I found a Chipped Arrowhead at lat: -110.625 lng: 79.8515625 (shack above the "V" in San Luis River). 
None of the videos or other maps show an Arrowhead at that location.

**Comment by IronJeff80** [comment]
Locations produced a random item for me.
Abello Ruby Bangle Bracelet found at map location

**Comment by xsimtomx** [comment]
> Locations produced a random item for me.

Not sure what's happening but more and more locations are incorrect for me, or I find stuff at locations that are not on the map.

**Comment by IronJeff80** [comment]
The items on the map are static. They produce the same item each cycle. There are over 400 locations that produce a random item. You will obviously find items at random locations that are also at the static location.  The random item locations are NOT on the map.

**Comment by xsimtomx** [comment]
I understand but sometimes I don't find anything at a marked location on the map, quite frustrating if you're trying to find specific items.
