### ISSUE TITLE
random items cycle

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#270]
FYI several people (Blackwall42) indicates that the random item locations do not appear per cycle. They are actually collectible every 24 hrs. I can not verify this however he has produced a map with multiple locations. take a look here https://imgur.com/gallery/oYBpfcb.

Question: will this map be sufficient enough to get these added or do we need to fill out the form.

**Comment by IronJeff80** [comment]
Some random items repeat every day. Some repeat on the daily cycle. Others
respawn several times per day.
the item here in Great Plains, is one you can find to pick up every couple
hours
lat: -89.640625
lng: 86.421875
