### ISSUE TITLE
Herb locations for Dailies

### ISSUE THREAD

**Issue by chrissydewet** [jeanropke/RDR2CollectorsMap#275]
hi, add popular herb locations like clickables. eg put them on the map like indian herb, poppy, bay bolete.

This way when we want to do a herb run, we can add it to our daily collector run as well. Even make it part of a list on the left and able to hide it like the other collectable items.

Thanks
chris.

**Comment by jeanropke** [comment]
https://jeanropke.github.io/RDOMap/
