### ISSUE TITLE
Missing location

### ISSUE THREAD

**Issue by Ctlz21** [jeanropke/RDR2CollectorsMap#276]
Not sure if it's random item location or no, but I found a Banais Topaz Ring by the water tower is Scarlett Meadows. Currently the map shows it as random item location on day 1, but October 28th, today, is day 3.
lat: -74.546875
lng: 125.5703125
![banais topaz ring day 2](https://user-images.githubusercontent.com/16960632/67692529-527d9400-f9b1-11e9-81b4-78e14789d5c4.jpg)

**Comment by EverettLawson** [comment]
Day 3 (Nov 15, San Diego) yields a "Crude Arrowhead" at that location. Must be a "Random".
