### ISSUE TITLE
Page of Cups/Cardinal Flower Day 2 (September 29th)

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#28]
I got the cardinal flower here instead of the tarrot card.

![cardinal_flower_not_tarrot](https://user-images.githubusercontent.com/55925524/65831706-2f31cd00-e2bd-11e9-8616-95f308459cab.png)

**Comment by githb123** [comment]
It's the shack/cottage in Bluewater Marsh on the east side.

**Comment by iligalodin** [comment]
found the Page of Cups in the broken down outhouse

**Comment by iligalodin** [comment]
found the cardinal flower, will add it to my next pull request

**Comment by githb123** [comment]
Yes, I found the card now too after loading into other lobby. Strange. I swear I was looking thoroughly after I picked up the flower and the card wasn't there at that time.

**Comment by iligalodin** [comment]
Thanks for checking! can you close this issue?
