### ISSUE TITLE
Incorrect item location Cycle: day 1 random #4

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#283]
incorrect location for day 1 random item #4. 

The coordinate should a little north and east of that location @ -60.1 / 85.75
Or 
It should mark the other location just to the west south west @ -60.4 / 83.53

Also note this random items is not cycle based. It will re-spawn 24 hr after it’s collected.

**Comment by jeanropke** [comment]
I'll remove this item. Not cycle based.
