### ISSUE TITLE
Incorrect item Cycle: day 3   Random Item #1

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#285]
Incorrect item Cycle: day 3   Random Item #1
There is nothing.

**Comment by Ootat** [comment]
Random item re-spawn 24 hr after they’ve been collected. Verify that u didn’t collect it the day before.

**Comment by TomNamibia** [comment]
Sorry, I guess that was the case 

Tom 

Am 03.11.2019 23:09,
schrieb Ootat: 

> Random item re-spawn 24 hr after they've been
collected. Verify that u didn't collect it the day before. 
> 
> --
>
You are receiving this because you authored the thread.
> Reply to this
email directly, view it on GitHub [1], or unsubscribe [2].



Links:
------
[1]
https://github.com/jeanropke/RDR2CollectorsMap/issues/285?email_source=notifications|+|amp|+|email_token=ANN6QDRFTOJ6Q23LVTCC65DQR4VWRA5CNFSM4JH7ME32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC543QQ#issuecomment-549178818
[2]

**Comment by EverettLawson** [comment]
I came here to open a ticket for the same issue. I can verify that I have NOT picked up this item in the last 24 hours. I've only been doing flowers for the last week. Marker is very close to outhouse with a Tarot Card in it.  There is not, however, a dirt mound with yellow smoke nor a metal detector object anywhere in the vicinity.

**Comment by jeanropke** [comment]
Updated
