### ISSUE TITLE
Locations of treasure maps stuck on trees

### ISSUE THREAD

**Issue by Bryan20721** [jeanropke/RDR2CollectorsMap#286]
I would like to suggest new marker the treasure maps stuck onto the trees locations i would like that one the most because it would be most helpful thank you

**Comment by IronJeff80** [comment]
https://github.com/jeanropke/RDR2CollectorsMap/issues/271

**Comment by Bryan20721** [comment]
Do we know the times they spawn and or what days they spawn?  its a lot of hassle to ride around the map guessing which one will have it if not thats okay

**Comment by Bryan20721** [comment]
Nvm ill keep up to date with issue #271 until it is closed thank you very much

**Comment by IronJeff80** [comment]
About as random as a gang hideout. You can spawn them by rejoining free
roam from online menu. Mainly they spawn at night. A few locations have
spawned in daytime. They dont spawn if you have them map already.
