### ISSUE TITLE
Duck egg Day 1, 2nd Nov, another location

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#288]
Hi,

I've found the duck eggs on the day 1 here in a nest on the ground instead of in the far north of Brandywine Drop at the tracks.

![duck_egg_d1](https://user-images.githubusercontent.com/55925524/68069985-39396680-fd68-11e9-8999-0d042b8265d9.png)

I'm sorry Im' not going to create additional accounts (espacially google) to edit the spreadsheet - sorry :( Got aready enough accounts to track.

**Comment by IronJeff80** [comment]
Bird Egg nest can spawn in various locations that are not static. They are typically accompanied by a coyote or other predator trying to eat them. This is one of those locations. It spawns randomly, but if you visit enough, you can get it to spawn every day. Here are a few other locations: 

Bird Egg Encounter: Moonstone Pond: Coyote
lat: -45.3125 
lng: 130.59375

Bird Egg Encounter: Elysian Pool: Fox or Coyote 
lat: -49 
lng: 149.6015625

Bird Egg Encounter, Heartland Overflow: Coyote
lat: -54.625 
lng: 128.78125

Bird Egg Encounter, Lake Owanjila: Bear
lat: -69.3046875 
lng: 74.2734375
