### ISSUE TITLE
Three of Wands - Day 2 WRONG Location

### ISSUE THREAD

**Issue by Vampeth** [jeanropke/RDR2CollectorsMap#29]
Three of Wands - Day 2 is on a WRONG Location.

The RIGHT location in in the screen shots below. 
![Red Dead Redemption 2_20190929131037](https://user-images.githubusercontent.com/30540286/65832401-ebd65f00-e2ba-11e9-8a6a-66c40c7d3e8e.png)
![Red Dead Redemption 2_20190929131107](https://user-images.githubusercontent.com/30540286/65832402-ebd65f00-e2ba-11e9-8884-b1bc7f03f443.png)

**Comment by iligalodin** [comment]
will look into it, if so ill add it to my pull request

**Comment by Vampeth** [comment]
It is by the cemetery.

**Comment by iligalodin** [comment]
confirmed will send the request
