### ISSUE TITLE
Random Diggable in the 1st island in front of Braithwaite Manor 

### ISSUE THREAD

**Issue by Vampeth** [jeanropke/RDR2CollectorsMap#291]
I'm sending you this Random Diggable location because you don't have in the Interactive Map. 

![Red Dead Redemption 2_20191103112441](https://user-images.githubusercontent.com/30540286/68084452-8df2e500-fe2d-11e9-8bb2-e8aad76b3a42.png)
![Red Dead Redemption 2_20191103112541](https://user-images.githubusercontent.com/30540286/68084453-8df2e500-fe2d-11e9-8fb5-f7d369fa7f08.png)

**Comment by jeanropke** [comment]
Item added
