### ISSUE TITLE
Heron Egg: day #3 not found

### ISSUE THREAD

**Issue by KAiSER086** [jeanropke/RDR2CollectorsMap#292]

**Comment by IronJeff80** [comment]
Just went there and found it in the tree. Clear your cache and check again. 
https://youtu.be/f2CM0jmjxLI

**Comment by KAiSER086** [comment]
> Just went there and found it in the tree. Clear your cache and check again.

Aight, switched lobby like 10 times no change, gonna try that

**Comment by KAiSER086** [comment]
I looked again later, but the egg still wasn't there. I think it was a bug, I shot another egg from a tree, but the egg and those golden sparks disappeared even though the ringing was still there.
