### ISSUE TITLE
Day 3, six of cups tarot card not in area suggested!

### ISSUE THREAD

**Issue by nemesisnin** [jeanropke/RDR2CollectorsMap#293]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Thats a game issue. #241 

Screenshot taken 10 minutes ago
![six of cups day 3](https://user-images.githubusercontent.com/6243818/68140371-79d0e580-ff0a-11e9-9c50-4fadea1598f4.jpg)
