### ISSUE TITLE
Goose-eggs-day1 (missing on map)

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#295]
![Goose-eggs-day1](https://user-images.githubusercontent.com/56354830/68187905-9c1d3e80-ffb0-11e9-8363-61e4fad23693.jpg)
)
* What day cycle it is? 1
* Coordinates or a clear image of the location
* Include the item name : goose eggs

**Comment by jeanropke** [comment]
Item added

**Comment by Ootat** [comment]
I’ve checked this location twice now on day 1 cycles and there is no fixed spawn location there. I believe it’s a random animal encounter spawn.

**Comment by IronJeff80** [comment]
I have checked it as well. Nothing there. Verified that I had less than 10 goose eggs prior to checking location.

**Comment by jeanropke** [comment]
I found once in this place.
Removed from map.
