### ISSUE TITLE
missing item Tumbleweed_random (coin) Cycle: day #1

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#296]
![Tumbleweed_random](https://user-images.githubusercontent.com/56354830/68208644-4b224000-ffda-11e9-931f-7f2ee97080f4.jpg)

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Already added. Random spots are disabled by default.

![random item tumbleweed](https://user-images.githubusercontent.com/6243818/68212052-89f2ce80-ffb7-11e9-99ba-56cc4442d245.png)
