### ISSUE TITLE
missing random items (2) Benedict Point Cycle: day #1

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#297]
![Benedict_random_1](https://user-images.githubusercontent.com/56354830/68212399-203bea00-ffe2-11e9-85ab-59731215f1c7.jpg)
![Benedict_random_2](https://user-images.githubusercontent.com/56354830/68212402-20d48080-ffe2-11e9-898f-f39920044cb5.jpg)

#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Items added
