### ISSUE TITLE
Missing item Cholla_Springs_random_01 Cycle: day 1

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#298]
![Cholla_Springs_random_01](https://user-images.githubusercontent.com/56354830/68215803-81ff5280-ffe8-11e9-92bb-d54a575d4309.jpg)
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Item added
