### ISSUE TITLE
missing item Braithwait_random_01 Cycle: day #1

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#299]
![Braithwait_random_01](https://user-images.githubusercontent.com/56354830/68231090-065ecf00-0003-11ea-8bb5-3d88ef7cb4b2.jpg)
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by IronJeff80** [comment]
Can you use the form for missing items and not create a new issue for them? 

> Found a new location? Use this form here

If it is on this map, do not submit an issue: https://imgur.com/gallery/WOEkmz6
Random item locations repeat 24 hours after you collect them and they do not follow a day cycle.

**Comment by jeanropke** [comment]
Item added
