### ISSUE TITLE
Ojeda Rose Gold Bangle Bracelet - Day 2

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#30]
Got it here. Shovel and metal detector needed.
![Ojeda Rose Gold Bangle Bracelet - Day 2](https://user-images.githubusercontent.com/55925524/65833258-9015d100-e2ce-11e9-85d2-760e0f0b91d5.png)

**Comment by iligalodin** [comment]
will check it out soon, coincidentally i am on my way there

**Comment by iligalodin** [comment]
i found the "1792 Liberty Quarter Coin" there at the co-ords "x": "-59.5546875","y": "133.6875"

**Comment by iligalodin** [comment]
Random item location
