### ISSUE TITLE
Export route 

### ISSUE THREAD

**Issue by Evilbear311** [jeanropke/RDR2CollectorsMap#311]
Thank you amazing tool. How do I export a route - doesn’t seem ti work just pasting into a browser

**Comment by IronJeff80** [comment]
Click export route. It saves the code to clipboard. Save that on a txt file or note. to import, paste the code in the dialogue box

**Comment by Evilbear311** [comment]
Thanks. Made a donation to PayPal thanks so much for the map

**Comment by jeanropke** [comment]
Thanks. 🤠
