### ISSUE TITLE
Missing item Wisteria Cycle: day 3

### ISSUE THREAD

**Issue by TomNamibia** [jeanropke/RDR2CollectorsMap#317]
![Blauregen-Wisteria-day3](https://user-images.githubusercontent.com/56354830/68578656-194a2700-047b-11ea-937a-85e96a6cc4e5.jpg)

**Comment by IronJeff80** [comment]
Confirm

**Comment by BigGrvity** [comment]
shows up for me right now

**Comment by jeanropke** [comment]
Added on map
