### ISSUE TITLE
Possible bitterweed location, need verification!

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#32]
I found a bitterweed at the location where i am standing.

![image](https://user-images.githubusercontent.com/1492205/65834280-c442bf00-e2d9-11e9-8541-099f0aed9197.png)

co-ords: "x": "-64.671875","y": "144.9765625"

**Comment by githb123** [comment]
Yes, I can confirm this.

**Comment by iligalodin** [comment]
thanks will add it to my pull request!
