### ISSUE TITLE
..missing easter eggs etc...RDO

### ISSUE THREAD

**Issue by feiercrack** [jeanropke/RDR2CollectorsMap#320]
![a3640f6949f23ce7775c546b99abb1f7](https://user-images.githubusercontent.com/47046040/68629817-809cc100-04e5-11ea-9e7c-73ef68fdaa01.jpg)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeanropke** [comment]
I will not add Easter eggs to Collectors Map.
Maybe I add in RDOMap.
