### ISSUE TITLE
Banais Topaz Ring - Cycle 2

### ISSUE THREAD

**Issue by kittrellbj** [jeanropke/RDR2CollectorsMap#324]
**Is your feature request related to a problem? Please describe.**
Item is only marked here. Add description to Banais Topaz Ring - Cycle 2

**Describe the solution you'd like**
Add "Inside dead tree" as description.

**Describe alternatives you've considered**
It was at the correct location, but a description would've helped make the find faster.

**Additional context**

**Comment by jeanropke** [comment]
Updated.
