### ISSUE TITLE
Images of coins are not displayed

### ISSUE THREAD

**Issue by caretaker0815** [jeanropke/RDR2CollectorsMap#325]
Images of coins are not displayed on the card when using Mozilla Firefox as your browser.

**Comment by IronJeff80** [comment]
What do you mean by "on the card". I use Firefox and haven't had issues. Have a screenshot?

**Comment by caretaker0815** [comment]
Sorry, I made a mistake and didn't pick a tool. Then only the dynamic routes are displayed without coin image.
