### ISSUE TITLE
1792 Quarter no dig icon

### ISSUE THREAD

**Issue by BigGrvity** [jeanropke/RDR2CollectorsMap#327]
on all 3 cycles I cant dig up the 1792 Quarter, I have 9 in inventory should be able to get 1 more, I get the metal detector indication at all indicated locations but no option to dig, anyone else have this issue or similar?

**Comment by IronJeff80** [comment]
Game bug, I've had that happens many times. Actually several times per day. The dig option just doesn't pop up. Usually, clearing the cache and returning to the location fixes it, but not every time.

**Comment by BigGrvity** [comment]
guessing my post was out of guidelines as it's been removed, I can collect everything on the map, except the 1792 quarter at any of its locations, tried clearing the cache to no avail, emailed Rockstar but haven't received a response
   On Thursday, November 14, 2019, 9:55:33 AM PST, jeanropke <notifications@github.com> wrote:  
 
 
Closed #327.
