### ISSUE TITLE
Possible splintered arrowhead day 2

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#33]
I found a splintered arrowhead at the location of my character, can someone verify this?
![image](https://user-images.githubusercontent.com/1492205/65834434-1fc17c80-e2db-11e9-8b51-0de33ad92c07.png)

Co-ords: "desc": "Besides a hollow and a fallen tree.","x": "-70.390625","y": "150.8359375"
tool needed: **shovel**

**Comment by githb123** [comment]
I found a metal hair pin in this spot. 4th item in the top row. Familiy Hairlooms.

**Comment by iligalodin** [comment]
again these inconsistencies :(

**Comment by iligalodin** [comment]
random item location
