### ISSUE TITLE
Treasure Maps possible locations

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#331]
Treasures in the treasure maps can be in different locations, so can we have all those possible locations marked in the map?

**Comment by IronJeff80** [comment]
Duplicate #271

**Comment by IronJeff80** [comment]
An image in the description would be better suited.

**Comment by brogsitter** [comment]
https://i.imgur.com/WQnHUFh.jpg

Just as an example (positions are not correct though)

**Comment by jeanropke** [comment]
![treasures locations](https://user-images.githubusercontent.com/6243818/69098710-e209e600-0a37-11ea-9896-d6b357b92f45.png)
