### ISSUE TITLE
Wildflower issue 

### ISSUE THREAD

**Issue by HFM1101** [jeanropke/RDR2CollectorsMap#332]
Hi,
  Great website btw, it's something of a marvel.
A new issue has started over the last few days. With American Wildflowers, the Agarita flower always shows as greyed out no matter what I do. There is no way to make it appear uncollected. Is this a known issue? Thanks.

**Comment by BigGrvity** [comment]
I had the Agarita do the same to me for a couple days, I could see the plant was there but no option to pick it and no indication of being near it, eventually I was able to pic them again

**Comment by jeanropke** [comment]
I changed how cookies are saved. Can you confirm if the bug still occurs?

**Comment by HFM1101** [comment]
Yes, I can confirm the bug still occurs. Currently there are four Agarita symbols showing in New Austin, but three are greyed out and only one (furthest west) is showing as uncollected. I can confirm also that I have not found the greyed out symbols and removed them.

**Comment by jeanropke** [comment]
I tested with all markers and worked fine. Try reseting markers. 
http://prntscr.com/pxt2ov

**Comment by Senexis** [comment]
If this is still happening please post a comment.
