### ISSUE TITLE
Different colour/size marker for 'random' sites

### ISSUE THREAD

**Issue by thebeanest** [jeanropke/RDR2CollectorsMap#335]
The way I use the map, I like to be able to load up everything I need to collect, but I also like the random spots visible so if I'm near it and feel like it, I can go get it.

The problem is because there's so many random spots, it really clutters up the map.

I have a couple of ideas - one is making the 'random' spots a different colour to the daily cycle markers, even a different shade of the same colour. The other suggestion, which I actually like more, is making a different marker. Possibly something half or quarter of the size of the regular markers? So that I can have them showing on the map, but not overwhelming everything else I wanna see on the map :)

**Comment by q1k** [comment]
For the time being, you can install stylus extension: [Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) / [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)
Go into Manage Styles -> Write new -> Import style (under Mozilla format)
then paste the following and hit overwrite.
```
@-moz-document url-prefix("https://jeanropke.github.io/RDR2CollectorsMap/") {
img[src*="icons/random_"] {
    width: 21px !important;
    height: 28px !important;
    margin-top: -25px !important;
    margin-left: -11px !important;
    filter: saturate(6) sepia(0.55) hue-rotate(45deg);
}
}
```
you can adjust the width, height and margins as you want

**Comment by jeanropke** [comment]
Changed marker color to lightgray.
http://prntscr.com/pxszx8

Mobile users will suffer with smaller markers
