### ISSUE TITLE
Unmarked item

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#337]
Found this dig spot with Metal Detector in Bard's Crossing in the south peak of the island in the river.
I got an Arrowhead

![item_bards-crossing](https://user-images.githubusercontent.com/7927176/68986052-ccb87000-081b-11ea-91f4-5570d8857fd0.jpg)

Not sure which cycle it was though. I got this 2-3 days ago...

**Comment by jeanropke** [comment]
Item added
