### ISSUE TITLE
Reset Daily Markers

### ISSUE THREAD

**Issue by TheEMP1978** [jeanropke/RDR2CollectorsMap#338]
Reset daily markers is default off & when I set it to on it occasionally falls back to the default off.

I think by default it should be turned on always resetting the markers unless set to do otherwise.  

Other than that you are a God & this map is amazing.

**Comment by jeanropke** [comment]
I changed somethings on daily reset. Can you confirm if the bug still happens?

**Comment by Senexis** [comment]
Just writing in to confirm that this bug still seems to be present. When I set to "Yes", do a run, then come back another day on the same cycle, the toggle is set back to "No" and the collectables are not reset.

**Comment by pandemicland** [comment]
It does the same for me. It worked a few times where I would collect and mark them. The next day I would get on the map and it was reset for me. I have mine set to reset daily but it still doesn’t. It hasn’t reset for me in a month or so.

**Comment by jeanropke** [comment]
Can you confirm if this still happening?

**Comment by Senexis** [comment]
No more complaints since then. If there's any further issue, please open a new issue.
