### ISSUE TITLE
Importing / Exporting Custom Routes

### ISSUE THREAD

**Issue by SSSidekick** [jeanropke/RDR2CollectorsMap#340]
Apologies as I was not sure if this would fall under "Feature Requests" or not... 

I'm having some trouble figuring out how this functionality works. I absolutely appreciate being able to set my own route. This has made a world of difference when it comes to _how_ I collect.

That said, the words "Export Route" and it's other half "Import Route" seem to suggest that you'd be able to set up a route and then "save" it through exporting... then be able to load that route in at a later date. I've tried Exporting and then pasting what's saved to the clipboard into a Google doc, however I encounter an error "Invalid route" when trying to import it again. 

This leads me to think that maybe that does not function in the way that I was thinking that it did... Care to shed some light on what this is actually for (and how to utilize it)?

Also, if this is not the function of this option, I would like to suggest that a way to properly export a custom route become a feature of the map, as it would be awesome to be able to "send" my route to my posse so they can see where we'll be headed next!

**Comment by SSSidekick** [comment]
here is the exported route data: 

egg_spoonbill,random_item_194,random_item_37,random_item_39,random_item_193,bottle_scotch_whisky,egg_heron,random_item_40,random_item_187,random_item_192,random_item_42,random_item_188,flower_creek_plum_3,wands_ace,random_item_43,random_item_44,random_item_45,random_item_186,flower_creek_plum_2,random_item_46,heirlooms_new_guinea_rosewood,cups_ten,random_item_185,random_item_184,random_item_183,flower_creek_plum,random_item_180,random_item_181,wands_page,random_item_140,random_item_139,random_item_138,wands_king,random_item_137,random_item_132,random_item_131,random_item_143,random_item_141,random_item_142,heirlooms_cherrywood_comb,pentacles_eight,random_item_144,random_item_146,wands_four,random_item_145,wands_ten,random_item_154,random_item_157,coin_draped_bust_silver_dollar,random_item_158,random_item_159,ring_harland_coral,random_item_153,random_item_152,random_item_151,random_item_122,random_item_150,random_item_120,random_item_121,random_item_119,random_item_118,earring_endicott_diamond,random_item_123,ring_banais_topaz,random_item_116,pentacles_five,egg_hawk_1,random_item_115,random_item_114,wands_knight,cups_eight,cups_ace,egg_hawk_2,egg_eagle_2,coin_new_yorke_token,random_item_102,random_item_101,arrowhead_obsidian,coin_half_dime,random_item_99,wands_three,random_item_106,flower_creek_plum_4,random_item_29,random_item_107,random_item_108,random_item_109,egg_eagle_1,random_item_98,flower_creek_plum_5,random_item_26,random_item_87,random_item_88,random_item_89,random_item_81,random_item_82,random_item_20,random_item_19,random_item_78,random_item_77,random_item_74,random_item_73,random_item_17,random_item_71,flower_agarita_3,random_item_9,random_item_70,wands_five,random_item_11,random_item_67,random_item_63,random_item_13,random_item_14,flower_agarita_1,flower_agarita_2,random_item_60,random_item_61,random_item_4,random_item_53,random_item_52,random_item_51,random_item_50,random_item_3,random_item_54,random_item_55,random_item_5,random_item_58,heirlooms_tortoiseshell_comb

**Comment by IronJeff80** [comment]
Your route has random items., Turn on random items, enable custom route, then import your route. It works fine for me

**Comment by jeanropke** [comment]
Now loading custom routes with disabled categories will create a route only with enabled ones.
