### ISSUE TITLE
Collectible Values different

### ISSUE THREAD

**Issue by HumanTree92** [jeanropke/RDR2CollectorsMap#341]
So i'm on PC and for me the Collectibles show a different Value for the payout in the satchel.

[RDR2 Online Collectibles.txt](https://github.com/jeanropke/RDR2CollectorsMap/files/3855275/RDR2.Online.Collectibles.txt)

I've included a list of my Collectible Values. Not sure if its an error or what.

**Comment by IronJeff80** [comment]
There is a current promotion this week ehich adds 25% to each set.

**Comment by HumanTree92** [comment]
Ah thanks. Yeah i looked it up but didn't see anything about that.
