### ISSUE TITLE
Treasure Map Markers

### ISSUE THREAD

**Issue by brogsitter** [jeanropke/RDR2CollectorsMap#344]
Wouldnt it be nice to have all the 4 possibilities where to find the treasure, when selecting a location? If I can help with that, just let me know what to do ;)

**Comment by IronJeff80** [comment]
Duplicate #331

**Comment by IronJeff80** [comment]
Dirty Tyler has laid them all out:
https://www.youtube.com/watch?v=_eg6Xq844so&list=PLTztSTSjscXXmBhtGyiqRPxzcc_9jUZ7a

**Comment by brogsitter** [comment]
I know, and he did great. But it would be much easier to have them directly within the collectors map.
