### ISSUE TITLE
Missing item (Random Metal Detector)

### ISSUE THREAD

**Issue by IronJeff80** [jeanropke/RDR2CollectorsMap#346]
Random item, requires Metal Detector
 Found at Cycle 3 6:47PM PST

lat: -44.118897067606305
lng: 153.0078125

https://rdr2map.com?notes=HqZ95DML5WG

I did verify Random Items are displayed and checked all map cycles

**Comment by jeanropke** [comment]
Only on cycle 3?

**Comment by IronJeff80** [comment]
Yes, but I believe it repeats every day
