### ISSUE TITLE
Idea: Monetary value per set

### ISSUE THREAD

**Issue by chrissydewet** [jeanropke/RDR2CollectorsMap#35]
Basically the list on the left that has the "Coins" = > make it "Coins - Set value $XXX"
That way we can make snap decisions what to do

**Comment by Shaftoe62** [comment]
That would be good but then it also would be handy if it would also show the quantity of items in the collection and/or the average value per item in that collection:

![collectionvalues](https://user-images.githubusercontent.com/53898212/66087733-cf674a80-e578-11e9-8fce-83d43cb9f30a.jpg)
