### ISSUE TITLE
Day 1 Chocolate Daisy 

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#354]
Day 1 Chocolate Daisy #11 is missing from the map.
#11 should be at lat -72.43 and lng 115.45

**Comment by jeanropke** [comment]
I messed up the coordinates.
http://prntscr.com/pza4jl

**Comment by Ootat** [comment]
Ah I saw that flower posted somewhere but I’ve not been able to expand out enough to see what it was.
