### ISSUE TITLE
Additional Potential Treasure Location (Map Search Areas)

### ISSUE THREAD

**Issue by IronJeff80** [jeanropke/RDR2CollectorsMap#355]
**Gaptooth Breach**
lat: -112.59383958432872 
lng: 16.69538800686946
lat: -113.53915208432872 
lng: 17.88292216473898
lat: -113.75008958432872 
lng: 18.961078176488932
lat: -111.71883958432872 
lng: 19.6173470532063

**North Ridgewood:**
lat: -97.9765625 
lng: 34.328372869276826
lat: -99.453125 
lng: 33.67210399255946
lat: -100.8046875 
lng: 34.92213994821158
lat: -100.1640625 
lng: 35.73466331938546

**San Luis Shore**
lat: -119.4296875 
lng: 61.45368950373833
lat: -118.859375 
lng: 62.53965824021111
lat: -117.15625 
lng: 63.789694195863234
lat: -116.359375 
lng: 62.484969167151334

**Blackbone Forest:**
lat: -59.7421875 
lng: 70.17985604211933
lat: -61.0546875 
lng: 68.66418744589113
lat: -62.203125 
lng: 71.03925576163016
lat: -63.234375 
lng: 70.49236503103236

**East Watsons:**
lat: -53.75 
lng: 83.98469770197781
lat: -51.2578125 
lng: 84.76597017426039
lat: -53.75 
lng: 86.4691441638364
lat: -53.75 
lng: 86.4691441638364

**Dakota River Bend:**
lat: -59.078125 
lng: 91.44577610318957
lat: -58.5078125 
lng: 92.93800652524929
lat: -57.5625 
lng: 93.73490444697752
lat: -59.0859375 
lng: 94.32085880118946

**Cattail Pond:**
lat: -51.5546875 
lng: 94.86774953178727
lat: -51.9453125 
lng: 95.4849547848905
lat: -52.7265625 
lng: 96.14903638633069
lat: -51.5078125 
lng: 97.48501231393391

**Diablo Ridge:**
lat: -66.0078125 
lng: 93.23455073324975
lat: -67.4296875 
lng: 92.75016180043455
lat: -66.7265625 
lng: 93.89081960996711
lat: -68.390625 
lng: 94.60177755974425

**Burned Town:**
lat: -65.4140625 
lng: 105.59428124476013
lat: -66.0234375 
lng: 105.98491748090142

**Bard’s Crossing:**
lat: -70.7890625 
lng: 99.92224309598862
lat: -68.921875 
lng: 101.89886245086353
lat: -73.3125 
lng: 103.12546023234718
lat: -70.7734375 
lng: 104.11767627214606

**Citadel Rock:**
lat: -60.6171875 
lng: 113.14858042371719
lat: -57.59375 
lng: 112.5470006200596
lat: -57.375 
lng: 114.21111098602151
lat: -58.4765625 
lng: 116.0002249475486

**Cumberland Forest:**
lat: -49.1796875 
lng: 109.57823466473897
lat: -47.9140625 
lng: 110.86733424400524
lat: -49.4140625 
lng: 111.27359592959218
lat: -47.8125 
lng: 113.21896438557579

**Calumet Ravine:**
lat: -28.7890625 
lng: 120.82837871207029
lat: -28.0234375 
lng: 121.6799657068583
lat: -29.0703125 
lng: 122.44561272969523
lat: -30.03125 
lng: 123.07844343224411

**Brandywine Drop:**
lat: -32.0703125 
lng: 152.9770270020809
lat: -32.1875 
lng: 152.36763447370046
lat: -32.53125 
lng: 153.19578329432
lat: -32.125 
lng: 152.78952160873305

**Kamassa River:**
lat: -35.03125 
lng: 149.59411719709732
lat: -36 
lng: 150.26601152326032
lat: -36.625 
lng: 148.62533933146693
lat: -37.1875 
lng: 148.3128303425539

**North Clingman:**
lat: -47.6953125 
lng: 139.82054823424423
lat: -48.8828125 
lng: 140.86745334710287
lat: -49.4453125 
lng: 141.6096621957713
lat: -48.125 
lng: 143.04720354477126

**Southern Roanoke:**
lat: -53.65625 
lng: 152.03946745053202
lat: -54.5546875 
lng: 149.02375570752127
lat: -55.4453125 
lng: 148.7581230669452
lat: -57.4140625 
lng: 150.828495118494

**Bluewater Marsh:**
lat: -71.46875 
lng: 146.5783508464399
lat: -71.4453125 
lng: 147.2111815489888
lat: -73.125 
lng: 148.53934475186918
lat: -73.1953125 
lng: 146.14083826196168

**Bolger Glade:**
lat: -92.1796875 
lng: 135.92992166118444
lat: -91.0859375 
lng: 135.56272359921164
lat: -91.2265625 
lng: 133.50797699710847
lat: -91.8828125 
lng: 134.20330949743996

**Lake Isabella:**
lat: -36.0703125 
lng: 83.53897777949467
lat: -36.328125 
lng: 82.44519631829907
lat: -38.078125 
lng: 83.38272328503817
lat: -38.1796875 
lng: 85.69528980299458

**Comment by IronJeff80** [comment]
If it is helpful, I can post them as I find them, or if you perfer, I can wait till I find all 4 for each location.
**Benedict Point**
Lat: -118.21264863014221
Lng: 29.193328142166138
**Hanging Rock**
lat: -98.26931285858154 
lng: 60.4923357963562

**Comment by jeanropke** [comment]
Just need this locations now:
Hennigan's Stead (Central): 4
North Tumbleweed: 4
O'Creagh's Run: 3
West Hill Haven: 4

**Comment by q1k** [comment]
Are you sure there are 4 in West Hill?
And how would you find all locations?? Isn't it get the treasure there once and that's it??!

**Comment by Ootat** [comment]
I think there 
<img width="911" alt="71553E46-8999-4BBA-9EE1-4DF437C9B6C8" src="https://user-images.githubusercontent.com/56455877/69269251-3b882700-0b96-11ea-9048-8126723cec61.png">
are only 3 in west hill heaven

**Comment by Ootat** [comment]
If you want/need them. I have graphic maps of each of the chest locations for each treasure map location.
