### ISSUE TITLE
What is the timer in the top

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#357]
What is the timer in the top?
At first I thought it might be the cycle timer, but it isn't so.
The daily challenge timer in the game is different (which I think is the cycle timer too).

**Comment by IronJeff80** [comment]
That is when the cycle changes. It is not the same as Daily Challenges. Cycles change at 12:00AM GMT.
Please review the Wiki for additional information regard map functions.
https://github.com/jeanropke/RDR2CollectorsMap/issues/198

**Comment by jeanropke** [comment]
Madam Nazar & Daily Challenges reset at 6:00AM GMT

**Comment by q1k** [comment]
Then I have a followup question about the cycles.
Do the gathered items reset at the start of a new cycle, or do I have to do something else too?
