### ISSUE TITLE
Treasure Locations No Longer Splittable

### ISSUE THREAD

**Issue by singemfrc** [jeanropke/RDR2CollectorsMap#358]
When the individual locations were added the treasure map heading on the left no longer expanded to let us choose which treasures to show and hide. It now only allows show all or hide all. 
The way that worked before was perfect, starting with none and allowing you to select/enable the ones you possesed so that you could see an overview of where all the treasures were that you have and determine where to start and work through the map picking them all up. The heading still has the expand arrow, but no longer expands, so hopefully this was just an accident!

**Comment by IronJeff80** [comment]
Try refreshing, I had this happen a few time over the past few days. Refresh usually solved the issue for me. As for right now, I am able to expand the Treasure Maps list and select accordingly.

**Comment by singemfrc** [comment]
Thanks Jeff, you were correct. Regular loading and regular refreshing didn't change anything but when I forced firefox to redownload all the content, it worked as intended. Probably caused by the changes implemented that werent properly being looked at.

**Comment by q1k** [comment]
You should use CTRL+F5 when reloading to load without cache.
