### ISSUE TITLE
Incorrect item Cycle: day # 2

### ISSUE THREAD

**Issue by INSANOPOTATO** [jeanropke/RDR2CollectorsMap#359]
(https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? Today is day cycle 2 but the map is stuck on day cycle 1

I cannot switch it manually to day cycle 2.
Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by IronJeff80** [comment]
It's been cycle 1 for the past hour

**Comment by INSANOPOTATO** [comment]
I guess I was confused. When I opened the imap the first time it had items
placed differently. I force reset and it is now showing correct placements.

I was more confused when I looked up cycle days and it showed Wednesday as
cycle 2.

Sorry for the error on my part.
