### ISSUE TITLE
Suggestion: inside maps when item is in cave or mine

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#36]
i was experimenting with the description of the nine of wands on day two and figured this might be usefull
![image](https://user-images.githubusercontent.com/1492205/65835335-66b46f80-e2e5-11e9-8db9-7f1fcaf2a45f.png)
no need to rewrite anything just add the <img> tag inside the description

should i keep this or not include it in my next pull request?

**Comment by jeanropke** [comment]
Include it in next pull request.

**Comment by iligalodin** [comment]
will do!
