### ISSUE TITLE
Missing Wildflowers on map

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#362]
There are presently 3 wildflowers shown in the Spreadsheet that as of today don’t show on the map
Day 1 Texas Bluebonnet #10 shown on line 177 of the Random Items Spreadsheet is not shown on the map.
Day 2 Blood Flowers #3 and #4 shown on Lines 194 and 195 of the Random Items Spreadsheet are not showing on the map.
![D4469CC9-38BF-4B6F-B57B-1A7D7C2BB0A1](https://user-images.githubusercontent.com/56455877/69453793-4e336500-0d2a-11ea-88f9-e0fe6d2b57aa.jpeg)

There are four additional flowers not yet reported. 
Day 1 Wild Rhubarb #9 and #10 
Day 2 Blood Flower #5 
Day 2 Agarita #4 
When the cycles come back around I’ll pinpoint their locations. 
Preview
![6DD37937-9CD1-409E-A7DD-C105E23100B6](https://user-images.githubusercontent.com/56455877/69453862-758a3200-0d2a-11ea-8c3b-d3a76f31ec46.jpeg)

The full maps can be seen at
https://imgur.com/gallery/6ZWWQ09

**Comment by Ootat** [comment]
I’m still looking for Chocolate #15 for day 1. I should have it pinpointed on the next day 1 cycle

**Comment by jeanropke** [comment]
Flowers added

**Comment by Ootat** [comment]
Final flower to complete Day 1
Chocolate Daisy #15 
![504C233C-DC2A-4D07-AAD0-33C41B1D4958](https://user-images.githubusercontent.com/56455877/69475393-1b24bc00-0d92-11ea-897b-2b865a89c1cc.jpeg)

And map location

![3D09A86E-E3A6-4203-AE92-A7BA155CD060](https://user-images.githubusercontent.com/56455877/69475401-28da4180-0d92-11ea-9a5b-45f5e29b4027.jpeg)
