### ISSUE TITLE
Last Random Dig sites

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#366]
After reviewing the random sites there appear to be 2 missing.

![688B3655-2B4C-402F-8BF7-5FD843A728CB](https://user-images.githubusercontent.com/56455877/69475560-68a22880-0d94-11ea-843f-c4df0fa69b05.jpeg)

**Comment by IronJeff80** [comment]
{"text": "random_item_198", "day": [1, 2, 3], "tool": "2", "x": "-72.3128", "y": "137.6875"}
{"text": "random_item_199", "day": [1, 2, 3], "tool": "1", "x": "-81.2600", "y": "156.8125"}
