### ISSUE TITLE
 New Spot - Ojeda Rose Gold Bangle - Bracelet

### ISSUE THREAD

**Issue by RabbitHol3** [jeanropke/RDR2CollectorsMap#369]
Cycle 1 Map position

 New Spot - Ojeda Rose Gold Bangle - Bracelet

![image](https://user-images.githubusercontent.com/22034062/69485633-1cd49b00-0df7-11ea-8875-49a48640e0f4.png)

**Comment by jeanropke** [comment]
Random spot #82. Already on map.
