### ISSUE TITLE
3 Coins Card on Van Horn on Day 2

### ISSUE THREAD

**Issue by Kettenknecht** [jeanropke/RDR2CollectorsMap#37]
![B3D6AE80-D35C-4888-83CA-4B76EDFC3B2F](https://user-images.githubusercontent.com/11272523/65838369-b8b7be00-e302-11e9-952d-7e8d174c2d08.jpeg)
![946B6F5F-91FD-4DD8-9789-7F1D9E312975](https://user-images.githubusercontent.com/11272523/65838370-b9505480-e302-11e9-8893-4cab6dc96ed2.jpeg)

**Comment by jeanropke** [comment]
Already on map
![van horn card day 2](https://user-images.githubusercontent.com/6243818/65839980-38d12a00-e2e9-11e9-918c-1475b3be5049.png)
