### ISSUE TITLE
Incorrect item / Missing item Cycle: day 1

### ISSUE THREAD

**Issue by nmbro** [jeanropke/RDR2CollectorsMap#370]
* What day cycle it is?
Day 1
* Coordinates or a clear image of the location
![image](https://user-images.githubusercontent.com/3308346/69487249-964fa600-0e56-11ea-8279-16e5831108fb.png)
![image](https://user-images.githubusercontent.com/3308346/69487253-ad8e9380-0e56-11ea-9866-941c0958a330.png)
```
lat: -92.1796875
lng: 59.9609375
```

* Include the item name
Helena Sapphire Bracelet - Cycle 1

**Comment by IronJeff80** [comment]
Cycle changed to 2 8 minutes before your post

**Comment by nmbro** [comment]
dammit XD
