### ISSUE TITLE
Incorrect item Cycle: day # (not on the map)

### ISSUE THREAD

**Issue by cdragonm** [jeanropke/RDR2CollectorsMap#376]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 3
* Coordinates or a clear image of the location: lat: -44.859375
lng: 146.734375

* Include the item name: Slate Arrowhead

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by cdragonm** [comment]
Applogies, I am new, I see the new item form now. I will use that.

**Comment by jeanropke** [comment]
Random spot #35.
