### ISSUE TITLE
Incorrect item

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#377]
* What day cycle it is? 3
* Coordinates or a clear image of the location
![image](https://user-images.githubusercontent.com/7927176/69572290-1e06f300-0fc4-11ea-8ff6-b9c554fef222.png)
* Include the item name
Ursula Citrine Earrings - Cycle 3
Random Item #88 - Cycle 3

This item is marked twice on the map.
I picked it up with metal detector, there was nothing else there. Item was Ursula Citrine Earrings

**Comment by jeanropke** [comment]
Before removing, I'll check the next cycle if the item exists.

**Comment by q1k** [comment]
I think that it's not random. There is no other Ursula Earrings as far as I can see.

**Comment by IronJeff80** [comment]
It is random on 2 days and static on 1 day
