### ISSUE TITLE
Reloading the page un-hides hidden collections

### ISSUE THREAD

**Issue by Megalex42** [jeanropke/RDR2CollectorsMap#378]
Here is a strange behaviour with hiding and reloading:

* Click the collection name for Antique Alcohol Bottles - the collection will be crossed out and will disappear from the map.
* Reload the page. The collection is no longer hidden

---

* From a non-hidden collection (for example, Antique Alcohol Bottles) expand it with the down arrow and click each item individually to make them transparent on the map
* Reload the page, they are still transparent.
* Click the Antique Alcohol Bottles title, they will all be hidden
* Reload the page
* The collection title has become shown again, and the items are transparent

I think it should work that when you reload the page, hidden collections should remain hidden

**Comment by Megalex42** [comment]
@jeanropke isn't this a bug? was it designed to un-hide on reload?

**Comment by jeanropke** [comment]
Yep. Some categories still disabled by default (random spots, treasures maps, etc...)

**Comment by Megalex42** [comment]
Thanks man! this makes the application quite smooth!
