### ISSUE TITLE
RDO Map, 3rd Panther location

### ISSUE THREAD

**Issue by IronJeff80** [jeanropke/RDR2CollectorsMap#381]
Been playing for a year and never found a Panther here. It is also not on any heat maps I have found.
Video verification: https://youtu.be/z6EtO3Y8OuY
lat: -74.50125791328237
lng: 139.703125

**Comment by jeanropke** [comment]
All heat maps uses the same source: RDR2 Guide.  Bat has a lot of locations missing on the guide.

Added this new location.
