### ISSUE TITLE
Incorrect item? 

### ISSUE THREAD

**Issue by EverettLawson** [jeanropke/RDR2CollectorsMap#384]
Crude Arrowhead - Cycle 1 location produced an "1800 Half Dime" today (Nov 26, 19). Not sure if this is a shift at Rockstar or an incorrect definition in the JSON.
Edit: This is the Mattock Pond location

**Comment by jeanropke** [comment]
I got the right item.
There is a random item next to Crude Arrowhead.

**Comment by q1k** [comment]
Are you sure you've picked up the right one?
There's two items there:
![image](https://user-images.githubusercontent.com/7927176/69679868-88de2a00-10a9-11ea-889e-400d9173961c.png)

I can't verify this, since I've already picked up that today
