### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by Blazer94** [jeanropke/RDR2CollectorsMap#385]
The 1792 coin is bugged. It will not let me collect it no matter what cycle its on. i do not have 10-10 of the coin. When i go to it it just buzzes and doesn't give me dig option. can some one please help me?

**Comment by IronJeff80** [comment]
Game bug. We cant help. Try clearing cache or reinstall.

**Comment by q1k** [comment]
I had multiple times now a nest not appear in the tree

**Comment by Ootat** [comment]
Scope the egg and shoot it. If you can hit it with the varmint rifle or a small game arrow it may fall out.

**Comment by q1k** [comment]
@Ootat nope, I was shooting it multiple times, it just makes a sound like a vase breaking and nothing happens. It's still glowing, but stuck in the middle of the tree and can't get it.
