### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by tysfergus** [jeanropke/RDR2CollectorsMap#386]
I go to the location for the coin and my metal detector does not light up at all at any of the places then when i went to a alcohol bottle location it gave me a coin

**Comment by IronJeff80** [comment]
Alcohol bottles are out in the opened and cannot be replaced by coins. Coins must be dug up. Make sure you are using the correct map cycle. Refresh the page

**Comment by tysfergus** [comment]
Eveything is in the wrong place dude i tried like 5 things so far and nothing
