### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#388]
Today (cycle 2) I couldn't find 3 items.
Now, I don't know if this was a game bug that the items never spawned or if Rockstar has actually moved them.. but here goes.

The items were:
- Eagle Egg - Cycle 2 (In a tree. Shoot down with varmint rifle or bow using small game arrows.) (lat: -72.1796875 lng: 76.6875)
- Spoonbill Egg - Cycle 2 (In a tree. Shoot down with varmint rifle or bow using small game arrows.) (lat: -85.71875 lng: 143.234375)
- Five of Wands - Cycle 2 (In the bookshelf in the kitchen.) (lat: -48.3125 lng: 114.75)

I didn't have 3 items left of those so I couldn't use a map to check if those were actually moved.
I guess for next time I could just use a map when there's 3 more left to find.

**Comment by Ootat** [comment]
R* Has not moved spawn locations.
There are five things that you can check Or do.
Verify that you aren’t carrying the max of those items.
Verify that you are on the current cycle by refreshing the map.
Move some distance away from the item then come back to it.
Switch server and revisit the location.
Close the game and your shut your system completely down, then restart system and then clear the system/game cache.
