### ISSUE TITLE
Checklist of collectibles

### ISSUE THREAD

**Issue by fejkb** [jeanropke/RDR2CollectorsMap#39]
It would be nice if there was some list of items available where you could choose only what you're missing and show only these collectibles on the map

**Comment by jeanropke** [comment]
Use the search:
Eg:
`five of c;six of pe;eagle eg;new guine;1800 half`

**Comment by fejkb** [comment]
Nice. Good enough for me, just it might not be that intuitive for casuals

**Comment by chrissydewet** [comment]
on the left where the arrow opens the menu. If you click the name have a drop down box with the days list of say coins- 1800, and so forth. Then in that list if you tick it removes it from the map.

**Comment by iligalodin** [comment]
nice suggestion, might look into it

**Comment by Mr-Schickadance** [comment]
Yes I thought of this as well. I have made local changes to the code on my computer but I am not that familiar with git or GitHub and am not an advanced developer. The way I implemented this on my local copy was by making a drop down menu from the top of the screen that lists all of the collection sets using grids. When you click on an item in the menu it changes color and appears on the map. The way it works is that each item has an element to click on in the menu and each of these elements is connected to the respective item in the items.json file. The code loops through the markers and finds the one that has the same name as the item in the json file AND has the same day and then makes it appear on the map (so "Ace of Cups" where day = 2 for example). Here is the function:

`function ShowCollectable(elem) {

    if ($(elem).hasClass('onmap')) {
        $(elem).toggleClass('onmap');
    }

    else {

    var elem_name = elem.getAttribute('name');

    $(elem).toggleClass('onmap');

    $.each(markers, function (key, value) {
        if (value.day == day && value.name == elem_name) {
            var Collectable = L.marker([value.x, value.y], {icon: L.AwesomeMarkers.icon({iconUrl: 'icon/' + value.icon + '.png', markerColor: 'day_' + value.day})}).bindPopup(`<h1> ${value.name} - Day ${value.day}</h1><p> ${value.desc} </p><p class="remove-button" data-item="${key}">Remove/Add from map</p>`) ;
            visibleMarkers[key] = Collectable;
            markersLayer.addLayer(Collectable);
        }
    });
    }
};`

In the html file I have code such as:
`<div class="right-side-menu">
    <h2>Collectables</h2>
    <div class="hide-show-container">
        <a href="javascript:void(0);" onclick="hideall()">Hide all</a>
        <a href="javascript:void(0);" onclick="showall()">Show all</a>
    </div>
    <div class="grid-container">
        <div class="set-title">Cups</div>
        <div class="set-title">Swords</div>
        <div class="set-title">Wands</div>
        <div class="set-title">Pentacles</div>
        <div class="set-container">
            <span class="set-item" onclick="ShowCollectable(this)" name="Ace of Cups">Ace</span>
            <span class="set-item" onclick="ShowCollectable(this)" name="Two of Cups">2</span>
            <span class="set-item" onclick="ShowCollectable(this)" name="Three of Cups">3</span>`

The key is that the "name" of the element exactly matches what is written in the items.json file. I see that the methodology has changed. It's no longer "name": "Ace of Cups" but rather "text": "cups_ace" This isn't a big deal so long as the developer knows this before building out the name attributes in the html span elements.
![RDR2Map](https://user-images.githubusercontent.com/55929247/65900449-06c0d600-e384-11e9-8ea7-b9ce633848f5.png)

**Comment by jeanropke** [comment]
I started working on checklist.
![checklist](https://user-images.githubusercontent.com/6243818/66224168-9d0a3a00-e6ab-11e9-98a4-e8faa9fcd277.png)

**Comment by Shaftoe62** [comment]
Yes!

**Comment by Shaftoe62** [comment]
I see this is done now. Fantastic!
