### ISSUE TITLE
Auto count collected items, and mark uncollected collection item

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#390]
The idea is to have a counter for each collection, and as we tick the item as collected it would add into storage. Then when cycle changes we could focus only on the rest of the items.
Basically if the five of wands was collected and marked as collected, that card won't be on focus for next time until the rest of the items are gathered.

Focus could look something like this:
![image](https://user-images.githubusercontent.com/7927176/69595436-d1410d80-0fff-11ea-9f95-92da8bd7326c.png)

Other cycles can have a different color.

I guess this also adds towards issue #235 

Whenever you have the time.. This would be much appreciated.

**Comment by Ootat** [comment]
You do understand that you can turn off the daily reset. That way only the items that you still need to collect carry over to the next cycle.

**Comment by dlldldl** [comment]
I like this suggestion, and the initial implementation just committed is really good.
Some additional suggestions: 
1. Have an option to show only items below certain count in each category. I usually keep everything at 5, or 8 for arrow heads and not selling them. 
2. Merge flowers and eagle/hawk eggs properly, so there is only one count for each kind not each location.
3. Make it possible to modify the count from list view. 
4. Option to turn off auto increment and decrement when making item transparent, not transparent.

**Comment by q1k** [comment]
A few problems I've found with the current implementation.
When the storage number is higher than zero, when clicked on the item to reveal the popup, the number is still 0.
Also, if the amount of an item is already at max, the item should be faded out (but still be distinguishable from other collected items, since it's still possible to get that one via selling).
Which brings me to the next point. Have a collection sold button which will decrease all items in the collection by 1, and reveal any unclaimed items (that were 10/10 before sell)

**Comment by q1k** [comment]
Another issue with this is the flowers, currently every flower has it's own counter which is not ideal.. we can't have 100 daisy flowers, can we?

**Comment by jeanropke** [comment]
I'm closing this issue. If need something new, open another one.
