### ISSUE TITLE
random item #195

### ISSUE THREAD

**Issue by Ootat** [jeanropke/RDR2CollectorsMap#391]
Needs verification.
I’ve gone there on the thee cycles and have yet to detect anything there

**Comment by IronJeff80** [comment]
Definitely there. I pick it up daily as I pass through Caliga Hall. I'll
run by now and grab a screenshot/video

**Comment by IronJeff80** [comment]
https://youtu.be/pBjgcw9MAkY

**Comment by Ootat** [comment]
You picked up #192 not 195. Q195 is under Bards Crossing at the end of the finger island in the middle of Dakota River

**Comment by Ootat** [comment]
![FD8184D7-2429-4981-BA88-797A2D6ADBFA](https://user-images.githubusercontent.com/56455877/69843128-c23ea300-122b-11ea-8ae5-bda2b2f76534.jpeg)

**Comment by IronJeff80** [comment]
Sorry about that. You are correct. I have never seen anything on that island except for a random encounter Bird egg. Fox/goose, but that was slightly north.

**Comment by IronJeff80** [comment]
That was reported by @q1k in issue #337. I remember scratching my head about that one.

**Comment by q1k** [comment]
I'm sorry if I was wrong, I was going off memory on that one. It might have been a little north or south, I can't be sure, I posted this a few days after I picked it up..

**Comment by dlldldl** [comment]
I never anything at that location.
