### ISSUE TITLE
Incorrect item Cycle: day #1

### ISSUE THREAD

**Issue by Williamo15** [jeanropke/RDR2CollectorsMap#392]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 1
* Coordinates or a clear image of the location lat: -108.84375 lng: 28.1796875
* Include the item name Emmelin Coral Earrings

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Item is on the map.
http://prntscr.com/q4bow8

If the item is not on the location in-game, was a game bug
