### ISSUE TITLE
4th location for east watson treasure map

### ISSUE THREAD

**Issue by VileAce** [jeanropke/RDR2CollectorsMap#394]
4th location for east watson treasure map (you have 3)

lat: -52.359375
lng: 87.6796875

https://i.imgur.com/UMMOOOX.png
https://i.imgur.com/uYB2ciD.jpg
https://i.imgur.com/zmpOCZO.png

btw excellent resource and very well written web app

**Comment by IronJeff80** [comment]
@ jean, that location is confirmed. I just had a look at the original dump and realized I duplicated the 3rd location. The third may be listed twice.
lat: -53.75 
lng: 83.98469770197781
lat: -51.2578125 
lng: 84.76597017426039
**lat: -53.75 
lng: 86.4691441638364**
**lat: -53.75 
lng: 86.4691441638364**
