### ISSUE TITLE
Poss mislabel? Day 3 1792 Liberty Quarter

### ISSUE THREAD

**Issue by singemfrc** [jeanropke/RDR2CollectorsMap#4]
In this spot just west of the Dakota River on day 3 I dug up the Abello Ruby Bangle Bracelet where the map marked a 1792 Liberty Quarter. Nothing else should be in that spot on other days, so it's not a wrong day error.
PS Thank you SO MUCH for this map it has saved me countless hours!!

**Comment by jeanropke** [comment]
Fixed. Thanks.
