### ISSUE TITLE
Incorrect item on cycle 1

### ISSUE THREAD

**Issue by Jordy217** [jeanropke/RDR2CollectorsMap#401]
The collector map is showing the spoonbill egg location for cycle 1, however it's not in it's cycle 1 location. Tried to open a collector map hoping it'd work but no luck. I've refreshed the map and restarted the game to no avail. also tried the cycle 2/3 locations with no luck as well

**Comment by jeanropke** [comment]
Try changing session or clearing cache.

![sponbill egg](https://user-images.githubusercontent.com/6243818/70235180-25a36600-1741-11ea-9361-a7e075d60c98.jpg)
