### ISSUE TITLE
Suggestion: Allow Fast Travels to be reflected in custom routes

### ISSUE THREAD

**Issue by SSSidekick** [jeanropke/RDR2CollectorsMap#407]
This is not related to any existing problem that I am aware of... I purely want to make a suggestion. 

Is there any way that you can allow fast travel points to be included in custom routes? 

Here is an example of what I mean: 

There are times when I only need a couple of items from each collection to complete a full set. This often results in small clusters of items in a small general areas, with large gaps of (for me) empty space. Rather than ride across these empty areas, I often fast travel as close as possible, to save time. 

For me, it would be really great to be able to include fast travel points when creating my custom route in this type of situation. Rather than a solid line, travel between two FT posts could instead be represented by a dashed line. 

While, yes, I could always select an item that is right next to the fast travel post that I want to go to, but there are times when there are no items near there (Wapiti, Emerald Station and Colter are a few good examples of this) and even selecting the closest does not accurately reflect the fact that I am planning on fast traveling to that location. A dashed line directly to the FT post would be way more beneficial... 

I feel that this would be a good feature to offer for those of us trying to complete collections!

Thanks for all your hard work!

**Comment by jonathonbarton** [comment]
Also, with a feature like this, it would be most excellent if a Dynamic Route used a best guess of travel time between two points and also estimated time using two FT Posts and used the faster. 
i.e. if you have one arrowhead in New Austin and one egg to collect in Bayou Nwa left to collect, Solid line to Tumbleweed FT, dashed line to Saint Denis, Solid line to the Bluewater Marsh.

**Comment by Senexis** [comment]
This is a feature in the path finder.
