### ISSUE TITLE
Missing dog encounter

### ISSUE THREAD

**Issue by signalrunner1** [jeanropke/RDR2CollectorsMap#408]
Sadly I don't have a screenshot with that white marker on minimap but I did a screenshot near the treasure with that dog.
So that white marker was at lat: -46.328125 lng: 110.8515625
https://i.imgur.com/aBp9Qtx.png - that's me standing near that treasure
https://i.imgur.com/xfxYcvL.png - red dot is my position on that screenshot and red marker is where that dog was before

**Comment by IronJeff80** [comment]
I usually just save a video and go back to watch for the location after the
fact.

**Comment by IronJeff80** [comment]
Here are the coordinates for the White Blip:
{"text": "dog_encounter_08", "x": "-46.3954", "y": "110.7494"}

**Comment by Ootat** [comment]
I’m a little late but
I can verify that location.
![912E7134-2BB2-4599-AFFF-DF1DE897D5BC](https://user-images.githubusercontent.com/56455877/70346806-c61e8680-1824-11ea-9521-1d1265f86702.jpeg)

And add another. 
It’s at -77.335 / 87.695

![5366DFC1-DA17-4008-8FD1-A47DC843A6C3](https://user-images.githubusercontent.com/56455877/70346824-cf0f5800-1824-11ea-8aa7-6f8465af84b4.jpeg)
