### ISSUE TITLE
Random Item #3 - Cycle 3

### ISSUE THREAD

**Issue by kittrellbj** [jeanropke/RDR2CollectorsMap#409]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 3
* Coordinates or a clear image of the location: https://imgur.com/EghlMtN

lat: -117.34375
lng: 18.90625

* Random Item #3 - Cycle 3

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by IronJeff80** [comment]
If it isn't there, it is a game bug or you collected it within the past 24 hours.

**Comment by kittrellbj** [comment]
It's there, it's just about an inch to the left in game from where it is showing on the collector map.

**Comment by IronJeff80** [comment]
Ok. Ill grab precise coordinates

**Comment by Ootat** [comment]
There’s another cycle 3 random item that’s a bit off.
Item #62 is shown between the hillock and the Railroad Track
When actually it on top of the hillock.

![2FCDD0E8-3B8E-489A-862F-552B70DD6810](https://user-images.githubusercontent.com/56455877/70347713-c1f36880-1826-11ea-82e8-882f35eced30.jpeg)

**Comment by dlldldl** [comment]
Random Item #3 Verification screenshot and cords:
![rand3](https://user-images.githubusercontent.com/58512865/70373747-053ded80-18a0-11ea-9d7f-720fdc0b8aa7.png)
lat: -117.4453125
lng: 18.9140625
