### ISSUE TITLE
Every single item is in the wrong place

### ISSUE THREAD

**Issue by jdunn85** [jeanropke/RDR2CollectorsMap#41]
I have tried experimenting with all 3 days for the collector map and NOTHING is in the right place. Completely off, not even close!

**Comment by iligalodin** [comment]
for certain items you need a shovel and other a shovel and metal detector. just for test could you go to the five of cups or any other tarot card on the map, if those are not there you might want to actually register as a collector over at madam nazar

**Comment by jdunn85** [comment]
I have all the tools including the metal detector and the refined binoculars. The items simply do not appear anywhere near where the map shows, on day 1, 2, or 3. And the places collectibles are being found are not listed on any of the maps here. Not even close. This was working just last night.

**Comment by jdunn85** [comment]
Any suggestions?

**Comment by iligalodin** [comment]
currently i do not know whatthe issue could be, this is the first time i've heard about this bug. 

are you using the beta map? 
what browser are you using?
what's your os?

**Comment by githb123** [comment]
I'm using this link and so far only a couple of items were different. But there was always something there in the spot according to the map.
https://jeanropke.github.io/RDR2CollectorsMap/index-beta.html

I also had some cases items were not listed on the map.

I'd sasy it's work in progress and we need some time untill it's complete. Also Rockstar seem to give different items to different players in the same spot. I heard that if you have multiple the same items the game won't give any more of these. Like e.g. 7 (or whatever number) of blood flowers. You won't get the next one blood flower anymore untill you sell.

**Comment by jdunn85** [comment]
I'm using google chrome and the auto refresh lists the current day at day 2, I am not using the beta version. It was working fine last night. I guess I will keep trying and maybe eventually something will be in the spot the map here shows but so far...nothing.

**Comment by iligalodin** [comment]
could you test the beta map and see if that works?

**Comment by jdunn85** [comment]
I will yes stand by

**Comment by Teddyrubskin** [comment]
I had this happen also.. It seems to be fixed today. If It happens again Ill be sure to report it.

**Comment by jdunn85** [comment]
testing the beta version now. I also noticed the main map auto refreshed to day 3 let's see if either map works...

**Comment by jdunn85** [comment]
I don't know what changed, but ever since the website auto refreshed to day 3 (even though I had tested the day 3 map earlier unsuccessfully) it seems to be working! I just got back on and suddenly the new map on the website that auto refreshed seems accurate now. Thanks!

**Comment by jeanropke** [comment]
If this problem occours again, create another issue. 😊
