### ISSUE TITLE
sorry new here rd2 online i found a naclace on small cliff at these cords, lat: -39.484375 lng: 146.34375  cycle 1

### ISSUE THREAD

**Issue by gearbox22555** [jeanropke/RDR2CollectorsMap#415]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeanropke** [comment]
Hey, welcome to RDO.
This item is already on map as Random Item #165.

![random item 165](https://user-images.githubusercontent.com/6243818/70377104-38f43400-18ef-11ea-8581-49b49ee01e02.png)
