### ISSUE TITLE
Sell weekly collection

### ISSUE THREAD

**Issue by Ralek** [jeanropke/RDR2CollectorsMap#421]
The new inventory system seems to be working well (although there's no easy way of setting up your initial inventory easily).

It would be really useful to have a way to quickly "sell" a weekly collection. Right now you have to edit the amount manually on each of the collection items map pins.

**Comment by MichalD96** [comment]
@Ralek  Is that option is still needed? it is not the problem but i added highlighting weekly items on green in menu, and in new inventory system you can adjust items count from menu.
We don't want to add so many controls in menu because menu become unreadable

**Comment by Ralek** [comment]
Not needed anymore. This was opened before there was a way to adjust inventory from the filter menu. It's still somewhat cumbersome, but liveable.
