### ISSUE TITLE
Improved inventory features

### ISSUE THREAD

**Issue by Senexis** [jeanropke/RDR2CollectorsMap#423]
**Describe the solution you'd like**
Currently, the way it seems to be intended is to use each item popup to manage the current inventory you have. However, there is no way to increase or decrease your inventory from the list of items in the sidebar. Adding a "-" and a "+" button on either side of the amount of items you have in the sidebar would be more useful than to have it on the popup of each item, as that way you can more easily manage your inventory.

My suggestion thusly is to add an option to hide it from the popups (as I really think it's useless there) and instead show it in the sidebar. Or at the very least add it to the sidebar as that doesn't seem to be a feature as of now (I am on mobile so if it's not showing up that should be considered a bug).

The reason I think it's useless in the individual item popups, is that unless you are using a bug in the game, it's not possible to encounter multiple items in the same location. That means that the option to increase or decrease doesn't do anything and the only useful option is to remove it to the map as it was before.

**Comment by Ootat** [comment]
Side bar 
Have an -/+ option to change your inventory # 
By selection a collectables name you show or hide it on the map.

**Comment by zedvash** [comment]
this will be really helpfull

**Comment by Senexis** [comment]
Add the "-" and "+" buttons.
