### ISSUE TITLE
Cook Fires

### ISSUE THREAD

**Issue by billotronic** [jeanropke/RDR2CollectorsMap#424]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A layer for the map to display public cook fires

**Describe alternatives you've considered**
lookin on the net? lol

**Additional context**
nope. This map is amazing and thank you for all the hard work. I will gladly volunteer getting coordinates for fires if they are not already known.

**Comment by q1k** [comment]
https://jeanropke.github.io/RDOMap/

**Comment by jeanropke** [comment]
Campfires, gang hideouts, defend campsites, rescues are on [RDOMap](https://jeanropke.github.io/RDOMap/)

**Comment by billotronic** [comment]
I wish you folks could of seen my head EXPLODE. Sorry for the bother, but a huge thanks for the link and the work!

**Comment by q1k** [comment]
I knew about the RDOMap, but it would be nice if we had both in one place. Perhaps it's too much work, thus not merged yet?
