### ISSUE TITLE
Selecting "Chocolate Daisy" in the Collectibles tab does not remove the mark for all Daises.

### ISSUE THREAD

**Issue by Fraastos** [jeanropke/RDR2CollectorsMap#425]
Whenever I try to select Chocolate Daises in the Collectibles tab to unmark all of them on my map, it only deselects some and leaves others selected. Furthermore, if you keep clicking on the Chocolate Daises in the Collectibles tab, it will change the number of Daises shown on the map which doesn't seem intended at all. Other items don't do this when deselecting them from the Collectibles menu (they either show none or all).

Note: Everything was working fine before the increase and decrease number values was added so maybe that has something to do with it.

**Comment by jeanropke** [comment]
Yes, it's buggy with flowers and eggs, but if you increase to 10, will remove them
