### ISSUE TITLE
Coordinate slightly offset Random Item #169

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#427]
lat: -37.296875
lng: 155.09375

The current labeled location is on top of hill. I took the screenshot too late, and it was an arrow head so no box appeared. but here is the screenshot anyways.
![rand 169](https://user-images.githubusercontent.com/58512865/70403646-52c77100-19ec-11ea-9e25-fca39abe1219.png)

**Comment by jeanropke** [comment]
Updated. Thanks.
