### ISSUE TITLE
All Items Not Showing Up On My Map

### ISSUE THREAD

**Issue by elstrecho** [jeanropke/RDR2CollectorsMap#428]
For some reason on google chrome all the items aren't showing up on my map.  For example there are 8 bracelets but only 4 show up:
https://gyazo.com/fe73a02d7201b9748e526b9b267fa8a9

2 earrings
https://gyazo.com/cf4f57949d5248644ab94146184f0ca2

6 necklaces
https://gyazo.com/64da7ce1b6c619a9c1fbb091a32ed86d

It happens for most categories.  In firefox it works fine.  I tried hide all then show all, refreshing and restarting.  Happens on all days.  Any advice?

**Comment by jeanropke** [comment]
Can you show if there is any error on Chrome console?
Press F12 or Shift + Control + i

**Comment by elstrecho** [comment]
No, but I think I figured it out.  Tool type was not set to all.
