### ISSUE TITLE
Madam Nazar is always missing?

### ISSUE THREAD

**Issue by pandemicland** [jeanropke/RDR2CollectorsMap#435]
I’m not sure if I’m posting this correctly. I am sorry if I am. But my map has not shown madam nazars location for me in over a month.

**Comment by jeanropke** [comment]
Is Madam Nazar option enabled on menu?
![Screenshot_1240](https://user-images.githubusercontent.com/6243818/70551637-a8b82800-1b56-11ea-9c87-c69ae109bc38.png)
