### ISSUE TITLE
Random Markers reset change

### ISSUE THREAD

**Issue by AdamNortonUK** [jeanropke/RDR2CollectorsMap#436]
Since the Random items only reset 24 hours after you pick them up and not at the time the known collectibles reset, is it possible to have a separate reset for the random markers so that they stay in the collected state for either 24 hours after being marked on the map or just reset manually using the sub menu.

Reason for this is when the daily reset occurs, the random markers are reset too, so isn’t useful if you have to wait for the game to reset the random marker, so it’s easier to know which random items have been collected after a daily reset.

I hope this make sense?

**Comment by Senexis** [comment]
Changed since the moonshine update, random items seem to work the same as other items now.
