### ISSUE TITLE
[missing] Beaulieux Diamond Ring Day 3 Location [pic&video]

### ISSUE THREAD

**Issue by Teddyrubskin** [jeanropke/RDR2CollectorsMap#44]
Tumbleweed

http://prntscr.com/pcn96g

https://youtu.be/10w7kbLm7gQ

**Comment by jeanropke** [comment]
This place had a 'Josephine Pearl Earrings'
https://www.youtube.com/watch?v=IkaZeEKO0hE

**Comment by Teddyrubskin** [comment]
Oh, randoms...

**Comment by iligalodin** [comment]
oh wait there are random item spots?
