### ISSUE TITLE
Incorrect item: Wild Flower Chocolate Cycle 2

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#444]
Chocolate Daisy Flower #9 - Cycle 2
I went back multiple times there and the flower didn't spawn.
Later I gathered all the rest of the flowers, and now with supposedly 3 left, I can't use the Flower Map.

**Comment by jeanropke** [comment]
The flower is there. Probably another game bug.

![ELhVzjHW4AAkmV3](https://user-images.githubusercontent.com/6243818/70642563-2abf5400-1c1e-11ea-964d-f7339aed247a.jpg)
