### ISSUE TITLE
Utilities sub-menu

### ISSUE THREAD

**Issue by AdamNortonUK** [jeanropke/RDR2CollectorsMap#446]
Just a small suggestion, perhaps this menu should now be an expandable sub-menu like the collection items since it's now has a lot of options to enable map markers, so that there isn't so much scrolling to get to the settings and inventory options at the bottom of the sub-menu.

Furthermore, the settings and inventory options could also perhaps change to a expandable sub-menu too, so that there is less scrolling is required when opening the sub menu.

**Comment by Senexis** [comment]
The menu has undergone a pretty big overhaul since this issue and I've just now moved random encounters to a sub-category. All that's resulted in a much more concise menu which is easier to scroll through, which is the underlying cause of this issue.
