### ISSUE TITLE
[missing] Pilgrim Moonstone Ring Day 3 Location [pic&video]

### ISSUE THREAD

**Issue by Teddyrubskin** [jeanropke/RDR2CollectorsMap#45]
Video Link, Pic in video.
North of Tumbleweed
https://youtu.be/6py4m3iMMws

**Comment by jeanropke** [comment]
This location had '1796 Halfpenny Coin' for me.
Probably a spot for random items.

**Comment by Teddyrubskin** [comment]
Ok thank you.
