### ISSUE TITLE
Minor offset of Random Item 183, 184 and 185  

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#451]
Random Item 183
![rand183](https://user-images.githubusercontent.com/58512865/70795913-d3240400-1d55-11ea-8f44-35679795a67e.png)

lat: -77.7578125
lng: 130.328125

Random Item 184
![rand184](https://user-images.githubusercontent.com/58512865/70795857-a53ebf80-1d55-11ea-9346-d86073306aa7.png) I took the screenshot too late, but the location is there.
lat: -79.984375
lng: 129.125

Random Item 185
![rand185](https://user-images.githubusercontent.com/58512865/70795806-83ddd380-1d55-11ea-96f0-9124fa4d989a.png)

lat: -82.5
lng: 126.7578125

**Comment by jeanropke** [comment]
Locations updated. Thanks
