### ISSUE TITLE
Collector Items not in the mapped locations

### ISSUE THREAD

**Issue by MachoBears** [jeanropke/RDR2CollectorsMap#452]
I have tested this with several items since the most recent update.

Both the Queen of Pentacles Tarot Card and the Tortoiseshell Comb are both found in the Heartland Oil Fields now, as opposed to their usual location on the map.

I believe Rockstar has switched locations for all items. The Page of Swords on Cycle 3 was not in the fields, nor was the Sterling Tooth Earrings up in the location provided.

**Comment by atomvova** [comment]
After update the treasures locations has been changed with the new randomized  code script. Unfortunately jeanproke map is not actual anymore. Thank's to all team for the great job, but the party is over now :(

**Comment by Lumi83** [comment]
since the update items are not at the locations on the collector map. its so sad as so much work has went in to this map.

**Comment by lavellj12** [comment]
Damn... thanks for everything tho and the people who helped create this!
