### ISSUE TITLE
Update reset cycle order

### ISSUE THREAD

**Issue by Ralek** [jeanropke/RDR2CollectorsMap#453]
Moonshiner update reset the cycle back to 1, instead of 3. Should be an easy fix.

**Comment by GabrielBallardin** [comment]
> Moonshiner update reset the cycle back to 1, instead of 3. Should be an easy fix.

No my friend, putting in cycle 1 does not solve the problem, already tested the positions in cycle 3 and cycle 1 and nothing has changed, remains unpredictable.

**Comment by Lumi83** [comment]
Ive tested them all too... and it didnt just reset to cycle 1. Im just hopeing they added a 4th cycle and the other 3 are fine

**Comment by Ralek** [comment]
Yeah. I jumped the gun. I tested 5 locations on cycle 1 and they checked out but now I've found fixed collectibles in locations not covered by any of the cycles. 
Guess they scrambled the locations and added some new ones.

**Comment by GabrielBallardin** [comment]
I hope you have added more cycles and not modified the current ones.

**Comment by RedPotato56** [comment]
Five cent coin from 1792

![rdom](https://user-images.githubusercontent.com/58853618/70806046-b79f1480-1dba-11ea-82c5-14ea7399785e.PNG)
![rdo](https://user-images.githubusercontent.com/58853618/70806053-bec62280-1dba-11ea-9c18-78d618696fbf.PNG)

**Comment by GabrielBallardin** [comment]
> Five cent coin from 1792
> 
> ![rdom](https://user-images.githubusercontent.com/58853618/70806046-b79f1480-1dba-11ea-82c5-14ea7399785e.PNG)
> ![rdo](https://user-images.githubusercontent.com/58853618/70806053-bec62280-1dba-11ea-9c18-78d618696fbf.PNG)

what?

**Comment by Ootat** [comment]
This is a known static location that yields a randomized item.
