### ISSUE TITLE
Red Dead Redemption 2 collection day change

### ISSUE THREAD

**Issue by RedDead2DM** [jeanropke/RDR2CollectorsMap#454]
Someone could corroborate if with the last update the collections changed, I am trying to find the rings and they are not in cycle 3 which is supposed to be Friday and Monday and now is in cycle 1

**Comment by IronJeff80** [comment]
Everything changed

**Comment by Ootat** [comment]
Every thing changed.

Each collectable set has been shuffled to different days?

Or there are new static locations for collectables within each set?

**Comment by RedDead2DM** [comment]
For now and for me, Is just the cycle only change, I get the ring, coin and pendant in the same spot on cycle 1. (friday Cycle 3)
