### ISSUE TITLE
Does every item location is changed after update? 

### ISSUE THREAD

**Issue by johnny071518** [jeanropke/RDR2CollectorsMap#455]
Now is day 3.
But I cannot find anything when I am at location.
I tried five location. But all is not at location.
Is everything ok? or just I set wrong wetting

**Comment by IronJeff80** [comment]
Everything is changed

**Comment by johnny071518** [comment]
Thank for your instantly cmd. And I find  "Tarot Cards - Two of Cups"  in VALENTINE station's outside bench in Day 3

**Comment by Dexterin0** [comment]
A few will be at the locations, or replacements, it's not enough for me anymore now though. Too bad just discovered this 2 days ago and was on my way to 66 for the horse, haha. It was the best way. Rockstar wants to make this a grind sooooo badly.

**Comment by jbunce34** [comment]
im sure the person knows. maybe its only jewelry and coins so far i cant find high value items in said spot

**Comment by Dexterin0** [comment]
As it took loads of your time to finish collections for me they could have left them where they are, it was the only real rewardable thing when you were fine with putting in some time. Without positions it's not worth the effort.

**Comment by Updowntheroad** [comment]
Wil map be fix??

**Comment by ThatKasper** [comment]
> Now is day 3.
> But I cannot find anything when I am at location.
> I tried five location. But all is not at location.
> Is everything ok? or just I set wrong wetting

Looks like R* may have just added a 4th Cycle. Be patient, we'll help Jean find them all & the map will no doubt be updated ASAP.

But thankfully I managed to collect 3 whole  sets of every collectible before this morning!

**Comment by Dexterin0** [comment]
Will contribute everything I find as well. Let's hope it's a 4th cycle. 
Kasper I already did some extra hours, thought about finishing the rest as well but didn't. Stuck with one last sword card now and 2 last flowers. hehe
