### ISSUE TITLE
two of swords tarot card

### ISSUE THREAD

**Issue by Jeph91** [jeanropke/RDR2CollectorsMap#456]
![Red Dead Redemption 2 Screenshot 2019 12 13 - 15 26 17 65](https://user-images.githubusercontent.com/58854297/70807477-ebc80480-1dbd-11ea-9807-bbfb7ea57438.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 15 25 52 35](https://user-images.githubusercontent.com/58854297/70807478-ebc80480-1dbd-11ea-8344-1567dd147ef7.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 15 26 00 46](https://user-images.githubusercontent.com/58854297/70807480-ebc80480-1dbd-11ea-8d54-45d6706170ec.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 15 26 12 94](https://user-images.githubusercontent.com/58854297/70807481-ec609b00-1dbd-11ea-9bce-5667ef0fff2e.png)

**Comment by Updowntheroad** [comment]
What now when wil map be fix

**Comment by Jeph91** [comment]
> What now when wil map be fix

I'm sorry, but the community must now begin to rewrite the map, i fear it may take months, a year max.

**Comment by Updowntheroad** [comment]
What omg it take that long

**Comment by Fraastos** [comment]
I mean we don't know if they edited all cycles or just added a 4th. If it's the former, then unfortunately, it will take way longer.

**Comment by jeanropke** [comment]
Item added
