### ISSUE TITLE
New collectible items locations

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#457]
As I find them I'll post here. Sorry if I duplicate some items or if it's already been reported.

Since I don't know which cycle it should be now, I'll just write the date.

### **Dec 13**
Five of Pentacles
`lat: -69.25
lng: 136.5`
In the shack, on the table

Tortoiseshell Comb
`lat: -54.7734375
lng: 119.328125`
In the Northern tent, in the chest

Queen of Pentacles
`lat: -54.7578125
lng: 119.9140625`
(https://i.imgur.com/wNcWpMr.png)

Page of Cups
`lat: -50.4375
lng: 123.3125`
On top of the fireplace

Ten of Wands
`lat: -69.828125
lng: 130.96875`
North side of the house, on the bench on the porch 

Six of Swords
`lat: -69.9140625
lng: 137.828125`
On the window sill

Eight of Cups
`lat: -72.859375
lng: 144.171875`
On the table on the porch

Goat Hairbrush
`lat: -75.53125
lng: 145.796875`
In the house in the back on the bench

Five of Swords
`lat: -59.5234375
lng: 125.296875`
On the table

Nine of Cups
`lat: -55.703125
lng: 128.625`
To the side of the outhouse, on the crates

Ace of Swords
`lat: -55.6328125
lng: 156.78125`
In the outhouse

Nine of Swords
`lat: -33.390625
lng: 141.3359375`
Top of the house

Six of Wands
`lat: -51.671875
lng: 106.234375`
In room 1a, on the fireplace

**====================**

### **Dec 14** (cycle 5?)

Five of pentacles
`lat: -56.8515625
lng: 129.5625`

Rosewood hairbrush
`lat: -55.90625
lng: 128.59375`
Inside the wardrobe in the northern room (this one seems to be the same as cycle 3)

Knight of wands
`lat: -54.34375
lng: 119.6953125`
Top of the tower

Page of Wands
`lat: -50.5390625
lng: 123.0703125`
In the outhouse

Eight of Swords
`lat: -48.1953125
lng: 114.296875`
On the toolbench

Gran Corazon Madeira
`lat: -51.578125
lng: 107.5625`
Behind the counter in the saloon

Two of swords
`lat: -51.6484375
lng: 107.5234375`
On a table in the saloon

Ace of wands
`lat: -69.9765625
lng: 138.4609375`

Blakely Miniature necklace (metal detector)
`lat: -70.15625
lng: 138.1171875`
Middle of graveyard

Another MD item
Bone Arrowhead (not sure if this is random though, I got it a little to the west of a marked random)
`lat: -69.046875
lng: 136.453125`

Page of cups
`lat: -69.1640625
lng: 136.484375`
On the bed

Cognac
`lat: -69.2578125
lng: 136.5078125`
On the fireplace, in the same room as the page of cups

Raw Arrowhead (MD)
`lat: -60.203125
lng: 122.7734375`
Edge of the cliff

Slate Arrowhead (MD)
`lat: -38.8203125
lng: 115.1015625`
Lower ledge of the cliff (be careful here, it's easy to fall to your death)

Splintered Arrowhead (MD)
`lat: -74.046875
lng: 145.6171875`
Next to the big tree on the island

Cardinal Flower
`lat: -76.1875
lng: 139.15625`
Same as #10 cycle 1 

Ebony Hairpin
`lat: -80.5859375
lng: 148.7734375`
Main floor, south side of the house, on the chair

New guinea rosewood hairbrush
`lat: -84.671875
lng: 138.8203125`
Back porch, on the table

Cherrywood comb
`lat: -90.96875
lng: 127.125`
Up the stairs, double door room on the right, in the chest

Three of cups
`lat: -92.2578125
lng: 127.4921875`
Side of the cabin, on some crates

Tortoiseshell comb
`lat: -70.15625
lng: 150.078125`
In the shack, on mirror vanity

Nine of wands
`lat: -70.0859375
lng: 150.03125`
In the shack, on the table

Nine of swords
`lat: -58.828125
lng: 149.1875`
In the north-west tower, on a barrel

Flint arrowhead (MD) - got this without a map, so if one can verify would be nice
`lat: -93.78125
lng: 133.703125`
Under the big tree

Page of pentacles
`lat: -75.4140625
lng: 142.4296875`
End of the dock, on the barrel

Queen of cups
`lat: -59.21875
lng: 155.203125`
Upstairs, end of the balcony

Scotch Whisky
`lat: -67.515625
lng: 155.84375`
Under the rock

Ten of wands
`lat: -67.53125
lng: 156.078125`
On a barrel in the broken cabin

Four of pentacles
`lat: -56.015625
lng: 157.8125`
Back of the boat

Six of wands
`lat: -79.078125
lng: 148.546875`
Bench on the pier

Eight of pentacles
`lat: -84.9765625
lng: 149.578125`
On a bench on the East side of the lake

Ten of pentacles
`lat: -80.7890625
lng: 155.0390625`
Bench in front of the church

Five of cups
`lat: -85.484375
lng: 155`
On a bench

Bone arrowhead (MD)
`lat: -43.2421875
lng: 153.71875`
Between the three dead trees (found without map, so might need to be verified)

Two of wands
`lat: -40.6015625
lng: 146.765625`
Inside the cave

**Comment by roulioz** [comment]
Found Queen of cups in Emerald Ranch near by the Lion when he attacks you in solo.

**Comment by destinysagent** [comment]
I was aware the map had changed. I discovered it when I tried to complete three collections this morning! I wonder if Rockstar have shuffled the cycles or if there are totally new ones. Anyway, I'm happy to help as I find things.

**Comment by Updowntheroad** [comment]
Wil map be fix cos dis map was best ever

**Comment by Jeph91** [comment]
![Red Dead Redemption 2 Screenshot 2019 12 13 - 16 05 44 90](https://user-images.githubusercontent.com/58854297/70812158-60537100-1dc7-11ea-8413-8d2e473fac8d.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 16 05 52 59](https://user-images.githubusercontent.com/58854297/70812159-60537100-1dc7-11ea-810b-733a675d6f7a.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 16 12 28 32](https://user-images.githubusercontent.com/58854297/70812161-60537100-1dc7-11ea-96b5-8487c1c42c8c.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 16 12 38 16](https://user-images.githubusercontent.com/58854297/70812162-60537100-1dc7-11ea-824f-297273c8f61e.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 16 12 40 82](https://user-images.githubusercontent.com/58854297/70812163-60ec0780-1dc7-11ea-9f39-752f556cef55.png)
By working together we will have the map remade, thank you all.

**Comment by funkybluehen** [comment]
Found Ten of Cups near MacFarlane Ranch fast travel post, on a bench at the train station.
Scotch Whiskey in Scarlett Meadows near the beach, the crumbling old house west of southfield flats

**Comment by Fraastos** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/58665728/70815459-6115e400-1d82-11ea-9fe5-acb9311b18f1.png)

King of Pentacles located in the Grizzly Mine (on the player icon in the screenshot).

**Comment by HenIchaer** [comment]
Like in cycle 1
![345](https://user-images.githubusercontent.com/58859009/70818710-6ce6c200-1de5-11ea-870b-7d94d3a7e2e1.png)

**Comment by LittleDansonGuy** [comment]
So sorry... Didn't get the name of this card, but it's inside the little hobbit house on the table. If someone could get the card name, feel free to update this!

![image](https://user-images.githubusercontent.com/58859409/70819403-c9bd8a80-1d9b-11ea-978d-afa560bebafb.png)

**Comment by Dexterin0** [comment]
Will add everything I find and edit post.

Four of the swords:
lat: -98.734375 lng: 89 ( thieves landing - behind upper left building )

**Comment by ShadowKingRPG** [comment]
This needs extra confirmation but Henlchaer is right, all the most valuable items (E.G jewelry, coins, heirlooms) have been switched to cycle 1 so just use that cycle if you're hunting for those sets :)

**Comment by Tuxeck** [comment]
If I find any I'll post as well:

Five of Swords Tarrot Card
![image](https://user-images.githubusercontent.com/58859685/70819994-d8299780-1dd7-11ea-8dc8-334e55b97d69.png)

**Comment by q1k** [comment]
> This needs extra confirmation but Henlchaer is right, all the most valuable items (E.G jewelry, coins, heirlooms) have been switched to cycle 1 so just use that cycle if you're hunting for those sets :)

I found 2 heirlooms that aren't there on any of the cycles.


> So sorry... Didn't get the name of this card, but it's inside the little hobbit house on the table. If someone could get the card name, feel free to update this!
> 
> [image](https://user-images.githubusercontent.com/58859409/70819403-c9bd8a80-1d9b-11ea-978d-afa560bebafb.png)

I'll check that soon

**Comment by Quahox** [comment]
Boxwood Comp up in the room in the chest. Also Knight of the wands down on the coffe table.
[https://imgur.com/O6XdWln](url)

Ebony hairbrush in wide wardrobe inside the house. Also Seven of cups on the chimney inside the house.
[https://imgur.com/fYzBDl4](url)

Suite Page of Pentacles outside of the house on the chimney.
[https://imgur.com/xJaKoOU](url)

**Comment by LittleDansonGuy** [comment]
It's fair to say some stuff is still in the same spot, especially with Cycle 1. The new challenge seems to be where the 'New' locations are paired with the old ones. For instance, from Cycle 1, I just found both Heron Egg and Hawk Egg (near Colter) in the same places. And I found the Coins and Jewelry than Hen mentioned. 

We'll all just have to keep playing and updating, I guess.

**Comment by LittleDansonGuy** [comment]
Seven of Wands: In this cabin on a table.

![image](https://user-images.githubusercontent.com/58859409/70820760-0d65c380-1d9f-11ea-9cd5-2e954eb6fe1f.png)

**Comment by Dexterin0** [comment]
> This needs extra confirmation but Henlchaer is right, all the most valuable items (E.G jewelry, coins, heirlooms) have been switched to cycle 1 so just use that cycle if you're hunting for those sets :)

Will check if that happened for the cards as well. That would be sweet.

For everyone posting here, might be faster to look for coordinates, you can turm them on in the settings here: https://jeanropke.github.io/RDR2CollectorsMap/ and write them with a basic description.

**Comment by herr-barus** [comment]
-118.56; 38.765 blaue texaslupine
-110.625; 44.98 kleine klette
-89.24; 80.58 tarot - zwei der münzen
-81.60; 85.43 schokoladenblume
-77.81; 85.95 (metall) knochen pfeilspitze
-93.96; 90.42 (metall) obsidian pfeilspitze

**Comment by githb123** [comment]
Caribbean Rum, Friday, December 13th
lat -82.7968
lng 98.0468
the coords are "about" as the tents are not there on the internet map.

It's inside of the most western tent in the southern row of 3 tents.

**Comment by HardTIP** [comment]
![image](https://user-images.githubusercontent.com/58859766/70821750-72a4cd80-1e0e-11ea-8374-90cabb1519b5.png)


![image](https://user-images.githubusercontent.com/58859766/70821723-6456b180-1e0e-11ea-85f9-fb48f9e5c524.png)

![image](https://user-images.githubusercontent.com/58859766/70821686-4a1cd380-1e0e-11ea-929d-56924c454902.png)
Карибский ром! 
В палатке на бочке!

**Comment by Fraastos** [comment]
Nine of Wands
lat: -116.9609375
lng: 30.546875

**Comment by Fraastos** [comment]
Agarita
lat: -119.1796875
lng: 54.1640625

this is the same coordinate as one of the Agaritas found in Cycle 3. May require further confirmation, but I believe Agaritas are the same as Cycle 3.

**Comment by Hyperfunk-zone** [comment]
Wild Rhubarb lat: -103.90625 lng: 73.765625
Same as cycle 3

**Comment by Fraastos** [comment]
Page of Pentacles
lat: -53.28125
lng: 83.09375

**Comment by DePoots** [comment]
2 new
BITTERWEED
![5b3510feba1b40600ac26d0c211160a2](https://user-images.githubusercontent.com/58863364/70829163-f59c3880-1dba-11ea-86e2-e87fac0095bc.jpg)

PAGE OF PENTACLES TARROT CARD
![8a62f3747fa322e8d8bde66b5a6bb57a](https://user-images.githubusercontent.com/58863364/70829193-06e54500-1dbb-11ea-9982-a058d63db5d5.jpg)

**Comment by HenIchaer** [comment]
Eight of wands - Baccus station 
lat: -37.46031469650689
lng: 120.453125

![Red Dead Redemption II Screenshot 2019 12 13 - 23 51 36 96](https://user-images.githubusercontent.com/58859009/70831619-16d54700-1e04-11ea-903b-74cda0019119.png)

**Comment by Updowntheroad** [comment]
Random spots be put in to map to ?

**Comment by Fraastos** [comment]
Nine of Swords
lat: -33.359375
lng: 141.359375

On top of tower.

**Comment by jeanropke** [comment]
@Updowntheroad yes, but they are low priority. I'm focused on add the fixed spots first

**Comment by Fraastos** [comment]
Quick question, have we figured out if all cycles have changed or did they just add another?

**Comment by Fraastos** [comment]
Ivory Hairpin
lat: -35.625
lng: 150.296875

**Comment by jeanropke** [comment]
Maybe they added more cycles and now each set was your own cycle.

**Comment by Fraastos** [comment]
Horse Hairbrush
lat: -36.03125
lng: 158.3515625

**Comment by Jeph91** [comment]
![Red Dead Redemption 2 Screenshot 2019 12 13 - 21 28 15 98](https://user-images.githubusercontent.com/58854297/70833330-c9eb7380-1df7-11ea-908e-7b72495929c6.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 21 28 26 81](https://user-images.githubusercontent.com/58854297/70833331-c9eb7380-1df7-11ea-81a5-a6f62ca7df90.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 22 24 09 34](https://user-images.githubusercontent.com/58854297/70833332-c9eb7380-1df7-11ea-83e2-af0b619bda45.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 22 24 14 08](https://user-images.githubusercontent.com/58854297/70833334-c9eb7380-1df7-11ea-850d-46c62f261c74.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 22 24 20 60](https://user-images.githubusercontent.com/58854297/70833335-ca840a00-1df7-11ea-9413-7ad2acdf42c8.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 22 24 26 92](https://user-images.githubusercontent.com/58854297/70833337-ca840a00-1df7-11ea-8d84-e968650821c2.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 17 21 50 87](https://user-images.githubusercontent.com/58854297/70833338-ca840a00-1df7-11ea-9f21-137400c7730a.png)
![Red Dead Redemption 2 Screenshot 2019 12 13 - 17 31 35 100](https://user-images.githubusercontent.com/58854297/70833339-ca840a00-1df7-11ea-9ade-15cfa2f2abd1.png)

**Comment by Fraastos** [comment]
Not sure if this is a random spot or not:

Dane Topaz Necklace
lat: -54.375
lng: 152.015625

**Comment by beaves** [comment]
Chocolate Daisy Flower #3 is the same position from cycle 3

**Comment by Fraastos** [comment]
Cardinal Flower
lat: -74.8515625
lng: 148.7890625

**Comment by Fraastos** [comment]
Knight of Pentacles
lat: -91.828125
lng: 140.90625

**Comment by T0M1988** [comment]
Cardinal Flower
lat: -79.0703125
lng: 142.3125

**Comment by Fraastos** [comment]
Six of Cups
lat: -83.984375
lng: 132.71875

**Comment by Fraastos** [comment]
Blood Flower #1 Cycle 1 is the same

**Comment by jeanropke** [comment]
Missing this cards now:
cups: four, five, knight
swords: three
pentacles: three, seven, eight
wands: two, five, page

**Comment by T0M1988** [comment]
Cardinal Flower
lat: -72.3671875
lng: 147.1484375

**Comment by Fraastos** [comment]
Jade Hairpin
lat: -91.1796875
lng: 126.8359375

**Comment by Fraastos** [comment]
Ten of Pentacles
lat: -94.4453125
lng: 128.65625

**Comment by Updowntheroad** [comment]
Why are some of the markers show out of the map?

**Comment by ilinyzili** [comment]
lat: -75.27991607716854
lng: 87.953125

Metal Hairpin Family Heirloom - metal detector

**Comment by andriisytnyk** [comment]
lat: -60.15
lng: 96.15

Under the old tree

Slate arrowhead - metal detector

**Comment by StarLord4hire** [comment]
I noticed all of the coins, rings, and bracelets were in the original location. Which was labeled as cycle 4, but they all changed an hour ago.

**Comment by q1k** [comment]
> I noticed all of the coins, rings, and bracelets were in the original location. Which was labeled as cycle 4, but they all changed an hour ago.

Cycles change every day at UTC+0

**Comment by StarLord4hire** [comment]
<img width="1440" alt="Screen Shot 2019-12-13 at 8 05 04 PM" src="https://user-images.githubusercontent.com/58867961/70841079-517bb700-1de5-11ea-858c-b23fd29355d9.png">


4 of Wands located on the attached image on the red marker. Right outside Annesburg

**Comment by DePoots** [comment]
DAY 5 CYCLE:

9 of swords tarrot card in watch tower second floor where standing
![b8a1c5f3a1df5667fb1cada7f947db41-jpg](https://user-images.githubusercontent.com/58863364/70841111-a15a7e00-1de5-11ea-8f02-95cb33785835.jpg)

**Comment by MinChoco3007** [comment]
Knight of the Swords
lat: -72.54
Lng: 94.31
Decription: Rigg Station, upstair, on top the barrel.

**Comment by Aqu4tic2** [comment]
Found the Boar Bristle Brush in Pleasance House, Cholla Springs, in the chest on the left as soon as you enter.

**Comment by StarLord4hire** [comment]
<img width="1440" alt="Screen Shot 2019-12-13 at 8 29 08 PM" src="https://user-images.githubusercontent.com/58867961/70841301-57729780-1de7-11ea-94c2-1934814d295d.png">


Banais Topaz Ring
location:  O'Creagh's Run, next to Stranger shack.
Metal Detector Required.

**Comment by MinChoco3007** [comment]
Chocolate Daisy
Lat: -81.37
Lng: 88.44
Decription surrounded by trees and bushes.

**Comment by MinChoco3007** [comment]
1795 Half Eagle
Lat:-88.54
Lng:91.72
Decription: between two rocks, metal detector.

**Comment by MinChoco3007** [comment]
Aubrey Onyx Ring
Lat: -87.11
Lng: 98.44
Decription: beside the tree, metal detector.

**Comment by MinChoco3007** [comment]
Aubrey Onyx Ring (2nd)
Lat: -93.87
Lng: 98.08
Decription: beside tree and rock.

**Comment by MinChoco3007** [comment]
Obsidian Arrow Head
Lat -78.48
Lng: 93.61
Description: beside the tree, metal detector.

**Comment by funkybluehen** [comment]
The Gran Corazon Madeira listed for cycle 5 in crappy valentine saloon...I found a Two of Swords there instead

**Comment by funkybluehen** [comment]
Thorburn turquoise ring (metal detector)
lat: -42.9140625 
lng: 147.3984375
Near beaver hollow cave, where Trelawney sits in Ch. 6 story mode

**Comment by q1k** [comment]
> The Gran Corazon Madeira listed for cycle 5 in crappy valentine saloon...I found a Two of Swords there instead

Both are there, bottle is under the counter, the card is behind the counter at the wall

**Comment by zombiegums** [comment]
I found a Tennessee Whiskey bottle under the schoolhouse/church looking building in Armadillo:

(I'd already looted it, but it's found in the gap where my shadow leads to):
![20191214035707_1](https://user-images.githubusercontent.com/38048911/70843196-1ea5e300-1e26-11ea-8a17-0643fc65c1e0.jpg)
![20191214035720_1](https://user-images.githubusercontent.com/38048911/70843200-22396a00-1e26-11ea-85c2-0d5d7cc65d76.jpg)

I'm sorry that I don't know the co-ordinates, but hopefully this is helpful enough!

**Comment by Sidzzz** [comment]
Carved wooden hairpin
lat: -55.601228350294264
lng: 101.89021484930423

**Comment by q1k** [comment]
@Sidzzz can you please not use spoilers in descriptions, thank you

**Comment by Sidzzz** [comment]
> @Sidzzz can you please not use spoilers in descriptions, thank you

That's not even a spoiler lmfao. There isn't any better way to describe the location, and I'd rather not simply comment a set of coordinates.

**Comment by Corneliu5** [comment]
Queen of Wands
lat: -118.02
lng: 30.22
On windowsill of the stable facing east

**Comment by herr-barus** [comment]
14.12.
all metal detector
-115; 29.22 5 cent 1792
-119.73; 53.62 siberdollar 1798
-117.46; 49.39 obsidian pfeilspitze
-105.61; 36.50 haford ohrring
-101.69; 44.0 5 cent 1800
-105.20; 79.08 hajmant garant armreif
-88.87; 80.30 silberdoller 1794

**Comment by Sidzzz** [comment]
Halfpenny coin
lat: -76.08413945634534
lng: 141.7644469460192
Near the moonshining still

**Comment by Sidzzz** [comment]
Gold eagle coin
lat: -65.80771672620139
lng: 151.61676241792728
Beneath the clothesline

**Comment by Corneliu5** [comment]
Sterling Tooth Earrings (metal detector)
lat: -29.71
lng: 136.00
Between a small cart and a tree.

**Comment by Sidzzz** [comment]
1792 Quarter
lat: -52.67754957803845
lng: 153.61740793341357
Between the rock and the shack

**Comment by Sidzzz** [comment]
New Yorke token
lat: -78.96832435692245
lng: 149.57779796354214
Beneath the bridge

**Comment by andriisytnyk** [comment]
lat: -40.3046875
lng: 137.8671875
Feldspar Arrowhead - metal detector
_Between the fence and tree._

**Comment by andriisytnyk** [comment]
lat: -73.890625
lng: 110.8984375
There is a random spot, not only arrowhead.

**Comment by andriisytnyk** [comment]
**Cycle 6**

lat: -84.78125
lng: 133.5546875
Tarot Card - King of Cups

**Comment by andriisytnyk** [comment]
lat: -60.2265625
lng: 96.1875
Slate Arrowhead - metal detector
_Under old tree._
