### ISSUE TITLE
Most Valuable Items In Cycle 1

### ISSUE THREAD

**Issue by ShadowKingRPG** [jeanropke/RDR2CollectorsMap#458]
Just thought I'd put this out there for anyone wondering but I'm pretty sure all the most valuable items like the coins, heirlooms, and jewelry have been switched from cycle 3 positions to cycle 1 positions, noticed someone else mention it in another post.
Obviously this needs confirmation but so far I've found 5 items (2 rings, 1 bracelet, and 2 coins) in their cycle 1 locations :)

**Comment by jeanropke** [comment]
Also birds eggs are from cycle 1.
