### ISSUE TITLE
jean you broke everything for nothing

### ISSUE THREAD

**Issue by missiah** [jeanropke/RDR2CollectorsMap#460]
I do not understand what the problem is...
Before this stupid introduce of cycle 4 everything was working like intended.
There are no new Item locations the only problem was after the patch R* reset the Circle to 1
After the patch i just had to set to cycle 1 and was able to find every item without a problem.
Now the Map is absolutely broken.

**Comment by Senexis** [comment]
This has some merit. When I change the map manually to cycle 1 it seems a lot of collectables in cycle 4 are in the same location as they are in cycle 1. Could it be that they just switched up the cycles and called it a day?

**Comment by TheDoomDay** [comment]
and now there's another new cycle....
cycle 5..

i checked on 1,2,3 and the collection item wasnt there...

idk how many cycle are there...

**Comment by ThatKasper** [comment]
> I do not understand what the problem is...
> Before this stupid introduce of cycle 4 everything was working like intended.
> There are no new Item locations the only problem was after the patch R* reset the Circle to 1
> After the patch i just had to set to cycle 1 and was able to find every item without a problem.
> Now the Map is absolutely broken.

How do you not realize Jean isn't the one that decides where these items are in the game?? He didn't change the map, ROCKSTAR CHANGED THEIR GAME!!
Plus you're complaining about something you're gaining a benefit from FOR FREE? Wow. You're welcome.

**Comment by jeanropke** [comment]
Rockstar changed the collectors role. New cycles are been added.
