### ISSUE TITLE
Map Status for Stadia

### ISSUE THREAD

**Issue by trollsaver** [jeanropke/RDR2CollectorsMap#461]
Red Dead Online for Google Stadia not on new Moonshiner mode yet.  Cannot view collectibles. 

Have a button to show achieved version that worked prior to Dec 13th. Possibly for platforms.

Legacy does not show.  Wish I would have had static maps even for the standard collectibles by rotation days.

**Comment by jeanropke** [comment]
There is a option to set cycles manually. Today cycle is 1
