### ISSUE TITLE
Item location (check for more update and info)

### ISSUE THREAD

**Issue by RedDead2DM** [jeanropke/RDR2CollectorsMap#464]
Cycle 5
Infanta Turquoise Bracelet

lat: -57.42792750645704 
lng: 126.15926578554111

Metal detectors need

**Comment by RedDead2DM** [comment]
Cycle 5

Flint ArrowHead

lat: -93.86691088048462 
lng: 133.78829707656956

Metal Detector need

**Comment by RedDead2DM** [comment]
Cycle 5 

1792 Nickel

lat: -95.97629795514601 
lng: 132.78821042486047

Metal Detector need

**Comment by extrokidd** [comment]
Cycle 5

Ten of wands tarot card

lat: -67.50237182207377
lng: 156.08801258983797

**Comment by extrokidd** [comment]
Cycle 5 

Scotch Whiskey 

lat: -67.70384030091972
lng: 155.84425546702556

It's between two rocks that has a boat on top

**Comment by RedDead2DM** [comment]
Cycle 5

1800 Gold Quarter Coin

lat: -72.36681647858651 
lng: 121.36628848851804

Metal Detector need (under the bridge)

**Comment by RedDead2DM** [comment]
Cycle 5 

1797 Gold Eagle Coin

lat: -63.92933623712332 
lng: 152.3744223219393

Metal Detector need

**Comment by RedDead2DM** [comment]
Cycle 5

Magnate Turquoise Ring

lat: -65.85103209460326 
lng: 146.08893165180092

inside the house, above the Chimney

**Comment by Znooze** [comment]
Cycle 5

1800 Half Dime

lat: -101.6015625
lng: 44.015625

Metal Detector need

**Comment by Znooze** [comment]
Cycle 5

Rough Arrowhead

lat: -104.7578125
lng: 62.484375

Metal Detector needed

**Comment by RedDead2DM** [comment]
Cycle 5

1796 HalfPenny Coin

lat: -74.15902942236136 
lng: 141.5863994365316

Metal Detector need (Kamassa Rive next to a small liquor cabin)

**Comment by gyp-rdo** [comment]
Cycle 5

1792 Quater

lat: -52.609375
lng: 153.484375

Metal Detector needed (next to small cabin door)

**Comment by RedDead2DM** [comment]
Cycle 5

Blakely Miniature Neckace

lat: -70.2306307340683 
lng: 138.21518529278302

Metal Detector need (Lemoyne location, near at the house when the (Ace of Wands Tarot Card is) and  front a tombstone

**Comment by RedDead2DM** [comment]
Cycle 5

1792 Libery Quarter

lat: -41.51025543232764 
lng: 116.9070488166836

Metal Detector need (In front of Fort Wallace, where the chopped tree trunk is)

**Comment by Znooze** [comment]
Cycle 5

Two of Swords Tarot card

lat: -51.6875
lng: 107.5234375

On the middel table in front of the bar

**Comment by Znooze** [comment]
Cycle 5

Page of Cups Tarot card

lat: -69.296875
lng: 136.4453125

On one of the bunkbeds

**Comment by D4rkf4t3** [comment]
Cycle 5

1800 Five Dollar Bechtler

lat: -35.5625
lng: 142.0625

Behind the AMBARINO train track sign

**Comment by Znooze** [comment]
Cycle 5

Bone Arrowhead

lat: -62.78125
lng: 154.7734375

Metal Detector needed (In-between two dead trees)

**Comment by D4rkf4t3** [comment]
Cycle 5

Chipped Arrowhead

lat: -56.75
lng: 87.4453125

Metal Detector need (Close to the big rock)

**Comment by squshiee657** [comment]
Tennessee whiskey 
Not sure how to get lat and lon
![20191214_141744](https://user-images.githubusercontent.com/58883847/70850344-2c3c8680-1e81-11ea-902b-54e3876a1ade.jpg)

**Comment by squshiee657** [comment]
Cycle 5 
Calumet turquoise earrings 
Metal detector 
![15763358526234224249101858781475](https://user-images.githubusercontent.com/58883847/70850517-0e702100-1e83-11ea-9585-61289e113042.jpg)

**Comment by D4rkf4t3** [comment]
Bitterweed

lat: -58.140625
lng: 85.0703125

**Comment by crazyace2019** [comment]
2 of penticules

[found in valentine in the east saloon on a shelf or table cant remember]
What day cycle it is? FOR DAY CYCLE 5

**Comment by Znooze** [comment]
Cycle 5

1800 Gold Dollar

lat: -79.6328125
lng: 80.3359375

Metal Detector needed

**Comment by Jummix** [comment]
obsidian arrowhead

Inside cave behind waterfall
lat: -47.1328125
lng: 146.53125

Metal detector
