### ISSUE TITLE
Can’t reset the founded items.

### ISSUE THREAD

**Issue by anonim070** [jeanropke/RDR2CollectorsMap#465]
Some items which founded before the update, appears red in the menu, and not show on the map. Can’t change them to white, these stay in red, and not showing on the map. Can’t reset them. 
![8BDB7E08-8112-431E-A4BC-8C33996FDCD4](https://user-images.githubusercontent.com/58875171/70845538-dbf50280-1e47-11ea-92a9-448132278453.jpeg)

**Comment by dlldldl** [comment]
Maybe at the end of cycle 5 it will be fixed.

**Comment by IronJeff80** [comment]
No verified location for red items

**Comment by anonim070** [comment]
Thank you dlldldl, I hope that will fix it.
Thank you IronJeff80. 👍🏻

**Comment by jeanropke** [comment]
Red items on menu are not found.
White items are not collected.
