### ISSUE TITLE
New item locations at Cycle 5. December 14

### ISSUE THREAD

**Issue by SuperFanz** [jeanropke/RDR2CollectorsMap#466]
Cycle 5. December 14

1794 Silver Dollar Coin
![rdo_1_2](https://user-images.githubusercontent.com/58881052/70849008-c4d30680-1e81-11ea-8968-d615b9f847d5.png)
![rdo_1_1](https://user-images.githubusercontent.com/58881052/70849018-dddbb780-1e81-11ea-9f5d-1d7ec3bfda00.png)

Hajnal Garnet Bangle Bracelet
![rdo_2_1](https://user-images.githubusercontent.com/58881052/70849029-efbd5a80-1e81-11ea-987c-badba489c7a7.png)
![rdo_2_3](https://user-images.githubusercontent.com/58881052/70849036-05cb1b00-1e82-11ea-92fb-220b02c37b56.png)

Sorry i dont remember what was here
![rdo_3_1_1](https://user-images.githubusercontent.com/58881052/70849137-3495c100-1e83-11ea-8969-2c5c4a80056f.png)
![rdo_3_2](https://user-images.githubusercontent.com/58881052/70849143-41b2b000-1e83-11ea-9b81-b7d5d81a1ca4.png)

Magnate Turquoise Ring
![2](https://user-images.githubusercontent.com/58881052/70849186-ae2daf00-1e83-11ea-9c95-e703a8633518.png)
![4](https://user-images.githubusercontent.com/58881052/70849188-b259cc80-1e83-11ea-8b52-d4570d692935.png)

Orchidee Diamond Earrings
![2](https://user-images.githubusercontent.com/58881052/70849199-dae1c680-1e83-11ea-80dd-b4a6dd8ce851.png)
![4](https://user-images.githubusercontent.com/58881052/70849206-e33a0180-1e83-11ea-8087-dcb6e99c9f78.png)

Ainsworth Cross Necklace
![2](https://user-images.githubusercontent.com/58881052/70849214-fa78ef00-1e83-11ea-91d1-3a7ea486a291.png)
![3](https://user-images.githubusercontent.com/58881052/70849218-01076680-1e84-11ea-9f3f-5b805421dd7c.png)
![4](https://user-images.githubusercontent.com/58881052/70849224-12e90980-1e84-11ea-8dfb-c400da42d3c2.png)
![5](https://user-images.githubusercontent.com/58881052/70849225-167c9080-1e84-11ea-832f-f033bd104c81.png)

**Comment by 8Johnson** [comment]
Dec 14.
Arrow (With Detector)
https://ibb.co/4ZMVqpX
Coin (With Detector)
https://ibb.co/djnhcHW

**Comment by Hawkeye1042** [comment]
Map reports the item in the Valentine saloon as "Gran Corazon Madeira Bottle - Cycle 5". I picked up a tarot card there.

**Comment by Hyperfunk-zone** [comment]
Dec 14, cycle 5
Beauchene Ruby Earrings - with metal detector.
lat: -50.4453125 lng: 115.9296875

**Comment by M3L0ns** [comment]
Random items are probably the same:

lat: -52.6328125
lng: 99.0546875

**Comment by SuperFanz** [comment]
Braxton Amethyst Necklace

![1](https://user-images.githubusercontent.com/58881052/70850024-927bd600-1e8e-11ea-9abf-917c396cea30.jpg)
![2](https://user-images.githubusercontent.com/58881052/70850025-9576c680-1e8e-11ea-819e-cf2bd11245de.jpg)
![3](https://user-images.githubusercontent.com/58881052/70850028-97d92080-1e8e-11ea-88c6-f98ae5d30be5.jpg)

Flint Arrowhead

![1](https://user-images.githubusercontent.com/58881052/70850068-fbfbe480-1e8e-11ea-9703-f9acfd79e9da.jpg)
![2](https://user-images.githubusercontent.com/58881052/70850070-00c09880-1e8f-11ea-95f0-c352a6eb7e83.jpg)
![3](https://user-images.githubusercontent.com/58881052/70850080-04541f80-1e8f-11ea-97a7-e1a16f0a19d6.jpg)
![4](https://user-images.githubusercontent.com/58881052/70850081-074f1000-1e8f-11ea-9bce-839f8f154098.jpg)

Splintered Arrowhead

![1](https://user-images.githubusercontent.com/58881052/70850095-2fd70a00-1e8f-11ea-99c1-66edb4f56e76.jpg)
![2](https://user-images.githubusercontent.com/58881052/70850098-35345480-1e8f-11ea-9e5a-95a0e8e1024b.jpg)
![3](https://user-images.githubusercontent.com/58881052/70850099-39f90880-1e8f-11ea-9d7c-3f055e7b36c4.jpg)

1700 New Yorke Token Coin

![1](https://user-images.githubusercontent.com/58881052/70850124-7298e200-1e8f-11ea-8d00-bc07e131253d.jpg)
![2](https://user-images.githubusercontent.com/58881052/70850128-77f62c80-1e8f-11ea-817e-2caa9cc180f7.jpg)
![3](https://user-images.githubusercontent.com/58881052/70850129-7b89b380-1e8f-11ea-9338-d4ebe136a9b5.jpg)
![4](https://user-images.githubusercontent.com/58881052/70850131-7fb5d100-1e8f-11ea-86cd-e9e7a6b111cf.jpg)

**Comment by Kwicko** [comment]
Can confirm 1794 Silver Dollar behind the main house at Manzanita Post, just outside of the horse hitching rail in back.

**Comment by ilinyzili** [comment]
lat: -88.84375 
lng: 80.375 

1794 silver dollar coin behind the house by where you hitch the horse

**Comment by Dexterin0** [comment]
We are adding stuff through discord, guess that's better for jean to implement. 
https://discordapp.com/channels/631510938016677889/631510942793990155

**Comment by ilinyzili** [comment]
Link won’t work when I add it to app . Send a working inv link and I’ll send what I find . If not I’ll just post cords here

**Comment by ruizalf5179** [comment]
Knights of wands located in tower in Heartland Oil Fields 
![image](https://user-images.githubusercontent.com/58884638/70850708-1c518200-1e42-11ea-8bce-4cc18b154aba.jpg)

**Comment by ilinyzili** [comment]
lat: -104.703125 
lng: 62.484375

Rough arrowhead - by a tree ( metal detector)

lat: -101.53125 
lng: 44.0546875

1800 half dime - by the back of a broken wagon (metal detector)

**Comment by Kwicko** [comment]
lat: -79734375
lng: 80.40625

1800 Gold Dollar

On an island just in the middle of the Upper Montana River.

**Comment by Kwicko** [comment]
Discord link doesn't work; need invite.

**Comment by SuperFanz** [comment]
Blakely Miniature Necklace

![1](https://user-images.githubusercontent.com/58881052/70850964-ba703700-1e98-11ea-932d-af9333cf3fcf.png)
![2](https://user-images.githubusercontent.com/58881052/70850967-be9c5480-1e98-11ea-8ed4-b6691314f217.png)
![3](https://user-images.githubusercontent.com/58881052/70850970-c2c87200-1e98-11ea-8149-bfc8c8d998ab.png)
![4](https://user-images.githubusercontent.com/58881052/70850973-c52acc00-1e98-11ea-8624-37486959d0e6.png)

Raw Arrowhead

![1](https://user-images.githubusercontent.com/58881052/70850989-f3a8a700-1e98-11ea-9f7b-fc75c25ab8ab.png)
![2](https://user-images.githubusercontent.com/58881052/70850993-f6a39780-1e98-11ea-9e0a-6bd8289f21a8.png)
![3](https://user-images.githubusercontent.com/58881052/70850995-f99e8800-1e98-11ea-8fa0-5b8485a126a1.png)
![4](https://user-images.githubusercontent.com/58881052/70850997-fd320f00-1e98-11ea-9044-8356b6f5f171.png)

1795 Half Eagle Coin

![1](https://user-images.githubusercontent.com/58881052/70851037-42564100-1e99-11ea-8b07-56f785d49120.png)
![2](https://user-images.githubusercontent.com/58881052/70851038-44200480-1e99-11ea-9a92-6f2421c76c39.png)
![3](https://user-images.githubusercontent.com/58881052/70851040-45e9c800-1e99-11ea-8132-4fcca7b9ee84.png)
![4](https://user-images.githubusercontent.com/58881052/70851041-471af500-1e99-11ea-97e7-6688bf7ac691.png)

1792 Liberty Quarter Coin

![1](https://user-images.githubusercontent.com/58881052/70851077-97925280-1e99-11ea-8ea0-c712f70c269b.png)
![2](https://user-images.githubusercontent.com/58881052/70851078-97925280-1e99-11ea-876b-6ecaf68a058d.png)
![3](https://user-images.githubusercontent.com/58881052/70851079-97925280-1e99-11ea-9331-4ed6667b700a.png)
![4](https://user-images.githubusercontent.com/58881052/70851080-97925280-1e99-11ea-8819-3e79d49d43f5.png)

1797 Gold Eagle Coin

![1](https://user-images.githubusercontent.com/58881052/70851093-c7415a80-1e99-11ea-94b0-92c3e808ee14.png)
![2](https://user-images.githubusercontent.com/58881052/70851094-c7415a80-1e99-11ea-894a-d13b0c401638.png)
![3](https://user-images.githubusercontent.com/58881052/70851095-c7415a80-1e99-11ea-90e1-c75b18e1ad3e.png)
![4](https://user-images.githubusercontent.com/58881052/70851096-c7d9f100-1e99-11ea-93b7-e4bafe174536.png)

1800 Gold Quarter Coin

![1](https://user-images.githubusercontent.com/58881052/70851111-f952bc80-1e99-11ea-9f60-4fe4a60c4788.png)
![2](https://user-images.githubusercontent.com/58881052/70851112-f952bc80-1e99-11ea-8a49-dadee33d079e.png)
![3](https://user-images.githubusercontent.com/58881052/70851113-f952bc80-1e99-11ea-8923-46b790dfd98b.png)
![4](https://user-images.githubusercontent.com/58881052/70851114-f9eb5300-1e99-11ea-99b2-24d5b3803664.png)
![5](https://user-images.githubusercontent.com/58881052/70851115-f9eb5300-1e99-11ea-9b4f-adcdbeaacdf8.png)

Tarot Cards - Cups - Page of Cups (on bed)

![1](https://user-images.githubusercontent.com/58881052/70851149-49318380-1e9a-11ea-9930-7109dac10b74.png)
![2](https://user-images.githubusercontent.com/58881052/70851150-49318380-1e9a-11ea-908f-00bab696d758.png)

**Comment by ruizalf5179** [comment]
Duchess Emerald Earrings -Metal Detector 

![image](https://user-images.githubusercontent.com/58884638/70851570-9fc3a100-1e4b-11ea-95df-59fc72a215f0.jpg)

**Comment by StupidUserName12345613645** [comment]
> Map reports the item in the Valentine saloon as "Gran Corazon Madeira Bottle - Cycle 5". I picked up a tarot card there.

I found both a card and the bottle in the Valentine Saloon last night.

**Comment by emcardinal** [comment]
14 December, cycle 5. 
7 of Wands tarot card, inside the mine at Millesani Claim

![PS_Messages_20191214_135856](https://user-images.githubusercontent.com/58889474/70853338-88e87300-1e7a-11ea-927a-8f839219823e.jpg)


![PS_Messages_20191214_135859](https://user-images.githubusercontent.com/58889474/70853334-740bdf80-1e7a-11ea-83d5-1735251751f2.jpg)

**Comment by justsomecoyote** [comment]
14 December, cycle 5.
Aubrey Onyx Ring
Beneath the tree
lat: -87.09375
lng: 98.4296875
![Red Dead Redemption 2 Screenshot 2019 12 14 - 11 19 49 47](https://user-images.githubusercontent.com/58889880/70853632-6861ee00-1e65-11ea-97b9-c9fb9908e06f.png)

![Red Dead Redemption 2 Screenshot 2019 12 14 - 11 20 04 32](https://user-images.githubusercontent.com/58889880/70853638-73b51980-1e65-11ea-9e2b-15c8572e2913.png)

**Comment by SuperFanz** [comment]
Durant Pearl Bracelet (maybe this one was a random item)
![1](https://user-images.githubusercontent.com/58881052/70853633-3f6b4880-1eb9-11ea-8886-8ab26083febd.png)
![2](https://user-images.githubusercontent.com/58881052/70853634-3f6b4880-1eb9-11ea-9f21-edbd6d03c2ed.png)
![3](https://user-images.githubusercontent.com/58881052/70853635-4003df00-1eb9-11ea-8b0d-cace053b26a0.png)
![4](https://user-images.githubusercontent.com/58881052/70853636-4003df00-1eb9-11ea-9e4b-791649fad259.png)

**Comment by SuperFanz** [comment]
Random item
![1](https://user-images.githubusercontent.com/58881052/70853711-45adf480-1eba-11ea-9246-2209294fb95d.png)
![2](https://user-images.githubusercontent.com/58881052/70853712-45adf480-1eba-11ea-9663-bedcf0196d3b.png)
![3](https://user-images.githubusercontent.com/58881052/70853713-45adf480-1eba-11ea-94d1-51c9f4e7b1b9.png)
![4](https://user-images.githubusercontent.com/58881052/70853714-45adf480-1eba-11ea-94fa-4c5f496abb14.png)

**Comment by SuperFanz** [comment]
Quartz Arrowhead

![1](https://user-images.githubusercontent.com/58881052/70853835-0385b280-1ebc-11ea-938c-27a1028df5d9.png)
![2](https://user-images.githubusercontent.com/58881052/70853836-0385b280-1ebc-11ea-994c-ca554706a725.png)
![3](https://user-images.githubusercontent.com/58881052/70853837-041e4900-1ebc-11ea-9624-12f0298d02f6.png)
![4](https://user-images.githubusercontent.com/58881052/70853838-041e4900-1ebc-11ea-9119-ac37a75f848d.png)

**Comment by maximu** [comment]
The Chipped arrowhead spot  indicated in the map, southeast of flatneckstation gave me a Rou Pearl Necklace.

**Comment by TheProfessor25** [comment]
> Map reports the item in the Valentine saloon as "Gran Corazon Madeira Bottle - Cycle 5". I picked up a tarot card there.

It's behind the bar by the barrel that's on top of the bar.

**Comment by beaves** [comment]
There is a item with wrong location
![rdrmap](https://user-images.githubusercontent.com/1618154/70854064-d551a400-1eb6-11ea-94e2-5e9bf4d88bac.png)

**Comment by beaves** [comment]
There is an item with a wrong location
![rdrmap](https://user-images.githubusercontent.com/1618154/70854084-16e24f00-1eb7-11ea-95ea-83657d4449ff.png)

**Comment by SuperFanz** [comment]
Crude Arrowhead

![1](https://user-images.githubusercontent.com/58881052/70854111-e81ca680-1ebf-11ea-848b-90eebf1e6807.png)
![2](https://user-images.githubusercontent.com/58881052/70854112-e81ca680-1ebf-11ea-94ad-3f9688666ea7.png)
![3](https://user-images.githubusercontent.com/58881052/70854113-e81ca680-1ebf-11ea-9ebe-522bf891ce99.png)
![4](https://user-images.githubusercontent.com/58881052/70854114-e8b53d00-1ebf-11ea-9733-6024b1925eb7.png)

**Comment by ruizalf5179** [comment]
Bitter weed 


![58A15228-D130-4DE9-9207-7A021E075226](https://user-images.githubusercontent.com/58884638/70854379-a3691f00-1e6f-11ea-8bd2-ca910b86e10f.jpeg)

**Comment by ruizalf5179** [comment]
Creek Plum 
![978011AA-022B-44CA-8B88-187C5636C1AD](https://user-images.githubusercontent.com/58884638/70854503-b250d100-1e71-11ea-821b-fcdc4a0ffb59.jpeg)
![68508287-1C41-4C7F-A08B-24EF7330FA63](https://user-images.githubusercontent.com/58884638/70854504-b250d100-1e71-11ea-859b-1e87813f8cbd.jpeg)

**Comment by justsomecoyote** [comment]
1800 Half Dime, by the wrecked wagon
 req'd metal detector

![Red Dead Redemption 2 Screenshot 2019 12 14 - 14 44 42 19](https://user-images.githubusercontent.com/58889880/70855495-7c671900-1e80-11ea-97a1-9336d36efae6.png)
![Red Dead Redemption 2 Screenshot 2019 12 14 - 14 44 47 43](https://user-images.githubusercontent.com/58889880/70855496-7ec97300-1e80-11ea-8771-c87995d27ae0.png)

**Comment by justsomecoyote** [comment]
Texas Bluebonnet
![Red Dead Redemption 2 Screenshot 2019 12 14 - 15 02 53 62](https://user-images.githubusercontent.com/58889880/70855630-f7313380-1e82-11ea-9e2f-ecee769dc7b9.png)
![Red Dead Redemption 2 Screenshot 2019 12 14 - 15 02 45 23](https://user-images.githubusercontent.com/58889880/70855631-fa2c2400-1e82-11ea-90fe-63086578a649.png)
