### ISSUE TITLE
Treasure map filters

### ISSUE THREAD

**Issue by Ralek** [jeanropke/RDR2CollectorsMap#467]
Treasure map filters are not saved between reloads.
This forces you to have to turn on the maps you have whenever you reload the page.

Would be nice if they behaved like the collectible filters. If you turn one on, it should stay on until you manually remove it, either from the list or by using the remove from map button on its map icon.
As a further improvement, map filters should not reset daily even if you have the "Reset markers daily" setting turned on, as treasure maps are not related to the daily cycle.

Normally, this isn't a big deal, but with the current digging for the new cycle system, I'm reloading the page frequently, making it a real pita.

**Comment by jeanropke** [comment]
Treasures keeps enabled between pages reloads
