### ISSUE TITLE
Hajnal Garnet Bangle Bracelet - Cycle 5

### ISSUE THREAD

**Issue by Ciomg** [jeanropke/RDR2CollectorsMap#475]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 5
* Coordinates or a clear image of the location Hajnal Garnet Bangle Bracelet - Cycle 5
![bruh](https://user-images.githubusercontent.com/58892558/70855056-12c12c00-1ecd-11ea-81cb-867db98b997e.png)
* Include the item name Hajnal Garnet Bangle Bracelet

Coordinates can be found by setting the `Show coordinates on click` to `Yes` 
lat: 3
lng: -0.75

**Comment by jeanropke** [comment]
Markers off the map does not have a known position.
