### ISSUE TITLE
Random items?

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#476]
Please verify whether those are random or not, because they are all found without map. 
If it's duplicate, please remove

Cycle 5
I got 1797 gold eagle coin from it.

lat: -69.1484375
lng: 136.4765625

![image](https://user-images.githubusercontent.com/58512865/70855131-50e13000-1e7a-11ea-9ddf-bd7362a9a54a.png)
![image](https://user-images.githubusercontent.com/58512865/70855122-327b3480-1e7a-11ea-9b3d-73a555e0b565.png)

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70855159-e977b000-1e7a-11ea-90e1-8cace875e352.png)
![image](https://user-images.githubusercontent.com/58512865/70855168-090ed880-1e7b-11ea-8798-5d9b16d7d7f7.png)

Could be random again or it is actually the item, because I found it blind.
lat: -70.265625
lng: 138.203125

**Comment by dlldldl** [comment]
Chocolate daisy #1 and #5 are duplicates

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70855420-6dcc3200-1e7f-11ea-8080-cde7e46be531.png)
![image](https://user-images.githubusercontent.com/58512865/70855424-77ee3080-1e7f-11ea-9dde-7fed56e9cd9f.png)
lat: -56.6328125
lng: 87.46875
should be random?

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70855471-137fa100-1e80-11ea-8a02-21fd683dc6ab.png)

![image](https://user-images.githubusercontent.com/58512865/70855481-30b46f80-1e80-11ea-90a2-3396160c530d.png)

lat: -51.921875
lng: 77.21875

**Comment by dlldldl** [comment]
Ursula Citrine Earrings - Cycle 5 is metal detector not shovel.

**Comment by jeanropke** [comment]
Confused: random / Heart: confirmed/updated

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70855775-45473680-1e85-11ea-94b0-763373e3b22f.png)
![image](https://user-images.githubusercontent.com/58512865/70855779-5c862400-1e85-11ea-8746-2de47bf5bf76.png)
Same as old Random Item #27

**Comment by dlldldl** [comment]
Posts after this are from Cycle 6.

![image](https://user-images.githubusercontent.com/58512865/70856735-e5598b80-1e96-11ea-8e0a-bff2afe0595e.png)
Same as old Random Item #1

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70866951-9e19dc00-1f24-11ea-9adf-46caeb7995c9.png)
![image](https://user-images.githubusercontent.com/58512865/70866956-aa9e3480-1f24-11ea-9620-96da9f175a83.png)
Same as Random Item #31 I corrected.

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70867851-0d94c900-1f2f-11ea-81f1-f026161a05b9.png)
![image](https://user-images.githubusercontent.com/58512865/70867855-1ab1b800-1f2f-11ea-8d89-5d3904f7d873.png)
Same as old
Random Item #38
