### ISSUE TITLE
Incorrect item Cycle: day # 5

### ISSUE THREAD

**Issue by enix505** [jeanropke/RDR2CollectorsMap#477]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`
![DD9D5E53-35F0-4CC2-AE6D-0ED74F811235](https://user-images.githubusercontent.com/58893670/70855758-6ad83e00-1e8d-11ea-9bd6-09ff46c7a615.jpeg)

Cycle 5 1800 golden dollar

**Comment by jeanropke** [comment]
This coin is on map.
