### ISSUE TITLE
We need a mean to contribute, to put new item locations! How?

### ISSUE THREAD

**Issue by rgrishanov** [jeanropke/RDR2CollectorsMap#478]
Maybe we could click, select type/class/collection/item and then it could appear on map to others to confirm, as unconfirmed? I just found some items but can not tell others about that...
Thanks for the awesome map/app!

**Comment by jonathonbarton** [comment]
The Missing Random Item Report works even though the items aren't Random Items.
https://github.com/jeanropke/RDR2CollectorsMap/issues/182

You can state what item you found, get the coordinates, and include notes about where it is and what "cycle" you think it's on. 

For instance I found a "Cycle 1" Cardinal Flower next to the Moonshiner Shack in Bayou Nwa yesterday, and submitted it for Cycle 5.

**Comment by rgrishanov** [comment]
Ok, I managed to understand all the instructions and use the form to submit items and even how to show coordinates on the map. And I will post all the items I find. But. It is too obscure and not trivial to most players, which contributions are so much needed at this time. I think a message should show upon loading the map, like "Dear players/users, rockstar reset it all, please help us submit all items you find, click here to submit, etc". And very clear instructions how to do so.

**Comment by jeanropke** [comment]
Use the Discord server. https://discord.gg/WJfrtmR
