### ISSUE TITLE
Blue lines drawing on left mouse click in BETA version.

### ISSUE THREAD

**Issue by Kiddamned** [jeanropke/RDR2CollectorsMap#48]
When you left click on map you get a straight blue line. After 2-3 hours of active map usage this undeletable lines starts to be annoying and all map looks similar to my screenshot =) 
![30092019 - 01](https://user-images.githubusercontent.com/49915750/65851180-a9645f00-e35a-11e9-93c8-ec7851ff5d24.png)

**Comment by jeanropke** [comment]
I'll added an option to clear custom routes and a button to remove the last node added

**Comment by jeanropke** [comment]
Added option to enable custom routes.
Left Control + Left Click to remove last node added.
