### ISSUE TITLE
Speculations Cycle #6: some of the item pattern matches original cycles, or new pattern is discovered. 

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#480]
To summarize, with fairly high confidence, coins and lost jewelry of Cycle #6(definitely a new cycle) is the same as Cycle #3. Verification and support of #488 

See posts below for supporting evidences.

Family Heirloom 
![image](https://user-images.githubusercontent.com/58512865/70856350-d91e0000-1e8f-11ea-9f1a-df609f868b0a.png)

Zoomed in and analysis:

This is close to but not exactly at:
Metal Hairpin Heirloom - Cycle 2
 On the side of the barn near some stacked crates.
![image](https://user-images.githubusercontent.com/58512865/70856358-f783fb80-1e8f-11ea-8500-37759941a590.png)

This is a new location, nothing has found there in previous three cycles.
![image](https://user-images.githubusercontent.com/58512865/70856360-0074cd00-1e90-11ea-944d-eba2d0d8a58f.png)

This could be the same as:
New Guinea Rosewood Hairbrush Heirloom - Cycle 1
On a chair in the room on the main floor.
![image](https://user-images.githubusercontent.com/58512865/70856362-08347180-1e90-11ea-8ea6-efee6b9faa9b.png)

Looks like a new pattern.

**Comment by jonathonbarton** [comment]
Submit! 
https://github.com/jeanropke/RDR2CollectorsMap/issues/182

**Comment by dlldldl** [comment]
Lost Jewelry
![image](https://user-images.githubusercontent.com/58512865/70856391-c22bdd80-1e90-11ea-8c85-7e45be9f9381.png)

Zoomed in and analysis:
Elliston Carved Bracelet - Cycle 3
 West side of the church near the entrance of the graveyard.
![image](https://user-images.githubusercontent.com/58512865/70856395-de2f7f00-1e90-11ea-87ee-d5b9455145e9.png)

Emmeline Coral Earrings - Cycle 3
 Next to the railroad at the start of the small bridge.
![image](https://user-images.githubusercontent.com/58512865/70856401-22228400-1e91-11ea-9f71-70cd7a2ef008.png)

Ursula Citrine Earrings - Cycle 3
 Between two rocks.
![image](https://user-images.githubusercontent.com/58512865/70856405-31093680-1e91-11ea-8974-44d3581cc636.png)

**Comment by dlldldl** [comment]
> Submit!
> #182

Yeah, I know, but I have never been to those location to verify them, I will submit when I actually see those locations. Those I posted are pure speculations.

**Comment by dlldldl** [comment]
Coins:
![image](https://user-images.githubusercontent.com/58512865/70856418-a248e980-1e91-11ea-9947-cde71b2e2d91.png)


From left to right, those matches the location of:
1795 Half Eagle Coin - Cycle 3
 Under bridge.
1800 Gold Dollar Coin - Cycle 3
 In between a big and small rock.
1800 Gold Quarter Coin - Cycle 3
 Under tree on cliff side.

It could be that all coins can be found in original Cycle 3 locations.

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70856539-8cd4bf00-1e93-11ea-8afa-3ab15d0f97e8.png)
![image](https://user-images.githubusercontent.com/58512865/70856541-9b22db00-1e93-11ea-83b3-b2675653fcac.png)

Found not as a part of the map I got:
Dane Topaz Necklace - Cycle 3
In the mass grave.
I'm pretty confident that all of the Jewlries and coins are what was in old Cycle #3, @jeanropke maybe try using the whole Cycle #3 set for Jewlries? It doesn't seem to be the case that we're on old cycle #3 since the family heirloom part doesn't match.

**Comment by Sr-Drako** [comment]
Tarots Cards seems to be from cycle 1 too. All of Lagras cards i found so far are in the same places as cycle 1

**Comment by dlldldl** [comment]
Some verification of: #488

**Comment by huanhuan271** [comment]
lat: -81.546875
lng: 90.53125
Ojeda Rose Gold Bangle Bracelet

**Comment by huanhuan271** [comment]
lat: -60.1875
lng: 96.171875
Metal detector
Slate Arrowhead

**Comment by huanhuan271** [comment]
lat: -41.421875 
lng: 104.1171875
Metal detector
Splintered Arrowhead

**Comment by dlldldl** [comment]
> lat: -60.1875
> lng: 96.171875
> Metal detector
> Slate Arrowhead



> lat: -41.421875
> lng: 104.1171875
> Metal detector
> Splintered Arrowhead

@jeanropke Those two locations are valid for Cycle 6, which means Cycle 4 too.
