### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by kamill5011** [jeanropke/RDR2CollectorsMap#481]
Today all cards locations should be from Day 1 i collect 5 and all was correct. Alcohol probably too its from day 1.

**Comment by jeanropke** [comment]
Map updated

**Comment by kamill5011** [comment]
Yep alcohol should be from day 1 in my opinion. jewellery dont match i start Here 
![20191215_005821](https://user-images.githubusercontent.com/35744994/70856525-70a64180-1ed6-11ea-8a06-5a30af8cb092.jpg)
![20191215_005828](https://user-images.githubusercontent.com/35744994/70856528-74d25f00-1ed6-11ea-9327-7bb4667a11c4.jpg)
![Screenshot_20191215-005857_Chrome](https://user-images.githubusercontent.com/35744994/70856531-78fe7c80-1ed6-11ea-824c-d8c3ccaf165f.jpg)
