### ISSUE TITLE
Suggestion for new item data structure

### ISSUE THREAD

**Issue by Senexis** [jeanropke/RDR2CollectorsMap#482]
I suggested this on Discord as well, but it may be a good idea to migrate the `items.json` structure to something like this to make it easier for yourself to update the cycles instead of having to add the cycle number to each item. Would probably be easier in general to make new cycles. Up to you.

```
{
    "cycles": {
        1: {
            "coins": 1,
            "heirlooms: 3,
            ...
        },
        2: {
            "coins": 2,
            "heirlooms": 5,
            ...
        },
        3: {
            "coins": 4,
            "heirlooms": 1,
            ...
        }
    },
    "coins" {
        1: {
            { "1898 whatever": "coords" },
            ...
        },
        2: {
            { "1898 whatever": "coords" },
            ...
        },
        ...
    },
    "heirlooms" {
        1: {
            { "comb or something": "coords" },
            ...
        },
        2: {
            { "comb or something": "coords" },
            ...
        },
        ...
    },
    ...
}
```

**Comment by jeanropke** [comment]
I'll start working on something like this

**Comment by Sr-Drako** [comment]
Thank you jeanropke and EVERYONE else in this community for aidding in this map. Seems todays cycle is a new one with a mix of cycle 1 and 3 with new items moved to new places, that's why i think it is cycle 6. THANKS AGAIN FOR ALL THE HARD WORK YOU DO!

ps. didn't want to start a new thread for this, i hope you read it jeanropke. THANKS

**Comment by Senexis** [comment]
@jeanropke Should you ever want to implement this, I already wrote a simple script to convert the existing data.

```
async function run() {
    let newObj = {};
    let response = await fetch('https://jeanropke.github.io/RDR2CollectorsMap/data/items.json?cache=' + (new Date).getTime());
    let data = await response.json();
    for (const [key, value] of Object.entries(data)) {
        newObj[key] = {};
        value.forEach(item => {
            if (item.day instanceof Array) {
                var tempDay = item.day;
                tempDay.forEach(day => {
                    if (newObj[key][day] === undefined) {
                        newObj[key][day] = [];
                    }

                    delete item.day;
                    newObj[key][day].push(item);
                });
            } else {
                var tempDay = item.day;
                if (newObj[key][tempDay] === undefined) {
                    newObj[key][tempDay] = [];
                }

                delete item.day;
                newObj[key][tempDay].push(item);
            }
        });
    }
    console.log(JSON.stringify(newObj));
}

run();
```

**Comment by dlldldl** [comment]
@jeanropke 
I found it better to list it like this considering now the new rule have been added and easier copy and paste adding coords:

{
	"card_cups": [
                [ //cycle 1
			{"text": "cups_ace", "tool": "0", "lat": "-26.421875", "lng": "90.65625", "video": "}, //displaying lat and lng by "Show coordinates on click", display partial json"lat": "-26.421875", "lng": "90.65625" instead of having it formatted, so you don't have to make it x and y 
			{"text": "cups_two", },
			...
			{"text": "cups_king", ... } ],
                [ //cycle 2
			{"text": "cups_ace", ...},
			{"text": "cups_two", ...},
			...
			{"text": "cups_king", ...} ],
                ]
        ],
}

I know you're trying to make them continuous, and easier to understand for people who don't count from zero, but array indexes are internal, and comments like //cycle 1 and //cycle 2 is sufficient to label them in file.

**Comment by Senexis** [comment]
Already done.
