### ISSUE TITLE
Eggs Locations

### ISSUE THREAD

**Issue by CesarAugustoJoaquim** [jeanropke/RDR2CollectorsMap#485]
Duck Egg 
lat: -86.515625 
lng: 72.4765625
Near Aurora Basin

**Comment by Sr-Drako** [comment]
Garcet Egg
lat: -69.0859375
lng: 140.1171875
Scarlett Meadow, Lemoyne, near the bridge there.

**Comment by Glovie** [comment]
Egret Egg - on the left side of the river from the B in Bluewater Marsh, in a tree next to the crossroad 
Heron Egg - There is a dock to the left of the S in Saint Denis. Above that dock the map is "cracked"
Vulture Egg - Above the A in Annesburg, on the top of the hill.

**Comment by gyp-rdo** [comment]
Dec 15 

Spoonbill egg
lat: -90.625
lng: 142.3359375

**Comment by dlldldl** [comment]
> Dec 15
> 
> Spoonbill egg
> lat: -90.625
> lng: 142.3359375

![image](https://user-images.githubusercontent.com/58512865/70867684-d3c2c300-1f2c-11ea-9c47-d883c3415041.png)
![image](https://user-images.githubusercontent.com/58512865/70867687-e1784880-1f2c-11ea-9ce0-6fb5354694bc.png)

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70867736-6cf1d980-1f2d-11ea-87fc-2cc8e48b538b.png)
Heron Egg mentioned above:
lat: -81.5078125
lng: 146.2578125

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70867788-2f418080-1f2e-11ea-83f0-8db29860791b.png)
Egret Egg mentioned above:
lat: -68.9765625
lng: 140.1796875

**Comment by funcmatic** [comment]
lat: -71.828125
lng: 73.3515625
Right under Owanjila, west from Strawberry
