### ISSUE TITLE
IMPORTANT !!!As for the new cycle that started one hour and a half ago!

### ISSUE THREAD

**Issue by maximu** [jeanropke/RDR2CollectorsMap#487]
Coins and jewlery are on cycle 3 locations and tarot cards are on cycle 1locations !

**Comment by Sr-Drako** [comment]
YEAH! I found in Lagras a calumet pendant from cycle 3 and all tarots cards from cycle 1 there. Seems this cycle 6 is a mix of those 2 with some other items in new places too.
