### ISSUE TITLE
Almost confirmed, Tarots Cards from this new cycle(6) are same as cycle 1

### ISSUE THREAD

**Issue by Sr-Drako** [jeanropke/RDR2CollectorsMap#490]
I've been in Lagras collecting cards from cycle 1, even used a collector map and it send me to 3 cards around Lagras from cycle 1. Now I'm in Rhodes Town and all 3 cards in there are from cycle 1. I think it is almost confirmed that the cycle 6 cards are from cycle 1. Just leaving a helpful note here, close it as soon as you want.

**Comment by Sr-Drako** [comment]
Seems Jewelry too,  Infanta Turquoise Bracelet was in the same place as cycle 3, 
lat: -78.953125
lng: 133.03125
North of Rhodes

**Comment by jonnyturbo** [comment]
Yeah I’ve got the card over the fire place near the post office in van horn from cycle 1
