### ISSUE TITLE
Cycle 6 Heirlooms

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#491]
Rosewood Hairbrush
![image](https://user-images.githubusercontent.com/58512865/70857152-581a3500-1e9e-11ea-94f5-bd60571edf1d.png)
lat: -79.1953125
lng: 137.8046875

**Comment by Glovie** [comment]
![unknown (1)](https://user-images.githubusercontent.com/47953335/70857207-96d5dc80-1eea-11ea-9fc8-99be33c2d0ef.png)
TOP-Turtoiseshell Comb; 
RIGHT-Horse Hair Brush; 
LEFT-Ebony Hairbrush

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70857503-91ee3a00-1ea4-11ea-8b15-20184b506213.png)
lat: -84.953125
lng: 131.9453125

**Comment by dlldldl** [comment]
> ![unknown (1)](https://user-images.githubusercontent.com/47953335/70857207-96d5dc80-1eea-11ea-9fc8-99be33c2d0ef.png)
> TOP-Turtoiseshell Comb;
> RIGHT-Horse Hair Brush;
> LEFT-Ebony Hairbrush

It would be more helpful to get a coordinates and/or screenshot of the actual item if you have collected them.

**Comment by dlldldl** [comment]
![image](https://user-images.githubusercontent.com/58512865/70865862-18436400-1f17-11ea-81fe-404a0d0bdabf.png)

lat: -105.9375
lng: 36.9375
