### ISSUE TITLE
Flowers 15 Dec

### ISSUE THREAD

**Issue by Glovie** [jeanropke/RDR2CollectorsMap#492]
Flowers appear to be part of Cycle 2, however night flowers are still unaccounted for so please keep an eye on them.

I also posted some egg locations in another topic called "Duck eggs" even though it contains more items.

Goodluck on getting everything back on it's feet!

**Comment by dlldldl** [comment]
I don't find the claim true, because I couldn't find blood flower #4 and cardinal flower #4. I found creek plums a good indication of which day it is, if you found any creek plum location, post a picture.

**Comment by Glovie** [comment]
This information along with the rest of it has been gathered with the help of the rest of the community, on the Red Dead Online official Discord server: https://discord.gg/m3V42g

There are many item locations posted with pictures and everything unfortunately I don't have the time to transfer everything here
