### ISSUE TITLE
Cycle 5 and Cycle 4 revisit

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#493]
Cycle 5 has the same egg pattern as Cycle 1 except the egret egg that always gets stuck.
![egret1](https://user-images.githubusercontent.com/58512865/70857778-bc8ec180-1ea9-11ea-8c1f-f9406d82eb9f.png)

I have collected the following to verify that it is true.
egg_spoonbill
egg_egret
egg_goose_1
egg_eagle_1
egg_loon
egg_duck

**Comment by dlldldl** [comment]
Cycle 5 also has the same heirloom pattern as Cycle 3.
I have collected the following to verify:
heirlooms_jade_hairpin
heirlooms_ebony_hairbrush
heirlooms_new_guinea_rosewood
heirlooms_tortoiseshell_comb
heirlooms_cherrywood_comb
heirlooms_boxwood_comb
heirlooms_carved_wooden
heirlooms_ivory_comb
heirlooms_ivory_hairpin
heirlooms_horse_hair_brush

**Comment by dlldldl** [comment]
Cycle 4 has the same Jewlery location as in Cycle 1.

**Comment by dlldldl** [comment]
Cycle 4 seems to have the same arrow location as Cycle 6, from Chipped and Quartz

**Comment by benzon** [comment]
You gotta remember we aint on cycle 5 anymore it changed cycle 4 hours ago :)
