### ISSUE TITLE
[BUGS] Settings Cycle broke, Collected counter broken

### ISSUE THREAD

**Issue by benzon** [jeanropke/RDR2CollectorsMap#494]
Okay so under settings the cycle box is empty so no method of changing cycle right now.

And the Collected counter is broken just says Collected {count} of {max}

**Comment by vxcreation** [comment]
experiencing this issue on all browsers as well, cleared cache and updated. Friend however does NOT seem to be experiencing this bug but may have had a cached version of the website

**Comment by benzon** [comment]
I can see you changed settings, perfect, the collected counter is still broken right now tho.
