### ISSUE TITLE
New location Madam Nazar. December 15

### ISSUE THREAD

**Issue by qwnbcd** [jeanropke/RDR2CollectorsMap#495]
I found Madame Nazar in a new location. December 15th. 
![Madam Nazar](https://user-images.githubusercontent.com/58901862/70859946-b6d5c200-1f23-11ea-843e-e5683de1f458.jpg)

Coordinates: lat: -43.1015625
lng: 132.8515625

**Comment by bugproof** [comment]
how do you check the coordinates?

**Comment by CaliMeatWagon** [comment]
> I found Madame Nazar in a new location. December 15th.
> ![Madam Nazar](https://user-images.githubusercontent.com/58901862/70859946-b6d5c200-1f23-11ea-843e-e5683de1f458.jpg)
> 
> Coordinates: lat: -43.1015625
> lng: 132.8515625

That's not a new location.

**Comment by qwnbcd** [comment]
If you don’t know, I tell you, Madame Nazar’s location changes every day. If you carefully look at the date of my post and the date of the calendar, you will understand that you are right, but this is your problem, that you are inattentive and know little.
