### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by qwnbcd** [jeanropke/RDR2CollectorsMap#496]
Ojeda Rose Gold Bangle Bracelet is not present on these coordinates (lat: -58.0390625 lng: 113.765625), under the ledge. Searched with a metal detector and did not find a bracelet.
![Missing Item](https://user-images.githubusercontent.com/58901862/70860752-60ba4c00-1f2e-11ea-980b-ea58272a3375.jpg)

**Comment by Touchmymonkeyuk** [comment]
I just checked and it is there. You might need to change servers as sometimes things don't show up.

**Comment by Quahox** [comment]
> Ojeda Rose Gold Bangle Bracelet is not present on these coordinates (lat: -58.0390625 lng: 113.765625), under the ledge. Searched with a metal detector and did not find a bracelet.
> ![Missing Item](https://user-images.githubusercontent.com/58901862/70860752-60ba4c00-1f2e-11ea-980b-ea58272a3375.jpg)

Restart your game for some reason my collectibles did not loaded in when i launched game today for first time but it worked after complete restart of game.

**Comment by qwnbcd** [comment]
Yeah, restart game help
