### ISSUE TITLE
[Feature] Merge RDOMap and RDR2CollectorsMap

### ISSUE THREAD

**Issue by benzon** [jeanropke/RDR2CollectorsMap#497]
**Is your feature request related to a problem? Please describe.**
Merge RDOMap and RDR2CollectorsMap in to one site.

**Describe the solution you'd like**
Create one site for getting all info about RDR2 insted of having to go to different sites.

**Additional context**
Would speed up things quite abit being able to have everything in one site, so you can open it up - and just toggle the things you need when you need them, insted of having to open up multiple sites.

**Comment by Senexis** [comment]
Sure it would speed up seeing all the items in one place. However, due to the massive amounts of markers that are on both maps, it would probably slow navigation down and make everything more sluggish. This probably won't happen.
