### ISSUE TITLE
Vulture egg location

### ISSUE THREAD

**Issue by Edinsho** [jeanropke/RDR2CollectorsMap#500]
Vulture egg 
 Coordinates : lat: -40.984375
                       lng: 147.8203125
is at the very top of the hill

Egret egg
Coordinates: lat: -69.0703125
                     lng: 140.046875

![image](https://user-images.githubusercontent.com/58910603/70864443-e8e52500-1f1f-11ea-9067-5e968a6fdb47.png)

![image](https://user-images.githubusercontent.com/58910603/70864568-28604100-1f21-11ea-9db9-7a62bb2effe8.png)

**Comment by jeanropke** [comment]
Added on the map
