### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by bradgrubbs** [jeanropke/RDR2CollectorsMap#502]
I don’t have any knowledge in reference to programming or coding, but I would like to help with this project since everything has been reset. If you have an assignment I can complete (keeping in mind I work a full time job too), I’m happy to do whatever is needed. An example could be: buy certain specific maps from Nazaar every day and report back the collectible locations for those maps/items. I can be pretty detailed in my findings. I’m just an RDR Oniline fan that really appreciates this map. I don’t know how to use this site, so just email me at bradgrubbs@hotmail.com. Put “RDR collectible map” in the subject line and I’ll get busy on whatever you give me as time allows!

**Comment by dlldldl** [comment]
Maybe just play the game and submit the items not shown on the interactive maps here.

**Comment by gravydave1974** [comment]
there's an egret egg in a dead tree where I've marked the red X today 15/12/19

![egret egg](https://user-images.githubusercontent.com/58914391/70866396-0d152600-1f61-11ea-977c-e5f488a123ec.jpg)

**Comment by zyrtec57** [comment]
Hi, I'm a bit lost since the update, I don't know the right cycle / day. What cycle are we today? And how many cycle in total?
Sorry for my bad english and good game.

**Comment by bradgrubbs** [comment]
Will do!  I’m glad to help any way I can!

Sent from my iPhone

On Dec 15, 2019, at 11:46 AM, dlldldl <notifications@github.com> wrote:

﻿

Maybe just play the game and submit the items not shown on the interactive maps here.

**Comment by Senexis** [comment]
Make sure to join the Discord for helping with stuff like locations and verifying that items are correct! See the README for more.
