### ISSUE TITLE
Map Uploading

### ISSUE THREAD

**Issue by KamaroRN** [jeanropke/RDR2CollectorsMap#505]
I went onto your map, as i had been off it for a couple days due to the new release of Moonshiners and noted that there were a whole bunch of different color icons on the map.  This being noted that multiple cycle dates are showing at one time and when i reset them manually, as there is not a button to change the cycle date anymore, if i refresh the web page, the map goes back to the original multicolor icon display.  this is a huge issue because it is now not saving previously saved data.  

I also noticed that random spots are no longer available.  I would like to first of all thank you, as this map has been a life saver and a huge cash grab in this game, as i have made tons doing the collector role.  I am hoping that these issues can be fixed soon to avoid having to pay Madam Nazar for random maps.  again, I would like to give you my greatest appreciation but would like to bring your attention to a few things that are not working as they should.  have a great day.

**Comment by funkybluehen** [comment]
Rockstar has removed many random locations that were previously on this map, amd perhaps there are new ones but there are also new locations for some items, until we see 2 or 3 days with multiple verifications, it will be hard to say if they are random or new item locations.
