### ISSUE TITLE
[Add Feature Again] Condor Egg

### ISSUE THREAD

**Issue by benzon** [jeanropke/RDR2CollectorsMap#506]
Just wondering do we get condor eggs back it was such a nice feature to have...

**Comment by benzon** [comment]
But why can we adleest get a word on why? since it worked perfect before.

**Comment by Sleyxz** [comment]
Not so nice, to be honest. From "egg search" event turned into "who guesses and the first runs"

**Comment by benzon** [comment]
To be honest its still that way... Had a Condor Egg last night litterly took a guy 30 sec to find the egg.
