### ISSUE TITLE
[BUG] Cookie size issue

### ISSUE THREAD

**Issue by benzon** [jeanropke/RDR2CollectorsMap#508]
Okay, so when using the hide feature of items, the cookie can get a bit large, and in the end it actually makes it impossible to visit the site unless you know how to delete cookies, i think they need to be shared out on even more cookies to avoide one single cookie getting to big.

**Comment by jeanropke** [comment]
I disabled all markers and no problem on Chrome. 
But I reduced from 2400 to 2000 cookie length

**Comment by benzon** [comment]
Just to mention i used the button when you click a marker, so it saves an amount you collected somehow it adds 4 by it self and then it goes nuts ad some point
