### ISSUE TITLE
Incorrect item Cycle: Monday#

### ISSUE THREAD

**Issue by flackyard** [jeanropke/RDR2CollectorsMap#511]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? monday
* Coordinates or a clear image of the location
* Include the item [name]([url](url
![Sans titre](https://user-images.githubusercontent.com/58934471/70893081-a5a3b880-1fea-11ea-9246-00b7d060d4ea.png)
))

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by YdaydreamerY** [comment]
family heirlooms are in cycle 1, the rest seems to be in cycle 2
