### ISSUE TITLE
Incorrect item Cycle: day 5 Hajnal Garnet Bangle Bracelet

### ISSUE THREAD

**Issue by NF13** [jeanropke/RDR2CollectorsMap#515]
* What day cycle it is?
5

* Coordinates or a clear image of the location
![new1](https://user-images.githubusercontent.com/6102845/70911701-ba944200-2012-11ea-9d31-4538c114ee46.JPG)
![new2](https://user-images.githubusercontent.com/6102845/70914161-ba4a7580-2017-11ea-8e2e-d9ae903502cb.JPG)
![new3](https://user-images.githubusercontent.com/6102845/70911710-bff18c80-2012-11ea-963d-a3db8af07f45.JPG)
![new4](https://user-images.githubusercontent.com/6102845/70911724-c3851380-2012-11ea-980e-3d44ec07ccc5.JPG)

* Include the item name
Hajnal Garnet Bangle Bracelet

#182

**Comment by jeanropke** [comment]
commit b455c3b
