### ISSUE TITLE
Incorrect item Cycle: day 5 Royal Victoria Diamond Earrings

### ISSUE THREAD

**Issue by NF13** [jeanropke/RDR2CollectorsMap#516]
* What day cycle it is?
5

* Coordinates or a clear image of the location
![new1](https://user-images.githubusercontent.com/6102845/70913624-aeaa7f00-2016-11ea-95c2-b3630c9e6682.JPG)
![new2](https://user-images.githubusercontent.com/6102845/70913629-b1a56f80-2016-11ea-849e-2249bf2532a0.JPG)
![new3](https://user-images.githubusercontent.com/6102845/70913632-b36f3300-2016-11ea-92cd-ba64d6157d8d.JPG)

* Include the item name
Royal Victoria Diamond Earrings

#182

**Comment by jeanropke** [comment]
commit 68ffbf1
