### ISSUE TITLE
BEAULIEUX DIAMOND RING Cycle: day 5

### ISSUE THREAD

**Issue by Touchmymonkeyuk** [jeanropke/RDR2CollectorsMap#517]
Coords for the BEAULIEUX DIAMOND RING.

lat: -123.76759371939326
lng: 42.169372215800124

![Red Dead Redemption 2 Screenshot 2019 12 16 - 17 56 55 47](https://user-images.githubusercontent.com/58904912/70931059-80d13480-202e-11ea-8783-b27d29874d48.png)

![Red Dead Redemption 2 Screenshot 2019 12 16 - 17 57 10 67](https://user-images.githubusercontent.com/58904912/70931068-8464bb80-202e-11ea-9213-498dab9a481f.png)

![Red Dead Redemption 2 Screenshot 2019 12 16 - 17 57 16 60](https://user-images.githubusercontent.com/58904912/70931078-86c71580-202e-11ea-976b-52fa8162bb71.png)

**Comment by jeanropke** [comment]
commit b455c3b
