### ISSUE TITLE
Incorrect item Cycle: Carved Wooden Hairpin Heirloom - Cycle 1

### ISSUE THREAD

**Issue by Jaander69** [jeanropke/RDR2CollectorsMap#518]
was'nt on the location.

**Comment by jeanropke** [comment]
Pino de Madeira Entalhada means Carved Wooden Hairpin
![EL7ZBjCWwAAWXiD](https://user-images.githubusercontent.com/6243818/70932288-262cde00-2018-11ea-9c18-4a511503aa72.jpg)
