### ISSUE TITLE
Royal Victoria Diamond Earrings - Cycle 5

### ISSUE THREAD

**Issue by Jaander69** [jeanropke/RDR2CollectorsMap#519]
a friend of mine said that this item was no where to be found. I'm not sure if he's right because I was hunting jewelry earlier today, so I might have found it. but check it out. :)

**Comment by Touchmymonkeyuk** [comment]
Already been added to the map today.

![Screenshot_9](https://user-images.githubusercontent.com/58904912/70943766-84be8000-2049-11ea-941b-7aba832ccfab.png)

**Comment by Jaander69** [comment]
they went there and didn't find it.. i'l try. one second...

**Comment by Jaander69** [comment]
no probs... got it.. it's there.... ;)
