### ISSUE TITLE
第三天 1789 Penny Coin 位置错误

### ISSUE THREAD

**Issue by yamazakitouma** [jeanropke/RDR2CollectorsMap#52]
![image](https://user-images.githubusercontent.com/28669193/65885415-3516d380-e3cd-11e9-8b56-2e8ba01b09a1.png)

实际位置

**Comment by iligalodin** [comment]
Google translate: 我会检查位置，可能是这是随机物品...

**Comment by iligalodin** [comment]
did you find it in a cabinet? i've found tennessee whiskey there

你在壁橱里找到硬币了吗？ 我在那里找到田纳西州威士忌。

**Comment by iligalodin** [comment]
there was no 1789 . i found "1800 gold dollar"

没有1789年。 我发现“ 1800金币”
