### ISSUE TITLE
Today's Tarot Cups cycle seems to be #4!

### ISSUE THREAD

**Issue by PogoMan361** [jeanropke/RDR2CollectorsMap#520]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by maximu** [comment]
and hairlooms on 5, dont know the other stuff tho

**Comment by CesarAugustoJoaquim** [comment]
Arrowheads: Cycle 1
Antique Alcohol Bottles: Cycle 1
American Wild Flowers: Cycle 1

Bird eggs, all lost jewelry and coins non cycle match

**Comment by Touchmymonkeyuk** [comment]
Yep, bought a map for lost Jewelry and they are in places i've never been to before.

**Comment by maximu** [comment]
they don't even match the red and purple cycles? damn

**Comment by PogoMan361** [comment]
I needed the metal detector for Goat Hair Brush (cycle 5)
