### ISSUE TITLE
Bracelet

### ISSUE THREAD

**Issue by bradgrubbs** [jeanropke/RDR2CollectorsMap#524]
5/16/19 10:35 eastern time USA. Bracelet (not sure which one) by animal pen at flat neck station. Must be found with metal detector.

**Comment by Touchmymonkeyuk** [comment]
I bought a map because no cycles were showing anything and that was the first one i found. Never been to that location before at all so now wondering how many cycles they have put in the game. Hoping it isn't 365 lol

**Comment by bradgrubbs** [comment]
That would be messed up!  I did the same (bought a map). Can’t afford that every day though!

**Comment by Touchmymonkeyuk** [comment]
Buying a map every day isn't the problem. Buying 18 maps a day is. Jewelry and coins is 54 items. Coins on their own are 15 so thats is 5 maps, and the rest on the rest.

Not only would it eat into any money made after collecting those 5 sets it would take a long time to do as you have to go back to the mad woman in a caravan after using the map.

**Comment by jeanropke** [comment]
Bracelets added
