### ISSUE TITLE
1 more jewelry item

### ISSUE THREAD

**Issue by bradgrubbs** [jeanropke/RDR2CollectorsMap#525]
Pilgrim Moonstone Ring:
12/16/19 11:07pm Eastern time USA
Metal detector 
By the rock wall. Outside Wallace Station. Photo attached. 
![B68A731B-3D1E-4D3B-9DD8-3C52922DEF63](https://user-images.githubusercontent.com/58911699/70964234-197caa00-2059-11ea-9290-b4b91a5458a9.jpeg)

**Comment by jeanropke** [comment]
Lost jewelry added
