### ISSUE TITLE
Abello Ruby Bangle Bracelet (December 16th)

### ISSUE THREAD

**Issue by kittrellbj** [jeanropke/RDR2CollectorsMap#526]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
December 16th. Not sure how cycles are working right now.

* Coordinates or a clear image of the location
lat: -69.2421875
lng: 104.625
https://imgur.com/oDAvNBg
https://imgur.com/0fsrSTb

* Include the item name
Abello Ruby Bangle Bracelet

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

Notation:

"Near pig pen between two train loading ramps."

**Comment by jeanropke** [comment]
All bracelets added
