### ISSUE TITLE
Pilgrim Moonstone Ring (December 16th)

### ISSUE THREAD

**Issue by kittrellbj** [jeanropke/RDR2CollectorsMap#527]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? December 16th. Don't know how cycles are running right now.

* Coordinates or a clear image of the location
lat: -58.5390625
lng: 92.8984375

https://imgur.com/cMja26P

* Include the item name
Pilgrim Moonstone Ring

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

Notation: "Under cliff overhang near river shore."

**Comment by jeanropke** [comment]
All rings added
