### ISSUE TITLE
Orchidee Diamond Earrings (December 16th)

### ISSUE THREAD

**Issue by kittrellbj** [jeanropke/RDR2CollectorsMap#528]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? December 16th.

* Coordinates or a clear image of the location
lat: -49.96875
lng: 104.1796875

https://imgur.com/DxqXDhJ

* Include the item name
Orchidee Diamond Earrings

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

Notation: "Top of cliff under a dead tree."

**Comment by jeanropke** [comment]
All earrings added
