### ISSUE TITLE
[Suggestion] Show Madam Nazar Location on the map

### ISSUE THREAD

**Issue by sundaran-rm** [jeanropke/RDR2CollectorsMap#53]
Show Madam Nazar location on the collector map if possible for respective days.

**Comment by iligalodin** [comment]
i believe nazar is not on a specific rotation so that would be hard

**Comment by chrissydewet** [comment]
or do this, give us that use your map, to let you know where she is for the day. give option at the bottom "NAZAR LOCATION" - PLACE PIN" ThenSome can confirm it for the day and everyone that has your map knows where it is.

**Comment by iligalodin** [comment]
i'll look into the nazar thing

**Comment by iligalodin** [comment]
Okay seems doable the folks over at nazarfinder developed an api, will try to add that soon!

**Comment by iligalodin** [comment]
nazar is kind of implemented, will be updated later
