### ISSUE TITLE
Lost Jewelry Earrings: Sterling Tooth Earrings. December 17th.

### ISSUE THREAD

**Issue by qwnbcd** [jeanropke/RDR2CollectorsMap#532]
I found Sterling Tooth Earrings. Search with metal detector

![Серьги с серебряными зубами](https://user-images.githubusercontent.com/58901862/70992482-78323a00-20d2-11ea-954e-62987692b2f0.jpg)
![Серьги с серебряными зубами карта](https://user-images.githubusercontent.com/58901862/70992488-7c5e5780-20d2-11ea-9d6c-f2b8fa1043ec.jpg)

Coordinates: lat: -44.171875; lng: 110.84375

**Comment by Touchmymonkeyuk** [comment]
Confirmed it is there.

**Comment by jeanropke** [comment]
All earrings added
