### ISSUE TITLE
Randoms Dec 17

### ISSUE THREAD

**Issue by Yizzen** [jeanropke/RDR2CollectorsMap#533]
HI, firstly thanks for all the hard work on this project. Issue all the randoms are not there on Dec 17th, tried many. Secondly Hajnal garnet bracelet, shows as off map ?

**Comment by Touchmymonkeyuk** [comment]
I think if they are off the map they are just sat in a placeholder waiting to be put on the map when it is found.

**Comment by Yizzen** [comment]
ahh ok, thanks for info.

**Comment by jeanropke** [comment]
Random spots aren't 100% correct anymore.

**Comment by Yizzen** [comment]
Hi thanks for reply, i did try like 20 of them and not one was a hit.

**Comment by Ootat** [comment]
It looks like we are at 5 new cycles for each collectable set. My guess is the original 200 random sites may be broken out into 5 groups of 40 so far I’ve found two for today.
