### ISSUE TITLE
Beaulieux Diamond Ring, December 17t

### ISSUE THREAD

**Issue by OmaformZiO** [jeanropke/RDR2CollectorsMap#534]
Beaulieux Diamond Ring is in treasure box on the second floor of the barn
![AEEF1DE8-006F-4D27-ACB4-D75662162B6A](https://user-images.githubusercontent.com/58984771/71007149-8196c300-2121-11ea-8e9a-f769ab50d4ab.jpeg)
![2EE3AB45-651D-43D8-B340-4C8950278CC3](https://user-images.githubusercontent.com/58984771/71007152-8196c300-2121-11ea-8a16-80e2befae685.jpeg)
![640FEAE3-7D5C-4AD9-AB15-26254BF51D06](https://user-images.githubusercontent.com/58984771/71007154-822f5980-2121-11ea-90c0-4f038069c9be.jpeg)

**Comment by Touchmymonkeyuk** [comment]
Confirmed.

**Comment by jeanropke** [comment]
All rings added
