### ISSUE TITLE
Coin locations showing on mobile but not browser

### ISSUE THREAD

**Issue by ClarkAU99** [jeanropke/RDR2CollectorsMap#535]
First time using GitHub, sorry if this is in the wrong place.

But yeah, the coin locations are showing on the mobile version of the website but not the PC version of the website.

**Comment by qwnbcd** [comment]
I am fine. Clean the hash and disable ad blockers, maybe this will help

**Comment by ClarkAU99** [comment]
> I am fine. Clean the hash and disable ad blockers, maybe this will help

What do you mean by "clean the hash"? Also, disabling ad blocker did nothing.

**Comment by ClarkAU99** [comment]
> I am fine. Clean the hash and disable ad blockers, maybe this will help

Clearing the cache fixed it. Thank you.

This can be closed.
