### ISSUE TITLE
Gosselin white gold necklace Beaulieux diamond ring and Pelle pearl necklace (cycle 4 , Dec 17th)

### ISSUE THREAD

**Issue by M00NSH1NE34** [jeanropke/RDR2CollectorsMap#537]
gosselin white gold necklace
lat: -61.34217014828481
lng: 151.1796875

beaulieux diamond ring
lat: -36.373771226443736
lng: 104.84375

**Comment by M00NSH1NE34** [comment]
Pelle pearl necklace
lat: -42.07440321479537
lng: 155.7203130722046

**Comment by bradgrubbs** [comment]
I’m at the spot for the pelle necklace now but can’t find it. Annesburg near the y’all rectangular building at the top of the hill, correct?  Inside a building or outside?  Metal detector or not?

**Comment by jeanropke** [comment]
All necklaves and rings added
