### ISSUE TITLE
Multiple Pins at the exact same location.

### ISSUE THREAD

**Issue by MateusRoscoe** [jeanropke/RDR2CollectorsMap#538]
**Is your feature request related to a problem? Please describe.**
With these new cycles it appears we have multiple pins at the exactly same location on the same cycle. This can be confusing to players and it can hide possible loot if they are not careful.

**Describe the solution you'd like**
A way to either handle pin collision (a multi item pin) or simply space them a little bit.

**Additional context**
Boxwood Comb Heirloom - Cycle 5 and Five of Swords - Cycle 4 are on the same spot and they're both in game today.

**Comment by jeanropke** [comment]
When markers cluster is enabled, clicking on markers next with others will separate them
