### ISSUE TITLE
Few issues with the map

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#539]
1. If you have the sidebar open and zoom in on the map by one level, the leftmost part is hidden behind the sidebar.
2. The sidebar doesn't stay open on refresh
3. Show coordinates on click doesn't stay active on refresh
4. Flowers list is empty
5. Red items stay red after changing cycle

**Comment by q1k** [comment]
6. Selling doesn't work

**Comment by jeanropke** [comment]
Issue 5 fixed

**Comment by jeanropke** [comment]
Issue 4 is because there is 0 flowers added in that cycle

**Comment by jeanropke** [comment]
Added sugestions 2 and 3

**Comment by jeanropke** [comment]
Increased bounds area
