### ISSUE TITLE
Search bar error

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#54]
i tried to search for multiple items today with the query "ursula; ace of c; old;" but noticed only the first came up. if i searched without the spaces after the ";" it would be fine, not sure if its a bug or intended. but i suggest we include the spaces in the seperator filter.

**Comment by rbcunhadesign** [comment]
Can you guys confirm this fixed the search? I had to clear all the cookies for the domain in order for it to work on mine.

**Comment by iligalodin** [comment]
will search

**Comment by iligalodin** [comment]
works perfectly!
