### ISSUE TITLE
Sackville Diamond not showing at all for me. CYCLE 4

### ISSUE THREAD

**Issue by Touchmymonkeyuk** [jeanropke/RDR2CollectorsMap#541]
Shows it in a house/shack just above Annesburg but not there at all. Anybody else managed to get this one ?

**Comment by jeanropke** [comment]
Its on a wardrobe or chimney. The vibration started after I got the item.

**Comment by Touchmymonkeyuk** [comment]
Found them eventually about 30 odd feet from the house. Had to use the Metal Detector to find them and dig them up.

**Comment by jeanropke** [comment]
This one is a random spot. I got a arrowhead.

![Screenshot_1242](https://user-images.githubusercontent.com/6243818/71034030-4384a980-20f7-11ea-9f27-9d177162c8e8.png)
