### ISSUE TITLE
Calumet Turquoise Earrings Cycle: day 4

### ISSUE THREAD

**Issue by Touchmymonkeyuk** [jeanropke/RDR2CollectorsMap#542]
Found them. Inside the tree.

lat: -28.752562483138796
lng: 119.19938269456998

![Red Dead Redemption 2 Screenshot 2019 12 17 - 20 51 36 20](https://user-images.githubusercontent.com/58904912/71033548-68851680-210f-11ea-9578-1360fc247d05.png)

![Red Dead Redemption 2 Screenshot 2019 12 17 - 20 51 20 94](https://user-images.githubusercontent.com/58904912/71033562-7044bb00-210f-11ea-8cb7-d5cff2b11ae3.png)

**Comment by jeanropke** [comment]
All earrings added on map
