### ISSUE TITLE
locations for the 1800 gold dollar coin. cycle 6 

### ISSUE THREAD

**Issue by firefacefull** [jeanropke/RDR2CollectorsMap#547]
please help where is the locations for the 1800 gold dollar coin for cycle 6. on the map its at the top left.

**Comment by benzon** [comment]
The reasson it's in the top left corner is the current possition is unknown.

**Comment by qwnbcd** [comment]
Someone check the previous position for the 1800 gold dollar coin for cycle 6?

**Comment by benzon** [comment]
Cycle 6 is rather new, that is why the gabs are still being filled in.

**Comment by Quahox** [comment]
[Imgur](https://i.imgur.com/zs2US8Y.png) Can someone check this spot? I got a duplicate there {Token Coin} And it should not be there because its in other spot already.

**Comment by herr-barus** [comment]
1700 New York Token Coin on this location for me too. (-63.8; 116.85)

**Comment by Quahox** [comment]
That make no sence because it's already under this coords - lat: -32.5625
lng: 147.09375

**Comment by NF13** [comment]
I think theres a bug in the new cycle

**Comment by Touchmymonkeyuk** [comment]
Got to be a bug. Bought the map after collecting all the other coins and it shows a yellow search area right over the oil pit thing. 1700 Yorke down the hole but yellow search area still showing. Nothing anywhere near there showing that it could be collected so something isn't right at all.
