### ISSUE TITLE
A little translation problem 

### ISSUE THREAD

**Issue by M00NSH1NE34** [jeanropke/RDR2CollectorsMap#554]
![en](https://user-images.githubusercontent.com/58986182/71193331-ea6a7080-22c4-11ea-9098-04ed38f811a4.png)
![CN](https://user-images.githubusercontent.com/58986182/71193332-ea6a7080-22c4-11ea-998e-eeaf4eff2469.jpg)

According to the context ,  you can use "共" (in total) in chinese to replace "of"

**Comment by jeanropke** [comment]
Like this?
`已收集 99 共 165`

**Comment by M00NSH1NE34** [comment]
> Like this?
> `已收集 99 共 165`

yeah, it is correct.
