### ISSUE TITLE
Helena Sapphire Bracelet Cycle: day 1

### ISSUE THREAD

**Issue by skotos999** [jeanropke/RDR2CollectorsMap#560]
The lockbox is empty at the entrance of the tunnel. No orange smoke, no chiming sound effects. It's been like this for three times in a row.

**Comment by jeanropke** [comment]
Probably its a game bug
https://www.youtube.com/watch?v=dGvAjfCsVQ8

**Comment by skotos999** [comment]
Thanks! 
Is there any way to fix it? I raised a ticket at R* Support, so I'm just waiting for their reply.
