### ISSUE TITLE
Madame Nazar Location / 20th Dec. 2019 is wrong

### ISSUE THREAD

**Issue by Juergen1967** [jeanropke/RDR2CollectorsMap#561]
The correct position today is west/southwest of plainview.
Don`t know if you can correct it.
thx
J.

**Comment by NF13** [comment]
@Juergen1967 The Problem is it changed every day at 6 o'clock CET not like the collection items they changed at 0 am CET. So some people have to work and can not directly changed it at 6 o'clock so you have wait till somebody have time to change it, now it is correct.
