### ISSUE TITLE
Can we get a date added?

### ISSUE THREAD

**Issue by chrisparadies** [jeanropke/RDR2CollectorsMap#564]
**Is your feature request related to a problem? Please describe.**
Because things are no longer on a clear cycle, when you log on at 4:00 PT it's the wrong information, and you don't necessarily know when it becomes correct.

**Describe the solution you'd like**
It'd be great if there was text that said: "Cycles for 7:00 PM ET 12/20/19 though 6:59 PM ET 12:21/19" or something along those lines

**Describe alternatives you've considered**

**Additional context**

**Comment by jeanropke** [comment]
Added a date in menu
