### ISSUE TITLE
Settings backup (server or local file/code)

### ISSUE THREAD

**Issue by SullieLore** [jeanropke/RDR2CollectorsMap#565]
Hi,

I like this project a lot and use the service frequently. However, I frequently encounter lost data or different data when using multiple browsers.

It would be great if the server remembered the user's data, such as collected items, hidden points, routes etc.
This could be achieved via a dedicated part of the server with username/pw logins, or it could simply spit out a code similar to the routes section. This code could contain all of the user's prefs and collections etc.

Thanks for any consideration,

Sullie

**Comment by q1k** [comment]
I'd like it to sync settings and inventory to logged-in github user. And auto update on change (from another device)

**Comment by Senexis** [comment]
I'll look into exporting it to some form of file so you can sync it wherever you want. Github syncing might be going a bit too far for this though, so no promise on that.

**Comment by Senexis** [comment]
This is now available, let me know if there's issues or other suggestions for it in a different issue.

![image](https://user-images.githubusercontent.com/6360733/71985207-60aa2500-322a-11ea-84af-95b1175d887f.png)
