### ISSUE TITLE
Hide markers if location isn't correct

### ISSUE THREAD

**Issue by Puddingpapst** [jeanropke/RDR2CollectorsMap#568]
After the cycles had been changed by Rockstar the map isn't 100% correct. Therefore we currently have the option to upvote and downvote markers on the map. It would be helpful if downvoted markers would be hidden, with an option in the settings to show the hidden markers that have been hidden trough downvotes. 

I often forget at which markers I've been and at which I've not been, because downvoted markers are shown the same as markers that haven't been found by me.

**Comment by IronJeff80** [comment]
Its for inventory. Not upvote
