### ISSUE TITLE
[Suggestion] translation of the menu text (black pop up screen)

### ISSUE THREAD

**Issue by githb123** [jeanropke/RDR2CollectorsMap#57]
How about translating the whole menu and presenting it according to the browser language preferences? Also the items could be in a language of the browser preferences automatically.

However the possibility to set the language manually should be kept.

**Comment by Rakmarok** [comment]
I would volunteer for the German translation.

**Comment by iligalodin** [comment]
yeah if you want you can proof read and add descriptions to it if needed

**Comment by jeanropke** [comment]
Added translation on menu.
