### ISSUE TITLE
Caves

### ISSUE THREAD

**Issue by PogoMan361** [jeanropke/RDR2CollectorsMap#571]
It would be great if we could have markers for cave entries and detailed images of the inside with the popup...

**Comment by dlldldl** [comment]
There is a way to implement this, but image of the cave detailed map is needed to make it work. Currently there is one cave image.

**Comment by jeanropke** [comment]
Caves overlays are planned, but it's complex to fit the image correctly on the map

**Comment by jeanropke** [comment]
Added 4 new caves overlays.
