### ISSUE TITLE
Incorrect item Cycle: day 4

### ISSUE THREAD

**Issue by kferrano** [jeanropke/RDR2CollectorsMap#572]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 4
* Coordinates or a clear image of the location lat: -87.125 lng: 147.4609375
* Include the item name: Tennesee Whiskey - Cycle 4

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Underground.
https://pbs.twimg.com/media/ELsF7VQXUAE79sS.jpg
