### ISSUE TITLE
Found missing WISTERIA Flower: Cycle #4

### ISSUE THREAD

**Issue by iiKraze** [jeanropke/RDR2CollectorsMap#573]
hey i love your map and i would love to assist in keeping it updated so here is a submission to the missing WISTERIA Flower for Cycle #4

Map location : https://i.imgur.com/RXTFEAC.png
Flower Proof : https://i.imgur.com/w5HUqsC.png

(sorry if this is submitted in the wrong section)

**Comment by iiKraze** [comment]
here is another submission to the missing CHOCOLATE DAISY Flower for Cycle #4

Map location : https://i.imgur.com/IvmwiKD.png
Flower Proof : https://i.imgur.com/rXLH9Jt.png

**Comment by whoispmb** [comment]
Rough Coordinates for WISTERIA are: 
lat: -47.09375
lng: 148.0703125

DUCK EGGS in this cycle around Elysian Pool as well. Rough coordinates are: 

lat: -48.3203125
lng: 148.3125

**Comment by jeanropke** [comment]
Items added on the map
