### ISSUE TITLE
Incorrect item Cycle: day 6

### ISSUE THREAD

**Issue by kferrano** [jeanropke/RDR2CollectorsMap#581]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 6
* Coordinates or a clear image of the location  lat: +-0 lng: +-0
* Include the item name Queen of Pentacles - Cycle 6

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Markers off the map does not have a known location.
