### ISSUE TITLE
Obsidian Arrowhead - Cycle 4

### ISSUE THREAD

**Issue by mifriis** [jeanropke/RDR2CollectorsMap#587]
Sorry, i don't have the right location, but this is the second time (i did the same the last cycle 4 for arrowheads) i have visited this arrowhead at this location. It's not there. I tried relogging both times.

**Comment by connsoul** [comment]
the marker is correct and this item is in a cave.

**Comment by NF13** [comment]
the entrance is at the waterfall careful first set the marker the cave is very dark so you need a light if your  at the right location switch to metal detector and dig in the dark...

**Comment by mifriis** [comment]
> the marker is correct and this item is in a cave.

could you do a pull request with the description for this one then? I doubt i am alone with this problem.

Thank you for the info, i will close the issue.
