### ISSUE TITLE
any help needed locating items or information.

### ISSUE THREAD

**Issue by T0rNaDo69** [jeanropke/RDR2CollectorsMap#593]
if there are any items your still needing locations for and on what cycles or any details.
it would be great if you could put up a list, 
so RDR2 players can help with the information  for you to get this great map  fully working again.

as me and a friend play this everyday, and have used this map a lot.
shame rockstar decided to mess it up, on the last update.
guess they didn't want us players getting items too easy, like we have been.

so any help we can give, is welcome..

like today..   no Horse Hair Brush Heirloom on cycle 4

**Comment by CollectorConniseur** [comment]
Wanted to Update The Cycle 4 Calumet Turquoise Earrings are Inside a Dead Tree Next to a rock

**Comment by KingBeast679** [comment]
I need help with finding 1800 Gold Dollar. It is showed way off the map so I dont know where to go.

**Comment by T0rNaDo69** [comment]
i dunno if thats in the cave up there,
i remember when i got a map from nazar, one of the items was outside the map boundary.
that one was to the left side of little creek river.
and was showing outside the map..

**Comment by KingBeast679** [comment]
Thanks I will check they did say some item will be in caves. Will check it out.

**Comment by KingBeast679** [comment]
Hey I see you guys have a Treasure map thing too. Do I need to have the map itself or is it the spawn areas?

**Comment by KingBeast679** [comment]
Hey never mind I figured out how to do it. 
P.S. keep up the good work you guys are God sent!

**Comment by Nxtlvlgaming101** [comment]
I was just wondering a few things,
after each day when i reload the collectors map do i have to go around and click "Show" on all the collectors items or does it do it itself after the items spawn back in ?
