### ISSUE TITLE
Blood Flower Nighttime Notification

### ISSUE THREAD

**Issue by DonnieNarco** [jeanropke/RDR2CollectorsMap#595]
I noticed after searching through cycles 4-9 for the Blood Flower that I could not find, that it only appears at night, and this was because one particular flower location near Lakay had a notice on it saying Nighttime only, but all other locations in multiple cycles did not have this same notice. 

Please consider adding the notice to all Blood Flower locations in each cycle to make it easier for people who are not familiar with collecting yet.

**Comment by jeanropke** [comment]
Added missing texts. 880c5aa
