### ISSUE TITLE
[Need Verification] Possible multiple location for single item

### ISSUE THREAD

**Issue by rbcunhadesign** [jeanropke/RDR2CollectorsMap#60]
I was going through collecting items Sunday afternoon before 8EST so day cycle 2, and found items that are already listed on the map in a different location.

If the item indeed is in two different locations, how should we account for that?

Example item DAY 2 (Sunday and Wednesday before 8 EST):
Agate Arrowhead - **current** `"x": "-85.9609375", "y": "86.0078125"`

Agate Arrowhead - **possible second location** `"x": "-112.71774291992188", "y": "51.654937744140625"`
_Second location reference **NOT CURRENTLY ON MAP_**
![Screen Shot 2019-09-30 at 12 56 29 PM](https://user-images.githubusercontent.com/24467388/65899438-c3656800-e381-11e9-80ad-425c985ac3ea.png)

**Comment by Mr-Schickadance** [comment]
Yes I have noticed this as well. The thing is that these "second locations" appear to be random. If we can find a pattern and know for a fact that an item also appears in another location we should add it to the code. But as of now it appears to be random where we don't know where it will show up.

**Comment by rbcunhadesign** [comment]
@Mr-Schickadance Do you know if the location is the same even if there is a different item on the spot?

We could maybe create a new index for locations that yield random items.

**Comment by iligalodin** [comment]
@rbcunhadesign yeah thought about that i'll mark "random item" locations with a new tag in the closed issues

**Comment by Mr-Schickadance** [comment]
@rbcunhadesign Oh I didn't think of that. Good point. Yeah it might be the case that there are "lottery locations" on the map where you will get an item for sure but it's just a question of which one and what the probabilities are. Maybe a particular lottery location can be any item with an equal probability for all items or maybe it's the case that only 3 items can be pulled from it (like an Agate Arrowhead, Endicott Earrings, or 1800 Half Dime).

**Comment by jeanropke** [comment]
I found a Raw Arrowhead.
Maybe this spot give a random arrowhead?

**Comment by rbcunhadesign** [comment]
@jeanropke let’s wait until day 2 comes around again and see what comes up.

**Comment by rbcunhadesign** [comment]
Just visited this spot again and got a 1800 Half Dime 🤔

It may be that the spots are just extra random items?

**Comment by IronJeff80** [comment]
I've noticed the sites are all static on the day/cycle schedule. If it is there on cycle/day 1, it is always there on day 1. The item usually rotates between 3 items. 
I am watching to see if they have a cycle vs completely random:

Day 1 Tuesday = Item A
Day 1 Thursday = Item B
Day 1 Saturday = Item C

If on a 2 day cycle, do they go:
Day 2 Wednesday = Item A
Day 2 Sunday = Item B
Then repeat or
Day 2 Wednesday =Item A
Day 2 Sunday = Item B
Day 2 Wednesday = Item C
Day 2 Sunday = Item A
Day 2 Wednesday = Item B
Day 2 Sunday = Item C

**Comment by jeanropke** [comment]
Added almost 200 random spots
