### ISSUE TITLE
Ursula Citrine Earrings, Cycle: 3

### ISSUE THREAD

**Issue by JeanRopkeSpankMeDaddy** [jeanropke/RDR2CollectorsMap#601]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

Woof wake up nothing's there.

**Comment by jeanropke** [comment]
Cycle changed to 1
