### ISSUE TITLE
Hajnal Garnet Bangle Bracelet; Cycle 3

### ISSUE THREAD

**Issue by JeanRopkeSpankMeDaddy** [jeanropke/RDR2CollectorsMap#602]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

No Daddy, this is not right. It's not in a lockbox underneath the bridge. It's nowhere to be found.

**Comment by jeanropke** [comment]
Cycle changed to 1
