### ISSUE TITLE
Incorrect item Cycle: day #4 Spoonbill Egg is missing

### ISSUE THREAD

**Issue by superbiggy** [jeanropke/RDR2CollectorsMap#604]
Spoonbill Egg - Cycle 4 is missing
![image](https://user-images.githubusercontent.com/59314444/71545818-46558900-2998-11ea-802f-691e0d9d8c67.png)

**Comment by jeanropke** [comment]
This egg was there. Try to switch session 
http://prntscr.com/qgvc49
