### ISSUE TITLE
Enable rotes again / Ativar as rotas novamente

### ISSUE THREAD

**Issue by Claudao01** [jeanropke/RDR2CollectorsMap#605]
[EN/US] 
Please, enable the rotes again, like it was before the actualization. This helped a lot in finding items.

[PT/BR]
Por favor, habilite novamente as rotas, assim como era antes da atualização. Isso ajudava muito nas buscas de itens.

**Comment by jeanropke** [comment]
Não tem como colocar elas no momento, os ciclos das coleções mudam completamente de um dia para o outro. E calcular a menor distância entre os marcadores não funciona muito bem
