### ISSUE TITLE
Incorrect item location: Cycle #3

### ISSUE THREAD

**Issue by EdgelordInferno** [jeanropke/RDR2CollectorsMap#609]
Form submitted as well to be safe.

* Day Cycle: 3
* lat: -84.9068680397487 ; lng: 98.7781252861023
   Inside a chest outside the photo studio in Blackwater
* Item: Ivory Comb (Heirloom)

![ivorycombnew](https://user-images.githubusercontent.com/59168525/71564989-59329100-2a5e-11ea-8a5c-dccb152f90b9.png)

**Comment by Ootat** [comment]
I don’t recall any item on cycle 3 in that location. That item (ivory comb) is marked at that location on cycle 6. Isn’t cycle 6 the current heirloom cycle.
