### ISSUE TITLE
Bird eggs not present.

### ISSUE THREAD

**Issue by Regis2553** [jeanropke/RDR2CollectorsMap#620]
Hi, first of all thank you for this wonderful map :)

One thing I have a problem with after the December 13th update are bird eggs. Some days only some of them are where indicated. Today I couldn't find a single one and I tried all cycles (it should be cycle 3 today). After I didn't find two eggs today I checked all the other cycles (one egg from each, depending on which should be the closest to my location) and found none. Perhaps it's a game problem and not your map.

Also, one day I couldn't find an egg at the location indicated on your map, but after I used Madame Nazar's map it showed me that the egg should be in that exact spot and it actually was.

**Comment by jeanropke** [comment]
I collected all items today December 31th. Any issue collecting them.

**Comment by Regis2553** [comment]
Strange I can't find a single bird egg today.
