### ISSUE TITLE
Ivory Hairpin Cycle 2 Location:

### ISSUE THREAD

**Issue by Nxtlvlgaming101** [jeanropke/RDR2CollectorsMap#622]
![Ivory Hair Pin- Cycle 2](https://user-images.githubusercontent.com/59348880/71628220-e8f24f80-2bc4-11ea-9911-791f24d85c4f.png)

Find while i was roaming, wasnt marked on the collectors map

**Comment by jeanropke** [comment]
Random item spot #9
http://prntscr.com/qhydjv
