### ISSUE TITLE
Dynamic Route is missing

### ISSUE THREAD

**Issue by dermatz** [jeanropke/RDR2CollectorsMap#624]
Was the dynamic route removed? I can't find it nomore.

**Comment by jeanropke** [comment]
It is currently disabled. After the update, routes were handmade. Now it's more complex to create routes.

**Comment by Senexis** [comment]
Since the last comment I've added a route generator to help make a guide for you. It'll probably be a while before the, like Jean mentioned handmade, routes come back.
