### ISSUE TITLE
chipped arrowhead

### ISSUE THREAD

**Issue by StenKilla** [jeanropke/RDR2CollectorsMap#625]
Chipped arrowhead cycle 4 is in wrong place. Should be south of caliga hall

**Comment by mamath21** [comment]
lat: -89.1015625
lng: 140.0703125

**Comment by Senexis** [comment]
Confirmed, even though the game itself seems to think it's where the marker is on the map currently.

![image](https://user-images.githubusercontent.com/6360733/71642899-bf175680-2cb2-11ea-935b-33edb0d1f339.png)
