### ISSUE TITLE
Raw Arrowhead - Cycle 4

### ISSUE THREAD

**Issue by sixis45** [jeanropke/RDR2CollectorsMap#629]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? cycle 4
* Coordinates 
![prenos](https://user-images.githubusercontent.com/59418356/71644415-415e4580-2cc8-11ea-83ce-ab0302de17d8.png)
lat: -90.6484375
lng: 96.28125
* Include the item name Raw Arrowhead

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by jeanropke** [comment]
Game code says another coordinate. Even Nazar Map show an invalid location.
Coordinate updated.
