### ISSUE TITLE
Incorrect item Cycle: day 5

### ISSUE THREAD

**Issue by LeonZewe** [jeanropke/RDR2CollectorsMap#634]
Cycle 5
lat: -36.828125
lng: 105.171875
Dane Topaz Necklace

Can't be found at the location marked on the map.

**Comment by TheGateBabylon** [comment]
Cycle 5
lat: -52.1328125
lng: 76.2421875
Duchess Emerald Earrings

Can't be found at the location marked on the map.

**Comment by LeonZewe** [comment]
Cycle 5
lat: -65.828125
lng: 145.953125
Magnate Turquoise Ring

Can't be found at the location marked on the map.

**Comment by sydthakyd** [comment]
Ace of Swords in the Strawberry Jailhouse isn’t there today either cycle 6

**Comment by Ciggyhore999** [comment]
Has anyone got the correct loction for the Duchess Emerald Earrings yet?

**Comment by BE3dARt** [comment]
My ingame map marks jewelry (the Duchess Emeral Earrings) at exactly this location, but I can't find it either.

**Comment by Senexis** [comment]
Yup, some items are bugged in the game itself. This could be another one, had two yesterday as well.

@sydthakyd I found the Ace of Swords on the window still of the jailhouse (outside, not inside).

**Comment by iiKraze** [comment]
> Ace of Swords in the Strawberry Jailhouse isn’t there today either cycle 6

it is there, check the little window near the ground on the left side of the building

**Comment by Senexis** [comment]
All of the items reported here can be found, bar the Duchess earrings.

**Comment by LeonZewe** [comment]
> 
> 
> All of the items reported here can be found, bar the Duchess earrings.

Do you know where to find the Magnate Turquoise Ring and the Dane Topaz Necklace? I checked for them everywhere but the location marked on the map isn't right.

**Comment by Senexis** [comment]
I found them at the marked locations. Try switching sessions or relaunching the game.

**Comment by LeonZewe** [comment]
The description of the Magnate Turquoise Ring says "On top of the fireplace", but I checked everywhere and its just not there. Even switched lobbys multiple times. Heres a screenshot of the fireplace, empty as you can see...
https://i.imgur.com/tjvgkW4.jpg

**Comment by Senexis** [comment]
All I know is that I've been there, wrote that description _today_ and got the item.

What I'm saying is that it could be bugged for you unfortunately but that doesn't mean it's bugged for everyone. This issue happens to multiple people, but doesn't to others, I just can't confirm that it's actually bugged since I've gotten it myself.

**Comment by Ciggyhore999** [comment]
I got that ring but I noticed that some items do not spawn until your literally right on top of them, then they appear. Also the vibration is not always present until after you’ve collected it... in general the map is 99% accurate but I suspect it’s the game glitching rather than anything else

________________________________

**Comment by Senexis** [comment]
@Ciggyhore999 I've noticed that too, especially with cards today. Sometimes the cards even spawn _under_ the snow which is just evil.

**Comment by Ciggyhore999** [comment]
Lol indeed, and I’ve complained at the lack of wildlife to hunt too, the trader role is impossible unless you trigger a mission just so you have something to hunt.... I bet nobody saw a Rooster today... I looked everywhere!!

________________________________

**Comment by iiKraze** [comment]
> All of the items reported here can be found, bar the Duchess earrings.

i have to agree, i have found everything apart from the Duchess Emerald Earrings
