### ISSUE TITLE
Item Cycle AND Location correct, but items missing: Random or aim to use maps?

### ISSUE THREAD

**Issue by D353R7F0x** [jeanropke/RDR2CollectorsMap#636]
Yesterday i tried to collect 2 specific eggs (cycle3)(hawk+vulture) both were NOT present at their locations, I checked it several times with hours in between to make sure!!!
Then i collected all other eggs and afterwards used a egg-collector-map for the missing 2...and they appeared at their supposed location, but only after using this map!

...can someone check if this is random or maybe on purpose?

**Comment by Senexis** [comment]
Report these things on day this happens so we can verify that the locations are incorrect. As far as I know, the locations were correct for these eggs yesterday as I grabbed them all from their correct locations. It must've been an issue with your session.

**Comment by PogoMan361** [comment]
Yes, a session problem. Had a similar issues few days agos, item (some ring or lace) was not there. After switching sessions, it magically appeared...

**Comment by D353R7F0x** [comment]
@senexis ... cycle and day were told and that they appeared later with the map too. What to verify if its random?
And today its probably a session-issue, because right now i cant collect any items at all (will reboot now), but the day before yesterday i found all other items(/eggs) in the same session, but not those 2 eggs before opening the egg-map.
...just guessing the key to make "missing"-items appear MIGHT BE the use of a collector-map

...but thank you guys for the info with the session, easy to miss in those situations ;-)
