### ISSUE TITLE
Different color for searched items (suggestion)

### ISSUE THREAD

**Issue by jcdarkie** [jeanropke/RDR2CollectorsMap#64]
Thanks for the awesome interactive map.

I love the search function but I think it would be great if there was an option to also show all the non searched items together with the searched items.

The searched items could show in a different color. That way when focusing on searched items all the other collectibles would still be on the map.

A toggle function allowing the user to chose to show only searched items or all items would be great.

**Comment by richardwestenra** [comment]
To add to this, instead of changing the colour, I'd suggest fading out the filtered items to about 10% opacity (give or take).

**Comment by jeanropke** [comment]
Added grayscale & opacity.
![search colors](https://user-images.githubusercontent.com/6243818/66087031-6d90eb80-e54c-11e9-8201-9ab03673008c.png)
