### ISSUE TITLE
Incorrect item Cycle: day #6

### ISSUE THREAD

**Issue by HFM1101** [jeanropke/RDR2CollectorsMap#649]
Rou Pearl Necklace, Day 6, missing.
Coordinates also not working (only works when clicked an empty area, does not reveal longitude or latitude for items!).
Item is showing in Gaptooth Ridge, top of the map in line with the T and U of Tumbleweed (but further north). Nothing there.

**Comment by jeanropke** [comment]
The item was there. Try joining another session.
