### ISSUE TITLE
What is the license of RDR2CollectorsMap? And thank you for your work

### ISSUE THREAD

**Issue by bass3l** [jeanropke/RDR2CollectorsMap#663]
@jeanropke. My man, you've done/and doing an amazing work, thank you so much.

I'm building a mobile app for the RDO community (totally free, no monetization at all), It'll contain the map you've built with some modifications for the app, it'll keep getting the updated locations from this as an upstream. So, I was wondering on which license is this project? (Your work will be credited in the app).

Anyways, thank you, and keep up the good work.

**Comment by jeanropke** [comment]
Hey, I added a license. Feel free to use the project.
https://github.com/jeanropke/RDR2CollectorsMap/blob/master/LICENSE
