### ISSUE TITLE
Cannot see items on New Version

### ISSUE THREAD

**Issue by ssdoomgloom** [jeanropke/RDR2CollectorsMap#665]
Tried using Firefox and Chrome, but I could anything at all on the collectibles map.  I can turn on the dynamic route and see the route it wants to take me to items and if I turn off a collectible while the dynamic route is on it changes the route.  Last thing to note is that I can see the collectibles in the legacy version.

**Comment by jeanropke** [comment]
Open browser console (F12) and check if there is an error.

**Comment by ssdoomgloom** [comment]
I just went back to it today, having done nothing that I normally don't do in between then and now, and I can see all the collectibles on the map.
