### ISSUE TITLE
Route generator regenerating route each time after removing item from the map? 

### ISSUE THREAD

**Issue by yeradd12** [jeanropke/RDR2CollectorsMap#667]
So I don't know if it's intended or not but I've been trying to use the new route generator and each time I collect an item (and mark it as found by removing it from the map) the route regenerates changing my previous route which kinda destroys the whole purpose,

Also if it's already known issue I'm sorry.

Screenshots before and after:

https://imgur.com/a/5kIhCF6

**Comment by yeradd12** [comment]
Ok so choosing option "ignore collected items" seems to help. I didn't use it before.

**Comment by Senexis** [comment]
I'll write up how the route generator exactly works and some tips and tricks for it in a wiki article soon. Glad you figured it out already.
