### ISSUE TITLE
Can I download apps on my IOS？

### ISSUE THREAD

**Issue by qq234425655** [jeanropke/RDR2CollectorsMap#67]
Can I download apps on my IOS？

**Comment by iligalodin** [comment]
this is a map that you can access via your browser, you can open the page on your phone, tablet, nintendo switch, Nokia 6310, anything with an internet browser

**Comment by qq234425655** [comment]
ok thx




| |
會飛de豬！
|
|
邮箱：qq234425655@163.com
|
On 10/01/2019 19:28, Odinn H wrote:

Closed #67.
