### ISSUE TITLE
Missing: Duchess Emerald Earrings - Cycle 1 

### ISSUE THREAD

**Issue by snewtrino** [jeanropke/RDR2CollectorsMap#671]
The Duchess Emerald Earrings are missing not only from cycle five but also from cycle one. I think this might be an issue with R* though.

**Comment by jeanropke** [comment]
The item was there. I was able to collect all items from this day.
The only exception wasthis flower, my horse hit me when I was collecting http://prntscr.com/qk6dgn

**Comment by snewtrino** [comment]
Not for me. I've left the session and rejoined a new one three times with no change.
