### ISSUE TITLE
Cycle is not auto updating?

### ISSUE THREAD

**Issue by Walter-Correa** [jeanropke/RDR2CollectorsMap#673]
Last cycle was 5, but after the time reset the cycle still 5. 
I have to change myself to cycle 3.

**Comment by nutinmyjam** [comment]
which item are you changing the cycle to 3 for? cause it can't be all items due to the update

**Comment by jeanropke** [comment]
Cycles are changed manually. There is a delay between the game cycle change and the map cycle change

**Comment by Walter-Correa** [comment]
> which item are you changing the cycle to 3 for? cause it can't be all items due to the update

Tarot Card - Three of Wands in Anesburg
