### ISSUE TITLE
Clear Shown Markers Only instead of all or nothing?

### ISSUE THREAD

**Issue by singemfrc** [jeanropke/RDR2CollectorsMap#678]
Frequently I come back to resume collecting and want to just reset flower icons and nothing else. There's no real way to do that, so I can either reset everything and then reprogram which other items I already have, or click each individual flower separately and reset it.
I was thinking it would be nice if there's a "reset flower markers" icon, but that may be too niche.
But what if there was a "reset visible markers only" option? This would give users a fast way to reset whichever group of markers they choose using the search feature. You could do just flowers, just alcohol and necklaces, or whatever combination you wanted without resetting absolutely everything. That might be worth implementing.

**Comment by Senexis** [comment]
I like this, I'll take a look.

**Comment by Senexis** [comment]
Thanks @MichalD96 for this. :-)
