### ISSUE TITLE
Blakely and Rou Pearl Necklaces not showing up

### ISSUE THREAD

**Issue by jdunn85** [jeanropke/RDR2CollectorsMap#68]
I went to the spots on the map where Blakely and Rou Pearl Necklaces are supposed to be (went inside the cave too), they are not there.

**Comment by jdunn85** [comment]
Pelle Pearl necklace didn't show up either

**Comment by jeanropke** [comment]
The day changed.
Need be tested on day 3.

**Comment by Jugrnot8** [comment]
I tested and found both on day 3. 
It shouldn't matter but it was night time.
