### ISSUE TITLE
Map does not load any icons error

### ISSUE THREAD

**Issue by Senexis** [jeanropke/RDR2CollectorsMap#681]
I encountered the issue where the map doesn't load icons fully. Seems that the map.js file, specifically the part where the layers get defined runs after the files in the errors. Posting this here for safekeeping in case I can't reproduce it later. These errors result in not being able to see _any_ markers.

![image](https://user-images.githubusercontent.com/6360733/71998001-1aab8c00-323f-11ea-937a-2c011a2e1d38.png)

**Comment by q1k** [comment]
just throwing this here for when this is being looked at properly
![image](https://user-images.githubusercontent.com/7927176/72229383-7d3db880-35ae-11ea-8553-380785e4e5c4.png)
