### ISSUE TITLE
Knight of Pentacles - Cycle 6 Missing

### ISSUE THREAD

**Issue by Ciggyhore999** [jeanropke/RDR2CollectorsMap#685]
Knight of Pentacles - Cycle 6 Missing
Map states on the dinner table with lantern above, have checked all of the tables and its not there
lat: -52.455497814877596
lng: 77.453125

**Comment by MichalD96** [comment]
you have to change the session (sometimes even 3 times or restart the game) to spawn some items, it is common bug but i am sure card is there
I picked it up by myself several times
