### ISSUE TITLE
Tarrot Cards missing Cycle 6

### ISSUE THREAD

**Issue by Kaindred** [jeanropke/RDR2CollectorsMap#686]
Cycle 6
Seven of Cups
-104.9296875, 36.234375

Seven of Pentacles
-108.9453125, 25.6953125

Ace of Wands
-99.2734375, 88.7265625

Two of Pentacles
-97.6875, 89.1875

Ace of Swords
-69.1484375, 83.1328125

**Comment by MichalD96** [comment]
All cards are on the map since a few weeks
maybe you disabled this cards in menu?

**Comment by Kaindred** [comment]
Hi,
I meant rockstar had to change something, because thery are not in game
world where they should be according to the map.
Sorry for the confusion ☺

Czw., 9.01.2020, 15:43 użytkownik Michal__d <notifications@github.com>
napisał:

**Comment by MichalD96** [comment]
I dont think they changed anything.
They did this only once in big update and it would be very weird if they do this again that quick

**Comment by Kaindred** [comment]
Strange because I checked aforementioned locations and cards are simply not there.

**Comment by jeanropke** [comment]
When the same cycle occurs in a row, there is a 24 hours cooldown to each collectible

**Comment by Kaindred** [comment]
Ah, ok thanks. I didn't know that.

czw., 9 sty 2020 o 17:19 jeanropke <notifications@github.com> napisał(a):
