### ISSUE TITLE
Suggestion: Don't increase/decrease inventory counts when hiding pins on individual collectibles in the left menu

### ISSUE THREAD

**Issue by DenL** [jeanropke/RDR2CollectorsMap#699]
Basically the suggestion is to have hiding individual collectible work like when hiding a set. When hiding a set, the entire set disappears from map, but hiding individual collectible instead mark them as collected (faded out). Even if that collectible have multiple pins on the map (flowers).

Use case example, I do not want to collect Cardinal Flowers when generating route using the tool, however hiding only cardinal flower will mark it as if "collected" and increment the inventory count. The first part is not that much of a problem since I don't want to collect it in the first place, but I've had to manually decrease the inventory count back to the original amount after hiding what pins I want to hide.

The rationale behind the suggestion is that, when people mark things as collected, they would usually use the pin itself since they are there to collect it. When they hide pins (or a group of pins) on the left menu and not on the map itself, it usually means they just don't want to see/collect it, thus inventory should not be effected.

This can currently be worked around by manually decrease the inventory count back to what it originally was, in which the latest update (adding inventory editing to left menu) had made much easier.

Thank you for making the map, it has been an immense help!

**Comment by Senexis** [comment]
![image](https://user-images.githubusercontent.com/6360733/72202193-ec0afc80-345c-11ea-9e03-23ea2034ebd0.png)

**Comment by DenL** [comment]
Thank you. That was real fast!
