### ISSUE TITLE
Suggestion for quality of life changes.

### ISSUE THREAD

**Issue by AnuKaro** [jeanropke/RDR2CollectorsMap#70]
So Ive been using the map quite much since I started the collector role. And since there was the selfmade route update Ive been thinking. Maybe a way to share set routes with others. Instead of taking pictures and uploading them to imgur.

And the second suggestion is a more difficult one. Id imagine. 

It goes for both the premade and selfmade route. Getting an option to make a start point on the route. And once youve collected the first mark. And youve disabled set mark. The map should remove that mark from the route and selfcentre on the next mark in the route? I know its a quality of life suggestion. But its hard to come up with suggestions for a near perfect product 😉

**Comment by iligalodin** [comment]
#106 implemented dynamic routes

**Comment by jeanropke** [comment]
Added import/export for custom routes.
