### ISSUE TITLE
ignore fully stacked items when generate route

### ISSUE THREAD

**Issue by JafarZ** [jeanropke/RDR2CollectorsMap#700]
Hello, 

First of all, I would like to thank you for this wonderful tool you have created and all the efforts you are putting to make it better every day.
This is a suggestion to ignore the max stacked items when we generate a route
as things stand, if I have 10 items of a collectible, the route doesn't ignore it.

**Comment by Senexis** [comment]
Done. It'll ignore it now if the inventory is enabled and the stack is full.
