### ISSUE TITLE
Pentacles Tarot Cards - Cycle 3

### ISSUE THREAD

**Issue by Tmease5580** [jeanropke/RDR2CollectorsMap#708]
All the pentacles cards for this cycle have bugged descriptions. Its just pentacles_cardname_number.desc

**Comment by Tmease5580** [comment]
Update: Its just some of the tarot cards in general. Some of every suit have the bug while some have the actual description.

**Comment by q1k** [comment]
I just checked and seems that only happens on items without a description.

**Comment by Senexis** [comment]
Uh... Whoops.
