### ISSUE TITLE
Missing items Day 1 

### ISSUE THREAD

**Issue by jlp20002** [jeanropke/RDR2CollectorsMap#71]
1. Gosselen Gold Bracelet 
Coordinates lat,lng:(-34.73,154.03)

2. Ojeda Rose Gold Bangle Bracelet
Coordinates (-31.3, 149.03)

3. Bosque Emerald Ring
Coordinates (-37.8, 149.4)

4. Bonnard Pearl Ring
Coordinates (-43.5, 149.8)

5.  Banais Topaz Ring
Coordinates (-39.3, 151.3)

6. Banais Topaz Ring
Coordinates (-38.8, 152.2)

7. Tuamotu Pearl Necklace
Coordinates (-37.3, 151.1)

8. Beauchēne Ruby Earrings 
Coordinates (-39, 154.7)

9. Quartz Arrowhead (-35.5, 160)

10. Emmeline Coral Necklace 
Coordinates (-43.7, 155.4)

11. Bone Arrowhead
Coordinates (-51.8, 153.5)

12. Chipped Arrowhead
Coordinates (-54.3, 151.9)

13. Splintered Arrowhead (-59.3, 155.4)

14. Braxton Amethyst Necklace (-62.6, 153.2)

15. Crude Arrowhead (-53, 145.9)

Most of these items are metal detector finds

**Comment by jeanropke** [comment]
1. not found
2. Tuamotu Pearl Necklace
3. 1798 Draped Bust Silver Dollar
4. Orchidee Diamond Earrings
5. 1800 Five Dollar Bechtler
6. Richelieu Amethyst Necklace
7. not found
8. Feldspar Arrowhead
9. Rough Arrowhead
10. 1798 Draped Bust Silver Dollar
11. Sterling Tooth Earrings
12. Harland Coral Ring
13. Ursula Citrine Earrings
14. Emmeline Coral Earrings
15. Slate Arrowhead

**Comment by jeanropke** [comment]
Items added.
