### ISSUE TITLE
Egret egg cycle 4 (01/13/20)

### ISSUE THREAD

**Issue by IbziDk20** [jeanropke/RDR2CollectorsMap#716]
The Egret egg is not in the shown location on cycle 4, today jan. 13. 20

**Comment by MichalD96** [comment]
Location on the map is correct
Try change the session or restart the game

**Comment by IbziDk20** [comment]
Still not working. Have relogged several times, and still no egg

**Comment by Senexis** [comment]
Sorry dude, I can confirm it's there as I just got it. It might be bugged for your game but the location itself is correct.
