### ISSUE TITLE
Incorrect item Cycle: 17. Januar

### ISSUE THREAD

**Issue by NF13** [jeanropke/RDR2CollectorsMap#735]
(https://github.com/jeanropke/RDR2CollectorsMap/issues/182)

I checked this cycles used for today:

Lost Jewelry: 2
Arrowheads: 2
Family Heirlooms: 5
Coins: 6

Alcohol Bottles seems to be like yesterday cycle 1 but i cant confirm because i check all others and can collect because of the 24 h-Bug...

**Comment by fuzzbuckets** [comment]
Random Spots are Cycle #4

**Comment by Jadyn167th** [comment]
To add onto this I was doing the Dailies and Figured I would find all the Correct Cycle locations for ease for anyone else. 

They are as follows:

Wands:-4
Cups:-4
Swords:-4
Pentacles:-4
Antique Alcohol:-1
Lost Jewelry Rings:-2
Lost Jewelry Necklaces:-2
Lost Jewelry Earrings:-2
Lost Jewelry Bracelet:-2
Family Heirlooms:-5
I have no done Arrowheads, Flowers or Coins.

Hopefully this helps anyone and can be fixed.
-Jadyn167th

**Comment by neodeath198** [comment]
flowers are on cycle 1

**Comment by NF13** [comment]
somebody knowing bird eggs than i can create a pull request with all collected infos

**Comment by whytheseaisboilinghot** [comment]
> (#182)
> 
> I checked this cycles used for today:
> 
> Lost Jewelry: 2
> Arrowheads: 2
> Family Heirlooms: 5
> Coins: 5
> 
> Alcohol Bottles seems to be like yesterday cycle 1 but i cant confirm because i check all others and can collect because of the 24 h-Bug...

Coins are cycle 6

**Comment by whytheseaisboilinghot** [comment]
Bird eggs cycle 1
Coins cycle 6

**Comment by NF13** [comment]
> Coins are cycle 6

@whytheseaisboilinghot Thanks I correct it
