### ISSUE TITLE
Map Won't Update

### ISSUE THREAD

**Issue by alizim110** [jeanropke/RDR2CollectorsMap#737]
The map hasn't updated for me. About 6 hours after the time it was supposed to update the map still hasn't changed cycles. I've been refreshing and watching to see if it will update and closing and opening the browser a few times.

**Comment by Cheerrii** [comment]
Same problem here.

**Comment by Bhakedl** [comment]
Same here. I’ve been checking a couple times every hour and the cycle still hasn’t refreshed

**Comment by UTFTerran** [comment]
Yes the map has not updated now a little over seven hours after it should have. Love this map and all it provides for the game and hate to complain but it is concerning that it hasn’t updated on time especially after the new cycles have been implemented for some time now thus no net new surprises on collectible locations.

**Comment by NF13** [comment]
see #736 im collecting at the moment to create a pull request i need bird eggs if somebody know the current cycle inform me

**Comment by XoRedmaliC** [comment]
Same problem :/

**Comment by whytheseaisboilinghot** [comment]
> see #735 im collecting at the moment to create a pull request i need bird eggs if somebody know the current cycle inform me

Bird eggs cycle 1
Coins cycle 6 (I've confirmed with 3 locations)

**Comment by MostHostLA** [comment]
Arrowhead cycle 2
