### ISSUE TITLE
Eliminating Detailed Map, and use Geojson Paths to map out roads on top of R* Default Map.

### ISSUE THREAD

**Issue by dlldldl** [jeanropke/RDR2CollectorsMap#744]
#668 has a great demo of GeoJSON Path Finder. Actually if we display all of the GeoJSON path on top of Default map, it eliminates the need of detailed map. The only thing left to do is map out Railroads and modifying the css a little bit to show the lines as solid black.
It will be a solution to Jeanropke's bandwidth problem from github by redirecting most of the map downloading to R* server.

**Comment by dlldldl** [comment]
Darkmode detailed map is possible to be changed via css filters as well.
https://stackoverflow.com/questions/7415872/change-color-of-png-image-via-css

**Comment by dlldldl** [comment]
I can start working on a prototype starting Sunday if nobody wants to do it ahead of me.

**Comment by AlanXYLi** [comment]
I'm making an prototype.

**Comment by AlanXYLi** [comment]
Poggers
![image](https://user-images.githubusercontent.com/31291584/72652782-05201b80-393d-11ea-8386-ad331f2db43c.png)

**Comment by AlanXYLi** [comment]
Make routes black and beautified css darkmode.
![image](https://user-images.githubusercontent.com/31291584/72658826-6e1e8800-396b-11ea-9172-65ace414e5b1.png)
![image](https://user-images.githubusercontent.com/31291584/72658828-770f5980-396b-11ea-9d53-02436c3b6225.png)

**Comment by jeanropke** [comment]
The detailedPath seems good, but the dark map is a bit slowly.

**Comment by stdrew** [comment]
just as a non-tech observer, what would be the usability benefits of this?  If we can't integrate the routes directly with the game, then it's just looking back and forth between the jeanropke browser window and the game itself and following the route?  If it's not on the game's HUD/map, then wouldn't just placing our own waypoints be the preferred action?

**Comment by Senexis** [comment]
This is slow as heck on mobile.

**Comment by dlldldl** [comment]
@Senexis https://codepen.io/sosuke/pen/Pjoqqp, something that can be used to give symbols color instead of hardcoding 20 each...

**Comment by Senexis** [comment]
I fail to see how that is relevant to this issue. Besides, having to use filters over images is probably less performant. The benefit of having the images is that one image can be used for multiple markers, while using filters would mean having to calculate the color for every marker. Additionally, it's fine as is.

**Comment by jonathonbarton** [comment]
Here's an interesting challenge for you  @AlanXYLi and/or @dlldldl 

Can you use the GeoJSON to calculate steep terrain rather than roads - or calculate BOTH, and then try to route in straight lines, _except_ where there's steep terrain, then route around it?

**Comment by dlldldl** [comment]
> Here's an interesting challenge for you @AlanXYLi and/or @dlldldl
> 
> Can you use the GeoJSON to calculate steep terrain (based on the color/closeness of the elevation lines) rather than roads - or calculate BOTH, and then try to route in straight lines, _except_ where there's steep terrain, then route around it?

I'm afraid it is not an option with GeoJSON. GeoJSON can only represent points for positions, lines for roads and borders, and polygons for areas.

**Comment by AlanXYLi** [comment]
I had some thoughts in mapping out impassable borders instead of roads to enhance route generation. With GeoJSON, here is an example to generate routes when blocking the roads. https://developers.arcgis.com/javascript/3/samples/routetask_multiple_stops/
I don't recently have time for this project, but definitely worth a try.

**Comment by tkon99** [comment]
> Here's an interesting challenge for you @AlanXYLi and/or @dlldldl
> 
> Can you use the GeoJSON to calculate steep terrain (based on the color/closeness of the elevation lines) rather than roads - or calculate BOTH, and then try to route in straight lines, _except_ where there's steep terrain, then route around it?

Actually, game files include a height map that could be mapped to the coordinates and use it as reference. I'm also working on game integration to be able to set waypoints from the browser (in SP).

**Comment by dlldldl** [comment]
The original detailed map idea is eating up too much performance of the browser.
