### ISSUE TITLE
Some Icons not popping up on the map.

### ISSUE THREAD

**Issue by F8sound** [jeanropke/RDR2CollectorsMap#746]
![jean map](https://user-images.githubusercontent.com/60030166/72660921-463e1d00-3989-11ea-910b-2d02fa4b25a7.PNG)
For some reason, the coins, arrowheads, lost jewelry bracelets, most of the lost jewelry earrings and only three of the lost jewelry necklaces and rings pop up.  I don't know why this is happening is there a fix to this?

**Comment by jeanropke** [comment]
Can you check if tool type is set to 'All'? If not, select this option.

http://prntscr.com/qph85v

**Comment by F8sound** [comment]
Omg, thank you soo much man.  I must have turned this off one day and not even realized it was an option.  So yea that fixes it thanks again for the reply and help.
