### ISSUE TITLE
[SUGGESTION] Option to carry over "Remove/Add from map" items to the next cycle/day.

### ISSUE THREAD

**Issue by AkaiEffect** [jeanropke/RDR2CollectorsMap#75]
Like the title suggests. It would be nice to have an option that carries over your removed items from one map to an other.

For example, if I remove the "Feldspar Arrowhead" on the cycle/day 3 map, it should still be removed on the cycle/day 1 and 2 map. That would make it a lot easier to me, because I don't have the time to collect all the items in just 1 day, so saving the collected items across all 3 cycle/day maps would be incredibly helpful. Otherwise I'd need to manually remove them every time and that's a lot of work, to be honest.

You'd probably also need a toggle to quickly add/remove all the items that you either marked "remove" or "add" on the map again, otherwise you'd have to do that manually, too.

I hope my point is understandable and I also hope that this is easy to implement. Thanks for reading either way and thank you for such an awesome tool.

**Comment by jeanropke** [comment]
Added an option to keep removed items and an option to reset it.
