### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by MyNameIsChangHee** [jeanropke/RDR2CollectorsMap#752]
I can't tell when the cycle gets reset

I wish there is a timer that shows when the cycle gets reset

**Comment by MichalD96** [comment]
this timer shows when the cycles will reset, every day at 00:00 UTC time
![timer](https://user-images.githubusercontent.com/53737762/72674999-6d2a4b00-3a7e-11ea-87ff-28d359d741ef.PNG)

if you click that timer it will show you time in game
