### ISSUE TITLE
Show only items with inventory amount < X

### ISSUE THREAD

**Issue by Riddim77** [jeanropke/RDR2CollectorsMap#755]
**Is your feature request related to a problem? Please describe.**
When trying to complete item collections, I always check my RDRO inventory and add all items to the map search manually which I need to complete collections. This is teadious and could be improved with the help of the inventory in the collectors map.

**Describe the solution you'd like**
It would me nice to be able to configure a maximum inventory amount X of a single item. As soon as an item is at least X times in the inventory, it is not shown on the map anymore (or greyed out).

This way it would be much easier to complete collection. If X is set to 1, only missing items are shown. If X is set to e.g. 3, only items are shown whith a low inventory amount.

Layout would be similar to the "Inventory Stack" configuration with a number selection (with max of "Inventory Stack").

**Comment by dlldldl** [comment]
I think marking those items <X as important (glowing red) vs greyed out works better, because greying out is intended to label whether it's collected or not for today's cycle.

**Comment by jonathonbarton** [comment]
It's functionally the same thing, I think. 

I tried using Stack Size to do the same thing @Riddim77 was attempting, but it just nerfed anything I had over the stack size. i.e. if I set Stack Size to 3, I "lost" 6 of the Texas Bluebells I had in inventory. 

Marking them as important doesn't accomplish the ask, since Pathfinder will still route you to anything that you haven't collected today. 

The ask is "Route me to ONLY the things I need to complete a set today".

**Comment by maeeh** [comment]
Well, i would prefer top have items <x not to be displayed (greyed out) , as I currently use the mark as important glowing feature especially  for missed items that are currently not available (bug / glitch) and which I'd like to revisit after a restart.

**Comment by MichalD96** [comment]
I added option that disable all items which you already have in your inventory - "Disable collected"
and option to add every item from the collection to the inventory.
To enable this options go to Settings, turn on inventory and check "Enable advanced inventory options" checkbox

**Comment by q1k** [comment]
I'd prefer if it was glowing in a different color. Pathfinder can have an option to just focus on important items first or only important.

**Comment by MichalD96** [comment]
Pathfinder has option to create a way only between important items.
Check option "Highlight low amount items" it creates stroke around every item low in your inventory. I think it is close to what you want.

**Comment by MichalD96** [comment]
I added option to show only items with amount < X in your inventory (inventory must be enabled)
![low_inv_items](https://user-images.githubusercontent.com/53737762/110270868-16a40700-7fc7-11eb-867c-bc27da04b39c.jpg)
