### ISSUE TITLE
Not an issue, but a suggestion. 

### ISSUE THREAD

**Issue by Vitor-Borba72** [jeanropke/RDR2CollectorsMap#764]
Maybe make the buttons for the dropdown lists a little bigger.  I mean the button where you click to open the lists of collectibles.
On the mobile (I use the iPad), it gets a little tricky to click the dropdown without activating the 
option to show/hide all instead. 

Thank you for your godly work, sir.

**Comment by jeanropke** [comment]
Updated the arrow size. 
Here is a comparison http://prntscr.com/qqzi2s
