### ISSUE TITLE
Map won't load at all

### ISSUE THREAD

**Issue by SaladGoat0** [jeanropke/RDR2CollectorsMap#765]
The map won't load at all (see screen shot).

I have tried clearing cache and opening it in google chrome, internet explorer and firefox. I have tried turning adblock and VPN off as well.

Any advice or tips would be greatly appreciated. Thank you.

![rdr2map](https://user-images.githubusercontent.com/60158631/72845073-d7eca980-3c6b-11ea-9f67-eeb8b5e6d91f.jpg)

**Comment by Senexis** [comment]
Should be fixed now.

**Comment by SaladGoat0** [comment]
It is! Thank you!
