### ISSUE TITLE
Missing Egret Egg

### ISSUE THREAD

**Issue by theycallmetmac** [jeanropke/RDR2CollectorsMap#779]
Hello, the Egret egg for cycle 5 is currently missing. I've hopped sessions but its not there.

**Comment by MichalD96** [comment]
I found this egg 3 hours ago, and i am sure it is there

**Comment by theycallmetmac** [comment]
Okay, I'll have to give it another try then. I server hopped a couple of times but it wasn't there. I'll try again tho.
