### ISSUE TITLE
Darkmode map have white background in New Austin when you zoom

### ISSUE THREAD

**Issue by TDLCTV** [jeanropke/RDR2CollectorsMap#78]
My bad, my script for photoshop failed for the "6" folder 

from 6/8_10.jpg to 6/9_37.jpg
And one picture from 7/23_4.jpg

[Fix here](http://beauj.eu/rdr/maps/darkmode/darkmode_v1.1_fix_only.rar)

**Comment by jeanropke** [comment]
Fixed now.
