### ISSUE TITLE
Order from the items sometimes different

### ISSUE THREAD

**Issue by Silent-Warrior5** [jeanropke/RDR2CollectorsMap#791]
Hi,

the map is good, but sometimes the item order ist not the same like last day:

some example:

yesterday:
01-Ein-Cent-Münze von 1787
02-Fünf-Cent-Münze von 1792
03-Fünf-Cent-Münze von 1800
04-Fünf-Dollar-Bechtler von 1800
05-Fünf-Dollar-Münze von 1795
06-Golddollar von 1800
07-Goldvierteldoller von 1800
08-Halber Penny von 1796
09-Liberty-Vierteldollar von 1792
11-Penny von 1789
12-Silberdollar mit Büste von 1798
13-Silberdollar von 1794
14-Virteldollar von 1792 
15-Zehn-Dollar-Münze von 1797

but today:

01-Goldvierteldoller von 1800
02-Silberdollar mit Büste von 1798
03-Ein-Cent-Münze von 1787
etc....

can you make the items always in the same order?

Thx &  Cheers
Silent

**Comment by Senexis** [comment]
That's because the first order is alphabetical and the second is in-game. There's an option to toggle between the two now. It doesn't change every day.
