### ISSUE TITLE
New Pathfinder option routes you on impassable terrain from the road.

### ISSUE THREAD

**Issue by jonathonbarton** [jeanropke/RDR2CollectorsMap#792]
The new Pathfinder doesn't account for inaccesibility very well. 

For instance: https://jeanropke.github.io/RDR2CollectorsMap/?m=coin_half_dime on Cycle 4 is on the TOP of the cliff, next to the train tracks, and Pathfinder has you arriving at the location on the trail at the foot of the cliff.

**Comment by PakL** [comment]
I'll add some 'fake' roads later to fix that.

**Comment by dlldldl** [comment]
Agarita Flower #3 - Cycle 1 or any items on Rio Del Lobo Rock have the similar issue or is there a route to climb up from the cliff side?
