### ISSUE TITLE
Pathfinder Enhancement: Allow Pathfinder to route via railroad tracks in addition to roads.

### ISSUE THREAD

**Issue by jonathonbarton** [jeanropke/RDR2CollectorsMap#793]
As per title: Pathfinding already uses roads and Fast Travel. 

Adding pathfinding via railroad tracks would be bonus!

**Comment by PakL** [comment]
I had thought about that. Just didn't have the motivation to do it yet.
I'd weight them higher than the normal roads, though, to discourage the pathfinder from using them.

**Comment by Senexis** [comment]
Train tracks can get the same weight in my opinion, the "speed bonus" roads sometimes give seems to be minor enough to not give them a preference as long as the finder can effectively use them. Just my 2 cents.

**Comment by PakL** [comment]
That is definitely true for routes like from Flatneck Station to Rhodes, and I don't want to make them too heavy. Just like 1.1x or something in that area.
I'm just worried about the train tracks around Tumbleweed. But we'll see, I guess.

**Comment by jonathonbarton** [comment]
I'd prefer a user-selectable weighting, since I personally STRONGLY PREFER train tracks. Especially around Tumbleweed, since there are never any rattlesnakes on the tracks! =)

**Comment by AlanXYLi** [comment]
@PakL What tool do you use to draw line strings?

**Comment by PakL** [comment]
@jonathonbarton I guess we could add sliders so everyone can set the weight to their preference...
@AlanXYLi I use the normal CollectorsMap with an added [Draw Plugin](http://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html). In Firefox for better performance.

I have the railroads done so far, just have to connect them to the existing net now.

**Comment by dlldldl** [comment]
> @jonathonbarton I guess we could add sliders so everyone can set the weight to their preference...
> @AlanXYLi I use the normal CollectorsMap with an added [Draw Plugin](http://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html). In Firefox for better performance.
> 
> I have the railroads done so far, just have to connect them to the existing net now.

I mean creating/making the GeoJSON file.

**Comment by PakL** [comment]
You can play around with the railroads as soon as the PR is merged. I'll add some weighting options on the weekend.
