### ISSUE TITLE
Item not at location on map

### ISSUE THREAD

**Issue by ThatKasper** [jeanropke/RDR2CollectorsMap#799]
There is nothing here

* What day cycle it is?
Cycle 4

* Coordinates or a clear image of the location
Latitude: -53.2891
Longitude: 117.9531

* Include the item name
Magnate Turquoise Ring
https://jeanropke.github.io/RDR2CollectorsMap/?m=ring_magnate_turquoise

**Comment by Senexis** [comment]
It's fine. Relaunch game.

**Comment by ThatKasper** [comment]
I relaunched several times & that location has always been a problem, going
back weeks. I also clear my cache fairly regularly as well & there are 2
spots that I never find the item located on the map: this one & the one at
Hanging Dog Ranch
