### ISSUE TITLE
[suggestion] Routes shown ase loops and can be optimised

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#8]
Hello! i was looking at the map routes and noticed they dont have a start and finish, they are more like a branching path. i was wondering if you could use an algorithm like the traveling [salesman] to figure out the routes with the least distance traveled

**Comment by jeanropke** [comment]
Some tests with salesman algorithm, not sure if works as intended.
![salesman](https://user-images.githubusercontent.com/6243818/65819510-dba77c80-e1f3-11e9-8bc2-4cb62b476eb0.png)

Using this repository https://github.com/lovasoa/salesman.js/

**Comment by iligalodin** [comment]
oh yeah that's not how it's supposed to look not sure how your nodes are placed on the map but it should look something like the example upon [this wiki page ](https://en.wikipedia.org/wiki/Travelling_salesman_problem) one line or loop, that does not visit previous nodes

**Comment by iligalodin** [comment]
the salesman will be to slow for this application, we might be better of manually creating routes and remove nodes from the list if they are hidden (not collected)

**Comment by flameango** [comment]
Is it possible to have some navigation features, like google maps has with roads?

**Comment by iligalodin** [comment]
fixed #106
