### ISSUE TITLE
Automatically open next pin tooltip when using path finding 

### ISSUE THREAD

**Issue by LordChunk** [jeanropke/RDR2CollectorsMap#800]
# Feature description
Currently you have to manually select each tooltip (the box that opens up when clicking a pin) for each pin you want to go to. It would be nice if it would open up the next one in the list when you select the next pin.

## Example
When selecting the your next item on your list.
![Example image 1](https://m.chu.mk/2020-01/RDR2_14-09_48.png)
It opens up the next tooltip as well
![Example image 2](https://m.chu.mk/2020-01/RDR2_14-10_02.png)

**Comment by jonathonbarton** [comment]
Duplicates #794
