### ISSUE TITLE
Reset daily markers, reset inventory

### ISSUE THREAD

**Issue by PurpleLi0u** [jeanropke/RDR2CollectorsMap#804]
I usually use the page to count my inventory and search a few collectibles. Always that i put the option "reset daily markers", my inventory return to 0 all... idk if i'm the only one with this little problem

**Comment by MichalD96** [comment]
I can't reproduce this bug with any settings,
could you post your map settings here?

try turn off all programs/ settings that clean your cookies, 
i think something delete your saved data, because there is no option that this setting may affect your inventory

**Comment by PurpleLi0u** [comment]
yesterday before the reset i put 10 "wild rhubarb flower" in the inventory, now after the reset in the inventory i have 0
![image](https://user-images.githubusercontent.com/60455314/73586825-9e007c00-4491-11ea-91b2-7bf90cf747ab.png)

my options
![image](https://user-images.githubusercontent.com/60455314/73586822-8d500600-4491-11ea-98f3-498231392bef.png)
![image](https://user-images.githubusercontent.com/60455314/73586829-b5d80000-4491-11ea-8f3e-6a5edfdc6b37.png)

i use the map on google chrome

**Comment by MichalD96** [comment]
You use very old map version, 
i don't know from what source you have this map, even if this bug have ever exists, have been fixed long time ago.
this map is updated several times a day, and you should use this version:
https://jeanropke.github.io/RDR2CollectorsMap/

**Comment by PurpleLi0u** [comment]
i use the map of this page
https://madamnazar.io/maps
i will use the map that you show me now.

**Comment by PurpleLi0u** [comment]
Today, one day after the change to the most updated map, i have my inventory without problems :) it was the version i think
