### ISSUE TITLE
Paths at Cumberland/Dakota river incorrectly connected

### ISSUE THREAD

**Issue by LordChunk** [jeanropke/RDR2CollectorsMap#808]
A set of paths that from the map look connected aren't actually connected

Coordinates:
Latitude: -42.6172
Longitude: 107.3281

A quick illustration alongside the paths to show which are and aren't connected
![Proper paths](https://m.chu.mk/2020-01/brave_20-44_36.png)
[Direct link](https://m.chu.mk/2020-01/brave_20-44_36.png)

The red path
![Red path](https://user-images.githubusercontent.com/23651869/73484699-11c35b80-43a2-11ea-9a7b-c2009a82dd27.png)[Direct link](https://m.chu.mk/2020-01/RDR2_20-45_28.png)

The green path
![Green path](https://user-images.githubusercontent.com/23651869/73484735-23a4fe80-43a2-11ea-8724-b4df8eda63ac.png)
[Direct link](https://m.chu.mk/2020-01/RDR2_20-46_52.png)

**Comment by PakL** [comment]
Thank you, for your report. Will be fixed as soon as #809 is merged.
