### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by rbcunhadesign** [jeanropke/RDR2CollectorsMap#82]
I think it would be helpful if we could add templates to the issues so people are more likely to include everything needed for an easier change.

Possible questions:

- Is the issue a suggestion, missing item, other - (please specify)

**Suggestion** or **Other**
- include any suggestions you may have
- *include coordinates when possible

**Missing Item**
- What day cycle it is?
- *Include coordinates or a clear image of the location
- include the item name

<br><br>
*Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by iligalodin** [comment]
Would love to make em, i don’t have access to the settings of the github though

**Comment by jeanropke** [comment]
I added Missing Items and Feature request.

**Comment by rbcunhadesign** [comment]
Nice, looks good!
