### ISSUE TITLE
Roads 

### ISSUE THREAD

**Issue by SapphicSpacePrincess** [jeanropke/RDR2CollectorsMap#824]
Is there any way to make the roads more opaque like they are on the actual game map? I use them as guides and to help me pinpoint where I need to go for collectables, but having the roads on the collectable map be almost invisible often makes pinpointing the more precise location rather difficult when I'm setting my waypoint on the game.

**Comment by MichalD96** [comment]
In right top corner of the map you have different map versions. Chose "Detailed" version, is almost the same as in game
