### ISSUE TITLE
Show the length of the route

### ISSUE THREAD

**Issue by beaves** [jeanropke/RDR2CollectorsMap#825]
Is it possible to display the length of the route or also the length of parts of the route?
From lat 0 lng 0 to lat 0 lng 1 on the map there are 0.04 miles in game.

**Comment by MichalD96** [comment]
sure, it is possible, but why you need this? You will never travel on straight line in game.
i think it will have more sense if @PakL consider something like this in his route generator

**Comment by PakL** [comment]
Before I might waste my time with this, may I ask what the benefit of this might be?
I can't see the point of having that information.
The only way that may become interesting is to calculate the time it could take. And that would also depend on the horse you have and item accessibility. Too many variables to be viable.

**Comment by Senexis** [comment]
Unless you can think up a good reason, it's not worth doing. Like PakL mentioned, the only valid use case would be to calculate time but there's too many variables to get that ball rolling.

**Comment by MichalD96** [comment]
There was a lot similar ideas like scale bar, map grid, rullers on the map edges but If you have ever made one longer way you should know how long it will take
