### ISSUE TITLE
1 Item not as stated

### ISSUE THREAD

**Issue by Mojnator** [jeanropke/RDR2CollectorsMap#83]
I did every item on the map today and found 1 item was missing, the goose eggs near Blue Water marsh were not where indicated (they were not present at all in the vicinity), pretty high accuracy but wanted to let you know about that one. Big thanks for you efforts and hard work.

![2019-10-01 18_11_31-Red Dead Redemption II Collector Map](https://user-images.githubusercontent.com/56042017/65984117-f5a4c180-e476-11e9-9550-acd411f7963f.png)

**Comment by TDLCTV** [comment]
i think eggs spawn are based on day time
for me i can't find too "Spoonbill Egg - Day 1"@"lat: -74.78125 lng: 154.8125" in game time 07:00 A.M.

**Comment by jeanropke** [comment]
This Goose Egg is a random item spawn. I'll remove it.

I'll check the Spoonbill Egg, this egg is on a tree.
