### ISSUE TITLE
Bugged item: Egret Egg Cycle 4 (near Kamassa River)

### ISSUE THREAD

**Issue by simmayor** [jeanropke/RDR2CollectorsMap#831]
Not sure if this is the best place to report this, but the egret egg for cycle 4 is bugged for me. I shot the nest and destroyed it, but the egg didn't drop; it stayed on top of the tree. 

Latitude: -69.6641
Longitude: 140.7813

**Comment by Senexis** [comment]
Welcome to Egret Eggs. Location is correct though. Also, you can still get the item if you jump on top of a bounty wagon.
