### ISSUE TITLE
Default Cycle Config

### ISSUE THREAD

**Issue by ImIOImI** [jeanropke/RDR2CollectorsMap#845]
**Is your feature request related to a problem? Please describe.**
It's hard to know which item is on what cycle

**Describe the solution you'd like**
A json config that maps items to cycles and last update times. Something like:
```
{
  "eggs": {
    "cycle": 3
    "updated": "2019-02-19"
  },
  "coins": {
    "cycle": 6
    "updated": "2019-02-19"
  }
}
```
Ideally, the update time would be added via a node publish script or something.

This info would be used to populate the cycles via a button or something.

**Describe alternatives you've considered**
Possibly having an issue here where the latest cycles are discussed

**Comment by Senexis** [comment]
Not sure why you'd want this, but check out `cycles.json`.

![image](https://user-images.githubusercontent.com/6360733/74448660-9e2e4d80-4e7b-11ea-9249-b67c2eb6ab38.png)

**Comment by ImIOImI** [comment]
Ah ha! I missed that file in data. Thanks!
