### ISSUE TITLE
Unable to collect the 1792 Quater Coin 

### ISSUE THREAD

**Issue by StarLord4hire** [jeanropke/RDR2CollectorsMap#850]
Over the last 4 days, I have not been able to collect 1792 Quater. I do not know if others have experienced the same issue, so please let me know. 
If it is something nobody else has experienced, I will reach out to Rockstar.
If it is something everyone is experiencing, then the only recommendation would involve a notation on this item explaining it is bugged. 

Thanks!

**Comment by ToTster** [comment]
https://jeanropke.github.io/RDR2CollectorsMap/?m=coin_quarter  Same here.

**Comment by jeanropke** [comment]
R* messed up `1792 Quater Coin` with `1792 Liberty Quarter Coin`.
If you have 10 `1792 Liberty Quarter Coin`, you are unable to collect  `1792 Quater Coin`
