### ISSUE TITLE
Tarot Cards Swap Knight and Page in the list

### ISSUE THREAD

**Issue by JRSC01** [jeanropke/RDR2CollectorsMap#856]
@jeanropke 
Is it possible to reorder the list here swapping the Knight and Page cards, so that they match the order in game.
The game version has listed them as **Knight**, then **Page, Queen, King**

Thanks, not a huge difference, but as i cross off the list i keep mixing these two up, matching with the ones i already have.

PS, Thanks to all you and the rest of the team for this. It is fantastic and i hope that it is not too long before the Rockstar devs fix the Duchess Emerald (Cycle 5) Earrings!

**Comment by jeanropke** [comment]
Cards order are already correct

https://i.imgur.com/Qk1tp7l.mp4
