### ISSUE TITLE
Cannot get 1792 Quarter Coin 

### ISSUE THREAD

**Issue by N0X-44** [jeanropke/RDR2CollectorsMap#857]
3rd day in a row where I cannot collect the 1792 Quarter.

**Comment by shotblstr** [comment]
I've been trying the last 4 days to get it too. It's bugged. I submitted a ticket to Rockstar. It's the last coin I need for the collection.

**Comment by dlldldl** [comment]
I encountered the same bug and filed support ticket. It is related to "1792 Liberty Quater". If you get ten "1792 Liberty Quater" already, you won't be able to collect "1792 Quater". It would be fixed if you sell one "1792 Liberty Quater" to Madam Nazar.

**Comment by shotblstr** [comment]
No I do not have 10 of the item.

**Comment by dlldldl** [comment]
Hmmm, you still can sell a 1792 Liberty Quater to Madam Nazar and try again...
