### ISSUE TITLE
Not an issue, repeating daily non cycle items - is there a plan and can I help.

### ISSUE THREAD

**Issue by Mojnator** [jeanropke/RDR2CollectorsMap#86]
Outside of the daily cycles shown in the map there are other items at static locations, the locations are consistent but the items appear not to be (although they "seem" to be consistent in their category) is there any plan to add these? is it worth me correlating any info I can?

**Comment by iligalodin** [comment]
Hey thanks for the interest! If you could, could you collect some co-ordinates and descriptions on where you found the “digsites” obv in which cycle found

We’ve archived some locations if you look at the closed issues

**Comment by iligalodin** [comment]
A.e:
"lat": "-45.9296875","lng": "142.5078125"
![image](https://user-images.githubusercontent.com/1492205/65992325-43c5bf00-e48f-11e9-96fe-299ff1fadb35.png)

**Comment by iligalodin** [comment]
Day 2:
 "lat": "-59.5546875","lng": "133.6875"
![image](https://user-images.githubusercontent.com/1492205/66056410-55fb3800-e537-11e9-99c7-263c026432ad.png)

**Comment by iligalodin** [comment]
Day 2:
lat: -75.734375
lng: 148.2578125
![image](https://user-images.githubusercontent.com/1492205/66058316-74166780-e53a-11e9-9a1d-8ad8fb26d9fb.png)

**Comment by iligalodin** [comment]
Day 2
lat: -76.6484375
lng: 122.9453125
![image](https://user-images.githubusercontent.com/1492205/66059173-e0459b00-e53b-11e9-8490-d0d0e0560b1d.png)

**Comment by jeanropke** [comment]
Added almost 200 random spots
