### ISSUE TITLE
Can't Import on tablet and mobile browsers

### ISSUE THREAD

**Issue by Smiffleblurf** [jeanropke/RDR2CollectorsMap#860]
I enjoy using maps like these on my tablet while playing so that I don't need another monitor. With my iPad I am able to use all other functionalities of the map including export to a folder, but whenever I choose either the settings or user pins file - when I tap Import I get an error message that this is not supported.

But I've been able to upload and download files to and from sites before on either Chrome or Safari for mobile. Not sure if this can be allowed to import via tablet and mobile devices.

As a last resort, I copied the files to my PC and tried to upload them in Chrome. The settings file worked, but the import for user pins came up that the export file I have is broken.

**Comment by Senexis** [comment]
@Smiffleblurf Can you confirm that this is still happening? Commit 4d7f7bd3859d4896f811ec0d01339cca44a81129 attempts to fix this. Let me know if it doesn't.

**Comment by Smiffleblurf** [comment]
> @Smiffleblurf Can you confirm that this is still happening? Commit [4d7f7bd](https://github.com/jeanropke/RDR2CollectorsMap/commit/4d7f7bd3859d4896f811ec0d01339cca44a81129) attempts to fix this. Let me know if it doesn't.

Testing on Chrome for iOS.
I verified Settings exports and imports ok now.

When I try to import User Pins it gives this error.
![70AEEB3A-F58D-4FE7-826C-825841636F6D](https://user-images.githubusercontent.com/41557065/75084911-8b012a80-54d8-11ea-8273-f2d99eb5dc82.jpeg)

**Comment by Smiffleblurf** [comment]
Also this is the file I had exported for User Pins is you wanted to analyze it.
[UserPins.txt](https://github.com/jeanropke/RDR2CollectorsMap/files/4238737/UserPins.txt)

**Comment by Senexis** [comment]
That's because that's not a valid pins file. Did it give you that when exporting and did you have pins?

**Comment by Smiffleblurf** [comment]
Yes, that’s the file it exported and I saved to my drive as “UserPins.txt”. I had a custom set of pins only enabled on the map, then exported.

Terry

**Comment by Senexis** [comment]
Due to miscellaneous changes I'm closing this issue. If there's any more troubles, feel free to open a new one!
