### ISSUE TITLE
Touch Target for Inventory increase/decrease too small

### ISSUE THREAD

**Issue by Loriath** [jeanropke/RDR2CollectorsMap#869]
I use the map on an iPad mini while I am playing on Xbox. When I am setting up my Inventory levels for each item, the touch targets are very small and 80% of the time I end up removing the items from the list instead of increasing or decreasing the count.

I have tried pinch to zoom which does not work in order to increase the size of the targets. If I pinch and zoom, the targets do increase, but then because the side panel fills the screen, it scrolls the item names off the screen and I cannot see which one I am dealing with.

I have included some pics so you can see what I am seeing.

Possible solutions : 
Make  the + and -  larger, or actual buttons,
Make the side panel Dynamically allocate the width based on the labels as it is on PC browsers

I know I am in the Minority using it on a smaller device but this is my only option while playing on Console.
Thanks in Advance.

<img width="1024" alt="PNG image 3" src="https://user-images.githubusercontent.com/61407090/75137216-544d2f00-56e7-11ea-8a0f-5d9737283f04.png">

<img width="1024" alt="PNG image 4" src="https://user-images.githubusercontent.com/61407090/75137217-54e5c580-56e7-11ea-8354-d89f5736be0a.png">

<img width="768" alt="PNG image 2" src="https://user-images.githubusercontent.com/61407090/75137218-54e5c580-56e7-11ea-8082-850e53a8c5f3.png">

**Comment by jeanropke** [comment]
Did the 8f2778d commit to update this button size. Can you please tell me if it better now?

**Comment by Loriath** [comment]
I just tried it and it is definitely 100% better. I would like it to be a bit larger (Say 10-15%), but I can understand that it would get too large and cause spacing issues.  If this is the fix, I can live with it. 

Thanks for looking at this so quickly.

**Comment by jeanropke** [comment]
I can increase even more.
They were 20px, now are 26px. I'll set to 32px.

**Comment by Loriath** [comment]
Ok. if that is where your are putting it, I can live with that. Lets consider this dealt with.

Thanks.
