### ISSUE TITLE
Route map not updating after deselecting items

### ISSUE THREAD

**Issue by Jelbrehir8** [jeanropke/RDR2CollectorsMap#88]
This is a great project and this is not a complaint, but the "enable route" only works for me with all the items. If I select just one collection, and turn off routes and then turn routes back on, the route is still for every collectible, not just the selected collection

![](https://i.gyazo.com/5f53a2cc0d6371c712f4615864306846.jpg)

**Comment by iligalodin** [comment]
yeah the route is currently hardcoded, we're working on a sollution

**Comment by iligalodin** [comment]
fixed! #106
