### ISSUE TITLE
Collectibles count wrong, can reach higher than 10???

### ISSUE THREAD

**Issue by Sr-Drako** [jeanropke/RDR2CollectorsMap#882]
Collectibles count let me reach more than 10 per stack. After 9 number turns red on 10 and can reach more than 10. Also this doesn't eliminate the collectible and for example, repeated plants don't turn off around the map, only the ones I disable.

**Comment by Sr-Drako** [comment]
![numero rojo](https://user-images.githubusercontent.com/58880055/75448531-24ea2c80-594a-11ea-8b79-436ff3943790.png)
![numero rojo 2](https://user-images.githubusercontent.com/58880055/75448539-274c8680-594a-11ea-8384-aa37cab48b15.png)

**Comment by Senexis** [comment]
Known issue, will return soon.
