### ISSUE TITLE
Something about moving down one step

### ISSUE THREAD

**Issue by kirkkertrats** [jeanropke/RDR2CollectorsMap#883]
Page of cups tarot card needs to be moved down one more step behind the knight of cups.  Same with page of swords. (Incidentally R* screwed up on their order of pentacles in this area)

**Comment by Senexis** [comment]
Please clarify what you mean by "move down one more step".

**Comment by kirkkertrats** [comment]
The order on the map doesn’t match the ps4 game.

**Comment by AdamNortonUK** [comment]
I think he means that Tarot Cards order is like this, as in the game:
Cups
Swords
Wands
Pentacles

But would prefer it to be

Cups
Pentacles
Swords
Wands

**Comment by jeanropke** [comment]
Rockstar messed up the cards order. On PC the order is Page > Knight > Queen > King
