### ISSUE TITLE
goose egg cycle 3 wasn't on the little island, scotch whiskey cycle 4 wasn't at the ruined hut - instead I found an arrowhead - splintred that should have been in lagras

### ISSUE THREAD

**Issue by mhbp81** [jeanropke/RDR2CollectorsMap#887]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by mhbp81** [comment]
correction: the whiskey was at the right location.

**Comment by jeanropke** [comment]
The egg was there. Probably a game bug. Try changing sessions or clearing game cache.
