### ISSUE TITLE
Random Item #59 - Cycle 6

### ISSUE THREAD

**Issue by PatrickTetz** [jeanropke/RDR2CollectorsMap#891]
![image](https://user-images.githubusercontent.com/8439727/75692187-76295180-5ca5-11ea-9705-cc01cbfaba98.png)

![image](https://user-images.githubusercontent.com/8439727/75692248-88a38b00-5ca5-11ea-999d-73400aa87f36.png)

**Comment by MichalD96** [comment]
fixed
