### ISSUE TITLE
changes cycles

### ISSUE THREAD

**Issue by davidaberger** [jeanropke/RDR2CollectorsMap#899]
sorry to bother you but i was just wounder if and how you can scroll though cycle 1-6 in each category because i tried to click on the numbers to cycle through for the wild flowers and i cant seem to change the cycle its only showing cycle 5. Any help would be appreciated thank you

**Comment by MichalD96** [comment]
we update the cycles every day, so everything should be up to date, and you don't need to change cycles by yourself
but if you want to check another cycles, in menu, last option in Customization tab "Enable manual cycle input", check this option and you will can change the cycles manually again

**Comment by jeanropke** [comment]
You can change cycles manually enabling this setting https://prnt.sc/rc4g6a
