### ISSUE TITLE
Check/Uncheck visited location

### ISSUE THREAD

**Issue by Isokafish** [jeanropke/RDR2CollectorsMap#9]
Is it possible to add a check on the positions of the labels? It happens sometime that I'm not sure if i visited a lcation or not and finding the corresponding item in the menu is time consuming

**Comment by jeanropke** [comment]
Added an option to remove markers from map. Remember to enable them again once finished on menu.

**Comment by iligalodin** [comment]
sorry to bump, @jeanropke  would it be a good alternative to have the markers semi transperant?

**Comment by jeanropke** [comment]
Now the markers are semi transparent.

**Comment by Isokafish** [comment]
Thanks guys, your work is amazing!

Inviato da iPhone
