### ISSUE TITLE
Bug: Can't shoot down Egret Egg

### ISSUE THREAD

**Issue by Rob-P53** [jeanropke/RDR2CollectorsMap#900]
Location:
https://jeanropke.github.io/RDR2CollectorsMap/?m=egg_egret
[Just to the WEST of the "B" in "Bluewater Marsh" on the map, and NORTH of the bridge that's under the "B" in "Bluewater Marsh" on the map. It's in an old dead tree with very few branches and no leaves at all.

Issue: This is not an issue with the map, but a GAME error (Egg won't drop)
Use Bow & Arrow with Small Game Arrow.
Shoot nest, but Egg will not drop.
Shoot Egg directly after nest destroyed, and egg will not drop.

**Comment by jeanropke** [comment]
Already known bug. IIRC, R* tried to patch this, but have failed miserably

**Comment by Rob-P53** [comment]
Then update the map, like you have other tiems and put a big RED "X": over
it saying you can't get it.
