### ISSUE TITLE
Wands tarot card

### ISSUE THREAD

**Issue by kirkkertrats** [jeanropke/RDR2CollectorsMap#908]
Page of wands tarot card is out of order. Doesn’t match the game.

**Comment by jeanropke** [comment]
Seems right on PC, probably R* messed up something again.
https://i.imgur.com/NyqbcJN.mp4

**Comment by kirkkertrats** [comment]
Thanks for reply,  I think you are right on the R* bit as the last few tarot series doesn't match their first two series orders.  Anyway it is only a slight inconvenience.  Thanks for all you do.
    On Sunday, March 8, 2020, 08:30:19 AM PDT, jeanropke <notifications@github.com> wrote:  
 
 
Seems right on PC, probably R* messed up something again.
https://i.imgur.com/NyqbcJN.mp4
