### ISSUE TITLE
Incorrect item Cycle: day #6 Duck eggs not there

### ISSUE THREAD

**Issue by tcarder** [jeanropke/RDR2CollectorsMap#911]
#### Duck eggs not there [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? 6
* Coordinates or a clear image of the location o'creagh's run
* Include the item name Duck eggs not there

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
try change the session, the egg must be there

**Comment by jeanropke** [comment]
Check if the amount of duck eggs in your inventory is less than 10.
