### ISSUE TITLE
Collect map with no items on it on mobile 

### ISSUE THREAD

**Issue by Andry92xx** [jeanropke/RDR2CollectorsMap#912]
Hello i used the collectors map on RDR2 with my phone and it worked well.
Now i'm trying to open it  but when i open it with my phone ( iphone SE ) i have no items on it but if i try to open the other version ( no collectors ) everything is ok. 
I opened it with my mac and is ok , with another phone ( samsung s3 ) anche is ok. 
Can u help me? 
thx

**Comment by jeanropke** [comment]
Are there the categories in menu disabled or a search query is being used?

**Comment by Andry92xx** [comment]
All the options are default , i ve already did the reset also but nothing happens. With my mac or anothre phone works. I don't even see the time on the left

**Comment by jeanropke** [comment]
Try to open the map in incognito window/tab.

**Comment by Andry92xx** [comment]
Nothing happens mate, i really don't know what to do.

**Comment by Senexis** [comment]
Still having this issue? If so, please visit https://jeanropke.github.io/RDR2CollectorsMap/?show-alert=1 and see if there's any error messages.

**Comment by Andry92xx** [comment]
Still i can't see anything, now i can't see even the map. 
Before that i saw the map but with no icon and no time ( i didn't flag anything on the menù ) 
I really don't know what to do i m using it with the mac and it works but u know with phone its easier

**Comment by PaleReidar** [comment]
I`m having the same problem in windows after using the map for months. (thanks a lot!) The map is just empty..

**Comment by whytheseaisboilinghot** [comment]
Cookies might be causing the issue ☺️

**Comment by MichalD96** [comment]
@PaleReidar in what file and line you can see that error?
could you make a screenshot of that error?

**Comment by whytheseaisboilinghot** [comment]
Iphone SE is an older device and if 6ou are using the Safari browser to view the map it won't be able to load because apple doesn't  grant Safari permissions to view HTML sites. I suggest you get the Firefox browser in order to be able to view the map for an older iphone in lieu of Safari.

**Comment by PaleReidar** [comment]
A great day! It is alive again! Thanks a lot!

**Comment by PaleReidar** [comment]
> A great day! It is alive again! Thanks a lot!

just for so long, now it`s dead again, on any browser

**Comment by MichalD96** [comment]
i can't say what is going on, but since 9 days there wasn't any change in the map code that may cause that behavor.
Try to open map in browser incognito mode, if that load everything you should `Reset all settings`, in normal mode. if this error `TypeError: Cannot read property 'menu.collectables' of undefined` still exists it is caused by old inventory. and don't import any settings file, created before settings reset.

**Comment by PaleReidar** [comment]
Ouff, the problem was all my settings the way, pardon moi
