### ISSUE TITLE
Incorrect item Cycle 4: Texas Bluebonnet flower and all collectibles from Tumbleweed

### ISSUE THREAD

**Issue by progkcah** [jeanropke/RDR2CollectorsMap#917]
So, I tried looking for some items in New Austin... I started from the abandoned mineshaft and I found the two items at the end of the rail, then I went to Tumbleweed but I didn't find nothing, neither the Texas Flower in the countryside. I can't get it since some items from the same cycle can be found.

**Comment by Senexis** [comment]
Try swapping sessions or rebooting the game next time you come across this issue.

**Comment by progkcah** [comment]
oh okay, thank you mate, I appreciate the amount of effort you're putting
into this map.

Il giorno sab 14 mar 2020 alle ore 14:36 Timo Viveen <
notifications@github.com> ha scritto:
