### ISSUE TITLE
[QoL] Navigation Line Placement option to prevent accidental placement when clicking map

### ISSUE THREAD

**Issue by Rakmarok** [jeanropke/RDR2CollectorsMap#92]
**Is your feature request related to a problem? Please describe.**
After finishing to place a custom route, every time I click on a map marker to hide it, I place a new navigation line. That forces me to constantly delete them again. Which is not breaking anything, which is why I filed it under "Quality of Life".

**Describe the solution you'd like**
"Enable Custom Route" could be changed to "Enable Custom Route _Placement_", enabling placement of new navigation lines only when this is turned on but keeping the already placed lines on the map when turned off after placing them. The addition of a "Clear Custom Route" button would work well together with it.

**Describe alternatives you've considered**
An alternative would be to have to hold Shift to place new navigation lines, while still keeping holding CTRL to delete them. This could be a option toggle in the settings for people that like the old functionality.

**Additional context**
Should you be able to implement the route to automatically adjust to the chosen collectibles then my request could be nullified. But having more options is always better than less.

Thanks for all the amazing work on this map. You helped me immensely making RDO$ in the last 4 days. 

- Rakmarok

**Comment by jeanropke** [comment]
Selecting 'no' keeps the lines on the map. Added option to clear custom routes.
