### ISSUE TITLE
1792 Quater 

### ISSUE THREAD

**Issue by ToTster** [jeanropke/RDR2CollectorsMap#921]
The Quarter I can not get.  Only have 6 in inventory.   

https://jeanropke.github.io/RDR2CollectorsMap/?m=coin_quarter

**Comment by jeanropke** [comment]
How many liberty quarter in inventory?

**Comment by ToTster** [comment]
6

**Comment by Senexis** [comment]
A few people are reporting this issue on this cycle specifically. Can, however, confirm that it spawns fine for me.

![image](https://user-images.githubusercontent.com/6360733/76683026-fb472b80-6600-11ea-8bb7-df6c60577e3b.png)
