### ISSUE TITLE
Incorrect item Cycle: day #2 for arrowhead_flint

### ISSUE THREAD

**Issue by tmoench** [jeanropke/RDR2CollectorsMap#922]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* arrowhead day cycle 2
* Coordinates: Latitude: -108.7813, Longitude: 26.8359
* item name: arrowhead_flint ("Kiesel-Pfeilspitze" in German)

**Comment by jeanropke** [comment]
Random item spot #56
