### ISSUE TITLE
Issue with Cookies

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#932]
Hi,

There seems to be an issue with certain cookies that are blocked from being used as a cross-site resource.

I use the map in an iFrame combined with some other tools on a ultrawide screen. Since a couple of days my selection of collections (ie coins and jewelry) gets reset after very page refresh.

Which is not the case with individual items. That selection reloads correctly.

It seems to have something to do with a cookie setting:

The default behaviour applied by Chrome is slightly more permissive than an explicit SameSite=Lax as it will allow certain cookies to be sent on top-level POST requests. You can see the exact details on the blink-dev announcement. This is intended as a temporary mitigation, you should still be fixing your cross-site cookies to use SameSite=None; Secure.

**Comment by Senexis** [comment]
Currently not possible due to being hosted on GitHub pages, and you can't edit headers on there as far as I know and found. Will try another way later, but there's no guarantee that will work. Hopefully they will change their policy later.

**Comment by Shaftoe62** [comment]
Strange, becaus there used to be no problem before. Has something changed?And the funny thing is most cookies do work. Except te ones controlling the active/inactive selection of collections.

**Comment by Senexis** [comment]
No longer an issue, not using cookies anymore.

**Comment by Shaftoe62** [comment]
Nice. No more cookie errors in console. May I ask; how do you store the settings now? Server side session?

**Comment by Senexis** [comment]
Local storage. Caused some other issues today, but most of those have been fixed now too.

**Comment by Shaftoe62** [comment]
Ok, can be complicated. Consider my remarks as testing/debugging assistance. Also see issue 935. They are probably connected.

Keep up the good work!
