### ISSUE TITLE
"Reset markers now" does not work

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#935]
The function "Reset markers now" seems to have stopped working...

**Comment by Senexis** [comment]
Fixed.

**Comment by Shaftoe62** [comment]
Hmm, "Reset markers now" seems to fall back on an old cookie or something. It doesn't reset all the items to "visible".

**Comment by Senexis** [comment]
Works fine for me. Is your inventory filled up?

**Comment by Shaftoe62** [comment]
No, inventory is not active.

What seems to happen is this:

Say I start now and all items are active.

Then I "find" some stuff and make those items inactive.

Then I do "Reset markers now" and I see the selection as where I left of yesterday.

Then I do a refresh (F5) and then I have the pages as if it were reset.

But if I do a "reset markers now" again, I have the selection of yesterday again.

So I think a reset does take place, but it then is followed by a reload of the cookie values from yesterday. Or something like that.

**Comment by Shaftoe62** [comment]
So, what I have to do now to get a reset is:
1. "Reset markers now"
2. "Reload page" (F5)

**Comment by Shaftoe62** [comment]
This is very persistent and it loads exactly the same "selection" everytime. So it has to be something that is stored in some way and gets loaded again after "Reset markers now".

I tried Ctrl - F5 and a restart of my browser. It keeps doing that with the same selection every time.

**Comment by Shaftoe62** [comment]
Ok, I now did a "Reset all settings" and now the old cookie (or whatever it was) has been reset or deleted.

So now I can't reproduce it again but it's there, lurking in the shadows...
