### ISSUE TITLE
Settings and inventory reset, and import of settings file does not change settings

### ISSUE THREAD

**Issue by PJRay** [jeanropke/RDR2CollectorsMap#936]
During the last 12 hours or so, the site reset for me. I did not clear my cache or cookies at any point, I simply refreshed the site in my browser this morning when I saw the bar at the bottom of the map telling me to. All settings was set to standard (including changing the map layers to standard instead of detailed), and all inventory went to zero. If I try to import a previously exported settings file, nothing changes, like the import is simply ignored.

This is the third time it has happened to me. 

Any ideas what could cause this, and is there any way to get my inventory and settings back, apart from manually doing it all again?

**Comment by Senexis** [comment]
Something unfortunately changed with a reset as a result. The import is also not backwards compatible. This will never happen again in the future due to this being a future-oriented change, and configuring the map again will allow you to get back to where you started.

Sorry for the inconvenience.

**Comment by PJRay** [comment]
Good to know that there at least was an explanation, thank you for the super quick response! :)
