### ISSUE TITLE
Utilities -> Random Encounters now opens RDO map in new browser tab?

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#937]
If you click on Utilities -> Random Encounters a new browser tab opens which loads RDO map.

**Comment by MichalD96** [comment]
yes, Random Encounters are only on RDO map now

**Comment by Shaftoe62** [comment]
Ehm, ok. That's not very logical for a user. 

It is not a spot where you expect navigation to another page.

And there allready is a link to RDO map.

Best leave out the link alltogether then.

Or make it greyed out with a mouseover text telling it's been moved or someting.

**Comment by MichalD96** [comment]
It is temporary. it have been made because most of the people dont know that RDO map exists and ask over and over to add something to collector map what is on RDO map for a long time

**Comment by Shaftoe62** [comment]
Ok, I can understand that. 

But why don't you put it on the bottom and name it: 

For all other resources see RDO map.

Perhaps in a smaller font-size.

**Comment by MichalD96** [comment]
On the bottom is also link to RDO map, since the beginning of this map. 
A lot people don't even scroll to the settings section, so in my opinion it is very good place for that link

**Comment by Shaftoe62** [comment]
I agree. I meant on the bottom of the "Utilities" section. Something like this:

![image](https://user-images.githubusercontent.com/53898212/77153850-d89e9200-6a9a-11ea-8c0a-06270188b12c.png)

**Comment by Senexis** [comment]
Like Michal mentioned, it's to point existing people that use it to RDO, and will be entirely removed in a little bit. For now, we won't change anything about this in case people "lose" it.
