### ISSUE TITLE
Program is not currently saving or reading the state of the items that have been "removed" after pick up. If you shut down the page and reload it, all items on the map are shown as being available. Acting as if "Daily Reset" is activated on reload.W10, Google Chrome.

### ISSUE THREAD

**Issue by EverettLawson** [jeanropke/RDR2CollectorsMap#940]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalD96** [comment]
go to Settings -> Reset all settings -> yes
that should solve the problem
