### ISSUE TITLE
Item description while mouse hovers is pretty bad

### ISSUE THREAD

**Issue by ChickenExotic** [jeanropke/RDR2CollectorsMap#942]
I have a double monitor, when i try to click on an item to read the description i realized that all i have to do is hover. thats good and all and it saves a click BUT since i am playing in one screen and looking at the map in the other when i mover my mouse i might hover over another item and it gives me the description. I am really not a fan of that, it takes me longer to get collectibles done even with a map due to this. not only that, if an item is at the edge of my chrome page, the page will move along to where the i just might have hovered. Can we change this back or make it optional. or can i disable that on my own somehow?

**Describe the solution you'd like**
have it the way it was a few days ago

**Describe alternatives you've considered**
expanding my page, but i always have multiple programs going on at once, i need the image space

**Comment by MichalD96** [comment]
you can disable it in menu
uncheck "Open marker popup on hover"

**Comment by ChickenExotic** [comment]
> you can disable it in menu
> uncheck "Open marker popup on hover"

I LOVE YOU WITH ALL MY HEART!!!
