### ISSUE TITLE
Where did the roads go?

### ISSUE THREAD

**Issue by bobmotownmail** [jeanropke/RDR2CollectorsMap#943]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalD96** [comment]
i think you mean detailed map. click icon on top right map corner and change value form "Default" to "Detailed"

**Comment by Shaftoe62** [comment]
This is also related to the general overhaul of the way settings are stored. Why don't you make a temprary splash screen to advice everybodt to execute a "Reset All Settings" that resolves all issues and 

> i think you mean detailed map. click icon on top right map corner and change value form "Default" to "Detailed"

This is also related to the general overhaul of the way settings are stored. Why don't you make a temprary splash screen to advice everybody to execute a "Reset All Settings" that resolves all issues?

**Comment by MichalD96** [comment]
@Shaftoe62  because code contain function that removes all old cookie data, and it rarely happens that something doesn't work
