### ISSUE TITLE
Hide all items (individually) in category

### ISSUE THREAD

**Issue by dlim87** [jeanropke/RDR2CollectorsMap#948]
**Is your feature request related to a problem? Please describe.**
Similar to #281, when I'm going through and hunting for just a handful of items to complete a collection (instead of building up a whole collection), I have to hide all of the items EXCEPT the ones 
I want to find inside a category in order for it to correctly path to them in the route finder

It would be a lot easier if there was a button to hide each item inside the category individually, and then just re-enable the ones I want included in the path finder.  

This would be a separate UI element from the 'hide category' functionality when you click on the category's name, since that non-destructive (to the individual item hide/show list) functionality is still useful, and probably even more important.

**Describe the solution you'd like**
A new UI element, separate from the current 'hide category' functionality, to hide each item inside a category. When you click on that UI element, it would set every item inside that category to the hidden state (where it's crossed out), instead of hiding the whole category. 

**Describe alternatives you've considered**
Alternatively, a setting to hide any items which have a non-zero inventory count might be cleaner...Which I guess is #755

**Comment by dlim87** [comment]
https://github.com/jeanropke/RDR2CollectorsMap/pull/889 May also be similar, is there any documentation on how to use this in the UI?

**Comment by MichalD96** [comment]
Do you use map on PC or mobile device?
i am asking because in menu is no space for next buttons and would be easier to add this option to right or middle mouse click

**Comment by dlim87** [comment]
Yeah, I don't think there's really space on the PC interface either, tbh. I'm not sure if binding it to an alternate click world be a good idea, though, since that UI would be non obvious and could result in frustrating if you misclick without knowing about it

**Comment by MichalD96** [comment]
yes, this is another thing
on the list is to add more functions like add 1 of every item to the inventory from the category
or disable only items that are in your inventory
maybe that would need to add next line of buttons, i will look at it

**Comment by MichalD96** [comment]
I added option that disable all items which you already have in your inventory - "Disable collected"
and option to add every item from the collection to the inventory.
To enable this options go to Settings, turn on inventory and check "Enable advanced inventory options" checkbox

**Comment by dlim87** [comment]
That sounds great, thanks
