### ISSUE TITLE
Keeping Accurate Inventory

### ISSUE THREAD

**Issue by Hankooktired** [jeanropke/RDR2CollectorsMap#950]
I sometimes horde items but items i have more than 5 of stays crossed out even when I haven't collected it yet. I can only have it stay lit on the map when I decrease actual count of the item down to 5 or less.

**Describe the solution you'd like**
It would be nice if I can keep toggle add/remove item without relation to how many i have in inventory. So it will not stay crossed off the map just because I have more than 5.

**Comment by MichalD96** [comment]
make sure your "Item stack size" and "Flowers soft stack size" are set to 10
this is the only option that may cause that map behavior

**Comment by Hankooktired** [comment]
Oh, thank you!
