### ISSUE TITLE
Family Heirlooms Same Cycle As Yesterday

### ISSUE THREAD

**Issue by zeekiwi** [jeanropke/RDR2CollectorsMap#955]
I am just wondering why the family heirlooms are still on the same cycle as yesterday and what that means? We are unable to find any new heirlooms for collector. We see the message stating they are on the same cycle as yesterday. Why is this? I am just trying to understand why and how often this happens so I can fully understand how the cycles work. I just started doing this yesterday and until today it has been flawless.
Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
It means that if you picked the heirloom yesterday for example at 8:45PM you can't pick up this heirloom today until 8:46PM
there is 24 hours delay before item in the same cycle spawn again, 
normally everything resets at 00:00 UTC, but not items that are in the same cycle as yesterday
