### ISSUE TITLE
Route Generation 

### ISSUE THREAD

**Issue by OliverLefter** [jeanropke/RDR2CollectorsMap#965]
The route Generation specifically the path finder does not work

**Comment by Dark360** [comment]
Noticed the same thing this morning.
Worked fine yesterday.

**Comment by Dark360** [comment]
I have tested all the collection sets individually in case one collection/set had path issues, same issues occurs no matter which collection sets is visible.
Enabled Debug Tool and tested last 7 days, which has been working fine and same issue occurs.

**Comment by MichalD96** [comment]
Fixed
