### ISSUE TITLE
2 or 3 Save Slots

### ISSUE THREAD

**Issue by LAxExcalibur** [jeanropke/RDR2CollectorsMap#968]
This way those Collecting with friends can assist them in obtaining their own personal count. And for other miscellaneous purposes.

**Comment by MichalD96** [comment]
could you describe more precisely what feature do you want?

**Comment by LAxExcalibur** [comment]
The option to have an additional (2nd) screen or slot....of saved (checked off/marked) collectibles. This way players can have the chance to have a prime slot for their collections they do daily, then they’re second slot would be for assisting other players all while not disturbing your own marked collection. OR simply for other uses.

As of late I’ve been helping quite a few people with Collections, it’s tough to know what they have and how much they need. I say 30% of our travels are to collectible location they already have. If I can already mark down the ones they have this would make the Travel a lot more smoother.  I know it’s knit-picky as to what I’m suggestion but it’s become a small nuisance now many are trying to obtain 10x Collectibles.

**Comment by Senexis** [comment]
If it's temporary, you can just open a new incognito window (usually CTRL+Shift+N) and get as many clean slates as you want. If it's not temporary, why don't you just tell your friends to use the map themselves?

**Comment by MichalD96** [comment]
Good idea with incognito window and also that way don't need to be temporary if you export map settings, you can load it on the next day
@LAxExcalibur scroll down in menu to Import/ export section and click export button
