### ISSUE TITLE
Incorrect Map/Cycle?

### ISSUE THREAD

**Issue by RDOCollector** [jeanropke/RDR2CollectorsMap#969]
This is a really incredible tool. I wholly appreciate how much it helped me get to level 20. I used this map for two days in a row, and it was perfect. Today when I signed on, 10 out of 10 items I walked to, were not there. I read through the wiki a few times, and reset everything a few times, and nothing worked.  Please let me know if I am the issue, or if there is a lag on the cycle update? I appreciate your time and help.

**Comment by MichalD96** [comment]
Do you use this map or version on other site?
https://jeanropke.github.io/RDR2CollectorsMap/
What cycles numbers you can see in menu?

Cycles are up to date, try to click "Reload map now" in menu
If this not help try "Reset all settings"
Another possibility is, you are in bad session in game, try change the session, and collectibles should spawn again

**Comment by RDOCollector** [comment]
Wow... I was on a replica site? This link worked perfectly! Everything is there. Thank you so much for your help. Do you all have a venmo? I would love to donate, but am not going to put my credit card info on github.

**Comment by MichalD96** [comment]
Link to donate is on the bottom of menu (payPal)
