### ISSUE TITLE
How would i get the name of an item from the removed item id

### ISSUE THREAD

**Issue by iligalodin** [jeanropke/RDR2CollectorsMap#97]
When removing a node it stores a random number in the cookeis
I don't know how exactly the number is correlated to a marker / item

I would like to know how the markers get that random number and if i can get the name of the item with that number eg "cups_ace"

the reason why i am asking is because i am creating a dynamic route that is build up with the names of the items

**Comment by iligalodin** [comment]
not sure if i made any sense, if you have questions related to my question i will try to elaborate further and more clear

**Comment by jeanropke** [comment]
I'll change to items text name in next update. Its finished, just waiting GMT 0 midnight to change it.

**Comment by jeanropke** [comment]
And the item id is the order in items.json.

**Comment by iligalodin** [comment]
> And the item id is the order in items.json.

oh wow that makes sense, ill wait untill tomorrow to continue the dynamic route
