### ISSUE TITLE
Bug: Inventory count changes when hiding single items

### ISSUE THREAD

**Issue by jros92** [jeanropke/RDR2CollectorsMap#974]
Steps to reproduce:
1. Enable inventory
2. Enable advanced inventory options
3. Enable "highlight low amount items"
4. Increase inventory amount for an item
5. Hide that item (either clicking on it in the menu, or clicking "hide on map"on the item icon on the map)
6. Observe the item count increase: the item count seems to increase by 1 for each of the items that is hidden on the map. This means, hiding any item other than a wildflower (of which there is only 1 present on the map at any time) will increase its count by 1. If you hide a single wildflower on the map by clicking on its hide button, the count will increase by 1. If you however hide all wildflowers of a certain kind (either by clicking the wildflower in the menu, or by clicking "disable all collected" for the wildflowers), the count will increase by the total number of wildflowers currently shown on the map for this kind.
7. Show item again
8. Observe that sometimes, the count jumps back to the correct count, but other times, it jumps back to a different count than what it previously was (think this is only true for wildflowers but not sure)

Clicking "disable all collected" will yield the same effect for each item that gets hidden by this.
Hiding an entire item category seems to not cause the same issue.

**Comment by jros92** [comment]
Just realized there is an option in the settings "toggling menu items updates inventory" that was enabled by default. So I guess this is indeed expected behavior.

**Comment by jros92** [comment]
Okay, just realized even with "toggling menu items updates inventory", there is still unexpected behavior.

Hiding/showing an item from its icon on the map will still change the inventory count by 1 - in the menu it seems to work correctly.

**Comment by MichalD96** [comment]
This is intended behaviour. The option is called "Toggling **menu** items updates inventory"
This option have been added to have more controll on your inventory from menu. Normally you dont manage the inventory from marker popup, you only add one just collected item, so the button "Remove/Add from map" will always increase amount of items in your inventory.

**Comment by jros92** [comment]
Understand! Thanks. Sorry for the confusion ;)

**Comment by MichalD96** [comment]
No problem ;)
