### ISSUE TITLE
Emmeline Coral Earrings - Cycle 1 Bugged

### ISSUE THREAD

**Issue by NightEagle256** [jeanropke/RDR2CollectorsMap#976]
The Emmeline Coral Earrings in the Lost Jewelry Earrings collection set cycle 1 is bugged. Its meant to be a metal detector dig, but it isn't picked up at all. Switching lobbies doesn't work either. Attached an image of the location on the map including cycle. Needs marking as unobtainable
![Untitled](https://user-images.githubusercontent.com/63644612/79217472-d4ba2180-7e46-11ea-82f7-5ba74eb26bbe.png)

**Comment by MichalD96** [comment]
just collected:

![emelline](https://user-images.githubusercontent.com/53737762/79259648-5634a280-7e8d-11ea-9cb7-4bcfd41fa2ad.png)

try change the session or restart the game, and everything will works
