### ISSUE TITLE
Sterling tooth earring : Day 1

### ISSUE THREAD

**Issue by Jawgermaster** [jeanropke/RDR2CollectorsMap#977]
Hello there,
My Sterling Tooth Earring Day 1, does not appear at 6pm and today it’s my first time on the site
Coordinates : -73.7968 ; 132.4375
Lemoyne, Scarlet meadows, Ringneck creek 

Do you have a problem with ?
Thanks
RNZ_JAWGERMASTER

Edit : I found Raw Arrowhead on the Canon and the tree at -90.1797 ; 134.4609 
I’ve found 2 Raw Arrowhead on my session, it’s possible ?

**Comment by MichalD96** [comment]
i collected this earrings around 12 hours ago, 
so this earrings probably was bugged in your session, try change the session (if this not help restart the game) and earrings will be there
