### ISSUE TITLE
Incorrect item Cycle: Madam Nazar

### ISSUE THREAD

**Issue by MrLinio** [jeanropke/RDR2CollectorsMap#979]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name : Madam Nazar
On the website : Window Rock
In reality (and here : https://holdtoreset.com/where-is-madam-nazar-today-in-red-dead-online/) in Bluewater Marsh. Other items seem to be in correct place.

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
This is normal, we dont know Madam Nazar future positions so it always take some time before map find her
