### ISSUE TITLE
Madam Nazar not showing up on map?

### ISSUE THREAD

**Issue by SNIZZLEPRETZAL88** [jeanropke/RDR2CollectorsMap#983]
As simple as Madam Nazar isn't showing up on the map for me. I know there other ways in which you can find this info out, but I normally visit the webpage and would like to see that it is not having any issues although I, of course, understand that websites are hard to manage and take lots of work to find out what's going on 👍 I hope this helps with fixing this situation.

**Comment by MichalD96** [comment]
@SNIZZLEPRETZAL88  do you still have this problem?

**Comment by MichalD96** [comment]
i cant reproduce this bug on any browser/ device
if you will have this problem again, let me know (write everything about i asked in my first comment)
