### ISSUE TITLE
What is the yellow circle next to item groups in the index ????

### ISSUE THREAD

**Issue by michaelsygo** [jeanropke/RDR2CollectorsMap#985]
*

What is the yellow circle next to item groups in the index ???? Please 

Msygo@hotmail.com

*Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalD96** [comment]
This collection is in the same cycle as yesterday. In this case, there is a 24 hour delay before you can pick up the item again.
it is game bug

**Comment by michaelsygo** [comment]
Thank you lol driving me crazy
Thanks for your map
I almost have 10 sets of everything waiting now for outlaw pass 3 before I sell it all
That should get me everything in the outlaw pass
Wonder if anyone else has thought to do this. Lol

Sent from my iPhone

On Apr 23, 2020, at 11:28 AM, Michal__d <notifications@github.com> wrote:

﻿

This collection is in the same cycle as yesterday. In this case, there is a 24 hour delay before you can pick up the item again.
it is game bug

**Comment by MichalD96** [comment]
you can enable "Show help on hover" on the touch screens you have to hold the option you want to check, there is everything described.
Map also can show you a few more game bugs so, i highly recommend to use this option
