### ISSUE TITLE
Found an Arrowhead Not on the Map.

### ISSUE THREAD

**Issue by WingedPaladin** [jeanropke/RDR2CollectorsMap#987]
I found a Flint Arrowhead not on the map on 4/24/2020 around 12:32 AM HST.  Here are the screenshots of the map where my cursor and horse are and the discovery place.

https://steamcommunity.com/sharedfiles/filedetails/?id=2072253376
https://steamcommunity.com/sharedfiles/filedetails/?id=2072253408

**Comment by MichalD96** [comment]
Random Item #190 - Cycle 6 
https://jeanropke.github.io/RDR2CollectorsMap/?m=random_item_190
