### ISSUE TITLE
Hide all markers except important

### ISSUE THREAD

**Issue by singemfrc** [jeanropke/RDR2CollectorsMap#989]
Would be handy to have a "show only important markers" or "hide all but important markers" button, perhaps right next to the "reset important markers" option. I keep certain items always marked important because I want to grab those every time I'm online, and sometimes I hop on just to get those and leave, would be handy.

**Comment by theocdlistmaker** [comment]
Agree. This would be a great feature. Beyond the highlighting of low items I mark certain ones as important. Being able to just see those would be nice to have!

**Comment by MichalD96** [comment]
Just added markers filter to the map
https://github.com/jeanropke/RDR2CollectorsMap/commit/57549dd14cc601f0ad8e98de00c1d25d4eda211e
![Bez-nazwy-1](https://user-images.githubusercontent.com/53737762/90301824-6348b900-dea2-11ea-9542-c70cb2dd6634.jpg)


it allows you fo filter markers by:
- Naturalist items,
- Moonshiners items,
- Weekly set items,
- Important items
