### ISSUE TITLE
Fast travel in route calculation.

### ISSUE THREAD

**Issue by dangalg** [jeanropke/RDR2CollectorsMap#990]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Most people use fast travel when collecting so please add it to the route generation
Also it would be nice to choose a town to begin from in a dropdown list instead of a general direction.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by MichalD96** [comment]
this option exists in route generator
enable "Show coordinates on click"
click on the town from where you want to start and in window with coordinates click "Set as route start"
next enable "use pathfinder" (set all settings you want like skip collected items)
and then click generate route
