### ISSUE TITLE
Is there a way to change time zones?

### ISSUE THREAD

**Issue by paulwhite20** [jeanropke/RDR2CollectorsMap#995]
Is there a way to change the map’s timezone? I am using mobile. I am using Pacific Time and the map is showing tomorrow’s locations.

**Comment by MichalD96** [comment]
Cycles in game change always at 00:00 UTC time, and not matter in what time zone you are. Also date on the map shows UTC time.
If you use Pacific Time it means cycles change at 5:00 PM your time 
Map always shows correct items positions and you don't need to change anything.

Map has build-in warning if the cycles are not correct, until you don't see any warning message everything should works

**Comment by paulwhite20** [comment]
> If you use Pacific Time it means cycles change at 5:00 PM your time

- So I only have until 5 PM Pacific Time to use the live map? My original question really isn’t answered. There’s no way to change the timezone or go back to the previous day? 
I was using the map when it was the 28th earlier in the day and went back later that night and the map was showing the 29th locations and they weren’t correct in game for me.

**Comment by paulwhite20** [comment]
> Cycles in game change always at 00:00 UTC time, and not matter in what time zone you are. Also date on the map shows UTC time.
> If you use Pacific Time it means cycles change at 5:00 PM your time
> Map always shows correct items positions and you don't need to change anything.
> 
> Map has build-in warning if the cycles are not correct, until you don't see any warning message everything should works

I was playing earlier in the day on the 28th and the locations were correct, but went back later that night around 9:00 PM and the map was showing locations for the 29th, not the 28th. I went to a couple locations and they weren’t correct in game. 

I feel like my original question isn’t answered. There’s no way to change it back or change time zones?

**Comment by MichalD96** [comment]
No there is no way to change the time zone/day because cycles change at the same time everywhere (00:00 UTC time) (different time in every time zone) and it means map should always show correct cycles. If you cant find the item try change the session or restart the game.
Date displayed in menu is also UTC date - not your time date

**Comment by MichalD96** [comment]
this timer in left top corner shows you how much time left to the cycle change:
![timer](https://user-images.githubusercontent.com/53737762/80663892-8d15d580-8a95-11ea-97c7-37f1773517ad.png)
and it shows the same time on the entire Earth
