### ISSUE TITLE
Ace of Wands Cycle: 1

### ISSUE THREAD

**Issue by maeeh** [jeanropke/RDR2CollectorsMap#996]
As there is no Piano at the Braithwaites, i think this is maybe pointing to the Mayors Villa in Saint Denis
![AceOfWands_Cycle1](https://user-images.githubusercontent.com/26537822/80859120-72db2380-8c5e-11ea-9113-ed11bdac8890.png)

**Comment by maeeh** [comment]
checked the mayors house, no card

**Comment by Senexis** [comment]
There definitely is a piano there. It's in the corner in the north-eastern room at the ground floor.

**Comment by maeeh** [comment]
you're right, I was looking for one of the big things, not the small ones. Got it right now. Maybe I need new glasses ;)
