### ISSUE TITLE
Add non-role events.

### ISSUE THREAD

**Issue by HellFireNT** [jeanropke/RDR2CollectorsMap#997]
Hello ! recently i started using the other map (for plants , fish and and animals) and i've noticed it shows more events than the normal collector map . When i opened the "SELECT ENABLED EVENTS" it only shows 5 events in the list (not all that are in the game)

Thanks for your time and hopefully it can be fixed ! Love your work otherwise !

**Comment by Senexis** [comment]
Will be adding these sometime soon.
