### ISSUE TITLE
Egret Egg - Cycle 1

### ISSUE THREAD

**Issue by rasczak1959** [jeanropke/RDR2CollectorsMap#998]
Egret Egg - Cycle 1 location (Lemoyne--Bluewater Marsh) is bugged.  Location does not allow for the player to collect the item.  Player can shoot the nest but the egg remains in the tree and is unreachable as it does not fall to the ground as per normal.  Recommend adding a notification to the RDO collection map when this cycle occurs.

**Comment by MichalD96** [comment]
This information is in the item description that this egg is most cases bugged. We cant add description that egg is permnently bugged because if you are enough patient and change session/ restart game a few times, it finally fall from the tree
