### ISSUE TITLE
bracelets, necklaces, coins 

### ISSUE THREAD

**Issue by ams123456789** [jeanropke/RDR2CollectorsMap#999]
I’m not sure if my cycle is off but it is not matching the map that has been giving. I can only find a few pieces and then i can’t find the others. is this a bug or what?

**Comment by MichalD96** [comment]
Do you use this map?
https://jeanropke.github.io/RDR2CollectorsMap/
or version on another site?
what items you have problem to find and in what cycle you can see them on the map?
First try change the session, or restart the game. Some sessions are bugged and don't spawn all of the items.

**Comment by ams123456789** [comment]
Yes i restarted the session and it still didn’t pop up. Should i restart the game? and it was the Roy pearl necklace.

**Comment by MichalD96** [comment]
Cycles seems to be fine, but i will check in game in a moment.

if you play on PC you can also delete cache files, turn off the game,
go to this directory:
`C:\Users\<your user name>\AppData\Local\Temp`
and delete all files that begins from cloud_ and has `.dat` extention
and launch the game

**Comment by ams123456789** [comment]
i’m on the xbox so i’ll just restart the game and see where that gets me. i found some of the necklaces that’s why this is not making sense.

**Comment by MichalD96** [comment]
ok, so you can't do much with it, try change the sessions until you find something
